### PR TITLE
Item Storage Populator Optimiations

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: Item Storage will only spawn stuff on first open not round start anymore

Using Square Station quick load (square is the only scene) as a test:

Before PR:
Lobby: 2513 Start: 4277

After PR:
Lobby: 2513 Start: 2591

1686 less game objects!

This will need some actual testing as item storage is used in lots of stuff unlike the locker PR which was easy to test.

If some stuff isnt spawning there is an override on the item storage component which will spawn the stuff at start like before.

Related to #6507 and #6513

-Adds tests to make sure all objects (not items) are forced to have spawn on start to avoid non spawning issues
-Also fixes cargo cash issue and adds tests for empty item traits
-Fixes singularity not locking points on stage 0

~Currently doing a build test now~
Looks like its working fine, cant find any problems.

### CODE REVIEW

**Comment by Aranclanos** [comment]
I fear that many objects will break different type of interactions that a sandbox game like ss13 has. 
On an easy example, lets say an EMP grenade goes off next to an untouched locker and there are energy guns that spawn from it. If they're not inside the batteries of these guns are not drained and once opening the locker you'll have loaded guns.
There's many cases that inacuaracies can happen with this strange on-use spawn.

**Comment by ThatDan123** [comment]
I get what you mean, but this optimisation is worth the extra effort to have to think about those niche situations and then remember to trigger the spawn manually (E.g if EMP'd)

**Comment by NoooneyDude** [comment]
~Works as expected, does what it says on the tin.~

**Comment by ThatDan123** [comment]
Ready to be merged

**Comment by corp-0** [comment]
Huh, we don't have the "test on staging" label anymore. Anyways, I'm test merging this, if something breaks in staging remember to revert it.

**Pull request merged**
