### PR TITLE
Scanner and first aid kit sprites, and some other stuff.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Updates sprites for health scanner and atmospherics analyzer.
- Changes sprite for shuttle engine heater.
- Update sprites for first aid kits, tweak .prefabs.
- Commit a few updated .meta files.
EDIT:
- Adjust localization and file names for analyzers and flashlight.
- Make flashlight use proper held sprites.

### CODE REVIEW

**Comment by Bod9001** [comment]
imo, I prefer the old sprites, but I'll leave the decision up to #Spriteign

**Comment by DooblyNoobly** [comment]
can we get some screenshots?

**Comment by PetMudstone** [comment]
Clipboard Image (3)
Clockwise from top left: first aid kit, burn treatment kit, health analyzer, and atmospheric analyzer.
To be honest, I don't quite like how all the new first aid kits (from /tg/) all use the medical cross on them instead of unique symbols (like a fire for the burn treatment kit).

**Comment by fomalsd** [comment]
I kinda like the older ones more as well, but it might be just nostalgia
I was initially against new locker sprites but they ended up fitting alright

**Comment by PetMudstone** [comment]
Yeah, I mainly want the new first aid kit sprites as their perspectives are more in line with most items in /tg/ and Unity now.

Also tests are failing but I think that's because of #4261 or something.

**Comment by corp-0** [comment]
the main reason to change sprites is to make stuff comply with one perspective and not have a mismatch of them. Old sprites use to have that “looking from left in 45°“ appearance when new sprites look like they are being looked slightly  from top.

**Comment by DooblyNoobly** [comment]
Might as well merge it and get peoples thoughts, we can always change sprites we don't like

**Pull request merged**
