### PR TITLE
VV Improvements

### PR DESCRIPTION
**Pull request by Bod9001**
made it so editor could load into any scene that was previously loaded

CL: **[New]** VV has hierarchy now

CL: **[Improvement]**  VV Is now way better to use

### CODE REVIEW

**Comment by corp-0** [comment]
solve the codacy issues but the ones about PascalCase with the GUI word and we're good.

**Comment by Bod9001** [comment]
still fixing a few things

**Comment by Bod9001** [comment]
is good now

**Comment by waffielz** [comment]
vv gaming

**Pull request merged**
