### PR TITLE
Increases conveyor belt speed

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Improvement] - Increases conveyor belt speed from 0.8 to 4

### CODE REVIEW

**Review by NoooneyDude — APPROVED** [review]
Which Factorio belt colour is this equivalent to? : P

**Comment by PerfectTangent** [comment]
Let's see. Factorio game tile is 1m. SS13 game tile is 2.5m. Assuming this belt speed is tile per second, then the old speed of 0.8 is 6% faster than yellow factorio belts and the new speed is 533% faster than yellow factorio belts, or 77% faster than blue belts, if my math is correct.

**Comment by PerfectTangent** [comment]
actually, how fast is this in game? Is there enough time for people to get up from being ejected from disposals before they are swept away to the mass driver? With the old speed (pre movement rework, at least) it was already pretty close.

**Comment by corp-0** [comment]
give a gif, I also want to see how fast it looks now

**Comment by MaxIsJoe** [comment]
> give a gif, I also want to see how fast it looks now

What you'll see in the gif wont carry over to staging terms because the server shows the movement much more smoothly than on an actual live server.
However looks doesn't matter, functionality does; the 4 speed is the equveilent of someone switching their movement speed to walking instead of running.

**Pull request merged**
