### PR TITLE
Log admin in ban entries

### PR DESCRIPTION
**Pull request by craftxbox**
### Purpose
It's sometimes unreliable to ask admins 'who banned x', the banning admin may not be around, have forgotten, etc, This fixes that but logging who banned who into the ban list.

### Changelog
CL:  Add the banning admin in job & normal ban json, not used within game.

### CODE REVIEW

**Comment by Bod9001** [comment]
have you tested this is compatible with old bans?

**Comment by craftxbox** [comment]
I have not tested at all, but it only adds new properties, and doesnt actually use them in any form. My system isnt capable of testing at the moment and might not be for a while

**Comment by corp-0** [comment]
rebase from upstream so the tests are happy green and not angry red, also if you could test the compability it'd be great. If not let us know and maybe someone has time to get on that.

**Comment by craftxbox** [comment]
I dont have a local git copy at the moment, So i can only do functions that the webclient would let me, and the same presently applies to testing functionality/compat. I'm gonna leave this in draft untill i i can test it unless someone else would be willing to do so.

**Comment by ThatDan123** [comment]
I think our coding guidelines says to keep local variables as `var` not as their specific type. So to keep consistency with the majority of the code base would be to keep them as `var`.

**Comment by corp-0** [comment]
That’s awful. This file was literally unreadable because you never knew what was what

**Comment by craftxbox** [comment]
Yeah... var is horrible, its egregious to even have it in a static typed language like c# in the first place.

**Comment by corp-0** [comment]
https://unitystation.github.io/unitystation/contribution-guides/Development-Standards-Guide/
Didn't find anything regarding the use of ``var`` against the explicit type

**Comment by ThatDan123** [comment]
humm, definitely remember Redline saying it, or at least recommending to do it.

**Comment by corp-0** [comment]
If you abandoned this, can you close it?

**Comment by craftxbox** [comment]
This isn't abandoned, I currently have no way test this, Unity refuses to work on my system but i've been trying to find someone who can compile a build for me so that i CAN test this, which is why it's still open.

**Comment by craftxbox** [comment]
Um, what?

**Comment by corp-0** [comment]
you tried to update to latest? How did you do it?

**Comment by craftxbox** [comment]
At this point im not sure, I tried to merge but instead this happened

**Comment by craftxbox** [comment]
Any good developer should learn the power of git reflog.

**Comment by corp-0** [comment]
I like rebasing instead of merging for updating a branch to latest upstream. 
``git fetch upstream``
``git rebase upstream/develop``

If there is any conflict it will stop the rebase process and you can solve it in your IDE, then do ``git rebase --continue``

**Comment by craftxbox** [comment]
Rebase was what was causing the issues, did a normal merge and it seems to be fine now

**Comment by craftxbox** [comment]
marking ready for review, it compiles, seems to not die instantly, but isn't fully tested

**Pull request merged**
