### PR TITLE
shutup meg

### PR DESCRIPTION
**Pull request by MaxIsJoe**
no-cl

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
oh hey, it works

**Comment by MaxIsJoe** [comment]
oh fuck off

**Comment by corp-0** [comment]
Not bad. Probably would be the best to do all of that inside the changelog action itself, it would also allow you to have the no cl tag anywhere in the description instead of forcing you to start with it.

**Comment by MaxIsJoe** [comment]
> Not bad. Probably would be the best to do all of that inside the changelog action itself, it would also allow you to have the no cl tag anywhere in the description instead of forcing you to start with it.

problem, the workflow test is always outdated; it doesn't use the latest one. So idk if this is even working or not

**Pull request closed without merging**
