### PR TITLE
Fix the antag box bug

### PR DESCRIPTION
**Pull request by VernaSaurus**
Have you ever had a perfect antag round lost by your items being in a box? Well no more! With the new stuff I'm committing here, you can rest easy knowing your stolen goods will be counted regardless of where they are!

Note: Has not actually been tested.

### CODE REVIEW

**Comment by corp-0** [comment]
what are the two lists used for?

**Comment by VernaSaurus** [comment]
the lists are used to write/read each itemstorage found to/from

**Comment by VernaSaurus** [comment]
basically it stores every itemstorage it finds in the first check, and then checks if it's found the item, if it has it ends, if it hasn't it checks to see if there are any itemstorages, if there are it repeats the process until either A: it's gone four layers deep, or B: it finds the item

**Comment by corp-0** [comment]
I see. It's a little bit hard to read, don't be afraid to divide your logic and create new functions to abstract the tasks. Also, remember the DRY rule, don't repeat yourself. If you need to do something n times, loop it n times, don't repeat the code n times.

Try doing a little refactor, pretty sure you can!

**Comment by VernaSaurus** [comment]
i can't loop it because even though it LOOKS like it's performing the same check, it's actually performing a slightly different check every time

**Comment by VernaSaurus** [comment]
This is actually required, otherwise I wouldn't do it

**Comment by ThatDan123** [comment]
The first two loops look the same. And try to reduce nesting.

**Comment by corp-0** [comment]
would it work if we iterated all item storages and appended content to a list, then from that list iterate again and append until there are no more itemStorages and then check this single list with all items the character has if it contains the requested item?

**Comment by VernaSaurus** [comment]
i have no idea what any of this means i'm sorry

**Comment by VernaSaurus** [comment]
because i'm a lazy idiot this'll probably never be merged so i might as well close it huh

**Pull request merged**
