### PR TITLE
Changes references to new health,

### PR DESCRIPTION
**Pull request by Bod9001**
you can now die from brain damage, 
adds healing chemistry for brain
made it so you can add additional reactions to certain reagent containers on prefabs

### CODE REVIEW

**Comment by corp-0** [comment]
weren't some of those commits part of your other pr?

**Comment by corp-0** [comment]
yep, you're undoing corrections you did in your other pr

**Comment by Bod9001** [comment]
am I, in total it corrected itself?

**Comment by corp-0** [comment]
> am I, in total it corrected itself?

you're using ``as`` instead of ``is``. Yeah you could redo the ``is`` thing but god knows what else got overriden. The safest would be cleaning up the git history for this pr.

**Comment by Bod9001** [comment]
I can't see it in the files changed?

**Comment by corp-0** [comment]
all of these 
image

**Comment by Bod9001** [comment]
idk how to clean commit history

**Comment by ReiderJack** [comment]
You know how to clean it. I made a video for you long time ago

**Comment by ReiderJack** [comment]
But you can just squash merge it

**Pull request merged**
