### PR TITLE
Adding a few more winter coats.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Adds winter coats for the following
  - In Lockers
    - Head of personnel.
    - Chief Medical Officer
    - Research Director
    - Head of Security
    - Chief Engineer
    - Quartermaster
  - In Vendors
     - Geneticists
     - Virologists
     - Chemists
     - Paramedics
     - Roboticists
     - Janitors
  - CentCom Officials (admin spawn only)  
- Also adds winter hood prefabs corresponding to all winter coats in this PR and those that already existed, but they cannot appear during normal gameplay yet.

#### Credits:
- @SomeAngryMiner: Original winter coat sprites.
- @Imaginos16: Color and pattern inspiration for all added sprites.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
did you add winter coats to locker populators? If so, we will have to remove the winter coats mapped into Outpost and Pog.

**Comment by PetMudstone** [comment]
I only added the new winter coats to locker populators in this PR. I did however add the standard winter coat to the ClothesMate in this PR. Furthermore medical, security, captain's, etc coats that already existed were already either part of vending machine inventories or locker populators. 
Therefore I would recommend removing the mapped in winter coats because they all could already be found in populators or vendors.

**Comment by PerfectTangent** [comment]
> Therefore I would recommend removing the mapped in winter coats because they all could already be found in populators or vendors.

that's what I said.

**Comment by corp-0** [comment]
will the mapped ones be removed in another PR?

**Comment by PetMudstone** [comment]
I can work on removing the winter coats not in Outpost. I'll see if I can commit some map changes.

**Comment by PetMudstone** [comment]
Removed stray winter coats in Pogstation and Fall. Didn't touch Outpost because PerfectTangent is working on that.

**Pull request merged**
