### PR TITLE
Fixes the dev spawner freezing lag on empty search

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes the dev spawner searching with an empty or really short string.

### CODE REVIEW

**Comment by Pockets-byte** [comment]
wait so this is just the nuclear option?....
well I guess I'll take what I can

**Comment by corp-0** [comment]
what you mean?

**Comment by Pockets-byte** [comment]
I was sorta hoping dev spawner was fixed so it handled having to load every prefab in the game didn't cause massive slowdown, rather than just removing that ability.

**Comment by Aranclanos** [comment]
well it was a bug, from design it was never inteded to show all loaded prefabs (it doesnt show ALL prefabs)
do you want to have the entire list?

**Comment by Pockets-byte** [comment]
It's always useful in my area to know and be able to use every usable item in the game. which is why I go through the list of items I can spawn every once in a while 
I haven't done it recently because the dev spawner list has been increasing exponentially in length

**Comment by Aranclanos** [comment]
it uses Resources.FindObjectsOfTypeAll() so objects not present in the scene wont show up, but we also have to re-do this to stop using the resources folder, maybe a proper dev spawner with categories could be used

**Pull request merged**
