### PR TITLE
added Pockets and  suit storage that grey out when no Suit or OXsuit Is equipped

### PR DESCRIPTION
**Pull request by Bod9001**
NOtes 
added function to ItemSlot to highlight if it's disabled, so  can fit will return false if this is False
### Changelog
CL:  Suit storage and pockets now Grey out when you're not wearing the appropriate Clothing,  and drop the contents if taken off

### CODE REVIEW

**Comment by Bod9001** [comment]
GIF43

**Comment by Bod9001** [comment]
note: 
need to make pockets more generic to allow variable amount, but pplanning to leave that after health rework

**Comment by Bod9001** [comment]
GIF44

**Comment by corp-0** [comment]
are you going to make any changes to this one?
edit: nvm it showed as open on my computer for some reason.

**Pull request merged**
