### PR TITLE
Windoor and Directional Firelock Rotation

### LINKED ISSUE #5778: Windors have not correct directions
image
image

### PR DESCRIPTION
**Pull request by Bobtheapple**
Went through and rotated all of the Windoors and directional firelocks on the remaining MainStations.
Fixes #5778
Note that #4995 is still an issue, I simply manually went through and properly rotated the children.

### CODE REVIEW

**Comment by corp-0** [comment]
```
OutpostStation: "APC" has a null value in the list.
OutpostStation: "APC" has a null value in the list.
SquareStation: "APC - RND" has a null value in the list.
```
You have some apc's with null values

**Comment by corp-0** [comment]
This is fine to merge as soon as it passes tests

**Comment by Bobtheapple** [comment]
The null entries on the APCs appears to be unrelated to my changes.  My best guess was that some object was connected to the APCs in the past, and the object was removed (or its usage of the script was) but the APC was not updated.  When I rotated the windoors, the APC updated and started throwing the error.  Unfortunately, I have no idea what the object was.  For now, I just removed the null entries.

The APCs in question were Outpost's Robotics APCs, at (40,43) and (41,45), and Square Station's RND APC at (65,62), so it has something to do with Robotics/RND.

I also went through and named every APC in Outpost Station so that things are easier to find.  Some of the name choices might not be correct, but at least each APC has a unique name now so we can find problems easier.

**Comment by corp-0** [comment]
> I also went through and named every APC in Outpost Station

Thank you!

**Pull request merged**
