### PR TITLE
improvements, 

### PR DESCRIPTION
**Pull request by Bod9001**
remove the default sound from radio communications, it was a bit loud and obnoxious and not particularly useful
hopefully makes it so null username makes it so the client is actually informed, the player knows what to do to fix it

CL: [Fix] added audio slider for radio message notification

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
> Remove

image

**Comment by corp-0** [comment]
I also dislike the plain out removal, I'd rather do the option to disable/lower its volume instead

**Comment by Bod9001** [comment]
Though it is kept for the security and other channels? Should I have it as a volume slider?

**Comment by corp-0** [comment]
> Though it is kept for the security and other channels? Should I have it as a volume slider?

Yes, a slider would be great

**Comment by Bod9001** [comment]
done

**Review by NoooneyDude — APPROVED** [review]

**Pull request merged**
