### PR TITLE
Mob creator/editor tool

### PR DESCRIPTION
**Pull request by MaxIsJoe**
part of  #10163

Allows contributors to easily create new mobs without having to worry about going through the manual process of creating them.
This has no changes related to gameplay or anything, this is just some tooling for developers.

### CODE REVIEW

**Comment by Bod9001** [comment]
does it initialise the Body health systems automatically?

**Comment by MaxIsJoe** [comment]
> does it initialise the Body health systems automatically?

It doesn't. You are given the option to edit them manually, however.

**Comment by Bod9001** [comment]
just saying this will result in stuff like the new species Spawning in without any blood

**Comment by MaxIsJoe** [comment]
> just saying this will result in stuff like the new species Spawning in without any blood

do you want me to add in something like presets for people to use automatically?

**Comment by Bod9001** [comment]
ideally it could be like prefab variance but I can't think of a good way of doing it

**Comment by Bod9001** [comment]
if you think it's outside the scope of the PR is good

**Review by Bod9001 — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
I can add that functionality later when I expand upon this tool.
But right now it does its intended use-case fully, anything else can be considered QoL additions to make the mob creation process faster.

**Pull request merged**
