### PR TITLE
Updates addressables Maybe fixes Mac error

### PR DESCRIPTION
**Pull request by Bod9001**
need someone with a Mac to try this

### CODE REVIEW

**Comment by corp-0** [comment]
what mac error?

**Comment by Bod9001** [comment]
on mac os it doesn't seem to find the addressable bundles in the editor, meaning that there is no sounds or music and It just spams a bunch of errors

**Comment by JustinTrotter** [comment]
Tested. Fixes the problem when running the game on the editor on my Mac. Thanks a bunch Bod.

**Review by corp-0 — APPROVED** [review]

**Comment by NoooneyDude** [comment]
Tests are having a lot of trouble with this, not completing. Also noticed that version isn't available in the package manager on 2021.1.14f, but you're on .28, right? Probably available on that version, might need to update to .28?

**Comment by NoooneyDude** [comment]
Addressables updated, no longer necessary.

**Pull request closed without merging**
