### PR TITLE
Sets Pipe Sprite on spawn

### LINKED ISSUE #8272: Pipe dispenser gives only straight pipes
Pipe dispenser gives only straight pipes when you click on bent ones.

### LINKED ISSUE #8273: Unwrenching bent pipe gives straight pipe
Unwrenching bent pipe gives straight pipe

### PR DESCRIPTION
**Pull request by Nianmi**
### Purpose
 <br>

Fixes the bend pipe sprite problem on spawn.

### Notes:

Resolves #8272 
Also Closes #8273 even though I could not reproduce this. But I think we can close this issue for now.

### CODE REVIEW

**Comment by corp-0** [comment]
@ThatDan123 @Bod9001 what do you guys think?

**Comment by Bod9001** [comment]
The issue because The Rotational script has to reset all The other sprites, because they all messed up from directional script changes scenes, you could make it so it doesn't apply if it's a pipe?

**Comment by Nianmi** [comment]
I didn't want to mess around in the Rotational script because I thought that this script is highly generic. Don't like do add specific stuff to generic scripts. Perhaps I don't understand it well enough. The Problem arises that the Pipe Script never sets it rotation on spawn.

**Comment by ThatDan123** [comment]
If this fixes it, then i'd rather have this than stick more stuff in Rotatable

**Comment by Nianmi** [comment]
It fixes #8272 for sure. For #8273 I don't know I could not reproduce this at all. Perhaps somebody else can reproduce this at let me know? I think adding to much specific stuff to a generic class like Rotatable is not the way to go.

**Comment by corp-0** [comment]
> For https://github.com/unitystation/unitystation/issues/8273 I don't know I could not reproduce this at all. Perhaps somebody else can reproduce this at let me know?

did you try reproducing in a server and client environment? You can launch the built game twice and make one of them act as server, the other as client

**Comment by Bod9001** [comment]
Do you need help with testing?

**Comment by Nianmi** [comment]
@corp-0 i did now and it seems like this fixes nothing o.O  Only fixes the bug on the admin side. Can close this PR

**Pull request closed without merging**
