### PR TITLE
switch suppressors to use slots

### PR DESCRIPTION
**Pull request by AutumnNova**
aint much too it
CL: fixed the radius around the player that caused them to accidentally attack themselves

### CODE REVIEW

**Comment by PetMudstone** [comment]
Tests just complain about the template scenes, which will be removed in 5705 anyways.

**Comment by corp-0** [comment]
the octagon of doom is the wrong interaction when clicking the adjacent tile and hitting yourself?

**Comment by AutumnNova** [comment]
it happens with guns, lowering the magnitude means the check is only done when your target is on the same tile

**Comment by corp-0** [comment]
how did you get to 0.5 as the right number?

**Comment by AutumnNova** [comment]
half a tile from the players position (the center of a tile) , as apposed to 1.1, which is a tile and a bit
i have tested these values

**Comment by corp-0** [comment]
alrighty then, thanks. Can you mention that fix for the changelog? It is an important one some players will be happy to read it is fixed.

**Pull request merged**
