### PR TITLE
Adding Boxstation

### PR DESCRIPTION
**Pull request by ThatDan123**
### Purpose
Adds BoxStation to the map pool.

Trying to keep it as authentic as possible, but some changes will need to be made.

### Notes:
Still Under Active Development

This PR is to list how far along the mapping is and to list anything that needs to be added for the map to be complete.

- [x] Base,Walls and Full Tile Windows

- [x] Wiring
Done, though could do with a clean up in some areas
- [x] APCs
Done and name labeled too
- [x] 0.4 Atmos
Done, ~~though the central hallway is depressurised just need to find leak.~~
- [x] Ian added.
- [x] Set up Solars
Solar locations mapped, solar panels not added. 
- [x] Lockers
All lockers put in right place, needs some touching up and items assigned fully. Most items assigned.
- [x] Items
Lots of items added, loads to go.
- [x] Other objects
- [x] Machines/Consoles
- [x] EscapeShuttle needs to be able to set destination of escape/centcom.
Needs a custom script created.
- [x] Adjust Map to allow for movable shuttles, ie fix cargo and escape.
Cargo Shuttle needs new script to dock as for some reason the shuttle moves one tile backwards when it stops.
Mining Has been moved to above arrivals for shuttle space.
- [x] Lighting
Lighting is very buggy atm, hard to work with so i've stopped.
Needs a rework, and the ability for lights to function without switches.
50% complete, all lights are in position, just needed reworking light scripts.

- [x] Shutters and BlastDoors
Most shutters are in position, but their buttons need access restrictions.
Only bridge needs doing, waiting for maybe blastdoor sprite.

TODO: After Merge

- [x] Floor Tiles
Mostly Done missing one or two textures, see: https://github.com/unitystation/unitystation/pull/3050#issuecomment-584826812.

- [ ] Doors
Lots of missing sprites, need see through and non-see through versions of all doors + special doors such as vault and AI, see: https://github.com/unitystation/unitystation/pull/3050#issuecomment-584828758.
Also glass window doors need to have their collision boxes fixed.

- [x] Asteroid spawn prevention, stop them spawning on the station
While funny, needs fixing

- [ ] Side Windows
Optional, but would be very nice to have.
- [x] Fire doors
When the PR is done, also optional.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] UPDATE OTHER MAPS TO SUPPORT NEW SHUTTLESCRIPT

- [x] - The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>

- [x] - The PR has been tested in editor

- [ ] - The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

- [ ] - The PR has been tested with round restarts.

- [x] - The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

Picture as of 15/02/2020:

image

### CODE REVIEW

**Comment by ThatDan123** [comment]
Missing Floor Tiles:

image
image


IGNORE BELOW, needs system to support it first.

~~Also all the decorations on tiles needs to be fixed:~~

image

image

**Comment by ThatDan123** [comment]
Missing Door Prefabs are:

See-through Security

See-through Command

See-through Engineering

See-through Cargo

See-through Atmospherics

See-through Medical

See-through Science

Non-see through Public

AI Doors

Vault Door

**Comment by craftxbox** [comment]
what variant box is this?

**Comment by voidel** [comment]
Impressive work.

**Comment by Misterixmax** [comment]
Oh my god!!! Really impressive, cool. How is it with performance?

**Comment by ThatDan123** [comment]
> what variant box is this?

Should be Tg, this is my reference image https://tgstation13.org/wiki//images/d/d1/Boxstation.png

> Oh my god!!! Really impressive, cool. How is it with performance?

Feels good to me but it hasnt been stress tested eg with plasma

**Comment by Bod9001** [comment]
We don't have a system for tile decals yet

**Comment by DooblyNoobly** [comment]
```
Lighting is very buggy atm, hard to work with so i've stopped.
Needs a rework, and the ability for lights to function without switches.
50% complete, all lights are in position, just needed reworking light scripts.
```
Did you add all of the light switches?

**Comment by ThatDan123** [comment]
Ive added all the light switches that are on the base tg boxstation map. But there are lots of places which dont require a light switch, it just feels a bit weird having a light switch for some of those places.

**Comment by Evan-R-Rogers** [comment]
You could disable the Sprite renderer for the light switches to essentially make them invisible as well as hiding them in walls or outside of the station to prevent them from being interacted with.

**Comment by voidel** [comment]
Seems a little bit shonky vs a solution that creates a new type of light that has no requirment on a switch.

**Comment by ThatDan123** [comment]
I've just mapped some temporary light switches.

**Comment by ThatDan123** [comment]
The last stuff that needs to be added/fixed is:

- Fixing glass windows, the collision box does not change when the direction is set.

- And the other door prefabs

Once those are done Box will be in a playable state.

**Comment by ThatDan123** [comment]
There's a bug currently which i cant track down, where you cannot place items on tables on the station matrix, tables work fine on the shuttles but not on the station.

**Comment by DooblyNoobly** [comment]
We can fix up annoying bugs like that for you. How far off are you do you think from removing the DNM?

**Comment by ThatDan123** [comment]
I can put temporary doors in later today, then it should be good to merge.

**Comment by ThatDan123** [comment]
Doobly you can merge box in, ive added the temporary doors.

~~Actually hold for a bit, found a bug.~~

Good to merge.

**Comment by ThatDan123** [comment]
You guys reverting and readding the updatemanager changes has broken my fork.

Dont merge this.

**Comment by ThatDan123** [comment]
Might have fixed it

**Comment by ThatDan123** [comment]
Has been fixed

**Comment by CodeKalias** [comment]
This map also has the Syndicate spawn point set to Robotics, which apparently breaks nuke rounds
(Related to #3210)

**Comment by AutumnNova** [comment]
it very much does, yeah

**Comment by ThatDan123** [comment]
Fixed

**Comment by fomalsd** [comment]
is this ready for review/merge?

**Comment by ThatDan123** [comment]
Yup

**Comment by DooblyNoobly** [comment]
What changes were made on outpoststation?

**Comment by ThatDan123** [comment]
Think my fork is completly messed up, i havnt commited any changes to outpost

**Comment by ThatDan123** [comment]
Ive backed up all the files ive changed, and trying to rebase.

**Comment by ThatDan123** [comment]
https://github.com/unitystation/unitystation/pull/3232

100% blame doobly and foma for their reverting wars :)

**Pull request closed without merging**
