### PR TITLE
More clothing crafting recipes.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Adds a number of crafting recipes involving clothing. 
  - Ports basic cowboy boots from https://github.com/tgstation/tgstation/pull/44880 by @Krysonism. Sadly they cannot have snakes in them (yet).
  - Ports human skin hats fromhttps://github.com/tgstation/tgstation/pull/60032 by @Krysonism and @YakumoChen.
- Edited the ammo crafting menu icon to have more distinct cartridges, courtesy of @Pockets-byte

#### Notes:
@YakumoChen: Human skin hat.
@Krysonism: Cowboy (and lizard skin) boots, human skin hat improvements.
@Pockets-byte: Ammo icon in crafting menu.

### Changelog:
CL: [New] Some animals such as corgis, monkeys, cats, and xenomorphs now drop hides when butchered.
CL: [New] The ClothesDrobe now dispenses cowboy boots.

### CODE REVIEW

**Comment by Bod9001** [comment]
Tests are failing

**Comment by ThatDan123** [comment]
Recipes will have to be added to SO after #7308

**Comment by PetMudstone** [comment]
I will wait for #7308 then.

**Comment by PetMudstone** [comment]
can we remove the merge conflicts label, also this PR passes tests now.

**Review by ThatDan123 — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
