### PR TITLE
Progress Bar Improvements

### LINKED ISSUE #1778: ProgressAction cancels on character turning
# Description
If your character turns, the progress action will stop.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Find anything that uses a progress action, in this case for example, a mop
2.Start cleaning the floor
3.Click behind you
4.Your character will turn and stop the progressaction bar, stopping you from cleaning the floor tile

### LINKED ISSUE #1780: Can't clean more than one tile at the same time
# Description
Probably related to ProgressAction, when using the mop, I can't clean other tiles next to me at the same time unless I cancel the current progress action. I should be able to clean all at the same time

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Click on a tile with a mop to clean it
2.Click on the tiles next to it to clean them at the same time
3.Nothing happens unless my character turns and the progress stops (covered in another issue report)

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #1780 
Fixes #1778 
Partially implements #2204 

Improves usability of progress bar API so it "just works" in the way you would expect and you don't have to write as much boilerplate.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Object-Lifecycle-Best-Practices)
- [x]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Wow, what a slog this was. Main difficulty was the networking and matrix move interactions. Didn't use PoolNetworkInstantiate and register tile / other networking stuff because progress bars only need to be known by one client and one server, don't even want to let other players know a progress bar was instantiated (even if we wouldn't send them the update messages). PoolNetworkInstantiate would've created the object on all clients, even if we never plan on sending any progress update messages it still would've exposed extra info to each client.

Hopefully that's okay that I didn't use registerTile / CNT / objectbehavior. These are more analogous to bullets, which also don't use those things. If it REALLY seems like a problem I can change it to use those, but I have tested it pretty thoroughly.

On the plus side it shows a way that such use cases can be supported if it will be needed for other things that should only be known by server + one client.

### CODE REVIEW

**Comment by fomalsd** [comment]
Haven't looked at this thoroughly yet, but at this point it doesn't fix #1780 – you can't clean more than one tile. Welding multiple tiles simultaneously no longer works, too (while it was possible before but with visual glitches)
GIF0

**Comment by chairbender** [comment]
I definitely tested that, must have regressed something

**Comment by chairbender** [comment]
@fomalsd try again

**Comment by DooblyNoobly** [comment]
- fixed the merge conflicts related to the new chat system

**Comment by DooblyNoobly** [comment]
looking alright. I just need to do some quick fixed with the chat when I merge this

**Pull request merged**
