### PR TITLE
Add Cornelius's redone locker sprites, again. 

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- A redo of #4966, but with completely different sprites.
- Just about every locker sprite has been redone **by Cornelius Bogfrollup Fitzgerald** , with a few new additions as well.
   - Unlike #4966, the lockers in this PR aren't as big. They're still bigger than 32x32 though.
   - Coffins also included.
   - Makes the tops of lockers into separate overlays to somewhat get around #4937 for the time being.
   - Adds one small and one large locker using old sprites.
Neu Lockers
- Makes lockers use sprite handlers for their frames, not the doors though.

A selection of lockers in-game.
image
New locker in the middle, old large locker on the right, and a small locker similar in size to /tg/ ones on the left.
image

### Notes:
- Cornelius made animated opening and closing sprites for the abductor's closet, but making them work is beyond my abilities at the moment. I've put the animated sprites in the asset library.

### CODE REVIEW

**Comment by PetMudstone** [comment]
Give me a few, looks like the lockers are offset in unsatisfactory ways.

**Comment by Aranclanos** [comment]
you should post screenshots of the lockers ingame, specially when there's a few alligned in a vertical line

**Comment by PetMudstone** [comment]
I was gonna do that, when I noticed everything was offset in ways they shouldn't be. Working on it.

**Comment by corp-0** [comment]
I'm adding a DNM until you're done with that. Please let me know.

**Pull request merged**
