### PR TITLE
Big refactor - Inventory / Lifecycle / Traits / Occupations

### LINKED ISSUE #956: Item type and damage recategorization
# Preliminary information

## Category
TODO

# Report
## Current Behavior
Items are not categorized correctly

## Expected/Wanted/Requested Behavior
Currently all items are categorized into types.  These types are things like Hat, Gloves, etc.

However, they also have the type of Gun, Knife and Food in this list.

This is logically inconsistent and will cause problems down the road.  Types should be the slot they are equipped in.  Gun, Knife and Food should be changed to "Usable".  Instances of Gun, Knife and Food should be removed in the code, and handled another way.

This will allow things like bashing with a air tank, because right now since an air tank is a back item it cannot be a weapon.

This will tie into #953 and #957

### LINKED ISSUE #1699: Inventory can mess up
# Description
had inventory fail on me in a weird way:
Scr 2019-04-03 в 0 36 11 2019-04-03 10_01_11

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
**Was unable to reproduce it again**, but what I did was:
1. Launched game from Outpost scene and joined as miner
2. Walked around station and across matrices, equipped and unequipped mask, finally got ejected into space in crit
3. Killed myself with a "Kill local player" command and respawned (a couple of times)

### LINKED ISSUE #1802: New player welcome message job name inconsistency
# Description
image
"Hos Edgar Butterfill has arrived at the station. Have a pleasant day! Try not to die..."

The issue is that HOS is spelled Hos.

## Category
BUG

### LINKED ISSUE #1946: UI indication of where you can place items
# Description
have a transparent green or red picture of the icon of the item when you mouse over a inventory slot 
red for not fit
and green for fit	

## Category
TODO

### LINKED ISSUE #2022: a standard way to test if a game object is a certain object E.G. a crowbar
# Description
So you want to test if someone has a fire extinguisher in there inventory, 
 Currently the only ways to observe what the item is, is to
A Get component for a component that's only on that item
B Test the name of the game Object

## Category
TODO

## Proposal
I say to have some type of standard systems items like item attributes that is unique to every prefab item, so you can easily tell that yes this is a clownmask/Fire extinguisher/any other item you could think of

Is only meant for doing generic interactions, like construction you just want a fire extinguisher (As one of the parts needed for the construction), you don't want to have to add custom code for that simple interaction

### LINKED ISSUE #2091: Allow spawning custom prefabs as part of job outfits
# Description
Currently job outfits only accept a list of hierarchy strings for each slot, and these are treated as UniClothes. 
You can't make players spawn with certain prefabs in their slots though (clown with a bike horn etc).
This needs to be addressed

### LINKED ISSUE #2211: PlayerLightControl does not remove light when object is thrown
# Description
While holding an item that emits light, such as a handheld torch, it adds itself to a list on the player for lightsources. PlayerLightControl listens for pickup and drop to determine when to add and remove the light from the player. However, it does not listen for throws, meaning that the light it was giving will stay on the player.

## Category
BUG

## Steps to Reproduce
1. Spawn a Handheld Torch
2. Optionally, go to maint or break lights to see effect better
3. Throw the torch
4. Observe that you will still be radiant

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Big refactoring modifying and building several interrelated systems focused on improving developer usability and long-term extensibility. 

  * Implements a new [Inventory System](https://github.com/unitystation/unitystation/wiki/Inventory-System) 
  * Significantly changes the [object lifecycle / spawning and despawning API](https://github.com/unitystation/unitystation/wiki/Proper-Spawning-and-Despawning-%28Object-Lifecycle%29)
  * Adds [Item Traits](https://github.com/unitystation/unitystation/wiki/Item-Traits-System)
  * Refactors how jobs are defined to use SOs, now dubbed [Occupations](https://github.com/unitystation/unitystation/wiki/Occupations)

Fixes #1946 
Fixes #2022 
Fixes #2211 
Fixes #2091 
Fixes #1802 
Fixes #1699 
Fixes #956 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Object-Lifecycle-Best-Practices)
- [x]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by fomalsd** [comment]
I assume this fixes #2129 and #2080?

**Comment by chairbender** [comment]
@fomalsd not 2080, it's in place as a prerequisite for 2080. It should fix 2129 though. There's a few other possibly related tickets but I was planning to go through and test to make sure they're fixed later when I review our backlog.

**Comment by chairbender** [comment]
added Fixes #1946 
Fixes #2022

**Comment by chairbender** [comment]
added fixes #2221 , #1802 , #1699 , #956 
also added fixes #2091 but I want @fomalsd to confirm this addresses that ticket to his satisfaction

**Review by fomalsd — APPROVED** [review]
awesome, excellent work!

**Pull request merged**
