### PR TITLE
Bounty Balancing and Chem Changes

### PR DESCRIPTION
**Pull request by AtnerNT**
This PR also includes some backend changes that are listed here:
Chemistry.Effects assembly has been moved to Assets

The effect array in reactions is now a dictionary with an int value (like ingredients and results). This removes the need for 'intermediate reagents', Whose only purpose was to control the severity of the effect. As such, these now useless reagents have been removed. I.E the reagent "Foam"'s only purpose was to spontaneously reaction into foam. Now the foaming reaction (Fluorosurfactant + water), immediately produces a foam effect.

### Changelog:

CL: [New] Stabilizing Agent may now be used to stabilize the smoke reaction to form smoke powder, which will smoke itself at 374K at one third the potency of the raw smoke reaction. (See TG wiki)
CL: [New] 3 new bounties have been added. One for EMP grenades, one for a variant of EMP grenades and one for a wholly smart foam grenade.

CL: [Improvement] A number of explosive bounties will now have names, describing what explosive you are attempting to make.

CL: [Balance] Required reactions in explosive bounties will now only be in quantities that are an integer multiplier of the reaction result. (If a reaction results in 3u of a chemical, required reaction will be a multiple of 3u).  Players will no longer be required to work with fractional u values. All bounty requirements may be met by use of only the chem dispenser and eyedroppers.

CL: [Fix] BYD yield values are now more accurate for chemical grenades.

### CODE REVIEW

**Comment by AtnerNT** [comment]
Failing code scan:
> Sandbox violation: Access to type not allowed: [UnityEngine.UnityWebRequestModule]UnityEngine.Networking.UnityWebRequest asmName Chemistry
Sandbox violation: Access to type not allowed: [netstandard]System.Collections.Specialized.BitVector32 asmName Chemistry
Chemistry.dll Failed scanning Cancelling

Not part of the changes in this PR so unsure why its only failing now.
@Bod9001 Unsure what I need to change here, what do I need to the codeScanWhiteList to make this work ^

**Comment by Bod9001** [comment]
What uses BitVector32 ?

**Comment by Bod9001** [comment]
did you update the smartFoamand foam grenades in engineering?

**Review by MaxIsJoe — APPROVED** [review]
Code looks good

**Comment by MaxIsJoe** [comment]
Waiting on Atner to respond to Bod's question

**Pull request merged**
