### PR TITLE
Update portable air pump sprites with Tex's. Update canister descriptions. Add more canisters to cargo list.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
 - Update the sprites for portable air pumps [with ones by Tex](https://github.com/yogstation13/Yogstation/pull/9496).
 - Update descriptions for canisters.
 - Remove tier overlay sprites on canister objects since they don't work well with the candidates for new sprites.
 - Add some canisters to the cargo list.

### CODE REVIEW

**Comment by Bod9001** [comment]
wasn't Cornelius working on canister sprites, https://cdn.discordapp.com/attachments/315652489544335361/740940406510059610/Untitled-2.png

**Comment by Bod9001** [comment]
imo the current canister sprites look perfectly fine

**Comment by PetMudstone** [comment]
Hmm, perhaps I can remove the canister sprites from this PR if you need me to. I think I'll keep the .prefab changes and the portable air pump sprites though.

**Comment by Bod9001** [comment]
think it's a good idea to talk with Cornelius  about it

**Comment by ReiderJack** [comment]
I like Cornelius  sprite more because you can see that it's a canister. This one is too noisy in my opinion.

**Comment by PetMudstone** [comment]
I've undone the changes to the canister sprites.

**Comment by corp-0** [comment]
All good to merge now?

**Comment by PetMudstone** [comment]
Yes, all good to merge.

**Pull request merged**
