### PR TITLE
Allow Xenos to become queens

### PR DESCRIPTION
**Pull request by corp-0**
### Purpose
This expands the xeno lifecycle in an attempt to preserve the perfect life form. Once spawned, xenos will check the amount of queens in the current round and in case the set cap (defaults to 1) isn't reached, they will try to become a queen themselves.

### Notes:
Minor changes:
- Converted death and random hostile sounds to Addressables, I set the Xeno sounds, the rest need setting.
- Might have fixed Queens not laying eggs.
- Increased the hugger cap for queens to 20 (it was 8). They weren't laying eggs because the huggers in caverna were enough to reach the cap.

CL: Xenomorphs can become Queens now if there are no Queens in the round.
CL: Fixed Queens not laying eggs.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
Might run into some weird edge cases where drones won't level up because the extra scenes like away sites start with queens. Caverna being the main one that comes to mind

**Comment by corp-0** [comment]
Yep. It happened already with huggers as stated in the description. If there is a queen in caverna, then the xenos will never become one. The cap can be tweaked per xeno if we wanted.

**Comment by PerfectTangent** [comment]
Could you make it check by matrix?

**Comment by PerfectTangent** [comment]
Could also make the xeno queen in caverna not count towards the cap.

**Comment by corp-0** [comment]
I think I like the last better. I can add a toggle box that would avoid that particular instance of the ai to count.

**Comment by Mute-Man** [comment]
what does space count as? is it its own matrix? 
if queens were counted by matrix, which matrix would xenos in space count as being on

**Comment by corp-0** [comment]
space is part of main station matrix afaik

**Comment by Mute-Man** [comment]
wack

**Comment by corp-0** [comment]
Checked caverna. It doesn't directly spawn mobs but uses a system to spawn mobs only after someone put a feet on the matrix so I can't really change anything about how they count.

**Comment by Bod9001** [comment]
good to merge?

**Comment by corp-0** [comment]
imo ye

**Pull request merged**
