### PR TITLE
AccessModule Change

### PR DESCRIPTION
**Pull request by ThatDan123**
-No longer use Access Restriction for doors (keeping on prefab for now in case someone wants to keep their scene changes are redo the migration)

- Merge after #9081 has been merged

### CODE REVIEW

**Review by corp-0 — APPROVED** [review]

**Comment by corp-0** [comment]
What's holding it?

**Comment by ThatDan123** [comment]
Think Jack was doing some scene stuff

**Comment by corp-0** [comment]
I already merged the other one, oof. If Jack's still doing mapping, we can revert it

**Comment by ThatDan123** [comment]
> What's holding it?

Oh, i think Noooney just put it on hold until the other PR was merged so its fine

**Comment by NoooneyDude** [comment]
Do we still want to hold (for Jack now) or all good?

**Comment by ThatDan123** [comment]
Jack can always just keep his changes from his branch and then redo the migration for those scenes, we wouldnt need to revert

**Pull request merged**
