### PR TITLE
Quick fix for #5163

### LINKED ISSUE #5163: Can weld self inside closet
## Description
Right now you can weld yourself inside a closet, you can also secure a closet whiles inside it. 

### Detailed Bug Report
Due to old implementation of breaking out of a locker, when ever you move inside a locked or welded locker you will try to use whatever is in your hand. also if your hand is empty you get the following error 
`
NullReferenceException: Object reference not set to an instance of an object
ClosetControl.ServerPerformInteraction (HandApply interaction) (at Assets/Scripts/Closets/ClosetControl.cs:506)
`

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Enter any closet with a weldgun 
2.  Weld the locker with harm
3. Try to move any direction and you will start de-welding 
4. remove welder from hand to see error msg.

### PR DESCRIPTION
**Pull request by jamessimo**
+ Player can no longer weld themselves inside or wrench a closet whiles inside it
+ Added a catch for when the player doesn't exist (needed for future resist/breakout code)
+ Removed some TODOs + minor cleanup

### CODE REVIEW

**Comment by corp-0** [comment]
When your PR closes a particular issue, you can type something like:
fixes #5163 or closes #5163 in the pr description so it automatically closes on merge.

**Comment by corp-0** [comment]
Did you forget to commit your changes? GitHub shows only white space changes.

**Comment by Bod9001** [comment]
yeah, can only see whitespace changes

**Comment by jamessimo** [comment]
I’m gonna close this, I think something has gone wrong. Let me recheck and try again

**Pull request closed without merging**
