### PR TITLE
Improve startup time.

### PR DESCRIPTION
**Pull request by RedlineTriad**
### Purpose
This should decrease start-up time by:

1. Remove UpdateManager safety checks.
2. Remove RoomNumber from atmos.

### Notes:
The UpdateManager safety checks for adding had a large performance impact due to `List.Contains()` having `n/2` complexity.

The UpdateManager safety checks for removing implemented checked if it even existed but that is not needed and is done automatically by `List.Remove()` is used `List.Contains()` for checks which had a large performance impact.

Atmos used a flood-fill algorithm for every single tile on every matrix to assign room-numbers, as these numbers aren't used by any used code I removed them.

I removed an unused script which caused MissingReference tests to fail on old maps, rather than updating or removing them I changed it so tests don't check maps that aren't included in build.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- [ ] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
yesssssssss

**Comment by ThatDan123** [comment]
You done goofed

You removed atmos.

**Comment by DooblyNoobly** [comment]
who needs atmos anyway

**Comment by PetMudstone** [comment]
Redline, give me back my atmospherics!

**Comment by DooblyNoobly** [comment]
Im reverting it. I was the one who goofed.

**Pull request merged**
