### PR TITLE
New Songs and SFX

### PR DESCRIPTION
**Pull request by Buldinn**
Added:

7 new Adminmusics
  The Settler - Chris Remo
  Miniboss Fight - Skidrow
  Clownman - Onulle
  h-o-n-k-e-r-s - Onulle
  Honkman - Onulle
  SilentHonk2 - Wandering Show
  The Challenge - Komiku

1 new Lobbymusic
  Clownman

3 new RoundEnd SFX
  AssBlastUSA
  Roleplay
  EscapingToSPAACE

2 new Effects
  FemurBreakScream
  ShyguyScream

Edited:
 Most songs volumes from .25 to .225

Removed:
Some songs from the lobby music pool, keeping them as Admin play only. These are songs meant for admin spawned game modes/events and should be kept rarely heard.
  Thunderdome
  SpaceManatees
  JourneyOfTheSorcerer

### CODE REVIEW

**Comment by corp-0** [comment]
what's the licensing situation of all of these? Everything safe, I imagine.

**Comment by Buldinn** [comment]
Yea its all good to go, I have direct permission to play any song uploaded
from the creators and/or they were part of bay or tgs git

**Comment by Buldinn** [comment]
was not implemented.

Checked assets and with other engineers. Everything looks correct and plays fine in playtesting.

Does not work on live servers.

**Comment by Buldinn** [comment]
Nevermind. I forgot to upload the SoundManager.Prefab lol.

**Pull request merged**
