### PR TITLE
refactor: separate server public and secret information into 2 different config files

### PR DESCRIPTION
**Pull request by corp-0**
### Purpose
Because of the way we build the docker images for our servers, having both information meant to be public and secret in the same file becomes a security issue as discussed in #conference-room channel in Discord.

Separating both files means we can mount the secrets to the container so they are never set in the docker image.

### Notes
I need to test it a little bit more to make sure I didn't break stuff and I might have to also update the build script.

### CODE REVIEW

**Comment by corp-0** [comment]
for easier time reviewing, read the commits instead of all changes at once

**Comment by NoooneyDude** [comment]
Looks good. Perhaps we should be committing example json files e.g. `secrets.json.example` with `secrets.json` gitignored?

I wonder if we could move these files closer to root, too, they're not easily discoverable at the moment.

**Comment by corp-0** [comment]
> Looks good. Perhaps we should be committing example json files e.g. `secrets.json.example` with `secrets.json` gitignored?
> 
> I wonder if we could move these files closer to root, too, they're not easily discoverable at the moment.

Uhmm, Im already committing a file as example but it is called like the real deal

**Comment by Bod9001** [comment]
what's this waiting on?

**Comment by corp-0** [comment]
> what's this waiting on?

Manual tests to make sure I didn't break anything. Also merging this isn't too security now that Redline made me realise I wasn't fixing the issue with this and the first suspect now is the build script alone

**Comment by Bod9001** [comment]
ok cool

**Comment by corp-0** [comment]
found no issue trying locally with two builds

**Review by NoooneyDude — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]

**Comment by Bod9001** [comment]
should the build script be updated before merging or after?

**Comment by corp-0** [comment]
> should the build script be updated before merging or after?

Yes it should, thank god you guys didn't merge this yet lol

**Comment by corp-0** [comment]
I have to re do this one, closing for now

**Pull request closed without merging**
