### PR TITLE
Getting riid of non  parentted prefabs

### PR DESCRIPTION
**Pull request by Bod9001**
ok, So not all of the prefabs have been set up to use the new ones, this is just adding the new ones and not mapping them yet, 
The next PR will be me remapping them and then testing

### CODE REVIEW

**Review by MaxIsJoe — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
tests are failing

**Comment by corp-0** [comment]
nooooo, you called the prefabs "new X" ? That is going to be so annoying when the old ones are nuked

**Comment by MaxIsJoe** [comment]
This is V2 all over again, nope, bad.

**Comment by Bod9001** [comment]
well we'll be renaming when I  delete the old ones

**Comment by MaxIsJoe** [comment]
Wouldn't this mess with the network manager list if its merged as is?

**Comment by Bod9001** [comment]
well It's only adding?

**Comment by MaxIsJoe** [comment]
> well It's only adding?

are the prefab tracker thingies fully updated?

**Comment by Bod9001** [comment]
looks like scenes are Upsety spaghetti somehow

**Comment by MaxIsJoe** [comment]
which tests are failing?

**Comment by corp-0** [comment]
> well we'll be renaming when I delete the old ones

are there references kept when you do this?

**Review by MaxIsJoe — APPROVED** [review]

**Pull request merged**
