### PR TITLE
Update names

### PR DESCRIPTION
**Pull request by Spessmen14**
Name update

### Purpose
Updates the names of some vending machines.

### Open Questions and Pre-Merge TODOs

- [ ]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [ ]  My code is indented with tabs and not spaces
- [ ]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [ ]  This PR does not bring up any new compile errors
- [ ]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### CODE REVIEW

**Comment by Spessmen14** [comment]
Finally getting the hang of Git; this should take care of the names of all the canisters in the repository. There are still some really oddball gasses on TG wiki I don't see here like Tritium or Stimulum.

**Comment by DooblyNoobly** [comment]
For some reason this removes all of the renamed machines from the map. Are there .meta files associated with the prefab changes at all? I've put a DNM on this PR in the meantime until we can figure out what is causing this problem

**Comment by fomalsd** [comment]
this removes all of the renamed machines from the map, also it's been stale for 13 days. closing

**Comment by DooblyNoobly** [comment]
yeah I did a test just before, if you don't include the meta file changes in your PR @Spessmen14  it breaks everything

**Pull request closed without merging**
