### PR TITLE
Printers, Handcuffs

### LINKED ISSUE #3213: Printers!
As a lawyer I have no way to replicate my legal documents!

Printers keep telling me to put in more paper, but no quantitiy seems to suffice. It's a travesty.

Printing and document copying would make all paper-based professions much more playable.

### LINKED ISSUE #3476: Restraint wait time is hard-coded
## Description

It's currently not possible do change the resist time of individual restraints.

(Resist time describes the amount of time it would take to remove the restraints without another player's help)

### Detailed Bug Report
The restraint overlay has a hard coded value for how long it takes to remove restraints. This value is 30 seconds.
https://github.com/unitystation/unitystation/blob/c9917dfa29ef820868cdd850f37c3a01e1209fa5/UnityProject/Assets/Scripts/Clothing/RestraintOverlay.cs#L92

But restraints have their own variable for how long this should take.  (Currently this value defaults to 0, which should be explicit. E.g. `= 30;`)

https://github.com/unitystation/unitystation/blob/c9917dfa29ef820868cdd850f37c3a01e1209fa5/UnityProject/Assets/Scripts/Items/Others/Restraint.cs#L31

The restraint overlay should use the restraint's resist time instead of a hard-coded value.

### PR DESCRIPTION
**Pull request by Jorge1o1**
# Purpose
Implements Printers (technically Photocopiers)!
Fixes #3213 

Fixes Handcuffs so that they use the Restraint Time set in the prefab
Fixes #3476 

### Notes for Printers:
This is my first substantial contribution to the codebase, so revisions would be appreciated.

Also, if you plan on creating Bureaucracy/Paperwork items in the future, please feel free to make use of the `Bureaucracy.Internal` classes like `Printer` and `Scanner`. The idea behind those classes is that we will be able to share logic for printing, scanning, etc. across a wide range of library machines _without_ having to inherit from other library machines.

### Notes for Handcuffs
This is a small, easy fix. 
1. Replaces a CancellationToken with StopCoroutine for ease of use and parsimony. 
2. Uses the RestraintTime set in the Handcuffs Prefab. 
3. Tweaks the chat to inform the prisoner how long it will take to break those cuffs

### Please make sure you have followed the self checks below before submitting a PR:

- [X] Code is sufficiently commented
- [X] Code is indented with tabs and not spaces
- [X] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [X] The PR does not bring up any new compile errors
- [X] The PR has been tested in editor
- [X] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [X] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [X] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [X] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [X] The PR has been tested with round restarts.
- [X] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by daalta** [comment]
Heh, thanks for tackling those issues! Your implementation looks very clean. Some more comments might be nice, but it's relatively self-explanatory.

**Comment by ThatDan123** [comment]
Sorry jorge forgot my PR had sound manager change

**Comment by Bod9001** [comment]
looks good, should I resolve the conflicts for you?
/Are you going to resolve them?

**Comment by Jorge1o1** [comment]
@Bod9001 please resolve the conflicts for me, I've been away from my computer all day and I won't have a chance to do it till later

**Pull request merged**
