### PR TITLE
Adjusting floor health.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Increases floor integrity, especially base plating integrity, across the board. Now hull breaches shouldn't immediately happen because of a mere water-potassium explosion.
- Moved around "ironsand" tiles into base tile (the ones that floor tiles and cables go over) folder.

### CODE REVIEW

**Comment by Bod9001** [comment]
odd Tests are failing to run, can you run a test on your branch just make sure?

**Comment by corp-0** [comment]
reran the tests so maybe we can merge and build

**Comment by Bod9001** [comment]
they seem to fail for no reason?

**Comment by corp-0** [comment]
yeah, this is weird. No log either to see what's wrong.

**Comment by Bod9001** [comment]
probably github messing up?

**Comment by corp-0** [comment]
you want to merge and see what happens?

**Comment by Bod9001** [comment]
I'll run the tests on the branch

**Comment by Bod9001** [comment]
All tests okay

**Pull request merged**
