### PR TITLE
#2209 Allow adding solid plasma to plasma canisters

### LINKED ISSUE #2209: TODO: Allow solid plasma to be added to Plasma tanks B: 30
# Description

As we don't have a way yet to convert solid plasma into gas we are just going to develop the ability to add the solid plasma directly to the tanks so that shuttles can refuel. We will develop the processing of solid plasma to gas after alpha release.

The player should be able to equip solid plasma in his hand, click on the plasma tank and have an amount of gas added to the tanks contents.

You will need to make yourself familiar with the interaction framework to complete this job: [https://github.com/unitystation/unitystation/wiki/Implementing-Interactions](https://github.com/unitystation/unitystation/wiki/Implementing-Interactions) 

## Criteria:

- Create the ability for players to click on a plasma tank and have the solid plasma be consumed by the tank (see how it is done with the plasma generators)
- Determine how much gas should be added to the tank per solid plasma chunk and add the amount when the plasma chunk is consumed
- Test to make sure that the measured pressure of the tank updates correctly when adding new plasma (On the net tab UI)
- Test to make sure everything works correctly in multiplayer

A bounty of 30 usd will be rewarded to the contributor on a successful merge.

### PR DESCRIPTION
**Pull request by StrawberryMoses**
### Purpose
Fixes #2209. Allows right clicking with plasma in hand to add to a plasma canister. 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Object-Lifecycle-Best-Practices)
- [x]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
I didn't know how to balance this at all, so 1 sheet of plasma adds 15000 moles, which is about 1/4 of a tank. It's easy enough to change.

### CODE REVIEW

**Comment by fomalsd** [comment]
Can you make it so that simply left clicking canister puts gas in as well? This was the original intention. It will be hard for newbies to figure out that you need to right click and find that special item while holding a piece of plasma in your active hand.
Also putting in a piece results in an NRE: 
```
NullReferenceException: Object reference not set to an instance of an object
UpdateSlotMessage.Send (UnityEngine.GameObject recipient, UnityEngine.GameObject item, System.Boolean removeItem, EquipSlot sentEquipSlot) (at Assets/Scripts/Messages/Server/UpdateSlotMessage.cs:32)
InventoryManager.ClearInvSlot (InventorySlot inventorySlot) (at Assets/Scripts/Inventory/InventoryManager.cs:29)
Pickupable.DisappearObject (InventorySlot inventorySlot) (at Assets/Scripts/Items/Pickupable.cs:189)
PlasmaAddable.ServerPerformInteraction (HandApply interaction) (at Assets/Scripts/Objects/PlasmaAddable.cs:43)
InteractionCoordinator`1[T].ServerValidateAndPerform (T interaction) (at Assets/Scripts/Input System/InteractionV2/Helpers/InteractionCoordinator.cs:73)
InteractionComponentUtils.ServerProcessCoordinatedInteraction[T] (T info, InteractionCoordinator`1[T] coordinator) (at Assets/Scripts/Input System/InteractionV2/CoreComponents/InteractionComponentUtils.cs:22)
NBHandApplyInteractable.ServerProcessInteraction (HandApply info) (at Assets/Scripts/Input System/InteractionV2/CoreComponents/NBHandApplyInteractable.cs:75)
RequestHandApplyMessage.ProcessHandApply (UnityEngine.GameObject handObject, UnityEngine.GameObject targetObj, UnityEngine.GameObject processorObj, UnityEngine.GameObject performerObj, HandSlot usedSlot, System.String specificComponent) (at Assets/Scripts/Messages/Client/Interaction/RequestHandApplyMessage.cs:51)
RequestHandApplyMessage+<Process>d__5.MoveNext () (at Assets/Scripts/Messages/Client/Interaction/RequestHandApplyMessage.cs:39)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```

**Comment by StrawberryMoses** [comment]
Will take a look at NRE when I can.
So the right click is in place because at the moment, left clicking on a canister will open up it's gui. This interaction seems to come before every other, and without modifying the base canister prefab or attaching the plasma component straight to the base canister (and placing it at the top) it'll always fire first.

**Comment by chairbender** [comment]
@StrawberryMoses that should be fine to have the plasma component as the first interactable component. ICs are intended to have multiple on a given object, and you just have to decide which order they should be checked in. Just make sure to implement WillInteract on the plasma component so that it doesn't fire when the user doesn't have plasma in their hand.

EDIT: Yeah, dealing with precedence on IF2 is clearly something people are having trouble with, so I'm going to hopefully find a way to make that easier in the next round of improvements to IF2

**Comment by StrawberryMoses** [comment]
I added the plasma addable component to the base prefab so there can be left clicking.

@fomalsd I wasn't seeing the nre- were you just in editor or a build? Multiplayer? (not sure how to reproduce)

**Comment by DooblyNoobly** [comment]
Looks good

**Pull request merged**
