### PR TITLE
Fires now produce light

### PR DESCRIPTION
**Pull request by ThatDan123**
Fully activates fire light.

Fixes gas multi overlays.

Fixes pipes on vents/scrubbers being seen.

Fixes pump sprite being On at round start.

Fixes atmos device layers

Animates vent/scrubbers

### CODE REVIEW

**Comment by ThatDan123** [comment]
Im honestly not trying to make merge conflicts for bod :p

**Comment by Bod9001** [comment]
how does the firelight work?

**Comment by ThatDan123** [comment]
Not sure if its the best way but atm it spawns a light prefab on the tile and then despawns it after. Uses the object pool, and i didnt see any performance issues.

**Comment by Bod9001** [comment]
cool

**Pull request merged**
