### PR TITLE
Adds Ministation, a new Mainstation for low-med pop

### PR DESCRIPTION
**Pull request by AtnerNT**
Nothing more to add other than what's in the title, this PR does not add the map into rotation as per request
Capture

CL: [New] Added Ministation, a low-pop map.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
very pog. might I recommend we don't immediately add it into the map pool until we get a bit of initial testing done.

**Comment by AtnerNT** [comment]
> very pog. might I recommend we don't immediately add it into the map pool until we get a bit of initial testing done.

Easy fix, just removed it now

**Comment by ThatDan123** [comment]
Theres some mapping tests which are failing. Go here, and download the artifact then open it and open the Index.html

https://github.com/unitystation/unitystation/actions/runs/1716990103

**Review by corp-0 — APPROVED** [review]
me like

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
