### PR TITLE
Automatic builds for master, develop and PRs using GitHub Actions

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
  - Adds automatic builds for pushes to develop, master and PRs to those branches
    - All builds include executables for each platform so you can play them easily
    - The Library dir is cached between builds for each version and platform to speed them up a lot
    - Included instructions to update the license file if needed
    - Only gets triggered for changes under the 'Tools/\*\*' and 'UnityProject/**' directories
  - Improved the CLI build scripts to make them work with GH actions

After caching, total build times are ~25 minutes for all platforms (~10 for Windows and Linux, ~25 for OSX 😢  )

#### Note:
To allow it to run on PRs it includes a UnityLicense file I made with a throw away unity account (it can only be used on the GitHub Action servers so I don't think there's anything malicious someone could do with it anyways).

### CODE REVIEW

**Comment by RedlineTriad** [comment]
I am in favor of merging, anyone against?

**Comment by fomalsd** [comment]
No objections

**Comment by RedlineTriad** [comment]
I will merge if it builds then.

**Comment by RedlineTriad** [comment]
Successfully created artifacts for all platforms, merging.

**Pull request merged**
