### PR TITLE
Tests refactor

### PR DESCRIPTION
**Pull request by Copern**
### Purpose
This PR refactors mostly scene, prefab, and ScriptableObject tests. A fluent interface TestReport class was added for integration tests. 

Currently our edit mode tests take a long time. Sometimes up to 20 minutes on my system. The aim of this is to significantly reduce the time it takes to run these tests. With the changes, edit mode tests now take a little under 3 minutes on my system.

Before : 
TestsBefore

After:
TestsAfter

### Notes:
There are no changes to play mode tests.
Yes there's LINQ, but it's for tests. The benefit of not using it is minimal.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
bruh, this is amazing.

**Comment by Bod9001** [comment]
45m  vs 35m~ About 10 minutes save so that's good

**Review by Bod9001 — APPROVED** [review]

**Comment by CdrCross** [comment]
> 45m vs 35m~ About 10 minutes save so that's good

That on your PC? Copern took it from about 20mins down to below 3mins.

**Comment by PerfectTangent** [comment]
> That on your PC? 

no, that's on the github unit testing.

**Comment by PerfectTangent** [comment]
It's closer to about 20 minutes saved though. Most of the time it takes about 50-60 minutes.

**Pull request merged**
