### PR TITLE
Creates Asset Library

### PR DESCRIPTION
**Pull request by CdrCross**
Every single well made and formatted sprite from the US13 Discord that we have not yer used, have been added to the AssetLibrbary folder at the repo source so that they can be accessed by anyone.

### Purpose
So far, we artists who have made assets which aren't tied directly to a feature in the making, have had to bury their work somewhere in the resources folder. The AssetLibrary folder exists as an organized place to offload art assets which are free to use but aren't yet earmarked for a particular addition to the game.

### CODE REVIEW

**Comment by Bod9001** [comment]
looks good, Just noting that this won't show up in the Unity editor so will have to be manually searched through but a good repository of assets

**Comment by corp-0** [comment]
Would you mind moving stuff to categorized folders? So you only see folders when you open AssetsLibrary

**Comment by corp-0** [comment]
> looks good, Just noting that this won't show up in the Unity editor so will have to be manually searched through but a good repository of assets

That's fine. We move stuff from here to the project when we're developing something and we need the sprite.

We should also use this to move unused stuff from the project to the library

**Comment by CdrCross** [comment]
> 
> 
> Would you mind moving stuff to categorized folders? So you only see folders when you open AssetsLibrary

I'd like to wait with that until a bit more stuff has been added. I don't have the faintest idea what categories will actually be needed, so it seems better to let the chips fall as they may, and then fashion categories a little later.

**Comment by corp-0** [comment]
You can take inspiration in the structure inside the project folder. See ``UnityProject/Assets/Textures``. That's where EVERYTHING imported from tg resides at the moment, including unused stuff.

**Comment by CdrCross** [comment]
> 
> 
> You can take inspiration in the structure inside the project folder. See `UnityProject/Assets/Textures`. That's where EVERYTHING imported from tg resides at the moment, including unused stuff.

Allright then, I can do that. Can I amend this PR to contain the changes?

**Comment by corp-0** [comment]
> Allright then, I can do that. Can I amend this PR to contain the changes?

Yes. Just commit your changes and push to your repo. All new commits will also appear here.

**Comment by CdrCross** [comment]
There we go.

**Review by corp-0 — APPROVED** [review]
Bod got here first, if he is also pleased he can merge.

**Pull request merged**
