### PR TITLE
Update Centcom ERT rooms and access, adds combat defibs to syndicate shuttles

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

This PR updates the centcom and fallstation centcom rooms to be more prepared for when ERT alert levels are added and to make it harder for ERTs to steal deathsquad weaponry. To do this, centcom_ert and centcom_specops access types were uncommented and added to ERTs and deathsquad to separate their equipment.

This PR also adds combat defibs and kits to the syndicate shuttle scenes and does a slight makeover to the fall centcom shuttles so they are roomier and hold more useful equipment like emergency oxygen supplies.

### Changelog:

CL: [Balance] the syndicate shuttles have gained combat defibs and combat medkits.
CL: [Fix] the deathsquad room in the centcom base now requires access unavailable to ERTs to prevent them from getting gear they are not supposed to have.

### CODE REVIEW

**Comment by craftxbox** [comment]
Any pictures of the changes?

**Comment by PerfectTangent** [comment]
> Any pictures of the changes?

there isn't much to show. I just made the shuttles a bit larger and separated the ERT shuttle into two rooms. If you must see it, I can post after the playtest.

**Review by corp-0 — APPROVED** [review]

**Comment by PerfectTangent** [comment]
Screenshot 2022-04-24 080437


Screenshot 2022-04-24 080530

**Comment by PerfectTangent** [comment]
ignore the shuttle heaters. they are a fuck and need to be reparented.

**Pull request merged**
