### PR TITLE
PogStationREDUX

### PR DESCRIPTION
**Pull request by LastCaptainBonk**
While the map still has an energy problem, the map is essentially done. When said energy problem is sorted, then I believe that the map is done for good.

PogStationREDUX is an attempt to revive and maintain the station known as "PogStation" after the previous mappers stopped working on it.

Notes:
Energy still seems to be a problem on the map.

 Changelog:
CL: [New] Added fully functional AI Satellite with power, an upload, control room, and a chamber, all including turrets on PogStation.
CL: [New] Added fully functional xenoarchaeology and updates to the entirety of science on PogStation.
CL: [Improvement] Added DNA console and a mutation grabber to genetics, with their own pet monkey named Lucy on PogStation.
CL: [Improvement] Added machines and trinkets into virology, such as the biochemical analyzer on PogStation.
CL: [New] Added cameras throughout the entire station on PogStation.
CL: [New] Added air control units throughout the entire station on PogStation.
CL: [New] Added cell timers (to the best of my ability) in security next to the five non-perma cells.
CL: [New] Added evil clown chamber to science on PogStation.
CL: [New] Added toxins, with both atmospheric (gas mixers/filters) and chemical equipment (chemical dispensers, chemical grenade casings, etc.) on PogStation.
CL: [New] Added an EVA room containing magboots, toolbelts, and suit on PogStations.
CL: [New] Added public order terminals to the parts of the station that needed them in engineering, security, science, cargo, service departments, command, AI satellite, and one in the tool closet on PogStation.
CL: [New] Added techfabs to most departments and research server to science on PogStation.
CL: [New] Added Telecommunications satellite East of science on PogStation.
CL: [New] Added some references to those who participated in Unitystation and PogStation as a little wink and nod on PogStation.
CL: [Improvement] Redesigned a lot of areas on the map to be more stylized, such as replacing the "SPACE STATION 13" sign at evacuation with "POG" and making the vault a much more secure area with heavy firelocks and turrets on PogStation.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
please follow our changelog format guidelines

use `CL: [Fix/Improvement/New] your change in explicit detail`

**Review by MaxIsJoe — DISMISSED** [review]

**Comment by LastCaptainBonk** [comment]
Seems to be a memleak issue as well...

**Comment by corp-0** [comment]
you are pushing some unwated changes. It should only be the map

**Comment by eurtod** [comment]
woohoo goodjob bonk!

**Comment by ThatDan123** [comment]
Tests are failing for pog.

If you go here https://github.com/unitystation/unitystation/actions/runs/4273889799

And scroll down and download the Test Results artifact you can see what is wrong by opening the index.html file.

You'll see there's issues with:

-GeneralSceneTests(PogStation)
-PipeTests(PogStation)
-PowerAndLightsSceneTests(PogStation)

**Review by NoooneyDude — APPROVED** [review]

**Pull request merged**
