### PR TITLE
General purpose fixes2

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:

CL: [Improvement] walk in disposals now grabs a piece of air when closing

 CL: [Fix] fixes glass duplication glitch with glass table deconstructing while climbing onto it

### CODE REVIEW

**Comment by corp-0** [comment]
> walk in disposals now grabs a piece of their when closing

I did not understand

**Comment by Bod9001** [comment]
walk in disposals now grabs a piece of air when closing
*

**Comment by corp-0** [comment]
Shouldn't the IsSealed be set the other way around then? First false, equalize, then true

**Comment by Bod9001** [comment]
the problem is if it's not Sealed that grabs the tile mix as internal mix

**Pull request merged**
