### PR TITLE
Staging Fixes and Balancing

### LINKED ISSUE #9980: [BUG] The Photo Copier does not work.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23071519

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

The photocopier in Libraries and where ever else do not work. You can't insert papers into it after opening the tray or fill it up with papers to be copied on to. The highlight on the item when holding the paper just goes away and you can't interact with it. onto

### What should have happened instead?

Should be able to put paper in scanner and tray.the 

### Steps to reproduce the issue

1. Go to a photo copier
2. Open the scanner
3. Try to put paper in it

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AtnerNT**
Not putting this in changelog as it is a behind the scenes fix, but the techwebSO now works again. Our Json library cant serialize the UnityColor struct. So now it is serialised as a System.Drawing Color struct, and then converted to a Unity Color struct when the file is imported.

Closes #9980
### Changelog:

CL: [Balance] Artifacts can now spawn in lavaland
CL: [Balance] Lavaland air is now appropriately hot.
CL: [Balance] Cyborg battery packs now on techweb.
CL: [Balance] AP hardsuit helmet now has a light cone as opposed to a point light

CL: [Improvement] Minor resprite for AP hardsuit helmet.

CL: [Fix] Fixed not being able to load photocopiers with paper.
CL: [Fix] Fixed not being able to craft butter.
CL: [Fix] Fixed not being able to cut killer tomatoes
CL: [Fix] Fixed not being able store folders in file cabinets.
CL: [Fix] Fixed atmos pipes being uninteractable once unsecured.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
Looks good, just fix tests.

**Comment by Bod9001** [comment]
this might conflict with File saver PR

**Comment by AtnerNT** [comment]
> this might conflict with File saver PR

Ah yeah they both modify TechWebImporter.cs... Depends how they are merged though, they both edit difference lines of the script, don't think they will conflict?

**Comment by AtnerNT** [comment]
hmm they probably will actually

**Comment by AtnerNT** [comment]
> Looks good, just fix tests.

Tests should pass now, although this might still conflict with Filesaver PR, not sure best course of action with that though

**Comment by eurtod** [comment]
you are my hero atner

**Comment by corp-0** [comment]
> not sure best course of action with that though

Bod goes first, as it is a foundational change. You will need to rebase and re apply your changes adjusting it so both things can work.

**Comment by AtnerNT** [comment]
Once tests pass, merge ready

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
