### PR TITLE
Basic botany

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
To add botany

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [?]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Proper-Spawning-and-Despawning-%28Object-Lifecycle%29)
- [x (but I think Something else was breaking the round restart)]  This PR has been tested with round restarts.
- [ ]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Plants can be found on Some of the asteroids, 
Plants can mutate
This is only meant to be a basic botany staging post, kind of like a starter kit

### CODE REVIEW

**Comment by Bod9001** [comment]
I'm not touching the web editor, Since I always accidentally merge it if I do Anything with it xD,
It's just a simple  job though

**Comment by chairbender** [comment]
@Bod9001 reviewing, please do the needful (can you fix the merge conflict)

**Comment by chairbender** [comment]
A few issues I noticed but overall it is working and will be a welcome addition! In the interest of not blocking other ongoing work I'll go ahead and merge this, but I have some issues to call out:

1. Growth sprites are not synced upon client re-joining - the plants appear blank in the hydroponics tray until they change sprites.
2. Probably that same issue affects the flashing lights on the trays but I couldn't confirm
3. Seed packets have some z fighting issues where they flicker which one is on top when in a stack and when you click the stack you don't always get the top one, they need to pick some arbitrary sorting index so this doesn't happen
4. I think harvested stuff should probably be Stackable? You can add this component to them.

**Comment by Bod9001** [comment]
in the the original game the produce wasn't stackable but If you get a plant bag They stack Inside of the  plant bag

**Pull request merged**
