### PR TITLE
Stating fixs

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [New] Made the possess right click option work only if you are the server or an admin
CL: [Improvement] Slime cores now have their colour in their names.
CL: [Fix] Fixed Space damage being too strong
CL: [Fix] Fixed release gas reaction when done in inventory not releasing gas at all.
CL: [Fix] Slime processor can now handle multiple cores.
CL: [Fix] Prevents Slimes from double eating something
CL: [Fix] Hopefully fixed the wizard Teleport kick

### CODE REVIEW

**Comment by corp-0** [comment]
> Fixed release gas reaction when done in inventory

What was wrong with it?

**Comment by corp-0** [comment]
Can you fix the slimes being called "Cuban Pete"? I imagine it is just changing the name in their character sheets when you spawn them. Same with monkeys.

**Comment by Bod9001** [comment]
what should they be called?

**Comment by Bod9001** [comment]
"What was wrong with it?"
it would use the local position of the object that would be hidden pos, now it should actually grab the Official position then convert it to local

**Comment by corp-0** [comment]
> what should they be called?

Slime, Monkey. Could be fun to give them some more personality by randomly picking adjectives so you have Courageous Monkey... Maybe. But just Slime and Monkey is fine I think.

> it would use the local position of the object that would be hidden pos, now it should actually grab the Official position then convert it to loca

in terms of what the players experienced. What was wrong? What did a player see when this bug happened.

**Comment by Bod9001** [comment]
it wouldn't release gas at all

**Comment by corp-0** [comment]
Will you do the name fix for monkeys and slimes? 

Also, your last commit will conflict with your other PR

**Comment by Bod9001** [comment]
I can do if you want to?

**Comment by corp-0** [comment]
> I can do if you want to?

Please

**Comment by Bod9001** [comment]
done

**Comment by corp-0** [comment]
You change it in the prefab? I would have thought it was changed in the CharacterSheet

**Review by corp-0 — APPROVED** [review]

**Comment by corp-0** [comment]
nvm I saw the CharacterSheet is exposd to the prefab so that's perfect.

**Pull request merged**
