### PR TITLE
A Fix to the ghost visibility issues.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
### Purpose

Fixes an issue reported in #6195 and ticks off one box in #6276 

### Changelog:
CL: Fixes ghost sprites visibility issues.

### CODE REVIEW

**Comment by Aranclanos** [comment]
How to properly fix bugs:
step 1: find out whats causing it
step 2: fix it with that knowledge

I dont want to see any coroutines that just generate more problems down the line merged

**Comment by MaxIsJoe** [comment]
> How to properly fix bugs:
> step 1: find out whats causing it

Can't be recreated easily and every time I ask someone about it they just give me possible scenarios for what could cause it, so I'm going with the most likely scenario as to why this is happening.

**Comment by Aranclanos** [comment]
sometimes its hard

**Comment by MaxIsJoe** [comment]
It's been confirmed by @Aranclanos that this issue happens on headless servers.
However I have yet to find this issue again while testing using the latest PRs in develop.

Could it be fixed? Needs more testing and for others to also hop on and test this possible fix I made.

**Comment by Aranclanos** [comment]
problem still exists on yesterday's staging build for admins only.
it's heavily related to https://github.com/Aranclanos/unitystation/blob/6aabf31842bed562c051d914cb92198ce7ba66cc/UnityProject/Assets/Scripts/Messages/Server/AdminTools/AdminEnableMessage.cs addition and the following changes during the mirror update on this file.

You have all the tools needed to recreate it now to perform a proper fix

**Comment by MaxIsJoe** [comment]
This solution I pushed actually fixes this issue, tested and works on headless and localserver.

We can merge now.

**Comment by Aranclanos** [comment]
This is still not good enough, which itemslot is the admin trying to fetch and why is he missing it?

**Comment by MaxIsJoe** [comment]
> This is still not good enough, which itemslot is the admin trying to fetch and why is he missing it?

there are no itemslots to begin with so I have no idea why it's trying to fetch itemslots,
Either way this kind of change is needed to avoid issues like this in the future and to tell people what's the problem. Someone else can worry about getting rid of this error log later, right now pushing a fix is more important.

**Comment by Bod9001** [comment]
Aranclanos is adamant

**Comment by MaxIsJoe** [comment]
> Aranclanos is adamant

And I did what my bounty told me to do, I fixed an issue and made a PR for it.
It's not a game breaking problem so I don't need to cover something outside of my bounty.

**Comment by Aranclanos** [comment]
That just makes it worse, you're just placing a null check for something that shouldn't be EVER null for a bounty, which should require more effort than this, lazy coding shouldn't be rewarded.
And this is after I spent hours doing the research for you when you claimed it was impossible to recreate it, doing builds and testing, pointing out the exact problems and where to continue investigating towards the real cause of the issue. 

Stop being lazy, find the real reason of the bug and fix it.

**Comment by PerfectTangent** [comment]
> > Aranclanos is adamant
> 
> And I did what my bounty told me to do, I fixed an issue and made a PR for it.
> It's not a game breaking problem so I don't need to cover something outside of my bounty.

you do have to complete it to our standards to qualify for the bounty and Aranclanos is a code reviewer. If he sees a problem consider taking the advice.

**Comment by MaxIsJoe** [comment]
> That just makes it worse, you're just placing a null check for something that shouldn't be EVER null for a bounty, which should require more effort than this, lazy coding shouldn't be rewarded.

A fix is a fix, regardless of what you did to fix that issue.

> Stop being lazy, find the real reason of the bug and fix it.

I'm not lazy coding, I'm just fixing a very specific issue and I don't need to go beyond what's needed to be done. If I wanted to lazy code I would have done what Bod did with `characterroll()` and just commented out the entire thing and called it a day.
Actually no one on this project has the right to criticize or call anyone lazy for ANYTHING when the health update was merged in it's broken state because of one the reasons was "Bod was sick of working on it" and Gillies tried defending this terrible decision by ignoring their argument and trying to use the fact that me and them were frustrated by how low quality this merge was and how a lot of the code was terrible and undocumented against them saying "have a civil discussion or leave".

It's 100% hypocritical to tell anyone on this project that they're lazy when the entire feature freeze that we're in is because of the result of people being lazy as well.

Am I going to keep pointing out how terrible this decision is? Yes. And I will continue doing so in every given moment until the steam release. Anyways, going to go find a "fix with more effort" and if I don't find it by Monday, we merge without questions.

**Comment by PerfectTangent** [comment]
> It's 100% hypocritical to say that anyone on this project is lazy when the entire feature freeze that we're in is because of the result of people being lazy as well

Two wrongs don't make a right. If we don't improve our standards, then the same thing will happen again.

> Anyways, going to go find a "fix with more effort" and if I don't find it by Monday, we merge without questions.

I'm afraid you don't get to make that decision, Max. I think it is an agreeable decision. But let's make something clear; bounties are a privilege that is administered and provided by us. It is our decision if and when things get merged and when things count as completed for a bounty, as stipulated in the contribution guidelines.

**Comment by NoooneyDude** [comment]
I agree with Aranclanos. Have you seen the Madagascar movies? This is like the penguin smashing the blinking warning indicator to "solve" the problem. 

Edit: well I guess you did log it, so it's better than that.

**Comment by MaxIsJoe** [comment]
I have no idea why, I shouldn't even have to wonder why, but headless straight up refuses to spawn in an itemstorage prefab for clients no matter what. This behavior is not present at all on localhost and their clients and no amount of testing or digging through code can explain why headless refuses to do something that works normally on localhost and their clients.

The fix I pushed makes the prefab already there from the start and referenced inside the admin manager, is this a bad solution? the results say no but my third eye that can see in the future can see Arancianos that this is unacceptable because i'm somehow still haven't solved the issue of headless refusing to spawn the itemstorage by it self yet everyone on discord seems to be scratching their heads in confusion because of this weird behavior.

**Comment by Aranclanos** [comment]
closing in favour of #6312

**Pull request closed without merging**
