### PR TITLE
PogstationREDUX Patch v3

### PR DESCRIPTION
**Pull request by LastCaptainBonk**
Purpose:

To finish PogstationREDUX so I can leave Unitystation for the foreseeable future.

Notes:
There shouldn't have been any sort of issue with the cargo shuttle whatsoever.

Changelog:

CL: [New] Adds a multitool to the warden's office to link up cells to timers in case anything happens on Pogstation.

CL: [New] Adds a supermatter in a secure area in atmospherics on Pogstation.

CL: [New] Adds slot machines and a piano chair to the bar on Pogstation.

CL: [Fix] Cargo Bay shutters now linked to button on Pogstation.

CL: [Fix] Reintroduces pens throughout the station (and gives fountain pens to all heads) on Pogstation.

CL: [Improvement] No more white stains in the arena on Pogstation.

CL: [Improvement] Light tube fixture in bridge moved slightly as to not conflict with the photocopier on Pogstation.

CL: [Improvement] Chairs in evac overhauled to accommodate more people on Pogstation.

CL: [Improvement] EVA storage massively overhauled to accommodate more people on Pogstation.

CL: [Improvement] Other minor tweaks all around the station.

### CODE REVIEW

**Comment by corp-0** [comment]
did you perhaps work in a branch you used to do a PR before?
Also, can you please make the changelog more concise?

**Comment by LastCaptainBonk** [comment]
This is going to be my final message on this PR. The "conflict" is PogStation being weird. The suit storages in EVA should be hooked up to APCs (or rather unhooked, then rehooked), and I don't know why that's causing this PR to shit itself. I've made the changes, and it's just making PogStation.unity act strange. Just iron out the edges/rehook the APCs in the EVA storage room, and the PR should be golden. I'll change the logs to be more concise, but that's it. Have fun with PogStationREDUX Patch v3, if you decide to iron those edges out; it allows for this station to (hopefully) be put back into rotation for the Unitystation players to enjoy.

**Comment by Maximal98** [comment]
Bundesrepublik Deutschland

**Comment by Bod9001** [comment]
just waiting for tests

**Pull request merged**
