### PR TITLE
Update Mirror to our packaged version

### PR DESCRIPTION
**Pull request by NoooneyDude**
This is a reattempt of #8434 but without updating Mirror at the same time.

- Removes unpackaged Mirror 42.2.11 and replaces it with our packaged version found [here](https://github.com/unitystation/Mirror), branch `dev`. This is the same Mirror version with (most) of our custom code, just packaged.

> Tested with two clients on headless.

### CODE REVIEW

**Comment by Bod9001** [comment]
What's the status with waiting on, the PR for multithreading networking? Shall we merge it into this or merge it into the main branch?

**Comment by NoooneyDude** [comment]
This can be merged now, no dependencies.

**Comment by NoooneyDude** [comment]
We can make another PR to change the Mirror version number.

**Comment by corp-0** [comment]
still on hold?

**Comment by Bod9001** [comment]
It's good to go

**Review by Bod9001 — APPROVED** [review]

**Comment by Bod9001** [comment]
good to merge now?

**Comment by Bod9001** [comment]
NoooneyDude Said it was okay merging

**Pull request merged**
