### PR TITLE
Adds 7 new pets to choose from!

### PR DESCRIPTION
**Pull request by Evan-R-Rogers**
**Adds a total of 7 new pets to help liven up the station**:
- _Sergeant Araneus_, the tarantula
- _Henrietta_, the hen
- _Jerry_, the mouse
- _Polly_, the parrot
- _Paperwork_, the sloth
- _Coffee_, the 'kreb'
- _Gaggle_, the goose

gooble

### CODE REVIEW

**Comment by fomalsd** [comment]
are they interactive in some way, or static like punpun?
also it's Poly, not Polly afaik

**Comment by Evan-R-Rogers** [comment]
They move around similar to Ian yet are a tad bit more active akin to the floorbots. I plan to lengthen the time between their movements to make them less hectic in the morning.

**Comment by Evan-R-Rogers** [comment]
Check failed? Wuhwoh

**Comment by fomalsd** [comment]
yeah
oops

**Comment by Jibbajabbafic** [comment]
If they're derived from Ian do they still follow commands?

**Comment by Evan-R-Rogers** [comment]
Alright, _should_ be fixed now. Issue was that the sprites they were looking for weren't PR'd along with them.

@Jibbajabbafic Not at the moment no, I didn't add the follow/Ian scripts to these pets though I could.

**Comment by Evan-R-Rogers** [comment]
Don't PR, screwed up file changes. Will fix.

**Comment by Evan-R-Rogers** [comment]
:0

**Pull request merged**
