### PR TITLE
Revert "New locker sprites by Cornelius Bogfrollup Fitzgerald."

### PR DESCRIPTION
**Pull request by VernaSaurus**
Reverts unitystation/unitystation#4966

sorry muddy it's not your fault man

### CODE REVIEW

**Comment by VernaSaurus** [comment]
this is too stressful

**Comment by optimumtact** [comment]
first time?

**Comment by floppa-in-a-hat** [comment]
How did you even create this pull request? Does the revert button only appear to members of the Unitystation organization?

**Comment by Dropgunner** [comment]
Organge man bad, baaad!

**Pull request closed without merging**
