### PR TITLE
Vendor gui

### PR DESCRIPTION
**Pull request by vlandemart**
### Purpose
GUI for all vending machines. 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
GUI frame color, items and their amount is set in VendorTrigger.
Also, includes VendingRestock.prefab which can restock items in machines.
[Picture of GUI](
https://cdn.discordapp.com/attachments/295186861377323009/588760102673317895/unknown.png)

### CODE REVIEW

**Review by fomalsd — CHANGES_REQUESTED** [review]
- VendingRestock isn't in Resources folder therefore can't be spawned in runtime, also will have problems in multiplayer
- Serverplayer doesn't get any feedback messages from vendors (wrong kind of "send to chat" message perhaps?)
- Empty glass, empty plate and UniCloth are displayed as white squares for some reason (but it's probably a NetPrefabImage issue)

other than that it's really cool!
is this intended btw?
img

**Comment by vlandemart** [comment]
I removed feedback messages for now, as I was having troubles with getting addressee of message - I was storing originator on `Interact` with vending machine, but it led to problems when two players interacted with one vendor.

Meat dispensers are intended (for now at least), these had VendorTrigger before.

**Comment by fomalsd** [comment]
Pretty sure you can broadcast vending messages to all current observers. That will be quite sufficient for now since no credits are involved yet.
Still, there should be a way to get click originator without any caching, but I'll look into that later

**Comment by vlandemart** [comment]
Addressed these issues.

**Comment by fomalsd** [comment]
Won't be able to test until Monday, maybe someone else could do it until then. But code looks fine!

**Review by fomalsd — APPROVED** [review]

**Pull request merged**
