### PR TITLE
Advanced Scanning Record

### PR DESCRIPTION
**Pull request by Silver-8ce**
### Purpose
You can now use the health records on cloning consoles to get specific limb, organ, and disease information.

### Changelog:

CL: [New] A "Health" button on the health record page of the cloning console opens a health information page.

CL: [Improvement] the health record page now gives you the actual toxin damage of the person.

Screenshot (13)

Screenshot (15)

Screenshot (16)

Screenshot (14)

### CODE REVIEW

**Comment by PerfectTangent** [comment]
probably more fitting for this to go into the medical records console, but cool PR, nonetheless 👍

**Comment by corp-0** [comment]
you know what would make this a stellar PR? Giving the option to print scanner data to a paper so detective can use it for his investigation

**Comment by Bod9001** [comment]
Shall I resolve the SpriteCatalogueSingleton conflict?

**Comment by Silver-8ce** [comment]
@Bod9001 
Yeah that would be helpful, I've been trying to figure it out on my own but I'm not that experienced with git bash.

**Comment by Bod9001** [comment]
ok, I'll do it after my walk

**Comment by Bod9001** [comment]
Should be good now

**Review by Bod9001 — APPROVED** [review]
some funny formatting probably could fix it with an auto formatter, 
code looks good,  if you have trouble with  git command line Try out Github desktop

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
