### PR TITLE
Might fix skeleton

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: Adds scene checker to the net identity

-In the long term we'll need to try to remove the identity

### CODE REVIEW

**Comment by corp-0** [comment]
how do we test this?

**Comment by ThatDan123** [comment]
I think just starting a headless server, joining one client and then late joining another client will make the late joining see anyone who was already in the game as a skeleton

**Comment by DTraitor** [comment]
> I think just starting a headless server, joining one client and then late joining another client will make the late joining see anyone who was already in the game as a skeleton

now you also see your own skull and skulls of people who joined after you did

**Comment by NoooneyDude** [comment]
I couldn't see any skeletons when testing with two clients and disconnecting, restarting.

Note that this had a conflict (at least, locally) with #6516.

**Pull request merged**
