### PR TITLE
Adds the option for disabling autostacking for some items

### LINKED ISSUE #8361: Not all stackable items should merge together when occupying the same tile.
### Description

The system added in #7285 for making stackable items merge together when on the same tile currently affects all items, but there are some exceptions that need to be added. For example, regen meshes should not merge together when occupying the same tile. 

This quality of stackable items needs to be a toggleable option for stackable items. 

The items that don't automatically merge can't be manually split either using the stack splitting added in #7870. They should stay discrete.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Some items do not automatically stack when dropped on the floor or when spawning, this adds the option to disable this behavior.

closes #8361

### CODE REVIEW

**Comment by corp-0** [comment]
when do we want stackable items to don't stack on drop?

**Comment by MaxIsJoe** [comment]
> when do we want stackable items to don't stack on drop?

I honestly have no idea
Another example that comes to my mind would probably be papers because not all of them should; Either way the option is there to disable it from the inspector so someone else can come and change it.

**Comment by CdrCross** [comment]
> when do we want stackable items to don't stack on drop?

Any time the individual object contains individual data. Papers is a good example, but forensics is also an interesting case.

**Comment by MaxIsJoe** [comment]
When we start working on forensics and detective stuff we can probably just merge that data into the stack item itself.

**Review by NoooneyDude — APPROVED** [review]

**Comment by Fr-Dae** [comment]
> when do we want stackable items to don't stack on drop?

Pizza part.
Pastec 
Paper

**Comment by PerfectTangent** [comment]
> Any time the individual object contains individual data. Papers is a good example, but forensics is also an interesting case.
> Pizza part. Pastec Paper

none of those items have the stackable component. This PR is about _stackable_ items merging when placed on the same tile, not just any items. Currently, there aren't many things except the regen mesh that need this.

**Comment by Fr-Dae** [comment]
> none of those items have the stackable component. This PR is about _stackable_ items merging when placed on the same tile, not just any items. Currently, there aren't many things except the regen mesh that need this.

Pizza slices, if placed on the same tile, merge into a stack.
which is a pain in the ass to arrange the 6 slices of pizza for 6 people.
and not one person eating a pizza by himself.

**Comment by Bod9001** [comment]
added to the pizza!

**Comment by MaxIsJoe** [comment]
> > Any time the individual object contains individual data. Papers is a good example, but forensics is also an interesting case.
> > Pizza part. Pastec Paper
> 
> none of those items have the stackable component. This PR is about _stackable_ items merging when placed on the same tile, not just any items. Currently, there aren't many things except the regen mesh that need this.

I haven't changed anything except regen meshes to use this change.
I'm saying that if anyone wants to change any other items to prevent autostacking on spawn/drop, the change is so easy because it's a simple toggle from the inspector. No code changes required.

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
