### PR TITLE
Readjusts the speeds of several mobs

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Balance] - A lot of mobs no longer move like snails.

### CODE REVIEW

**Comment by corp-0** [comment]
#8757 also has some speed adjustements, but honestly I'd rather have them all here in a single pr and the other one only code fixes.

**Comment by MaxIsJoe** [comment]
> #8757 also has some speed adjustements, but honestly I'd rather have them all here in a single pr and the other one only code fixes.

Bod only adjusted the speed of animals

**Comment by corp-0** [comment]
only sloth, it seems. Fair enough

**Review by corp-0 — APPROVED** [review]

**Comment by corp-0** [comment]
will you add any other mob here? Otherwise I will merge it now

**Comment by PerfectTangent** [comment]
I think the base mobs should be modified first before modifying individual mobs. That way it's more consistent and less mobs get omitted.

**Comment by MaxIsJoe** [comment]
> I think the base mobs should be modified first before modifying individual mobs. That way it's more consistent and less mobs get omitted.

I've modifed some base prefabs but i gave some unique speeds (i.e hunters being faster than other xenos and queens being slower)

**Comment by MaxIsJoe** [comment]
> will you add any other mob here? Otherwise I will merge it now

nah not planning, merge

**Pull request merged**
