### PR TITLE
more headset fixes

### PR DESCRIPTION
**Pull request by AutumnNova**
added missing tags
added centcom headset
added qm headset sprite
remove duplicate sprites
redone the sec headset from scratch in the hopes of it working this time
changed ammotype for shotguns

### CODE REVIEW

**Comment by ThatDan123** [comment]
Missing reference found in scene OutpostStation, GameObject Objects/LawDrobe (1), Component LawDrobe (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/SecDrobe (1), Component SecDrobe (1), FieldName Item

Missing reference found in scriptable object Warden field Element 0
Missing reference found in scriptable object DetectivePopulator field Prefab
Missing reference found in scriptable object Security field Element 4
Missing reference found in scriptable object SecurityOfficerPopulator field Prefab
Missing reference found in scriptable object WardenPopulator field Prefab

Missing reference found in prefab SecDrobe component SecDrobe field Item
Missing reference found in prefab LawDrobe component LawDrobe field Item

**Comment by AutumnNova** [comment]
fffffixeddddddd
hopefullyprobablymaybe

**Comment by daPotato** [comment]
can you elaborate on what sprites were duplicates of what please, trying to figure out if i fucked up when packing them or if Jack slipped up somewhere

**Comment by AutumnNova** [comment]
jack added a folder full of the sprites, I put sprites in a folder next to the headsets while i was doing my previous commit, meaning that two of each sprite existed

**Comment by daPotato** [comment]
alright, just had to check.
For the department heads that dont have bowman variants, looking at the QM, just give them the standard department sprite until i can get a bowman for it, just to maintain style consistency.

**Comment by daPotato** [comment]
fuck that previous statement heres a cargo bowman if you can stick that in for me
cargo_headset_alt

**Comment by Bod9001** [comment]
Tell me once you're ready

**Comment by AutumnNova** [comment]
good to go

**Comment by DooblyNoobly** [comment]
tested it locally with 2 clients?

**Comment by AutumnNova** [comment]
i haven't, no

**Comment by DooblyNoobly** [comment]
can you do that and let us know if it fixes `redone the sec headset from scratch in the hopes of it working this time`

**Comment by AutumnNova** [comment]
yeah it works fine

**Pull request merged**
