### PR TITLE
Make NetUIElement generic.

### PR DESCRIPTION
**Pull request by RedlineTriad**
# Pull Request Template

### Purpose
This makes `NetUIElement` generic so not everything has to use strings, only `NetUIDynamicList` has actually been changed to use anything other than string but it should work.

### Notes:
It uses the built in BSON serializer from Newtonsoft to serialize it into a NetMessage.

### Please make sure you have followed the self checks below before submitting a PR:

- [ ] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- [ ] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by Bod9001** [comment]
does this require changing existing code for tabs like chemistry dispenser in such if so you'll have to talk out what the person is doing with the lathe UI

**Comment by RedlineTriad** [comment]
@Bod9001 the only change required for backwards compatibility is changing `NetUIElement` to `NetUIElement<string>`.

**Comment by Bod9001** [comment]
cool, You willing to fix up the lathe UI if it breaks when merging this in?
preferably I want to get lathe UI in first

**Comment by Bod9001** [comment]
since new devs don't fix code once it breaks on a PR

**Comment by RedlineTriad** [comment]
@Bod9001 Yep, i can fix merge conflicts, i just want it to be in as soon as possible since working on `NetUIDynamicList` depends on this.

**Pull request merged**
