### PR TITLE
Some small fixes

### LINKED ISSUE #9964: [BUG] Chemistry foam is bugged.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23071201

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Making the foaming agent automatically makes metal foam walls even without the metal foam recipe included. When actually making the metal foam recipe, only aluminum works using iron does nothing.

### What should have happened instead?

The foaming agent should only make metal foam when the metal foam ingredients are part of it. Using iron in the recipe should also make metal foam walls.

### Steps to reproduce the issue

1. Make foaming in grenade
2. Activate it
3. Wait
4. Also try making the metal foaming agent but use iron
5. Activate it
6. No walls ):

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AtnerNT**
Closes #9964 and #9517

### Changelog:
CL: [Fix] Fixed salami being labelled as pineapple slices in the crafting menu
CL: [Fix] Fixed foaming agent spontaneously forming metal foam
CL: [Fix] Fixed iron not working as a valid ingredient for the formation of metal & smart metal foam
CL: [Balance] The recipes for all foams & their agent now match that of the TG chemistry wiki

### CODE REVIEW

**Comment by AtnerNT** [comment]
Was originally gonna include a fix for foam not spreading on floors, however, investigating it, that is gonna require the addition of a whole new layer in the tilemaps for floor overlays, and all the scene adjustments and such that come along with it. That is beyond the scope of this PR. Should be good to merge as is

**Comment by Bod9001** [comment]
what was the recipe before and after?
I think the reason I had it separated was because
the foam couldn't exist as a reagent because it would instantly react, so I made a precursor? idk I just remember it something being Complicated about it

**Comment by AtnerNT** [comment]
So before foam formed when foaming agent was made.
This has been changed so it now forms when fluorosurfactant reacts with water (like tg), as foaming agent is only used in the recipe for metal foam and smart foaming agent.
To make metal foam/smart metal foam, you take the corresponding foaming agent, mix it with iron/aluminium and fluorosulphuric acid (think thats the one)

**Comment by Bod9001** [comment]
ok, if it works then  it's all good

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
