### PR TITLE
AutoDrobe part 1: schoolgirls, chicken suits, plague doctors, and more. [Now updated to 2019.3!]

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR adds in a basic AutoDrobe and some clothing to go inside it. The new clothing includes
- Schoolgirl uniforms (come in blue, green, red, and orange).
- A green labcoat.
- A chicken suit (comes with head).
- A gladiator uniform (comes with helmet).
- A plague doctor's costume (based on bio suit, comes with hat and mask).
- Performer's outfits and boots (come in blue and yellow).
- Basic wizard and witch robes and hats (in both real and fake [statless] forms).
  - A staff and broom, for hitting people.
- A shrine maiden's outfit and wig.
  - A gohei, it's basically a stick with pieces of paper hanging off it. Also for hitting people.

I also added a bunch of pre-existing clothing to the AutoDrobe, like the maid outfits. The AutoDrobe's inventory is far from complete, and I plan on expanding it in the future.

### Notes:
The AutoDrobe that I added uses a slightly different sprite than the banana dispenser found in PogStation's clown and mime spawn room.

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Because of the unity editor upgrade you might need to re do this pr :(

**Comment by corp-0** [comment]
maybe deleting the meta files and regenerating them in the new version is good enough?

**Comment by PetMudstone** [comment]
.meta files regenerated by their selves, no deletion required. All new clothes appeared fine in testing.

**Comment by DooblyNoobly** [comment]
did you open it with the new editor version?

**Comment by PetMudstone** [comment]
Yes I did, I saw the new user interface icons and all. All the .prefabs also became pink squares too, but a reimport fixed that. The regenerated .meta files came from the new editor version.

**Pull request merged**
