### PR TITLE
Sprite handler simplification, and added convenience methods

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
Simplify Sprite handler 

### Notes:
I'm still wondering what to use
 scriptable objects for the in hands and inventory icon or
Just a class on One of the scripts?

### CODE REVIEW

**Comment by Bod9001** [comment]
Most of the in hands aren't done since I'm waiting on whether or not to use scriptable objects or a class for the Sprites?

**Comment by Jibbajabbafic** [comment]
If this breaks all the in-hands icons then I'd hold off merging until that's ready. We're really close to a public release now so any new features need to be as complete and bug free as possible.

**Comment by DooblyNoobly** [comment]
yes, please do not merge any structural changes to systems until after release. I'm putting a DNM on this. Bod you should be looking at polishing and bug fixing as discussed in discord

**Comment by Bod9001** [comment]
ok np

**Comment by DooblyNoobly** [comment]
Closing this as the merge conflicts are too large

**Pull request closed without merging**
