### PR TITLE
adds soda dispenser

### LINKED ISSUE #4296: booze dispenser doesn't allow things to be put in it
@otherguywolf  you messed up

### PR DESCRIPTION
**Pull request by AutumnNova**
adds soda dispenser, some drinks i missed to the booze dispenser and fixes #4296

### CODE REVIEW

**Comment by VernaSaurus** [comment]
what changes to outpost did you make

**Comment by VernaSaurus** [comment]
they already conflict anyway so you might have to undo them anyway

**Comment by AutumnNova** [comment]
firelocks, whole lot of firelocks

**Comment by VernaSaurus** [comment]
wonder what about it is conflicting

**Comment by Bod9001** [comment]
Ready to merge?

**Comment by AutumnNova** [comment]
yep

**Comment by AutumnNova** [comment]
lemme just redo this

**Pull request closed without merging**
