### PR TITLE
Antag preferences

### LINKED ISSUE #3266: Job preferences screen B: 140
Players should be able to setup their job preferences so that they can be assigned roles randomly at round start instead of everyone choosing from a list at the same time like we currently do.

Related to #3267 

Criteria:
- [x] Job preferences screen
- [x] Show all possible jobs
- [x] Allow choosing none, low, medium or high for each job
- [x] Only allow picking 1 high priority job
- [x] Show the already implemented job descriptions
- [x] Save preferences with current character settings
- [x] Add antagonist preferences screen too

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
Adds antag preferences and finishes off all the job selection options.

Fixes #3266 

RAm0Z52Ja8

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- [x] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by corp-0** [comment]
what happens if you select no to Rebel and your department rolled rebel?

**Comment by Jibbajabbafic** [comment]
Uuuh good point, I didn't test the rebel game mode with it. I think the game mode overrides it to spawn anyone from that department as a rebel.

**Comment by corp-0** [comment]
this happens before job alocation? If not, it could move you to another preference if the department you were supposed to get is rebel and you chose not to be rebel.

**Comment by Jibbajabbafic** [comment]
Yeah that will need to be factored in later

**Comment by Jibbajabbafic** [comment]
This is from the rebel/cargonia game mode:
```
	protected override bool ShouldSpawnAntag(PlayerSpawnRequest spawnRequest)
	{
		return RebelJob.Contains(spawnRequest.RequestedOccupation.JobType);
	}
```

So if you spawn in that department mid round you'll become a rebel no matter what you choose.

**Comment by ThatDan123** [comment]
Doesnt have to be added now but, when you hover over the name a description of the antag could be shown like the jobs on the old screen.

**Comment by Jibbajabbafic** [comment]
Yeah I thought about adding that too plus a little sprite, but I just wanted to get it done ASAP. It's all setup in a way that should make it easy to add that later on.

**Pull request merged**
