### PR TITLE
Adds sound and visual indicators when buckling to chair

### LINKED ISSUE #1858: Sounds and sprites for buckling people into chairs B: 40
# Description
There should be audible and visual feedback when buckling someone/being buckled into a chair

**Note**: there is a buckled icon for the person buckled into the chair, but it's impossible to tell for anyone else based on the sprites

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Buckle someone into a chair
2. Notice there is no sound and the chair sprite doesn't indicate if someone is buckled or not

### PR DESCRIPTION
**Pull request by JaytleBee**
### Purpose
Fixes #1858 

For now the sound is just a click and the buckle is some hasty programmer-art, but switching those out is trivial now (Sounds are played in BuckleInteract.cs). It also makes it so you can't look around while buckled, which is something I noticed while working on this.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
There's still two bugs with buckling in general that I haven't been able to fix yet: Buckling yourself on the client doens't update your direction (Seems less trivial to fix than it sounds) and if you buckle while moving you get very strange behaviour. I think it's best to make separate issues for those, though.

### CODE REVIEW

**Review by Bod9001 — CHANGES_REQUESTED** [review]
fix FOV on the buckle you just have to change the material, and the random bug with the buckle reappearing after you die, 
see If you can find out what caused the, UI element to get the wrong sprite randomly but It's not an issue if you can't find out what's causing it,
If you feel like you have spare time and you feel like doing it you can set up the rotation on matrix Rotation of the player

**Comment by JaytleBee** [comment]
Alright, I fixed the FOV and the buckle bug, I may have a look at the matrices at a later time (though I don't really think it's related to this)

**Comment by Bod9001** [comment]
matrices  I mean as in,
When the chair changes direction, the character doesn't

**Comment by JaytleBee** [comment]
I know what you mean, I just don't think it's related to the visual side of buckling

**Comment by Bod9001** [comment]
yeah it's ok, It's something minor not really much of an issue
Merging

**Review by Bod9001 — APPROVED** [review]

**Comment by JaytleBee** [comment]
I just tested it (not before mis-clicking on "Close and comment"; sorry about that!) and the player doesn't rotate if the matrix rotates regardless of whether they're buckled. Perhaps the player should just rotate in general?

**Comment by Bod9001** [comment]
I was thinking they should only rotate if they are buckled in?

**Comment by JaytleBee** [comment]
Hm, this is a matter of opinion

**Comment by Bod9001** [comment]
yeah, a discussion on the discord would be good

**Comment by Bod9001** [comment]
oops sorry, Didn't realise it was a bounty PR, 
I'll unmerge it,  since doobly has the final say on bounties, if he says it's OK then it can just merged back in

**Pull request merged**
