### PR TITLE
Fixes conscious state not updating once a client logged in

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes conscious state not updating once a client logged in
Changes its behaviour from a ServerMessage sent to all to a SyncVar

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Review by fomalsd — CHANGES_REQUESTED** [review]
I'd rather use messages than syncvars and just send conscious state message when syncing client after join:
https://github.com/unitystation/unitystation/blob/2709e6a68a7f965ba5dc63b9b979b5893176918f/UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs#L313

**Comment by Aranclanos** [comment]
I disagree, this way achieves and does the same thing while having way less bloat

**Comment by fomalsd** [comment]
with syncvars every player will always know every other player’s conscious state, and you can’t limit that using your own culling algorithms

**Comment by Aranclanos** [comment]
I don't see that being a thing anytime soon

**Comment by fomalsd** [comment]
Anyway conscious state should only be sent to subject player

**Comment by fomalsd** [comment]
I still think it's a good idea to scrap that PR and make conscious state be broadcasted to player in question only – unless there are side effects due to other clients not knowing your conscious state?
(Upright state is synced elsewhere, in PlayerUprightMessage)

**Comment by Aranclanos** [comment]
PlayerUprightMessage SendToAll or a synced var ;v)

**Comment by fomalsd** [comment]
Using SendToAll for upright message is fine for now, it doesn’t elaborate on player’s health state except for whether he’s down or not

**Comment by fomalsd** [comment]
Closing this one

**Pull request closed without merging**
