### PR TITLE
Player and objects spawn position clean-up

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
CL: [Fix] Increased performance by being more strict on objects getting stuck in a never ending synchronization loop.
-Adds a custom change on mirror code to send and read strictly worldpos while spawning networkidentities.
-Reduces the amount of random calls to reset a registerTile position on their spawn.
-Removes the few remaining WaitForMatrixInit() calls towards registerTile, these objects will now use OnSpawnServer()
-RegisterTile initialization will now be more ordered, waiting for MatrixMove to be ready and setting up the PositionStates from the IPushable afterwards, following the registerTile's own matrix and position setup.
-Adds an extra frame wait for the SubsystemManager to start its room generation, adding a TODO with it.
-Moved out the RegisterTile set variables that were several lines  long to their own functions to keep the file more ordered

### Notes:
Previous to this PR, objects and players would spawn and get tossed around to different positions and even start lerping several times in a frame or two, this PR rectifies said issue by not moving at all the spawned objects.
The idea is to tackle any issues of players spawning in space, the station lacking objects and others issues alike

However, due to the size of this PR and lack of organization when it comes to the amount of position states (around 8 different positions are tracked) I expect this to add more issues than what it solves once ingame, follow-up PRs should be able to fix said issues now that the code is way more organized -to an extent-

### CODE REVIEW

**Comment by ThatDan123** [comment]
Did you test walking back and forth between different matrixes?

And throwing stuff?

**Comment by Aranclanos** [comment]
Yes and yes

**Review by ThatDan123 — APPROVED** [review]

**Comment by corp-0** [comment]
I'm pulling and testing, if this works flawlessly then it is absolutely brilliant work

**Comment by corp-0** [comment]
I'm getting this trying to start the server from a build
```
NullReferenceException: Object reference not set to an instance of an object
Lobby.GUI_LobbyDialogue.OnStartGame () (at <b3755d4a3b2e4a11adfd3134b356f450>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <6e7a9b489b134053bc0600a292ec678e>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <6e7a9b489b134053bc0600a292ec678e>:0)
UnityEngine.UI.Button.Press () (at <93c957f88bd2446fbf93cc2b19d384a7>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <93c957f88bd2446fbf93cc2b19d384a7>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <93c957f88bd2446fbf93cc2b19d384a7>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <93c957f88bd2446fbf93cc2b19d384a7>:0)
UnityEngine.EventSystems.EventSystem:Update()

````

I will try building again

**Comment by corp-0** [comment]
I did the build 3 times, for the last one I regenerated library folder first. Same result on all of them. Let me know if it is only a thing for my local.

**Comment by Aranclanos** [comment]
that bug is kinda old, I dont know what causes it but its completely unrelated to this, I'd attach a debugger to see whats up.

**Comment by Bod9001** [comment]
only issue I found is, client dragging host to a spot with the mouse not updating client but might be unrelated
(actually it's just a Delayed by quite a bit)

**Comment by Bod9001** [comment]
was able to build fine

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
