### PR TITLE
WIP give some life to pets

### PR DESCRIPTION
**Pull request by corp-0**
# Pull Request Template

### Purpose
This PR will add some AI and interactions to pets so they are more alive.
I'm gonna need some help to finish this!

### Notes:
Detailed changes:
- [x] Refactored Pettable component. It will trigger a method from MobAI that you can override on your specific brain script.
- [x] Ian:
- - [x] Bark at his attacker and flee!
- - [x] responds when you pet him!
- [ ] Runtime:
- - [x] Hunt mice (when she feels like)
- - [x] Random actions (lick her paws, meow, purr)
- - [x] responds to being petted
- - [ ] Lays down and wags her tail (this only needs the animation scripted! Sprites are already in the repo)
- [ ] Jerry the mouse
- - [x] Randomly squeaks
- - [ ] Eat cables (I think this will have to wait until the electricity overhaul)
- [ ] Polly the Parrot
- - [x] Say random things from a pool of phrases.
- - [x] Say the last thing he heard.
- - [ ] Randomly steal stuff from your active hand (the logic is written, but I don't understand why he doesn't do it).

I'll gladly receive any help/correction to this code!

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- [x] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by AutumnNova** [comment]
runtime prefab conflict

**Comment by corp-0** [comment]
solved

**Comment by DooblyNoobly** [comment]
Do you want to merge this current progress?

**Comment by corp-0** [comment]
Yeah, sure. It won’t break anything... I think

**Comment by DooblyNoobly** [comment]
right I've been waiting for these damn tests to finish for an hour now. The test runner works, thats good enough for me. Merging

**Comment by hecksadecimal** [comment]
We were getting this on USA MRP's server logs today @corp-0 
Seems related to the cat being set on fire.
```
NullReferenceException: Object reference not set to an instance of an object
  at CatAI.OnAttackReceived (UnityEngine.GameObject damagedBy) [0x0001e] in /github/workspace/UnityProject/Assets/Scripts/NPC/AI/CatAI.cs:86 
  at LivingHealthBehaviour.ApplyDamageToBodypart (UnityEngine.GameObject damagedBy, System.Single damage, AttackType attackType, DamageType damageType, BodyPartType bodyPartAim) [0x00073] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:369 
  at LivingHealthBehaviour.ApplyDamage (UnityEngine.GameObject damagedBy, System.Single damage, AttackType attackType, DamageType damageType) [0x0002e] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:321 
  at LivingHealthBehaviour.OnExposed (FireExposure exposure) [0x0000c] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:416 
  at RegisterTile.OnExposed (FireExposure exposure) [0x00021] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Objects/RegisterTile.cs:667 
  at ReactionManager+ApplyExposure.Invoke (RegisterTile registerTile) [0x00035] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/ReactionManager.cs:395 
  at TileList.ForEachSafe (IRegisterTileAction action, UnityEngine.Vector3Int localPosition) [0x00098] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Utils/TileList.cs:160 
  at Matrix.ForEachRegisterTileSafe (IRegisterTileAction action, UnityEngine.Vector3Int localPosition, System.Boolean isServer) [0x00001] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/Matrix.cs:208 
  at ReactionManager.Expose (UnityEngine.Vector3Int hotspotPosition, UnityEngine.Vector3Int atLocalPosition) [0x0015e] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/ReactionManager.cs:324 
  at ReactionManager.ExposeHotspot (UnityEngine.Vector3Int localPosition, System.Single temperature, System.Single volume) [0x000ff] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/ReactionManager.cs:262 
  at ReactionManager.Update () [0x002e0] in /github/workspace/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/ReactionManager.cs:134
```

**Comment by corp-0** [comment]
Yes! Runtime runs from whoever attacks her but I guess fire is not a game object, thus she doesn’t know where to run. This is an easy fix, thanks for letting me know.

**Pull request merged**
