### PR TITLE
Fix: this should fix our issues with the servers

### PR DESCRIPTION
**Pull request by corp-0**
### Purpose
- Properly renamed things with case aware git.
- Changed ``chatlogs`` and ``admin`` to ``Chatlogs`` and ``Admin``, following our naming convention.
- Created two properties to get names of subfolders inside Config and Logs, so we don't have to hunt the names again if we do change them.
- Renamed the folder, asmdef and namespace of ``ConfigurationSaves`` to ``SafeFilesystem``, this was asked during review of this code.

### CODE REVIEW

**Comment by corp-0** [comment]
review changes by pressing on the individual commits, given the amount of files

**Review by MaxIsJoe — APPROVED** [review]
our lord art heaven, please bless this PR.

**Comment by MaxIsJoe** [comment]
tests failed, fuck.

**Comment by corp-0** [comment]
I'm runnig tests locally to see what's up

**Pull request merged**
