### PR TITLE
Add names to Grown plants

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
Due to an storage database error, the Station received the wrong Food Seed Package, Sadly This also resulted in Clown station Collapsing due to the lack of Bike horns
### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Proper-Spawning-and-Despawning-%28Object-Lifecycle%29)
- [ ]  This PR has been tested with round restarts.
- [ ]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes: 
Still can't work out how to do the onstar client Thing

### CODE REVIEW

**Comment by chairbender** [comment]
@Bod9001 for the client start thingy, you can just add logic to CustomNetworkManager.SyncPlayerData which sends the status of all plants to the client.

**Comment by chairbender** [comment]
@Bod9001 hm, it's still showing name / description as bike horn for me. I did a fresh revert and relaunched editor and it still happens.

**Comment by Bod9001** [comment]
humm odd To be fair only really Checked the game object name, Since item name isn't really use that much

**Comment by Bod9001** [comment]
oh i know, The prefab doesn't have the updated item attributes, Mostly because unity decides to go "LOL Let's change these sceneIDs", Causing me to accidentally discard the prefab change I want XD

**Review by fomalsd — APPROVED** [review]
tooltips aren't showing for an unrelated reason, merging

**Pull request merged**
