### PR TITLE
Just a health doll fix

### LINKED ISSUE #6339: Health Doll Selection Bug
### Environment
- Game Version: 21040800
- OS Version: MacOSX

### Detailed description of bug

Trying to select any other part of the body on the health doll just doesn't work, at all.
Screen Shot 2021-04-08 at 10 10 11 AM

### Steps to reproduce

1. Try to select any other part of the health doll than the torso.

### PR DESCRIPTION
**Pull request by DTraitor**
### Purpose
Closes: https://github.com/unitystation/unitystation/issues/6339

### Changelog:
CL: Fixed healthdoll selection bug

Shouldn't revert anything this time ._.

### CODE REVIEW

**Comment by corp-0** [comment]
what's the health doll selection bug?

**Comment by DTraitor** [comment]
You cant choose any part on healthdoll by clicking it

**Comment by corp-0** [comment]
why does disabling raycast on these gameobjects fix it?

**Comment by DTraitor** [comment]
When I made my raycast PR I enabled raycast on damage zones but disabled it on an actuall buttons. If you scroll down you can see I enabled some of them

**Comment by corp-0** [comment]
makes sense. I will add the ``awaiting test`` label so someone can test it before merging.

**Comment by MaxIsJoe** [comment]
image


Not sure why this PR gives me these prefab errors on my end. Someone else confirm that it isn't broken.

**Comment by NoooneyDude** [comment]
Has been tested again, above error is likely a local issue.

**Pull request merged**
