### PR TITLE
Protection against NaN in Atmos

### PR DESCRIPTION
**Pull request by JesterX666**
Protection against NaN in Atmos

Atmos breaks due to oxygen NaN infection B: 50 #2264

Fixes the possibility of NaN in CalcMeanGasMix

I was not able to reproduce a big NaN propagation into the Atmos System, it seems that some protections were already put in place to prevent that.

I crashed a lot of matrixes into the station and it seems I don't get NaN anywhere.

### CODE REVIEW

**Review by fomalsd — CHANGES_REQUESTED** [review]
Something else still causes NaNs:
mov
And so far I'm only able to detects NaNs post factum when checking what gas mix mobs are going to inhale:
https://github.com/fomalsd/unitystation/blob/aacdd44032ce0153e7beafa884fe427a81c1d427/UnityProject/Assets/Scripts/Health/RespiratoryHealth/RespiratorySystem.cs#L86-L90

**Comment by JesterX666** [comment]
That's weird... I believe it's only on your branch, @fomalsd ... Or related to a different setting?!

NAN

**Comment by fomalsd** [comment]
woops, might be just my branch indeed

**Comment by fomalsd** [comment]
ok, since it works on develop this can be merged – but I'd advise adding measures suggested in #2610, apparently it removes possibility of situations where `targetCount` is 0
but keep in mind that whenever someone starts fixing #1902 or #1856 oxygen NaNs might appear again, and for a different reason – that's what happens in my branch

**Comment by JesterX666** [comment]
Agreed.  I will not be able to incorporate #2610 tonight but I'll assign myself on it and put it "In progress".

**Pull request merged**
