### PR TITLE
Fixes profile command messages

### PR DESCRIPTION
**Pull request by ThatDan123**
Fixes the command messages for profiling.

### CODE REVIEW

**Comment by Bod9001** [comment]
hey, do you know if this turns on the extra logging in the update manager? when you send the logging message?

**Comment by ThatDan123** [comment]
dont think it does, but I can make it

**Comment by ThatDan123** [comment]
humm, but I'd have to remove the #if UNITY_EDITOR, might have a performance impact?

**Comment by Bod9001** [comment]
well, extra functionality so should be fine

**Pull request merged**
