### PR TITLE
Interaction Framework V2 (And Chair Buckling)

### LINKED ISSUE #1362: TODO: Player drag and drop interaction with machines/items B: 90
## Description

We need the ability to drag and drop players to seats, beds and to put players into machines like the cloner. The system should be Server Authoritative. 

### Criteria:
 - Develop a way (new handler component) to detect the click and drag event on a player object
 - Create a component that can react to a drop event that will be placed on any machine item that can be interacted with in this way (chairs, beds)
 - Make sure that any resulting actions are network synced and server authoritative (contact me if you get stick with this one)
- Drag and dropping a player to a chair should buckle that player to the chair

Note: (Bed and cloner behaviours will come in a later TODO)

A bounty of 90usd will be awarded to the contributor on the successful merge of these features.

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #1362 

Also FINALLY adds my first version of a new interaction system for #1760 , which I'm calling "interaction framework v2" or IF2 for short. Chair interaction is implemented in this system to start to prove out how it works. This lives alongside the old interaction system. A lot of thought and effort has gone into this so I hope it's at least a good starting point.

The full documentation on the new system can be found here:
https://github.com/unitystation/unitystation/wiki/Interaction-Framework-V2---How-to-Cleanly-Implement-Interactions

I think this PR can focus on making sure the chair buckling is working okay. We can discuss IF2 in design-discussion on Discord. As we port the old interaction logic to the new system, we can fix any concerns, bugs, design issues, or code duplication problems that we encounter with it.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by chairbender** [comment]
just fixing up an issue I noticed...

**Comment by chairbender** [comment]
fixed

**Review by fomalsd — APPROVED** [review]
Great stuff! Looking forward to using this framework.
Chair buckling probably also needs either orientation locking or chairs changing direction with player, but that's a minor thing

**Comment by DooblyNoobly** [comment]
Very nice!

**Pull request merged**
