### PR TITLE
Ghost reenter corpse & respawn buttons

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Adds minds, a connection between bodies and their ghosts, minds are the place to save special roles such as antag information.
Dying will no longer spawn a ghost instantly, you'll have to try to move to get the ghost out from your body.
A ghost won't instantly trigger the respawn, the player will have to manually use their UI to rejoin the game if the server allows it.
Ghosts can now reenter their corpses at will, using their UI buttons.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
the minds have a jobtype variable, this will replace the jobtype of playerscript in the future

### CODE REVIEW

**Review by fomalsd — APPROVED** [review]
great! now you can actually test ghosts for as long as you like

**Comment by fomalsd** [comment]
oh, looks like some conflicts arose after I merged #1950

**Comment by fomalsd** [comment]
One more thing that can be improved is not calling SyncPlayerData on each body enter/swap, it is meant to be executed only once for player joining server. 
SyncPlayerData sends a crapton of messages, literally thousands of them!
https://github.com/unitystation/unitystation/blob/eef0148c32047742d2818db64848b0657beb17b3/UnityProject/Assets/Scripts/Managers/NetworkManagement/SpawnHandler.cs#L74

**Comment by Aranclanos** [comment]
solved conflicts

**Pull request merged**
