### PR TITLE
New Game Mode: Blood Brothers

### LINKED ISSUE #3128: Add Blood-brothers.
Blood-brothers would add more variety to the types of traitors and encourage playing together.

Implementation reference: https://tgstation13.org/wiki/Traitor#Blood_Brothers

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes #3128
This is my own take on the blood brothers game-mode, since i wanted it to be more unique than /tg/'s.

posterbb

# Introduction:

You're a convicted criminal who have been experimented on while you're in prison. During your time there, you've gained an unnatural ability to withstand more damage than any other humanoid can, and have formed a ritual with another inmate that gave you the ability to become a "Blood Brother".

A shadowy figure took interest in your bond with your blood brother, and have offered you a job on behalf of the syndicate in exchange for your freedom.

# Bonds that tie:

In this cooperative game-mode, at least two Blood Brothers start together with the sole goal of achieving at least 70% of their objectives to earn their freedom and to showcase their newly found capabilities to their shadowy employer. However:

- Blood Brothers are linked to each other, and the death of one means the failure and death of all other brothers.
- Blood Brothers start with an uplink that only has 8 TC, limiting the amount of immediate resources provided by the Syndicate for them.

If the **total** amount of greentexts is less than 70%, all blood brothers automatically fail.

# Experiments:

Every Blood brother starts with significantly more health, making them much more resilient and harder to kill. But also, some brothers have a small chance to spawn with Paranoia or a random spell.

# Changelog:

CL: [New] A new game-mode has been added, Blood Brothers! It currently requires at least 6 players to be chosen at the start of a round.
CL: [Improvement] Added a black-list and "Always spawn with objective" list for antags.

### CODE REVIEW

**Comment by AtnerNT** [comment]
Closes #3128

**Comment by MaxIsJoe** [comment]
> Closes #3128

its written at the top :)

**Comment by MaxIsJoe** [comment]
To codacy:

https://user-images.githubusercontent.com/34368774/226509428-2716f7f0-8549-44ee-a13c-4e10849d5878.mp4

**Comment by MaxIsJoe** [comment]
It's done, can i get a wivew pwease? uwu

**Review by Bod9001 — DISMISSED** [review]

**Review by corp-0 — CHANGES_REQUESTED** [review]
please solve codacy issues. I can ignore the false positives, but they have to be at least considered and studied first to make sure they are indeed false positive.

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
