### PR TITLE
Improves backgrounds and parallax stuff

### PR DESCRIPTION
**Pull request by MaxIsJoe**
https://user-images.githubusercontent.com/34368774/185728290-d2cce191-f0b0-4e03-a366-f8bd18df6488.mp4

CL: [New] - Added the ability to create more detailed parallax backgrounds.
CL: [New] - Ported over /tg/'s parallax background and replaced it with ours.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
Ready for review

**Comment by Bod9001** [comment]
I would say it needs a bit more colour in the background

**Comment by Bod9001** [comment]
https://cdn.discordapp.com/attachments/312454684021620736/1010367641602490368/unknown.png
something like this looks pretty damn good

**Comment by MaxIsJoe** [comment]
> https://cdn.discordapp.com/attachments/312454684021620736/1010367641602490368/unknown.png something like this looks pretty damn good

The problem with this background that we have no idea what's its copyright

**Comment by corp-0** [comment]
The assets can be improved later. I think this pr is good as is

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
