### PR TITLE
Wet floor sign, chemical container, and trash bin sprites by CeUvi, Twaticus, and Kokonut.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Imports sprites for most beakers, the chemistry bottle, the dropper, and pill container done by CeUvi [from CEV Eris](https://github.com/discordia-space/CEV-Eris/pull/6070).
  - Uses transparency tweaks to CeUvi's sprites by Twaticus and sprites for the x-large and metamaterial beaker by Kokonut [from /tg/station](https://github.com/tgstation/tgstation/pull/58760).
  - Sprites for the cryostasis beaker could not be found, unfortunately.
- Adds new sprites for the wet floor sign icon and the trash bins by CeUvi (made specifically for Unitystation, thanks CeUvi!).
  - Wet floor sign in-hands and worn sprites not included. 
 
image

Credits:
- CeUvi: Beaker, bottle, dropper, pill container, wet floor sign, and trash can sprites.
- Twaticus: Transparency tweaks to CeUvi's beaker and bottle sprites.
- Kokonut: X-large and metamaterial beaker sprites using CeUvi's as a base.

### CODE REVIEW

**Comment by PetMudstone** [comment]
Could someone rerun tests? I ran all local tests and nothing failed on my end.

**Comment by Bod9001** [comment]
my only complaint about the sprites is the sign being one face and The bin being a bit dark

**Comment by PetMudstone** [comment]
CeUvi did make a wet floor sign in a different perspective. However the one in the PR is front-facing in order to make it fit with most things being 3/4ths
image

**Comment by Bod9001** [comment]
yeah, The actual style of the signs Better in the Face on one

**Comment by PetMudstone** [comment]
> 
> 
> yeah, The actual style of the signs Better in the Face on one

Is that pro-PR sprite or pro-comment sprite?

**Comment by PetMudstone** [comment]
And failing again. I'm just close this and try again in a new PR and hope things aren't buggered in there.

**Pull request closed without merging**
