### PR TITLE
Machine Construction

### PR DESCRIPTION
**Pull request by ThatDan123**
Complete

-Adds Machine construction and deconstruction

-Stock parts

-Has support for using any items for construction, they only need to have an item trait.
(Though atm if an item has multiple item traits which are needed by the building only the first is checked, this is an easy refactor, see line 404, but will need additional testing and i want this PR merged asap, also its very niche)

-The stock parts have two item traits, their base and their tier.

-Tier does nothing atm but a script can pull from the machine component on the machine to discover what level the items are inside.

TO ADD NEW MACHINE:

1) You need to create a MachineParts Scriptable Object e.g:

image
-Item Trait is the trait the script will be looking for. 
Note: for the stock parts use the category e.g "manipulator"item trait, not the item trait:          Micro-manipulator, unless you only want Micro-manipulators to be used(cant be upgraded then)

-Basic Item is the prefab to spawn when deconstructing a MAPPED version of the machine

-Amount is how many are needed so the machine can be built

Create it in this folder to keep things organised:

image

2) Add the machine.cs script to your machine and fill in these fields:
image
 
-Machine Parts is the SO you created in 1)

-Frame Prefab in the machine frame prefab in Prefabs/Objects/Construction

-Circuit Board Prefab is the prefab in Prefabs/Items/Construction/Circuitboard/Machine

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.

### CODE REVIEW

**Comment by Bod9001** [comment]
"Speed merge!!! /s" : P

**Comment by VernaSaurus** [comment]
qui ck add it before he finishes it!!!!! ! !!!

**Comment by ThatDan123** [comment]
I can tell you right now who ever reviews this is gonna hate me, cus this code ive made is horrible

Edit: Should be much better now

**Comment by ThatDan123** [comment]
Think this is ready for merge and testing on staging.

Only machine done is cloning pod.

**Comment by ThatDan123** [comment]
Just doing some cleaning up and commenting.

**Comment by ThatDan123** [comment]
Good to merge

**Pull request merged**
