### PR TITLE
Fixes #9717

### LINKED ISSUE #9717: Directional Sign for "Evac" is Broken Regarding Left and Up
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23030914

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

When setting the directional signs for "Evac" exclusively, the directions of left and up seem to be swapped.

### What should have happened instead?

The signs should have been the right way instead of left and up being swapped.

### Steps to reproduce the issue

1.) Open Unity Editor.
2.) Drag in the prefab for the directional evac sign.
3.) Set the direction to either "Up 0" or "Left 90".
4.) Observe.

### Additional context

image
image

### PR DESCRIPTION
**Pull request by coolcat1711**
### Purpose
Fixes #9717
Causes "up" and "left" evac sign sprites to match the Unity editor Rotatable labels.

### Changelog:
CL: [Fix] Fixes evac sign arrow orientation.

### CODE REVIEW

**Review by Bod9001 — APPROVED** [review]

**Comment by Bod9001** [comment]
Wouldn't you have to update the maps for this?

**Comment by corp-0** [comment]
yeah, all maps that corrected facing using the wrong direction will need to be updated.

**Comment by PerfectTangent** [comment]
> yeah, all maps that corrected facing using the wrong direction will need to be updated.

That can be done in a later PR. Sooner this is merged, sooner someone can get started on it.

**Comment by corp-0** [comment]
alright, fair

**Pull request merged**
