### PR TITLE
Moses/2400 cargo contents

### LINKED ISSUE #2400: Cargo Selling Needs to Account for Items That Hold Items B: 25
# Description

Current cargo system does not account for items that hold other items, such as crates. Ensure that the prices are updated correctly, and the export scanner says it includes contents (search for TODO with this id).

### PR DESCRIPTION
**Pull request by StrawberryMoses**
### Purpose
Fixes #2400. Cargo will now look through any storage containers or closet storages to sell all items. All items are removed from the shuttle, even if they are worth 0. New crate prefab variants were created from the base object prefab. Old prefabs were removed, and outpost station was remapped. Only the basic crates were added, so visually some of the "secure" crates are now showing as basic crates.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x]  Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x]  Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ]  This PR has been tested with round restarts.
- [ ]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### Notes:
_Please enter any other relevant information here_

### CODE REVIEW

**Comment by fomalsd** [comment]
have you attempted selling people?

**Comment by StrawberryMoses** [comment]
I have not!
... This should probably be fixed. Tg doesn't allow the ship to depart with anything alive on board

**Comment by StrawberryMoses** [comment]
Would it be worth making that into its own story, since this has prefab deletions and mapping changes?

**Comment by fomalsd** [comment]
There should probably also be a check for living things right before selling process as players can theoretically break into shuttle while it's flying (so just the pre-departure check is not enough)
Destroying player (returning to pool) makes game unresponsive for client because there's no one to control

**Comment by StrawberryMoses** [comment]
I opened this as #2427

**Comment by fomalsd** [comment]
Not sure how ordering behaved before this PR, but at the moment there are errors when attempting to spawn orders with crates, apparently crate prefab is null:
```
[13:20:44:995] [ItemSpawn] Cannot spawn, prefab to use is null
UnityEngine.Debug:LogError(Object)
Logger:TryLog(String, LogLevel, Category, Object[]) (at Assets/Scripts/Debug/Logger.cs:163)
Logger:LogError(String, Category) (at Assets/Scripts/Debug/Logger.cs:117)
SpawnablePrefab:SpawnAt(SpawnDestination) (at Assets/Scripts/Lifecycle/Spawnable/SpawnablePrefab.cs:50)
Spawn:Server(SpawnInfo) (at Assets/Scripts/Lifecycle/Spawn.cs:261)
Spawn:ServerPrefab(GameObject, Nullable`1, Transform, Nullable`1, Int32, Nullable`1, Boolean) (at Assets/Scripts/Lifecycle/Spawn.cs:117)
CargoShuttle:SpawnOrder(CargoOrder) (at Assets/Scripts/Shuttles/CargoShuttle.cs:141)
CargoManager:SpawnOrder() (at Assets/Scripts/Managers/CargoManager.cs:240)
CargoManager:CallShuttle() (at Assets/Scripts/Managers/CargoManager.cs:68)
GUI_Cargo:CallShuttle() (at Assets/Scripts/UI/Cargo/GUI_Cargo.cs:56)
UnityEngine.Events.UnityEvent:Invoke()
NetButton:ExecuteServer() (at Assets/Scripts/UI/Net/Elements/NetButton.cs:13)
TabInteractMessage:ProcessFurther(ConnectedPlayer, GameObject) (at Assets/Scripts/Messages/Client/TabInteractMessage.cs:52)
<Process>d__5:MoveNext() (at Assets/Scripts/Messages/Client/TabInteractMessage.cs:21)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```
I suggest using CommonPrefabs singleton for crate

**Comment by StrawberryMoses** [comment]
Ah, I had forgotten about ordering. It probably works fine before my changes, but I had gotten rid of the existing crate prefabs to make new prefab variant ones

**Comment by StrawberryMoses** [comment]
Added back in crates and adjusted some prices (no more infinite money)

**Comment by fomalsd** [comment]
There's something wrong with counting items in crates: 4 extinguishers count as 12 for some reason:
Scr 2019-12-08 в 19 24 30
But I'm merging this anyway since it's got a scene change

**Pull request merged**
