### PR TITLE
Fixes a possible cause of issue #2915

### PR DESCRIPTION
**Pull request by goman0**
A List can't safely remove items while it's being iterated over. Also, this should make chat code less expensive.

### Purpose
Fixes a code issue in chat code.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- [x] The PR does not bring up any new compile errors
- [ ] The PR has been tested in editor

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
did you test this in multiplayer?

**Comment by goman0** [comment]
Not yet @DooblyNoobly. I still need to set up Unity.

**Comment by Ruzihm** [comment]
ooh nice catch @goman0

**Comment by DooblyNoobly** [comment]
I'm testing it now. No errors so far. I might put it into production and see what happens

**Comment by DooblyNoobly** [comment]
Can't hear pete gasping from cargo so thats a good sign

**Comment by Scorr** [comment]
you can remove while iterating safely if you loop backwards.

I don't know what the exact intention of this code is (maybe removal is not the best here either?), but just setting list values to null doesn't sound like the right way to do it.

**Comment by DooblyNoobly** [comment]
Can't hear shuttles crashing into the otherside of the station so thats good too. Lets give it a go. Iterating backwards or setting them to null achieves the same result. Iterating backwards might of been better but it is what it is now. Lets see what it happens in a build

**Pull request merged**
