### PR TITLE
Staging fixes1234

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [New] Scrubber surge actually works now, and makes a big mess
CL: [Balance] Compact Shotgun Crate Bandoliers now has shells loaded
CL: [Balance] You can sell chicken nuggets for money now
CL: [Balance] Statues are worth money now
CL: [Fix] Fixed Nuclear Opperator game mode.
CL: [Fix] Fixed slimes eating you when you are in a container.
CL: [Fix] Fixed infinite monkey meat from chickens.
CL: [Fix] Fixed false walls catching bullets When open.
CL: [Fix] Fixed Smart Mag interactions
CL: [Fix] Fixed history file
CL: [Balance] False walls don't Show up on highlight now
CL: [Fix] Fixed ID early shuttle departure bypassing hostile environment for Blob game mode.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
whats with all the prefab changes?

**Comment by Bod9001** [comment]
Reactions were messed up for foam for some reason

**Comment by MaxIsJoe** [comment]
..how did that result in 187 asset changes?

**Comment by Bod9001** [comment]
Reordering the Reagent index

**Pull request merged**
