### PR TITLE
Cloth Killer + Belts

### LINKED ISSUE #2315: Consider Converting Cloths to be prefabs (and use prefab variants)
# Description
For many things, we've had to implement custom logic specifically for handling cloths. For example, prefabs have the capability to do prefab variants, but cloths don't unless we build it.

I personally have spent many hours dealing with cloth-specific logic due to them not using prefabs. We should decide if we're really going to stick to this system or refactor them to use prefabs / prefab variants.

IMO we would save a lot of trouble if we just moved them to prefabs / prefab variants. So many features we want to develop are hindered by having to account for unicloths.

EDIT: As far as space usage goes, it should be noted that prefab variants only store their modifications upon their base prefab (as you would expect), so they don't duplicate unnecessary data, see https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Resources/Prefabs/Objects/Canisters/PlasmaCanister.prefab

Also worth noting that the new Spawnables at least provide a standardized way to spawn a prefab or a cloth, but I view this only as a temporary stopgap measure as all the difficulties I mentioned in understanding and creating the cloths still apply.

In fact, by using the prefab variant system, we could do away with the need for spawnables, which adds a bit of convenience into the editor configuration due to not needing to create a Spawnable asset. Basically removing an unnecessary layer of indirection, thus making it easier to configure things which need to be able to reference other objects. Currently it's a little tedious having to create a SpawnablePrefab, reference the prefab, then reference the Spawnable in whatever you wanted it for (like an inventory populator). With prefab variants, you'd just directly reference the prefab you wanted to populate the slot with, and if you wanted any custom initial state, you could make a variant of that prefab and modify the state in the components and use that variant to populate the slot.

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
EDIT: New wiki page on creating objects which somewhat covers the changes in this pr is here: https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants

I also updated the inventory system as slot populators are slightly changed (to hopefully be easier to use) https://github.com/unitystation/unitystation/wiki/Inventory-System

Includes @StrawberryMoses belt PR #2342, which adds belts, refactored to use the new cloth variant system.
Fixes #2315 

Partially implements #2283 because I created a base "Item" prefab and further variants which can be used as the parent for different items (used for different types of clothing)

Adds name / description / resistances / flags to ALL cloths based on tg values, partially implementing #2340 

Things which were referencing Spawnables can now just directly reference prefabs, and all spawnable assets were removed. It's now MUCH easier to define what prefabs should go in things. And due to using prefab variants, if you want any custom logic for a particular prefab, you can simply create a variant and add extra config / component to that variant to handle its particular initialization logic.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Proper-Spawning-and-Despawning-%28Object-Lifecycle%29)
- [ ]  This PR has been tested with round restarts.
- [x]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
This requires some explanation.

First of all, all of the cloths are now in a prefab variant structure, under ClothKiller folder (to protect them from the upcoming Jibby PR). It very nicely aligns with the DM structure of inheritance.

Second of all, the remnants of the previous way of doing things are not fully eliminated yet! This is to try to avoid potential merge issues. In future PRs, this stuff will gradually be eliminated. Most notably:

- ClothingV2 was added to be a "better" version of Clothing, and a temporary interface IClothing was built to simplify the migration. The old clothing and interface will eventually be removed
- Same goes for ItemAttributesV2, I will need to migrate the prefabs that are currently using ItemAttributes to use the new ItemAttributesV2
- The ONLY purpose of ClothData and the other "data" assets now is defining their sprites. ItemAttributes and other stuff is all ignored, except for headset key. These are all now defined on the prefab variants. All of the extra fields are still left on these SOs however, to prevent potential merge issues. These will be removed in future PRs, and it's possible that the different subclasses of BaseClothData will be merged into one if they no longer have a need to have lots of different fields.
- The various SOs which referenced spawnables / slot populators still have those fields defined to prevent potential merge issues, but most of these will eventually be removed. I say "most" because I am planning to maybe remove the custom slot populators like AutoIDPopulator so that a prefab could  have slot population logic in it instead in a component using some sort of hook interface, as I really like the simplicity of all prefabs having self-contained logic of how to init themselves, and using prefab variants to achieve that. And it declutters the storage populator SOs so there's no confusion about whether you need to pick a prefab or pick a slot populator asset.

There are a number of additional changes planned in upcoming PRs, but wanted to get the minimum stuff merged ASAP so as not to block other's work. As it stands it should function correctly. Here's the stuff I'm planning in addition to the removals mentioned above:

- Rename the NamedSlot.exosuit to NamedSlot.outerwear and NamedSlot.uniform to NamedSlot.suit to try to better match what those slots actually represent
- Fix the belt setups, will get @StrawberryMoses to help with this. At the moment we have janitor, CE, and security belts but I am not sure that they have the correct structure, capacity and initial items. I think some of moses' changes may not have ended up in the PR.
- Delete all the code relating to cloth lifecycle stuff, as it shouldn't be needed anymore - no more Spawn.ServerCloth, no more cloth dictionaries, cloths in resource tracker, Uni-item prefabs
- Add a plugin which allows searching for things that reference a particular asset. This will be ESSENTIAL as we add more assets to the game, as it allows us to see what might be affected when changing or migrating a particular asset. Unity doesn't provide a built in way to do this!
- Move the ClothKiller stuff into its correct place after Jibby's PR

Wanted to get this PR up ASAP, I am in the process of updating the wiki with the new structure. I also want to flesh out information on how to create objects / cloths so it's a lot easier for people to do, coupled with the changes in this PR.

### CODE REVIEW

**Comment by StrawberryMoses** [comment]
I spawned in as the captain and I am naked

Hovering over the belts doesn't seem to show a name or description

The belts also all seem to have the default belt sprite

Final minor nitpick for now, i would rename the belts to be just, for example JanitorBelt and JanitorBeltFull, since imo the full is just a child/variant of the belt itself which doesn't need to specify it's state

**Comment by chairbender** [comment]
some stuff didn't get pushed, I'll tweak those things

**Comment by chairbender** [comment]
@StrawberryMoses should be fixed now. Make sure you do it with a clean branch - close unity, git reset --hard, reopen unity.

**Comment by chairbender** [comment]
EDIT: New wiki page on creating objects which somewhat covers the changes in this pr is here: https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants

I also updated the inventory system as slot populators are slightly changed (to hopefully be easier to use) https://github.com/unitystation/unitystation/wiki/Inventory-System

**Review by fomalsd — APPROVED** [review]
Looking good!

**Comment by fomalsd** [comment]
alright, going to merge this and port janitor tweaks to the new system

**Pull request merged**
