### PR TITLE
Pull request for #1018 Start Menu fixes

### LINKED ISSUE #1018: Start Menu fixes
## Current Behavior
Currently the Start Menu, isn't really comfortable, e.g. no "back" or "cancel" buttons. 

## Expected/Wanted/Requested Behavior
Make the start menu more comfortable.  These are just some small changes, have a look at the menu and add some buttons, so you can't get stuck in the menu.

### PR DESCRIPTION
**Pull request by starrlizzard**
### Purpose
Fixes #1018
Updated UI for a better start menu / lobby screen

### Approach
Created reusable prefabs for UI and updated the Lobby screen to use said components. This also includes graceful handling of separate panels (player login and information) which are navigable by the user.

This can be easily extended add additional panel / dialogues in the future.

### Open Questions and Pre-Merge TODOs

- [x]  I read the contribution guidelines and the wiki.
- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  This PR does not include files without specific need to do so.
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
This is my first pull request to this repo. Please let me know any changes / further fixes that need to be done to complete this request and I'll get them done asap.

### CODE REVIEW

**Comment by fomalsd** [comment]
Very nice! Looking very good.
Several small things:
1) I think that button is supposed to be called "Back" or "Return":
screenshot 2018-07-07 15 33 35

2) Another thing is about server address: it's `play.unitystation.org` in editor, but is always changed to `localhost` in `Start()`. 
It certainly should be set to `play.unitystation.org` in case if it `isForRelease`

3) Lastly, a performance/good practice advice:
Instead of checking if host toggle is on every frame in `Update()` you could hook up to toggle updates by adding a following listener in `Start()` instead, so that these assignments only happen when toggle is switched:
```cs
            hostServerToggle.onValueChanged.AddListener( isOn =>
                {
                    serverAddressInput.interactable = !isOn;
                    serverPortInput.interactable = !isOn;
                } 
            );
```
It's not a big deal in this case, but a good thing to know.

**Comment by starrlizzard** [comment]
Thank you for the eye-openers @fomalsd ! I will work on these changes and send and update soon.

**Comment by fomalsd** [comment]
I kind of hoped server IP would still be `localhost` when it's not for release, it's a good thing for testing.
And one more thing I've just noticed: please use tabs instead of spaces, all your new files seem to use spaces as delimiters. Please configure your IDE to use tabs instead, for consistency with our codebase

**Comment by fomalsd** [comment]
awesome!

**Pull request merged**
