### PR TITLE
Expanded acccess

### PR DESCRIPTION
**Pull request by Bod9001**
why? 
since we don't have 60+ pops most of the time you end up having to cover two jobs in one, 
so I've expanded the access to

Engineering, + atmospherics
chemist, + surgery
Medical doctor, + chemistry
bartender, + kitchen
cook, + bar + botany
botanist, + kitchen

### CODE REVIEW

**Comment by ilinm1** [comment]
Won't it be better idea to check if it's actually lowpop on round start and give access only then?

**Comment by NoooneyDude** [comment]
Could we have a comment on why this is on hold? Thanks.

**Comment by Bod9001** [comment]
I think Jack wanted it to be a game mode not sure though?

**Comment by CdrCross** [comment]
> Won't it be better idea to check if it's actually lowpop on round start and give access only then?

This is certainly what TG does. If the number of players  is below the "Skeleton crew" threshold at roundstart, expanded access is granted to everyone. Ideally, we should make it so that everyone who joins until the crew exceeds skeletal levels get expanded access, but everyone after does not.

**Comment by ilinm1** [comment]
Ik, just don't like this temporary solution, we might get medpop at playtest, and with "hardcoded" expanded access it will be uncomfortable

**Comment by craftxbox** [comment]
This feels like it should be configurable server-to-server, rather than hard-coded

**Comment by PerfectTangent** [comment]
closing because of the merging of #8599.

**Pull request closed without merging**
