### PR TITLE
Filth Generator improvements

### PR DESCRIPTION
**Pull request by MaxIsJoe**
image
image

CL: [New] Vomit splatters can now generate randomly, giving janitors more things to clean.
CL: [Improvement] Filth Generator can now generate more types of filth.

### CODE REVIEW

**Comment by Bod9001** [comment]
what is the list of objects It can spawn?

**Comment by MaxIsJoe** [comment]
> what is the list of objects It can spawn?

vomit splats and dirty floor stuff

**Comment by Bod9001** [comment]
ok cool, should vomits Splats have reagents in them, since I think that empty currently the prefab is?

**Review by corp-0 — APPROVED** [review]

**Comment by corp-0** [comment]
> ok cool, should vomits Splats have reagents in them, since I think that empty currently the prefab is?

It is fine. These are meant to make the station dirty. Reagents in vomits are for detective investigation and that kind of thing.

**Pull request merged**
