### PR TITLE
Added new test for missing reffence fields

### PR DESCRIPTION
**Pull request by Macoron**
### Purpose
Add new test to check if there are missing reference fields in any prefab. Checks all prefabs in the project (not the scene instances).
Fixed bunch of missing reference fields. Mostly some outdated sprites. 

### Notes:
Some missing refs was replaced by nulls. Can't find what supposed to be placed there.
Some missing refs was replaced be error sprite (mostly for outdated junk).

### CODE REVIEW

**Comment by CodeKalias** [comment]
> Some missing refs was replaced by nulls. Can't find what supposed to be placed there.
> Some missing refs was replaced be error sprite (mostly for outdated junk).

Is this a good thing to do? I feel like it might just make it a more difficult process for someone to find the correct references or even notice that they have been lost instead of intentionally null/error.

**Comment by Macoron** [comment]
@CodeKalias well, I only changed things that unimplemented/deprecated. All things that working are just fixed.

Damn, somebody added new push to master that broke something. Will fix that, hope this test will prevent such errors in the future.
```Missing reference found in prefab Managers component SpaceAmbience2 field Audio Clip
Missing reference found in prefab Managers component Yeehaw field Audio Clip
Missing reference found in prefab SoundManager component SpaceAmbience2 field Audio Clip
Missing reference found in prefab SoundManager component Yeehaw field Audio Clip
```

**Comment by fomalsd** [comment]
where would the missing references be listed?

**Comment by Macoron** [comment]
@fomalsd download artifacts of the failed job. There will be html report
image

**Comment by fomalsd** [comment]
so is this ready to merge?
> Damn, somebody added new push to master that broke something.

– assuming you're referring to some lost references rather than the test itself?

**Comment by Macoron** [comment]
Yeah, it's ready. I was wrong - it was due to Ubuntu editor side error (some problem on sounds import). All fixed now and all tests passing

**Review by fomalsd — APPROVED** [review]
sweet, merging

**Pull request merged**
