### PR TITLE
[Draft] .3.8f1 LTS upgrade

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Needs more testing before getting ready to update

### CODE REVIEW

**Comment by NoooneyDude** [comment]
You'll need to update things like actions and documentation too. grep for the current version should be enough to find 'em all.

**Comment by corp-0** [comment]
test will always fail if the version in the workflow isn't also updated.

**Comment by MaxIsJoe** [comment]
I've been testing this version for a while now, and it seems to not have any issues yet, I'll test out builds made with this version again and if everything goes smoothly I'll update the workflow and make this ready to be merged.

**Comment by MaxIsJoe** [comment]
I have found only one issue this whole time, and it's related to right-clicking. I'm not sure how to solve it but once I figure that out I'll push the fix and mark this as ready for review.

**Comment by NoooneyDude** [comment]
What's the issue? I've been running on .8 for a while now, all good here.

**Comment by NoooneyDude** [comment]
Generally we're more concerned with major/minor updates and not patches.

**Comment by MaxIsJoe** [comment]
> What's the issue? I've been running on .8 for a while now, all good here.

Right click menu doesn't work, you can't click on it or hover over it

**Comment by Copern** [comment]
> > What's the issue? I've been running on .8 for a while now, all good here.
> 
> Right click menu doesn't work, you can't click on it or hover over it

This happened in 3.6 as well. I believe it had to do with Unity changing the input system and how it handles events.

It might be the issue described [here](https://stackoverflow.com/questions/70719928/onmouseenter-doesnt-work-when-hovering-over-an-object-in-unity). You might have to change the input system on the new version.

Edit: Or it might be the issue described [here](https://forum.unity.com/threads/problem-with-ipointerenterhandler-ipointerexithandler-and-setactive.1235596/).

**Comment by MaxIsJoe** [comment]
closes for #9291

**Pull request closed without merging**
