### PR TITLE
Some new airlock-hacking sounds

### PR DESCRIPTION
**Pull request by Lizurt**
### Purpose
Video review: https://www.dropbox.com/s/6pv9d2ey9qzh5s0/HackingSounds.wmv?dl=0

- The process of hacking airlocks is accompained by sounds:
- - New sounds for cutting wires
- - New sounds for small electric shock
- - New sounds for mending wires

### Notes:

All sounds used are CC0- or CC3-licensed:

https://freesound.org/people/TiesWijnen/sounds/456029/
https://freesound.org/people/CGEffex/sounds/101129/
https://freesound.org/people/benjaminharveydesign/sounds/315918/
https://freesound.org/people/plingativator/sounds/188923/
https://freesound.org/people/deleted_user_7146007/sounds/383449/
https://freesound.org/people/Soundscape_Leuphana/sounds/210313/
https://freesound.org/people/JoelAudio/sounds/136542/

### CODE REVIEW

**Comment by ReiderJack** [comment]
Noticed you didn't commit changes to SoundManger prefab. Those sounds won't be played unless you do.
Here are the gifs on how to do it:
1) Search for SoundManager in resources:

FinsSoundManager

2) Double click on it:

OpenSoundManager

Just `ctr+d` on any sounds in the category which is suited for you sound. Rename it and reference your audio clip in it.

**Comment by ReiderJack** [comment]
Don't forget to save SoundManager prefab when you are done and commit the changes to it. Also make sure that the objects are have the same names as the sounds names in your code.

**Comment by ReiderJack** [comment]
Make sure you update your branch before changing SoundManager prefab. There were merged changes to it recently, so there will be conflicts.

**Comment by Lizurt** [comment]
Done
@ReiderJack

**Pull request merged**
