### PR TITLE
More round end sounds and restart vote cooldowns

### LINKED ISSUE #2961: Players can spam Restart votes
# Issue Template

## Description
Players are able to create new restart votes immediately after their current one finishes

Suggestion add a 30 second cooldown on creating a vote

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
Adds all current /tg/ round end sounds
Makes a random on play on round end
Makes restart votes trigger round end which plays sound and shows round report
Changes the round restart timer to a coroutine
Fixes #2961 
Adds a ~5~ 1 minute wait before restart votes can happen in the round
Adds 1 minute wait between votes

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by ghost** [comment]
Horrible idea with the delay. Most restarts are called way before the 5 minute mark for a reason. Bombing/L6SAW massacre/ramming/fire/whatever.

**Comment by Jibbajabbafic** [comment]
The values can be tweaked but there definitely needs to be a delay to curb the vote spamming

**Comment by Jibbajabbafic** [comment]
And this might encourage people to be more careful if they can't restart rounds instantly

**Comment by ghost** [comment]
> And this might encourage people to be more careful if they can't restart rounds instantly

Bad approach in the current situation without admins. The only thing this change will do is that it will make roundstart griefing even stronger, because the damage will last at the minimum the whole duration of the delay.

Currently: HoS rushes L6, kills all officers and doctors and starts hunting the survivors? No issue. We all peacefully restart and it won't happen the next round.
With your change: HoS rushes L6, kills all officers. Eventually kills everyone. 20 ghosts are following the HoS while waiting for the delay to be over. Half of the server disconnects.

Sure keep a delay _between_ votes, but in the current situation without admins, it's better to let the players decide when a round is over, even if it's just 30 seconds in.

**Comment by Jibbajabbafic** [comment]
I'll reduce it to 1 minute for now and then it can be tweaked in future.
I feel like having a delay will encourage people to take the griefing a bit more seriously, so if someone does ruin the round within 10 seconds the ghosts will have a little time to tell an admin instead of just moving onto the next round.

**Comment by Jibbajabbafic** [comment]
If you can instantly restart rounds whenever you want it makes people value them a lot less since they know they can restart it if anything goes wrong.

**Comment by Jibbajabbafic** [comment]
Damn conflicts 😢
I'll have to fix this up after work.

**Comment by Jibbajabbafic** [comment]
All good to be reviewed now!

**Comment by fomalsd** [comment]
hmm, did a test (called and boarded a shuttle) and didn't hear any round end sounds. vote restart cooldown worked fine though

**Comment by Jibbajabbafic** [comment]
Can you see the round end sounds on SoundManager?
I tested with the `call-shuttle` and `end-round` commands and heard sounds for both on a clean branch.

**Comment by fomalsd** [comment]
only tried github builds, yet to try the branch in editor

**Comment by Jibbajabbafic** [comment]
Hmm you're right it's not working on the builds

**Comment by Jibbajabbafic** [comment]
Oh wait, I tried again after that first round and it's working now.

**Comment by fomalsd** [comment]
maybe some sounds are missing and that's why it didn't play the first time, but got to check

**Comment by fomalsd** [comment]
I think it's an issue of how we end round for shuttle escape scenario. When ending round artificially sounds do play

**Pull request merged**
