### PR TITLE
Add door sounds to microwave

### LINKED ISSUE #7668: Microwaves make a punching noise
### Environment
- Game Version: Staging 27-10-2021
- OS Version: Manjaro Linux

### Detailed description of bug

Microwaves make a punching sound when used.

### Steps to reproduce

1. Add or remove something from it
2. hear the noise

### PR DESCRIPTION
**Pull request by ProudCipher**
### Purpose
Fixes #7668

### Notes:
Added door sounds to the microwave. 

### Changelog:
CL: [Fix] Added appropriate sounds to microwaves.

### CODE REVIEW

**Comment by Bod9001** [comment]
make sure to delete the old address will bundle in the addressable packing project

**Comment by PerfectTangent** [comment]
Where did you get the sfx from?

**Comment by ProudCipher** [comment]
> Where did you get the sfx from?

My microwave lol

**Comment by corp-0** [comment]
sound is good, clear and dry. Just out of curisousity, how did you capture it?

**Review by corp-0 — APPROVED** [review]

**Comment by Bod9001** [comment]
just a note will need to update the addressable bundle on CDN

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
