### PR TITLE
Adds missing gibtonite interaction

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Fix] Gibtonites had a missing welder interaction which prevented them from being easily activatable without putting them next to a heat source.

### CODE REVIEW

**Comment by corp-0** [comment]
Can you destroy items like the station disk with this?

**Comment by MaxIsJoe** [comment]
> Can you destroy items like the station disk with this?

No, items that are marked as indestructible won't get destroyed. Nuke disks already are marked as such.

**Comment by Bod9001** [comment]
I don't remember being able to melee items?

**Comment by Bod9001** [comment]
And the other question is why is this needed?

**Comment by MaxIsJoe** [comment]
You can now.

And because some items have interactions with damage. Right now, the only way to trigger these interactions is via environmental damage, which can be quite tricky to pull off. This lets players more easily trigger these damage interactions with items that they already have.

**Comment by Bod9001** [comment]
Well add it to the items that you want to have the functionality on?

**Comment by Bod9001** [comment]
liek just giving it Meleeble?

**Comment by MaxIsJoe** [comment]
Billions must be meleeable (for consistency)

**Comment by Bod9001** [comment]
remember with the gib  explosive you could activate in hand to startt the timer

**Comment by MaxIsJoe** [comment]
> remember with the gib explosive you could activate in hand to startt the timer

Player hands are not made of fire.

**Comment by Bod9001** [comment]
well I imagine you like snap a bit off and it causes it to be unstable

**Comment by MaxIsJoe** [comment]
It needs heat to activate again

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
