### PR TITLE
add Survive Objective for nuke ops

### PR DESCRIPTION
**Pull request by corp-0**
### Purpose
The idea is to have an incentive for Nuke Ops to leave the nuke and flee. This is also how it is played in original SS13.

### Notes:
I just added the scriptable object to the Nuke Ops antags.

### CODE REVIEW

**Comment by Jibbajabbafic** [comment]
Does this work? The intention was for escape objectives to be generated by ticking 'NeedsEscapeObjective' but that will randomly pick the escape or survive objective. There's no logic to *only* choose specific escape objectives yet which I could add since I've been modifying some of the antags in my PR.

**Comment by corp-0** [comment]
as far as I know, "escape" means escaping in the evac shuttle which is not what we want... I think. Survive objective only checks if you're alive at the end of the round.

The idea here is to make them flee after planting the nuke as the explosion has a radius in which it is deadly (see ``nuke.cs``).

**Comment by Jibbajabbafic** [comment]
Hmm the naming makes this a bit confusing. When I said 'escape objectives' I meant objectives like Escape or Survive, so if 'NeedsEscapeObjective' is true it will randomly pick one of those.

I'll rename 'NeedsEscapeObjective' to 'NeedsFinalObjective' or something like that to make it clearer.

Anyways, I think you will need to increase NumberOfObjectives to 2 for this to work like you intended.

**Comment by corp-0** [comment]
closing as the changes will be included in a bigger PR by @Jibbajabbafic

**Pull request closed without merging**
