### PR TITLE
Fix Issue #860, Graphical Fixes, Sprite Mesh Type Changed.

### PR DESCRIPTION
**Pull request by alex180500**
- Fixed Issue #860 using image.alphahitminimumthreshold
- Various graphical fixes in the lobby interface: panels equidistant from left and right, panel tooltip and panel right are connected in a more pleasant way in the bottom right, text fixes and separator dimension fixed.
- Every single sprite mesh type has been changed to FullRect in order to work correctly with alphathreshold.
- The sprite that weren't spliced has been spliced now, if i made some mistakes with the cell sizes/number fix them.
- Now the old (Just joined) text in lobby is (*just joined)

### Open Questions and Pre-Merge TODOs

- [X]  I read the contribution guidelines and the wiki.
- [X]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [X]  This PR does not include files without specific need to do so.
- [X]  This PR does not bring up any new compile errors
- [ ]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### CODE REVIEW

**Comment by fomalsd** [comment]
Hm, there is a conflict with Managers.prefab since someone changed it after you started working on this, so we should either recreate the changes made in repo in your version or do the opposite, as merging prefabs/scenes is a no-no
Had a very brief look and it looks like the scrollbar for player list is always active (even if there is just one player) and scrolled to the bottom by default (so you don't see players unless you scroll up), this is weird
Will test more and report back

**Comment by DooblyNoobly** [comment]
Easiest way to fix the managers problem @alex180500 is to copy Managers.prefab from develop on unitystation/unitystation, paste it into your feature branch on your fork and commit/push that. It will update here in the PR. You can also make changes to the Managers.prefab you cut and pasted and it will still clear the merge conflict

**Comment by alex180500** [comment]
I'll resolve soon

**Comment by fomalsd** [comment]
#860 is fixed alright, but what's resolution switcher for? it doesn't seem to work and always defaults to 1080p regardless of current resolution (I often test in 640x360-ish resolution, for example)

**Comment by alex180500** [comment]
The resolution switcher doesn't work now, I added it and in the next prs i'll make it work properly

**Comment by DooblyNoobly** [comment]
thanks @alex180500

**Pull request merged**
