### PR TITLE
Canister wrenching sound

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Canisters will play the wrenching sound when connecting and disconnecting them to connectors

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by chairbender** [comment]
Tested in multi. Client never hears the sound, even when performing the action themselves, since the logic which plays the sound only happens server side. The old interaction system strikes again!

Is the sound intended to only be heard locally, or should it be heard by all players? If it should be heard by others, then using PlayNetworkedAtPos should solve this issue easily.

**Review by chairbender — CHANGES_REQUESTED** [review]
Tested in multi. Client never hears the sound, even when performing the action themselves, since the logic which plays the sound only happens server side. The old interaction system strikes again!

Is the sound intended to only be heard locally, or should it be heard by all players? If it should be heard by others, then using PlayNetworkedAtPos should solve this issue easily.

**Comment by Aranclanos** [comment]
good catch

**Comment by Aranclanos** [comment]
Fixed

**Pull request merged**
