### PR TITLE
New floor decals, Fall and Ancient station fixes and improvements

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

Taking a cue from Ministation, this PR adds floor decal prefabs to replace the buggy tile palette versions. It also adds cleanable dirt decals as well. 

This PR also fixes several issues with Fallstation and Ancientstation, namely replacing all the tile palette floor decals in both scenes and fixing several missing or misplaced pipes in Fallstation (thanks for spotting that one in atmos, Dr. Dave).

### Notes:

- organized the decals into folders.
- added a base floor decal.
- fixed 5 cases of misplaced pipes in Falls.
- after removing the tile palette decal from two key spots, it should be less hellish setting up the plasma generator and the singulo in the Ancient station. They were blocking wire placement.
- removed the windows in the psychologist's room in Fall. Patients deserve some privacy.
- replaced some cases of reinforced windows with regular ones when the extra security wasn't needed in Fall.
- For a very long time the Captain has had 2 very large rooms in the bridge in Fall. This PR moves everything into one room and turns the other into a meeting room for the heads of staff.
- added a couple disposal bins to Fall's bridge.
- added cardboard sheets and wrapping paper to Fall's Cargo.
- added an additional randomized gas canister to Fall Atmos
- randomized some of the loot in the Ancient station.
- replaced the loose rock in Fall with smooth rock.
- fixed missing access requirement on a windoor in Fall's Cargo dept.
- added lavaland SSUs to Fall's mining department.

### Changelog:

CL: [New] Added dirty floor decals.
CL: [Balance] There is now a meeting room for heads of staff in Fallstation.
CL: [Balance] Randomized some of the loot in the Ancientstation.
CL: [Balance] reduced the prevalence of reinforced windows in Fallstation where they were not needed.
CL: [Balance] added cardboard sheets and wrapping paper to Fallstation's Cargo department.
CL: [Balance] added a couple disposal bins to Fall's bridge.
CL: [Balance] added lavaland Suit storage units to Fall's mining department.
CL: [Fix] Fixed 5 different map mistakes with Fallstation's atmos pipes. Atmos should flow much better now.
CL: [Fix] fixed some issues with floor decals in Fallstation and Ancientstation.
CL: [Fix] fixed two issues with setting up the singularity and the plasma generator in Ancientstation.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
New decals in action:
Screenshot 2022-05-28 155113

New meeting room in Fallstation:
Screenshot 2022-05-28 161109

**Comment by PerfectTangent** [comment]
`AncientStation: "APC - Shuttle" has an empty list of devices.`

APCs _have_ to have something connected to them?

**Comment by PerfectTangent** [comment]
That's a bit shit.

**Comment by NoooneyDude** [comment]
I agree. I think checking for null in the list is sufficient enough to check for broken references.

**Comment by Copern** [comment]
> I agree. I think checking for null in the list is sufficient enough to check for broken references.

Was there a reason why the empty list check was in the tests in the first place? Do things somehow break if an APC has an empty list? I sure hope not, that would just be silly.

**Comment by NoooneyDude** [comment]
> Was there a reason why the empty list check was in the tests in the first place? Do things somehow break if an APC has an empty list? I sure hope not, that would just be silly.

I'm not too certain, but it was probably this aggressive to catch all possible unintended disconnections while broken references were causing considerable pain. It won't break APCs if there's nothing connected.

**Comment by Copern** [comment]
I'll go ahead and remove that part of the test. Checking if we have an empty list does seem like overkill. We already check if powered devices are actually attached to an APC which should tell us about orphaned devices anyway.

**Comment by PerfectTangent** [comment]
force merge prayer

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
