### PR TITLE
General fixing2

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:

CL: [Improvement] Improves quick store (e) functionality now it will try storing in offhand storage or backpack
CL: [Improvement] adds cyborg repairs to synthetic body parts
CL: [Improvement] Throwing your own items shouldn't hurt you now
CL: [Improvement] added wrenchable vending machines
CL: [Improvement] rolling pin can be used  on items in the world
CL: [Improvement] Improved buckling logic and Slime eating logic, slimes will now the common reference for what they are buckling instead of having their own reference
CL: [Balance] more resilient microwave, microwave can withstand more food being removed and added before breaking down
CL: [Balance] remove sickness as a random event
CL: [Balance] increased potato growth speed
CL: [Balance] Adds spade and Cultivator to fall station
CL: [Balance] added Light replacer to Janitor locker
CL: [Fix] Removes accidentally added gas setter on square station
CL: [Fix] fixes the decals in cargo in ministation being cleanable
CL: [Fix] fixed medical console showing ??? if you had ID in PDA
CL: [Fix] fixed being a me to run when in critical
CL: [Fix] fixed slime still eating even though they've been vac gunned off  what they were eating

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
image

would have liked a heads-up about this on discord or on this PR
don't just make a version bump unannounced

**Comment by Bod9001** [comment]
Accidentally committed

**Comment by corp-0** [comment]
"improved buckling logic and slime eating logic" needs some clarification.

Same with "more resilient microwave"

**Comment by Bod9001** [comment]
done to both

**Comment by corp-0** [comment]
> done to both

Buckling and slime one is still hard to understand.

**Comment by Bod9001** [comment]
idk  how to write it any better

**Review by MaxIsJoe — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
from my understanding the changelog should be:

Slimes will now remember what they're buckling on instead of constantly switching between unintended targets.

**Pull request merged**
