### PR TITLE
Fix for green text problem for antags hiding in closets

### PR DESCRIPTION
**Pull request by MaxIsJoe**
part of #4658

The idea of this fix is that the game should check if the the shuttle has a tile that the antag is currently on when the matrix check fails

CL: [Fix] fixed antagonists not getting greentext for objectives if they were hiding in closets.

### CODE REVIEW

**Comment by corp-0** [comment]
Is the antag tile returning 0,0 or the closet tile?

**Comment by MaxIsJoe** [comment]
> Is the antag tile returning 0,0 or the closet tile?

Matrix ID is mismatched when in closet so I assume that yeah it thinks that it's in 0,0
`antagTile.WorldPositionServer` should solve this because we're retrieving his position on the closet and checking if the shuttle doesn't have a tile in that position.

**Comment by corp-0** [comment]
And did you test it? Because from what I remember WorldPositionServer is 0,0 when inside a closet. AssumedWorldPosition tho will return the closet pos

**Comment by MaxIsJoe** [comment]
> And did you test it? Because from what I remember WorldPositionServer is 0,0 when inside a closet. AssumedWorldPosition tho will return the closet pos

Tested now and pushed a fix

**Review by Bod9001 — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
