### PR TITLE
Continuation on Mobs improvements

### PR DESCRIPTION
**Pull request by corp-0**
# Pull Request Template

### Purpose
This PR focuses on fixing some styling, bad decisions and NRE's from #3714
It will also add a new interaction between Ian and Runtime.

### Notes:
- Tabified the unholy spaces.
- Better indentation on long ass method arguments.
- Rewritten Mice hunting behavior. It now uses MobMeleeAttack.
- Deleted non generic method from generic class MobAI
- Added a new toggable to MobMeleeAttack to only attack followtarget, defaults to false.
- Dogs will now chase Cats if in range.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [ ] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- [ ] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by Evan-R-Rogers** [comment]
Why did you mention #3728? Seems to have no correlation to this.

**Comment by corp-0** [comment]
stupid gitbhub keep suggesting me to tag that instead of the thing I'm literally typing

**Comment by Bod9001** [comment]
SoundManager.prefab Merge conflicts

**Comment by corp-0** [comment]
I know. ThatDaniel has some changes on soundmanager too, so I’ll wait until that’s merged and then redo my thing

**Comment by corp-0** [comment]
ready for mergerino e.e

**Comment by DooblyNoobly** [comment]
does this pr fix these nres being spammed:

```
NullReferenceException: Object reference not set to an instance of an object
  at MobExplore.IsTargetFound (UnityEngine.Vector3Int checkPos) [0x00091] in /github/workspace/UnityProject/Assets/Scripts/NPC/AI/MobExplore.cs:108 
  at MobExplore.CollectObservations () [0x00054] in /github/workspace/UnityProject/Assets/Scripts/NPC/AI/MobExplore.cs:84 
  at MLAgents.Agent.SendInfoToBrain () [0x00076] in /github/workspace/UnityProject/Assets/ML-Agents/Scripts/Agent.cs:596 
  at MLAgents.Agent.SendInfo () [0x0000c] in /github/workspace/UnityProject/Assets/ML-Agents/Scripts/Agent.cs:1039 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at MLAgents.Academy.EnvironmentStep () [0x000e7] in /github/workspace/UnityProject/Assets/ML-Agents/Scripts/Academy.cs:567 
  at MLAgents.Academy.FixedUpdate () [0x00001] in /github/workspace/UnityProject/Assets/ML-Agents/Scripts/Academy.cs:594 
```

**Pull request merged**
