### PR TITLE
Fixes the singulo not killing players

### LINKED ISSUE #6462: Players are invincible, even from Lord Singulo
### Environment
- Game Version: Staging 21050308
- OS Version: Irrelevant

### Detailed description of bug

This was encountered on the staging server. Some of the staging testers noticed that they were unable to kill one another. Even being thrown into singularity doesn't do anything.

Possibly related to the fire damage issue described in #6398.

image

### Steps to reproduce

1. Join a game, preferably with a client connected as well.
2. Try to kill each other.
3. Throw yourself into Lord Singulo.
4. Observe that you cannot die no matter what.

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes #6462
Fixes gibbing not ghosting out players.

### CODE REVIEW

**Comment by Korywon** [comment]
This does not completely resolve #6462, only progress towards it. There is still the issue of players not being able to receive damage from anything. This should only count as progress towards the issue.

**Comment by Aranclanos** [comment]
Damage still works, if players noticed that they weren't taking damage from space after stepping inside the singulo, is that their characters were actually in hiddenpos serverside.
However, I also just briefly tested shooting and stepping on space as a client and server, damage works just fine both ways.

**Comment by Korywon** [comment]
Ah okay, sounds good. Just making sure that we're covering all bases. That would explain why there was no damage being done.

**Comment by waffielz** [comment]
f

**Pull request merged**
