### PR TITLE
Dark FOV

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
Some people don't like the fact you can see the layout of the station, this could address it slightly, With a simple fix

Currently only limitations are that you can see a little bit further into walls Than you should be able to but it's only tiny amount, Wall brightness is is a separate issue
and space isn't covered by FOV

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [?]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [ ]  Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [ ]  Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ]  This PR has been tested with round restarts.
- [ ]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### Notes:
It's up for the maintainers to decide

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
dnm until its fully reviewed

**Comment by chairbender** [comment]
whatever we decide, I would suggest we make this a flag in one of the managers, like "mesonVision".

**Comment by DooblyNoobly** [comment]
Some screen shot comparisons:

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

**Comment by DooblyNoobly** [comment]
So the biggest problem I have with it is you lose a bit of brightness in the viewable area. If that can be fixed somehow then I don't mind merging the all black shroud area

**Comment by DooblyNoobly** [comment]
looks like that is pretty easy. Moving it to 0.23 seems to work pretty well: 
image

image

**Comment by DooblyNoobly** [comment]
I think I'll merge it pretty soon. Pretty easy to revert anyway plus I am liking the new black shroud the more I use it. I actually now have to get a lamp to explore a dark room which adds to the atmosphere

**Comment by DooblyNoobly** [comment]
Merging it into quick fixes branch so I can work on the lighting there

**Pull request merged**
