### PR TITLE
Added option to not consume healing item on use + Fixes Door crowbar ( thought this branch was already merged oops )

### PR DESCRIPTION
**Pull request by Bod9001**
pretty self-explanatory title
Fixes Door crowbar 

CL: [Balance] organ treatment no longer consumes gauze or ointment when used.

### CODE REVIEW

**Comment by corp-0** [comment]
So you still need to interact with the item but it isn't consumed, I'm understanding that correctly?

**Comment by Bod9001** [comment]
yeah

**Comment by corp-0** [comment]
I might have not read a discussion about it but why do  we need it to work like this now? It is odd using a consumable item but not actually consuming it.

**Comment by CdrCross** [comment]
> I might have not read a discussion about it but why do we need it to work like this now? It is odd using a consumable item but not actually consuming it.

If the item is consumed, surgery is 100% inferior to just using the item for heals.

**Comment by corp-0** [comment]
I thought surgery was needed to heal damage of internal parts and you couldn't heal those with the regular method of simply clicking body part with item In hand

**Comment by Bod9001** [comment]
you can't heal internal organs by, clicking them with the bandage

**Comment by corp-0** [comment]
ok so I'm back to the first question. Why do we need this?

**Comment by Bod9001** [comment]
Because, it doesn't give any advantage to surgery for doing healing stuff

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
