### PR TITLE
Changed UnRealStation and Fixes HoS Headset so it shows the right radio channels

### LINKED ISSUE #5992: The Singularity Engine should be mapped into at least 1 map
### Description

Now that the Singularity is in game, it should be added as the main power source for at least one Mainstation.

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Updated UnRealStation to have Singlo for Engies to set up, puts the map in maps.json and fixed the HoS's Radioheadsets because they were stuck on the common encryption key not the HoS one, so they are now on the HoS one.

closes #5992

### CODE REVIEW

**Comment by corp-0** [comment]
> puts the map in maps.json

this means it is available in rotation? Did you fix the weird cross matrix interaction?

**Comment by Akbadain29** [comment]
Yeah, it somehow fixed itself, I could suddenly board the mining shuttle with no issue. It's wack.

**Comment by Akbadain29** [comment]
It failed, why did it fail?

**Comment by corp-0** [comment]
> UnRealStation: "LightBulbFixture (2)" miss switch reference.
UnRealStation: "LightBulbFixture (1)" miss switch reference.

two lights missing switch

**Comment by Akbadain29** [comment]
Ok, that test is green now, I hate forgetting to tick the "Is without switch" box.

**Pull request merged**
