### PR TITLE
[DNM] the mess that is ComplexMealBase

### PR DESCRIPTION
**Pull request by VernaSaurus**
complexmealbase was supposed to be how to make things that needed more than two ingredients but i never finished it and it's a huge mistake

only pr'ing this to see if anyone wants to fix this horrid mess

### CODE REVIEW

**Comment by VernaSaurus** [comment]
ass we can, seems like i fucked up some files

let me delete those

**Comment by VernaSaurus** [comment]
that should do it, still don't merge it though

**Comment by kruezbergbier** [comment]
Fucked up

**Comment by VernaSaurus** [comment]
i'm just going to close this, it's never going to be finished

**Pull request closed without merging**
