### PR TITLE
Show control information in-game

### LINKED ISSUE #1153: Display the keyboard and mouse controls in-game
# Description
Have an option to view the in-game keyboard and mouse controls so that new players can learn how to interact.

## Category
TODO

## Criteria
* Show the controls in the lobby
* Show the controls in the main game

### PR DESCRIPTION
**Pull request by aodendaal**
### Purpose
Fixes #1153
Adds a new button to the lobby panel and to the in-game tab window with the game controls

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [ ]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [ ]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer

### CODE REVIEW

**Comment by fomalsd** [comment]
Looks fine, what is OutpostDeathmatch scene change for though?

**Comment by aodendaal** [comment]
In hindsight I didn't need to change the OutpostDeathmatch scene. I was working on the UIManager prefab adding the extra tab. I didn't need to update the scene. Let me try to remove the scene changes and update the pull request

**Comment by aodendaal** [comment]
Scene update removed. An update to the lobby scene is still included because the panels are not in a prefab.

**Comment by fomalsd** [comment]
Awesome, thanks!

**Pull request merged**
