### PR TITLE
Various microwave improvements, and player movement can cancel itself

### LINKED ISSUE #2527: Holding opposite movement keys does not move players but produces footsteps
# Description

Holding two different movement keys (UP and DOWN, LEFT and RIGHT, or UP, DOWN, LEFT and RIGHT) continuously produces footstep sounds, even though the player is not moving.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Hold two opposite (or all four) directional movement keys, either by using WASD or the arrow keys.
2. Listen to the footsteps.

## Suggestions

* Make cancelled movement not produce footstep sounds. 

Alternatively...

* Implement "Null Movement". (Might alleviate #1745)
  With "Null Movement", when a player holds two opposite directional keys (e. g. LEFT and RIGHT) the most recently pressed key will be used, moving the player. If one of the two keys is released, movement continues as normal.
   For example: A player is going LEFT down a corridor. The player now decides to go RIGHT while still (clumsily) holding LEFT. Instead of coming to a standstill they would move to the right. Thanks Null Movement!

### PR DESCRIPTION
**Pull request by daalta**
### Purpose

- Added comments!
- Microwaves now count down instead of up.
- Players can interact with the microwave to see:
  - How much cooking time is remaining
  - If the microwave is empty
  - If the microwave rejects their held item
- RegisterTile is now used to spawn the cooked meal (instead of transform.position)
- The microwave 'ding' sound now plays 1.5 seconds before the microwave is finished. The soundfile contains some 'warm-up' noises at the start and did previously not sync up with the microwave being done cooking
---
- Opposite player movement directions (e.g. left and right) now cancel each other
- Fixes #2527
- _Kind of_ addresses #1745?
- Autoformatted Chat.cs

### Self checks:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
  - One client in editor, one in a Development Build
  - The behaviour of the microwave is largely unchanged, so multiplayer checks were not extensive.
  - Player movement is only changed client-side

### CODE REVIEW

**Comment by Bod9001** [comment]
By gum, We don't have all the features of TG yet but We have the most advanced microwave code : P

**Comment by daalta** [comment]
Added my player movement changes to this pull request. Hope that's OK. When a player presses two opposite movement keys they are now interpreted as not moving at all.

**Review by chairbender — APPROVED** [review]
Working nicely, thanks! Good job for a first PR. This is probably one of our most stale components haha, and now it's much more robust. I'm going to approve and merge this since it's working but here's a few suggestions anyway.

Thank you as well for the code formatting changes.

General comments:
* Naming convention for editor assignable fields should be UppercaseCamelCase, not SNAKE_CASE. If our code style guide indicated otherwise I probably need to update it, I think the naming convention stuff might not be that clear or wrong because I wrote it a very long time ago.
* I don't actually think there's a need for Microwave and InteractableMicrowave to be separate anymore, the interaction logic from InteractableMicrowave can most likely be merged into Microwave and deleted. Don't think we plan on having any microwaves you can't interact with.

**Comment by daalta** [comment]
Thanks chairbender. Nice to hear that I did OK. 😙

The snake case is definitely a mistake for SPRITE_ON and COOK_TIME. I was toying with making those variables static and did not end up correcting the names. Oops.

**Pull request merged**
