### PR TITLE
Update of foam, less space needed.

### PR DESCRIPTION
**Pull request by Fr-Dae**
### Purpose
 <br>

It's probably not quite optimised, but it will take up less space this way.

### Notes:

there are already line breaks imposed, in addition to the use of boxes and headings to demarcate paragraphs

### Changelog:

- Modification: removed some line breaks to lighten the form a bit and make it take less space on discord.
No changes on github visible.

### CODE REVIEW

**Comment by corp-0** [comment]
I did those empty lines intentionally for readability

**Comment by Fr-Dae** [comment]
there are already line breaks imposed, in addition to the use of boxes and headings to demarcate paragraphs
I invite you to look at the difference with the new one, it's minimal, but I think it's a good improvement. 

https://github.com/unitystation/unitystation/blob/5c469dcb68912cb9a1b2c18a20092e1911b1d54d/.github/ISSUE_TEMPLATE/bug_report.yml

**Comment by corp-0** [comment]
Are you saying the empty lines in the yml file are showing in the rendered form?

**Comment by Fr-Dae** [comment]
> Are you saying the empty lines in the yml file are showing in the rendered form?

from my observations and some testing, yes the line break can have an influence on the organisation of the final document, including indentation.

**Comment by corp-0** [comment]
Ok, I will give it a better look tomorrow since I'm in bed already. For this kind of changes, that don't affect gameplay, you can skip the changelog and ignore the bot.

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
