### PR TITLE
Adds clownsteps, bootsteps and barefoot sounds

### PR DESCRIPTION
**Pull request by corp-0**
# Pull Request Template

### Purpose
Adds checks for footwear so we can play the proper sound when walking. Takes in consideration footwear, then surface.

### Notes:
- In this implementation, footwear sounds (clown and boots) sound **instead** of the normal surface sound. I don't remember if they played together, I think they didn't.
- When barefoot, takes in consideration the surface and plays the proper barefoot sound (Currently implemented normal barefoot when walking on any WalkingSoundCategory "floor", carpet barefoot when walking over carpet and wood barefoot when walking over wood).
- Adds a new field to BasicTile so other barefoot sounds can be declared for any tile.
- Adds 2 new traits to tag items as Squeaky (like clown shows) and Boots (for anyhting you want to sound like *thump thump*.

### Please make sure you have followed the self checks below before submitting a PR:
- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- [x] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by fomalsd** [comment]
how about not letting normal boots override floor sounds?

**Comment by corp-0** [comment]
Only boots? Can do that, but I’d confirm first if that’s how it was on byond

**Comment by fomalsd** [comment]
yeah, I'd check with tg first

**Comment by corp-0** [comment]
Boots sound (heavy) plays instead of the normal surface sound in byond. Only exception to that rule is water and lava. That means this implementation would work for now, but it is not a good representation of how Byond did their thing. I will make some changes and use the same categories TG uses.

**Comment by corp-0** [comment]
Done. With this new implementation I recreated the data structure used in TG, but it also let us fully customize sounds for each tile against type of step (maybe we want a bootOnGrass sound for reasons?). 

Each tile has the fields:
- WalkingSoundCategory
- BarefootWalkingSoundCategory
- ClawWalkingSoundCategory
- HeavyWalkingSoundCategory
- ClownWalkingSoundCategory

Fields have a default sound so you only change the one you need to be different. They all follow the classic TG behavior.

Notes:
- I didn't add claw sounds to SoundManager neither did the method to reproduce claw steps, because we don't have creatures with claws yet.

**Pull request merged**
