### PR TITLE
OOC Http/https links

### PR DESCRIPTION
**Pull request by ThatDan123**
Allows admins (or all players if the config is set to allow them) to post clickable http/https links in OOC

### CODE REVIEW

**Comment by corp-0** [comment]
what's the default for players, false?

**Comment by corp-0** [comment]
why are the spaces needed now btw? It wasn't a problem in old ui

**Comment by ThatDan123** [comment]
Had to change the chat front sadly which messed up the spacing for bold characters.

Tried to convert the old font to a TMP font but it wouldnt work.

**Comment by ThatDan123** [comment]
And yeah, its admin only by default

**Pull request merged**
