### PR TITLE
Fixes fires not smashing windows

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes fires not smashing windows.
Adjusted window fire armor values.
Increased fire damage on windows.
Made the AddDamage() function from TilemapDamage easier to read.

### CODE REVIEW

**Comment by corp-0** [comment]
did you live test how it felt? I remember we buffed windows fire armor because fire broke them way too easy.

**Comment by Aranclanos** [comment]
feeling is subjective

**Comment by corp-0** [comment]
in objective terms, how much time it took a window to break in a fire. Before we buffed them they might as well not be there to begin with because fire melted them almost instantly.

**Comment by Aranclanos** [comment]
25 bumps (recognizeable by the window hit sound that fires do) 
there's one each 0.5 seconds
12.5 seconds

**Comment by corp-0** [comment]
I guess that's alright. Codacy is complainig about a double ; in fire exposure thingy.

**Comment by Aranclanos** [comment]
just dnm so I dont make conflicts with the other pr that made me remember about fires

**Comment by PerfectTangent** [comment]
Does this pr address issue #4887? It seems to mitigate it at the minimum

**Comment by Aranclanos** [comment]
conflicts solved

**Comment by corp-0** [comment]
alright, bye bye windows.

**Pull request merged**
