### PR TITLE
Fix WinDoor hitbox rotation

### PR DESCRIPTION
**Pull request by AutumnNova**
# Pull Request Template

### Purpose
Correct the rotation of windoors to fix issues in maps like box and pogstation

### Notes:
was also going to make the windoor drop glass shards instead of metal sheets, but i couldnt figure it out

### CODE REVIEW

**Comment by Evan-R-Rogers** [comment]
Pog doesn't use windoors but this is still great! This will fix the windoors not being able to function correctly sideways, yes?

**Comment by AutumnNova** [comment]
it should do, yes

**Comment by ThatDan123** [comment]
If you want the test to succeed you just need to merge develop/upstream

But it should be fine to merge as it looks like the issue failing it has been fixed and there arent any other failures.

**Comment by fomalsd** [comment]
I suppose you meant Outpost instead of Pog, since outpost has obvious one at captains place

**Comment by ThatDan123** [comment]
Looks like windoors might be broken again.

**Pull request merged**
