### PR TITLE
Memory leak fix : RoundEndScoreBuilder

### PR DESCRIPTION
**Pull request by havietisov**
### Purpose
Pretty straightforward : allows RoundEndScoreBuilder to remove itself from places necessary in order to not cause any memory oppsie-doopsie

### Changelog:

### CODE REVIEW

**Comment by corp-0** [comment]
during the countdown of the next round, the score should still be visible. Does this work like that?

**Comment by havietisov** [comment]
@corp-0 Theoretically, yes, it should still be visible. However, it's probably nice to check.

**Comment by corp-0** [comment]
well, did you at least test it in play mode in editor? It should be easy to start a round, finish it and see what happens with the score window

**Comment by havietisov** [comment]
@corp-0 well, I decided to double-check and after round restart, I still see score.

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
