### PR TITLE
Wooden Cleanbot Sprites

### PR DESCRIPTION
**Pull request by BootlegBow**
Adds wooden cleanbot sprites, and separates the wooden cleanbot sprites and blue cleanbot sprites within the cleanbot folder.

The sprites are not functional yet, this just adds the .png files needed.

### CODE REVIEW

**Comment by Bod9001** [comment]
do you have access to the unity editor? 
 Since we need the .asset files for referencing them
is ok, if you don't we just make an issue for it

**Comment by BootlegBow** [comment]
I do, I didn't make the .asset files because I'm not entirely sure how to be honest

**Comment by Bod9001** [comment]
image
then the object it makes make sure to name it the exact same thing as your sprite png (might took a second or two to go through)
then make the variance list one
then make the frame list one
then drag in your Sprite then press
Control + s
to seve
And that should be done

**Comment by BootlegBow** [comment]
I’ve tried 3 times, all of which resulted in Unity crashing. Someone else will need to do it

**Pull request merged**
