### PR TITLE
Fixes randomised hunger

### PR DESCRIPTION
**Pull request by Bod9001**
technically work before but  is to fix it for non  1 values

### CODE REVIEW

**Comment by corp-0** [comment]
Wait, why is hunger random now? What does it solve?

**Comment by MaxIsJoe** [comment]
To be truly random, you should apply randomness to each body part.
Also, I still don't like that it's random in the first place.

**Comment by NoooneyDude** [comment]
> Wait, why is hunger random now? What does it solve?

Perhaps it solves the issue of all the roundstart crew bumrushing the vending machines at the same time. Initial hunger on spawn should be random, at least.

**Review by NoooneyDude — APPROVED** [review]

**Comment by Bod9001** [comment]
It's only the starting amount of hunger

**Pull request merged**
