### PR TITLE
Eating food via Activate keybinding added.

### LINKED ISSUE #1638: Pressing Z no longer makes you consume food in your active hand
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pick up meat steak
2. Press Z

### PR DESCRIPTION
**Pull request by NextThang**
### Purpose
Fixes #1638

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
Adds FoodTrigger which provides UI_Interact for any food items, it essentially only calls TryEat on it now.

### CODE REVIEW

**Comment by chairbender** [comment]
@ThangCZ works fine on the server, but nothing happens when trying to eat as a client.

**Review by chairbender — CHANGES_REQUESTED** [review]
@ThangCZ works fine on the server, but nothing happens when trying to eat as a client.

**Comment by NextThang** [comment]
@chairbender Yeah, my bad. The networking got me confused. Should be fixed now.

**Review by fomalsd — APPROVED** [review]
Sweet!

**Comment by fomalsd** [comment]
Why did you change meat steak prefab though?

**Comment by NextThang** [comment]
Because I gave it the newly created food trigger.

**Comment by NextThang** [comment]
@chairbender Ok, I remade all the food/drink prefabs (except raw meat) to use the FoodTrigger so now they should be consumped upon interaction

**Comment by chairbender** [comment]
Works great, thanks!

**Review by chairbender — APPROVED** [review]

**Pull request merged**
