### PR TITLE
Adds Rainworld Slug cat plushes.

### PR DESCRIPTION
**Pull request by AtnerNT**
Detailed plushie variant contributed by LastCaptainBonk
Downpour slug cats contributed by Error: Spiders expected, got nil

Capture

### Changelog:
CL: [New] Added "Odd slug plush", resembling the slug cat from rainworld, comes in 10 different variants.

### CODE REVIEW

**Comment by Bod9001** [comment]
did you remember to update the advanced section on Texture?

**Comment by corp-0** [comment]
I think the first one is way too big for a plushie

**Comment by MaxIsJoe** [comment]
it is a big plushie

**Comment by LastCaptainBonk** [comment]
Like one of those giant Teddy Bears. Only a slug cat.

**Comment by AtnerNT** [comment]
> did you remember to update the advanced section on Texture?

yeah nah all texture settings are set correctly

**Comment by AtnerNT** [comment]
Slugcat merge when?

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
