### PR TITLE
Adds sprites for mixed drinks

### PR DESCRIPTION
**Pull request by AutumnNova**
Adds the SOs for drinks that need to be mixed (e.g White russian. Screwdriver, etc)
Adds some drink sprites

### CODE REVIEW

**Comment by Bod9001** [comment]
Got the correct input settings?

**Comment by corp-0** [comment]
Test ran for 5 hours, more than likely it failed not for the PR but because Actions. 
image

**Comment by Bod9001** [comment]
*In Port

**Comment by AutumnNova** [comment]
yeah the import settings are correct

**Pull request merged**
