### PR TITLE
Cloning pod behaviour and player cloning acceptance

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Adds an objectBehaviour component to the cloning pod and DNA scanner.
Adds a button to ghost UI to toggle the acceptance of being cloned.
Cloning will now check if the player is dead, online and if they accept the cloning.
Adds a reference to the cloning pod for the cloning console.
Adds the CloningPod class, it'll be used to determined the spawn location of the cloned mobs and it changes its sprite depending on the status of the cloning process.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by Aranclanos** [comment]
Also fixes DNA scanners from being unable to be opened by the player inside of them

**Comment by Aranclanos** [comment]
for the acceptance/allowance of cloning I went a bit creative and stepped aside from the original, before polishing it I'd like some feedback

**Comment by fomalsd** [comment]
what exactly is different from original?

**Comment by Aranclanos** [comment]
Originally, you need to be inside your body to be able to be SCANNED, otherwise it'll fail. If you were scanned previously and ghost, you'll be cloned.
On this case, it's a toggle button on the ghost's UI, if it's off it'll reject any cloning and if its on it'll allow the player to be cloned. As for scanning, its always allowed.

**Comment by fomalsd** [comment]
Currently locking and scanning doesn't seem to work at all, player inside scanner can walk out at any time
Therefore I was unable to check if pressing "allow cloning" actually does anything (also there's no way of knowing its current state)
And when re-entering preciously dead body it was no longer dead but appeared like in crit with no body part damage:
wtf

Had a few exceptions on client side:
```
NullReferenceException: Object reference not set to an instance of an object
PlayerHealthUI.SetBodyTypeOverlay (BodyPartBehaviour bodyPart) (at Assets/Scripts/UI/PlayerHealthUI.cs:193)
BodyPartBehaviour.UpdateIcons () (at Assets/Scripts/Health/BodyParts/BodyPartBehaviour.cs:89)
BodyPartBehaviour.Start () (at Assets/Scripts/Health/BodyParts/BodyPartBehaviour.cs:27)
```
```
NullReferenceException: Object reference not set to an instance of an object
ClosetHandlerMessage+<Process>d__3.MoveNext () (at Assets/Scripts/Messages/Server/ClosetHandlerMessage.cs:23)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

**Comment by Aranclanos** [comment]
The right side icons is a separate bug on develop that I have to fix, also the cloning console isnt linked in the map.
Not sure about the runtimes though
also the cloning is still disabled in Mind.cs line 22, you would have to remove the comment lines. Should have mentioned it in the notes my bad

**Comment by Aranclanos** [comment]
I fixed the right side icons on different PRs and enabled cloning. You still have to make the references in the cloning console of the DNA scanner and cloning pod in the map.
I noticed a runtime when clicking on pulling, the client seems to still keep some control over the old body, but its an error on develop right now due to the respawn button, won't fix it in this PR.

**Pull request merged**
