### PR TITLE
Adds test for missing component in asset references.

### PR DESCRIPTION
**Pull request by Ruzihm**
Also, changes asset finder to only care if it starts with "Assets/" and ends with ".asset"

### Purpose
Addresses (Maybe fixes) #2851

### Notes
There are some missing components in unitystation/unitystation@6a71c84e996767df99d8656912d9e5f8208591cb that this test (correctly) fails on. I don't know how best to fix them~

### CODE REVIEW

**Comment by Bod9001** [comment]
Could try manually removing them if they don't look crucial?

**Comment by chairbender** [comment]
That's awesome. I wouldn't have expected in a million years someone would add more unit tests. I'll take a look at what's missing and see if it's okay to remove.

**Comment by chairbender** [comment]
This is great, I didn't even realize we had the ability to run normal unit tests outside of Unity's really slow test runners now.

Yes, removing them is fine

**Comment by Ruzihm** [comment]
@chairbender sadly it's still in unity's slow unit testing ;)

**Comment by chairbender** [comment]
ah, I was able to just tell rider to run all tests in solution and it seemed pretty fast, at least it's less cumbersome now, last time I was messing with unit tests was over a year ago and it was annoying to do, had to do it through editor

good to merge now though!

**Comment by Ruzihm** [comment]
Testing a fix for this working improperly. Will submit as a new PR

**Pull request merged**
