### PR TITLE
fix Languages

### LINKED ISSUE #9409: [BUG] Player names do not show in chat local or comms chat.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22112816

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

The player names do not appear in local or comms chat, it instead just says, "   says, "example"".

### What should have happened instead?

The chat menus should say, "PlayerName says, "example"".

### Steps to reproduce the issue

Press T and type in anything then look at the left chat box.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:

CL: [Fix] fixed character names not appearing in chat

### CODE REVIEW

**Comment by corp-0** [comment]
what did it fix about languages? Also use past tense

**Comment by Bod9001** [comment]
languages wouldn't work on client

**Comment by corp-0** [comment]
how did the players experience that issue?

**Comment by Bod9001** [comment]
https://discord.com/channels/273774715741667329/1047254202843414628/1047254202843414628

**Comment by corp-0** [comment]
I edited your changelog.

**Review by corp-0 — APPROVED** [review]

**Comment by eurtod** [comment]
Still experiencing this issue.

**Comment by corp-0** [comment]
This wasn't merged before latest build. You will have to wait until the next one is done.

**Comment by eurtod** [comment]
Okay, my apologies.

**Pull request merged**
