### PR TITLE
Security records wont be created if the player is a syndie or an AI

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Security records wont be created if the player is a syndie or an AI

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by Bod9001** [comment]
I think it would be pretty amusing to set the AI to arrest?

**Comment by Aranclanos** [comment]
dont merge id rather solve conflcits on this one than my other PR

**Comment by DooblyNoobly** [comment]
Looks like they've been solved?

**Comment by Aranclanos** [comment]
all good

**Pull request merged**
