### PR TITLE
oh yeah,  electrical on its own thread with Tile cables

### PR DESCRIPTION
**Pull request by Bod9001**
Still could use a bit of optimising and cleaning  and adding extra features but, Update was waiting on me so I decided to skip those for now

I tested in multiplayer before rebasing, but can't test on the newest version since there is a bug that everyone else is experiencing with being able to connect

### CODE REVIEW

**Comment by Bod9001** [comment]
odd am Able to build it fine

**Comment by DooblyNoobly** [comment]
why does jesus hate me? These tests are driving me mad

**Comment by AutumnNova** [comment]
> A meta data file (.meta) exists but its asset 'Assets/Mirror/Examples/Pong' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
>  
> (Filename: ./Modules/AssetDatabase/Editor/V1/RefreshAssets.cpp Line: 83)
> 
> A meta data file (.meta) exists but its asset 'Assets/Mirror/Examples/AdditiveScenes' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
>  
> (Filename: ./Modules/AssetDatabase/Editor/V1/RefreshAssets.cpp Line: 83)
> 
> A meta data file (.meta) exists but its asset 'Assets/Mirror/Examples/Discovery' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
>  
> (Filename: ./Modules/AssetDatabase/Editor/V1/RefreshAssets.cpp Line: 83)
> 
> A meta data file (.meta) exists but its asset 'Assets/Mirror/Examples/Chat' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
>  
> (Filename: ./Modules/AssetDatabase/Editor/V1/RefreshAssets.cpp Line: 83)
> 
> A meta data file (.meta) exists but its asset 'Assets/Mirror/Examples/Basic' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

seems to mostly be leftover metas causing issues?

**Comment by DooblyNoobly** [comment]
nvm I found the problem. Missing references on subsystem prefab. I'll fix it up when I figure out wtf is going on with staging errors

**Comment by Bod9001** [comment]
ok cool

**Review by RedlineTriad — CHANGES_REQUESTED** [review]
This adds naughtyattributes plugin, it does so by copying them to scripts. 
It should instead by copied to Plugins, or better yet use the UPM package: 
https://openupm.com/packages/com.dbrizov.naughtyattributes/

**Comment by Bod9001** [comment]
Done

**Review by RedlineTriad — APPROVED** [review]

**Comment by DooblyNoobly** [comment]
I need to merge this to a separate branch to work on it

**Pull request merged**
