### PR TITLE
No more client prediction on guns

### PR DESCRIPTION
**Pull request by Bod9001**
why?
Because of the problem of ping, you could have the client shoot and predict the shot but there's no way to guarantee the shot will be same and server, without making expensive state engine, that stores every single state for the last 2 seconds, then using that to reference when the client shot, 
so, with the current implementation The client could shoot at someone and hit them on their screen but not actually hit them, 
I believe this is a big frustration for players,

so, This changes it so that the server processes all the Relations of hitting and moving, 
the downside to this is that the clients shots will be delayed and will be from a different position that the client shot from
 due to the movement prediction, however the shots will be exactly as it is on server And will hit the exact same targets as on server, making the experience more reliable

### CODE REVIEW

**Comment by Bod9001** [comment]
oops accidentally included revert

**Comment by Bod9001** [comment]
It's okay I reverted the revert

**Review by Daxam12 — DISMISSED** [review]

**Comment by ThatDan123** [comment]
Can you check that bullet pooling still works and if the bullets are appearing at the correct place before they become visable.

**Comment by Bod9001** [comment]
I can confirm bullets are pooled on Server at least

**Comment by Bod9001** [comment]
can't fix the momentary appear on clients without reconfiguring client spawn code

**Comment by Aranclanos** [comment]
do players want this?

**Comment by Bod9001** [comment]
well, let's have a poll

**Comment by PerfectTangent** [comment]
I don't think the vast majority of players could accurately weigh the pros and cons of this PR, especially since both ways have negative consequences. This is more up to us to decide whether we think it's best for the game or not.

**Comment by PerfectTangent** [comment]
We may be able to set up a demonstration by simulating an acceptably high amount of ping and have one character strafe and fire at another character and record the results. If it feels gross at a level of ping players will often deal with, then we may not want to do this, but if it feels alright, then we continue with it.

**Comment by Bod9001** [comment]
true

**Comment by corp-0** [comment]
so what's the current state of this pr?

**Comment by Bod9001** [comment]
idk Needs a debate on it

**Comment by corp-0** [comment]
seems like this isn't compiling

**Comment by Bod9001** [comment]
fixed

**Review by NoooneyDude — DISMISSED** [review]

**Comment by NoooneyDude** [comment]
ah, tests

**Comment by NoooneyDude** [comment]
tests are still in pain

**Comment by Bod9001** [comment]
ok

**Comment by corp-0** [comment]
I want to merge this for next playtest, can you take a look at codacy's suggestions?

**Comment by Bod9001** [comment]
image
image
Codacy  being dumb again

**Comment by Bod9001** [comment]
yeah, All the code that Codacy  is talking about has been removed

**Comment by corp-0** [comment]
Let me rerun in it in that case

**Comment by corp-0** [comment]
Suggestions changed

**Comment by Bod9001** [comment]
image
The last one is this since its direct Assigning should be fine

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
