### PR TITLE
flipped health doll damage

### LINKED ISSUE #2966: The health doll on the right hand side of the screen is mirrored to the health doll that the player can select to heal.
Reproduce:
- Get shot in left leg.
- Select left leg.
- Try to heal left leg.
- "Your left leg is not injured."
- Do the same for the opposite leg, heals up just fine and dandy.

Haven't been able to test this with arms yet, will comment here if I can find anything.

### PR DESCRIPTION
**Pull request by myrmecoleonn**
fixes #2966 ; both the Player_v3 and PlayerHealth_UI_Hud prefabs had their right and left arms/legs swapped. this has hopefully been rectified

### CODE REVIEW

**Comment by daalta** [comment]
Hi @myrmecoleonn ! Thanks for taking a look at this, I would never have noticed, haha.

I think it's a bit weird that a body part such as `HumanBodyPartLeftLeg` now has the type `RightLeg`.

(EDIT: Image redacted - it was outdated!)

The solution https://github.com/unitystation/unitystation/pull/2987 currently also has a problem, but I think it avoids mislabeling the limbs. What a coincidence that both you @FijiWatr attempted to fix the same problem! 😅

**Comment by myrmecoleonn** [comment]
woah, what? that was the exact thing I was trying to fix in the first place - where did you get that `HumanBodyPartLeftLeg` from? I couldn't find a prefab of the any of the humanbodyparts with sprites(or a script) assigned!

**Comment by daalta** [comment]
Ooooh that makes absolute sense! I guess my player was outdated, so you fixed the right thing. Give me a moment and I'll merge it :)

**Comment by daalta** [comment]
Perfect, now it's all as it should be! Nice job 👍

**Pull request merged**
