### PR TITLE
DisplaySettings refactor, fullscreen fixes

### LINKED ISSUE #2575: Fullscreen resolution uses windowed resolution
## Description

When switching from windowed to fullscreen (using ALT + ENTER) the windowed resolution will be used (instead of using the highest possible screen resolution).

Windowed:
unitystation_2020-01-10_21-48-38

Fullscreen:

Take note of the Radeon Software prompt, which is overlayed in perfect resolution.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Start the game in windowed mode. 
2.  (Optional) Resize the window to a small size. This will make the issue more obvious.
3.  Enter fullscreen by holding the ALT + ENTER keys.
4.  The screen resolution will be too low and blurry.

### LINKED ISSUE #4323: Multi monitor mullscreen always uses main monitor resolution
## Description

`/Assets/Scripts/UI/OptionsMenu/DisplayOptions.cs` uses `Display.Main` to fetch the screen resolution for fullscreen, even if the application is running on another monitor.

### Steps to Reproduce

1.  Open Unitystation on a non-primary monitor which has a higher (lower?) resolution than the main screen
2.  Go into windowed mode, then enter fullscreen via the display menu option (NOT Alt + Enter, see https://github.com/unitystation/unitystation/issues/2575)
3.  Fullscreen resolution is that of the primary monitor

### PR DESCRIPTION
**Pull request by CodeKalias**
### Purpose
Separated Display Settings code from the menu UI, fix fullscreen and resolution bugs

### Notes
Disables default Alt-Enter behavior and do it manually 
Fixes incorrect resolution when using alt-enter - resolves #2575
Fixes incorrect resolution when fullscreen on a secondary monitor - resolves #4323

Alt-Enter isn't available in the StartUp scene as the managers are not yet loaded at that time, Lobby onwards will work.

- [x] Tested in build
- [x] Tested headless server and client still work

### CODE REVIEW

**Comment by Bod9001** [comment]
hey do you know why it goes out of maximised window when I press it after a little bit, I think it's maybe trying to get to a good resolution? otherwise seems all good , I can't seem to get to 1:1 on my 2560x1440 monitor, only allows me to go to 2:1

**Comment by CodeKalias** [comment]
There's something happening elsewhere which fights the maximized window function (issue exists prior to this, in dev build 2210), but shouldn't affect the true fullscreen this PR is for.
I'll probably look into maximized window stuff some other time though.

There are some limits on the camera zoom in and out which I didn't change from their existing values, if that's what you're referring to with 2:1 and 1:1

**Comment by Bod9001** [comment]
ok Sounds good, everything looks okay to me, you still got some stuff to change?

**Comment by CodeKalias** [comment]
Yeah, putting together one more commit to clean a couple of things up

**Comment by CodeKalias** [comment]
Ready to go again

**Comment by Bod9001** [comment]
play tested it, it works well, all good from me

**Review by fomalsd — APPROVED** [review]
thanks, works great!

**Pull request merged**
