### PR TITLE
Makes OutpostStation02 Main

### LINKED ISSUE #2916: Two Tiles in Research Are Impassable
# Issue Template

## Description
https://i.imgur.com/pQH3Jcl.png The two tiles I am pointing at are impassable. Not sure why? The game doesn't show anything in these tiles. 
### Detailed Bug Report
I cannot push things into that area nor see anything special there when I examine what's on the tile with alt-click. 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Spawn in as a scientist/go to science
2.  Try and enter those tiles
3.  Cry.

### LINKED ISSUE #3077: Spawning is limited to Departmental Spawns
## Description

Currently, all players will spawn in their department on the same tile location, what is supposed to happen is you are to spawn in more than one preset or randomized spawn locations. Preset ones, for example, are HoS spawning in his office, captain in his, an HoP in his office. 

Other jobs will simply spawn randomly in their department.

### Steps to Reproduce

1. Choose a role at roundstart  
2.  Notice the human centipede as people from same department spawn on top of you
3.  Cry

### LINKED ISSUE #3122: Nuke is too easy to access.
## Description
Nuke is way too easy to get to.
### Detailed Bug Report

Screen Shot 2020-02-15 at 3 20 03 AM
Getting nuke is trivial if you know what you're doing. Nukies have tools and can easily just deconstruct one wall, and blow nuke.
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Be nukie
2.  Go to point where there's only one wall between you and nuke.
3.  Deconstruct wall and you're in.

### PR DESCRIPTION
**Pull request by Ranzarth**
### Purpose

- Moves Old OutpostStation to OBSOLETE and replaces it with the 02 version
- Changes Spawn point Script to allow more individualized spawns
- Adds Detectives Office
- Adds new Cargonia
- Adds Vault
- Adds Science Department
- Adds Lawyers Office
- Medbay Fixes
- Other General Fixes
- Adds EVA

Fixes #3122 
Mostly Fixes #3077 
Fixes #2916

### CODE REVIEW

**Comment by Ranzarth** [comment]
DNM until completed EVA

**Comment by Ranzarth** [comment]
Ready to Merge

**Comment by fomalsd** [comment]
I'm against deleting original OutpostStation, could you just rename it to OutpostStationOG?

**Comment by Ranzarth** [comment]
I will just put the old map in the obsolete folder then instead

**Comment by Ranzarth** [comment]
All Done

**Comment by fomalsd** [comment]
just tried it – and wow it's quite a different map, that's bigger as well. how about just including it in map rotation together with the old one?

**Comment by fomalsd** [comment]
looks like this by the way:
 img

**Comment by Ranzarth** [comment]
The original OutpostStation is lacking many features, its still really built for testing only, that is why I was happy with just removing it anyway. New maps from other mappers are coming as well so it won't be the only one.

**Comment by RedlineTriad** [comment]
Do you want the map where you get plasma flooded or the other one? Well, they are both in rotation so good luck.

**Comment by AutumnNova** [comment]
not the one with plasmafloods
pleasethankyou

**Comment by ghost** [comment]
2020-02-18-094049_290x185_scrot
if the detective spawns on that chair he won't be able to leave since there's no way to move that locker... And why is there just one cloning pod like usual? It gets knocked out so quickly and so often... 2020-02-18-094632_233x176_scrot
This corner window is rather awkward.... Several other small issues but holy hell who cares this is beautiful, service department looks really well made, man nice job

**Pull request merged**
