### PR TITLE
Solar Panels

### PR DESCRIPTION
**Pull request by MaxIsJoe**
image
image
image

### Changelog:

CL: [New] Added functionality to Solar Panels and Solar Panel Controllers.
CL: [New] Added the ability to craft Solar Panels with 25 glass sheets, and you can print Solar Controller Boards from Circuit Printers for 1kG, 500M.
CL: [New] The Solar Panel setup on Ministation is now functional and hooked up to one of the station's batteries.
CL: [New] Circuits now display their required components for building machines. You no longer have to commit to building a machine frame to find out the requirements later.
CL: [Improvement] Machine frames print out their building steps in hover tooltips now.

### CODE REVIEW

**Comment by Bod9001** [comment]
solar panel controller needs to be parented properly

**Comment by Bod9001** [comment]
you forgot to make it so it can connect to standard cable, you forgot to set it up so medium voltage cable ( standard cable ) can connect to the solar panel controller

**Comment by Bod9001** [comment]
(77, 17, 0) < duplicate Please remove StandardCable on the thread Unknown

**Comment by Bod9001** [comment]
the cable doesn't overlap with the machine when it set to overllap

**Comment by Bod9001** [comment]
the resistance reaction is set to low voltage to cable when it should be medium voltage cable (seems to work fine if it's  the wrong cable)

**Comment by Bod9001** [comment]
you just need to drop the internal resistance of the Supply, and it should work now

**Comment by Bod9001** [comment]
have you tested what happens when you have multiple supplies / running multiple solar panel controllers?
since there's nothing to limit the voltage output

**Comment by MaxIsJoe** [comment]
> have you tested what happens when you have multiple supplies / running multiple solar panel controllers? since there's nothing to limit the voltage output

Solar Panels can only be connected to one controller at a time. If you move the panel or use a multi-tool on it while it's already connected to one; the controller will remove it.

**Comment by Bod9001** [comment]
I mean as in multiple solar panel controllers + output from SMES/plasma generator

**Pull request merged**
