### PR TITLE
Update BoxStation

### PR DESCRIPTION
**Pull request by NoooneyDude**
BoxStation updates.

- Activates the distribution and waste line pumps in atmospherics and increases the reservoir canister tiers so atmospherics is functional by default. Waste line filtering remains inactive, however.
- Fixes the wiring to the reactor room department battery.
- Adds Sergeant Araneus, Paperwork and the janitor's lizard.
- Updates some old BVOlds to the new variants.

CL:Updates BoxStation. Fixes atmospherics, wiring in engineering and adds a few mobs

### CODE REVIEW

**Comment by ThatDan123** [comment]
Assets/Scenes/MainStations/BoxStationV1.unity: SecurityBeltFull (5) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 

Might be the issue

**Comment by Bod9001** [comment]
man, I'm so glad I made this test

**Comment by corp-0** [comment]
why is it bad when things are at 0,0 ?

**Comment by ThatDan123** [comment]
Sometimes objects are moved to 0,0 when mapping. Could happen if the prefab was changed, not the most reproduceable thing.

**Comment by NoooneyDude** [comment]
In this case I had pasted the old variant's position into the new prefab's rotation ; )

**Comment by Bod9001** [comment]
ok looks good

**Pull request merged**
