### PR TITLE
Fixed some compilation warnings

### PR DESCRIPTION
**Pull request by daalta**
More progress on https://github.com/unitystation/unitystation/issues/2526 .

* Fixed some of the usual default value warnings
* Camera recoil was accidently using a local variable, which I fixed. Could someone please test if the camera recoil feels different? (Because it... should? Maybe?)
* Some obsolete functions were replaced - Behaviour *should* be identical in those cases.

I did a quick editor test, and things seem to be in order. Still, the prospect of having broken something is *terrifying*.

### CODE REVIEW

**Comment by corp-0** [comment]
from what I saw in the changes, everything needs a default value when declared? Could we make a test for it so peopel don't forget it?

**Comment by daalta** [comment]
@corp-0 I'm still not sure what the best way to handle that warning is.

Unity, by default, expects variables to get assigned somewhere. It doesn't know if that happens through the inspector, so it warns us. Just in case.

Most IDEs, however, see assigning variables to their default value as redundant. Rider suggests *removing* default values.

Seems like we can't really win..?

**Comment by daalta** [comment]
@corp-0 I'm still not sure what the best way to handle that warning is.

Unity, by default, expects variables to get assigned somewhere. It doesn't know if that happens through the inspector, so it warns us. Just in case.

Most IDEs, on the other hand, think that assigning variables to their default value is redundant. Rider suggests *removing* default values.

Seems like we can't really win..?

**Comment by Bod9001** [comment]
looks good, and the only way to find out is to test it : P

**Comment by daalta** [comment]
https://github.com/unitystation/unitystation/issues/3362

**Pull request merged**
