### PR TITLE
Fixes client spawning in space

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:

CL: [Fix] Fixed client spawning in space when spawning as nuclear operative or Wizard

### CODE REVIEW

**Comment by Bod9001** [comment]
TODO record which client did it so client can't spam multiple messages causing it to load too fast on clients

**Comment by corp-0** [comment]
seems like it doesn't compile

**Comment by Bod9001** [comment]
TODO is done, wasn't getting Compile errors on my end, will run tests

**Comment by Bod9001** [comment]
all good

**Pull request merged**
