### PR TITLE
Re-added references to glass sheet in CargoData.asset

### PR DESCRIPTION
**Pull request by CodeKalias**
### Purpose
Ordering Glass Sheets in cargo delivers an empty box due to null entries in CargoData.asset, re-added them.

### Notes:
glass sheet.prefab fileID was changed from 6201122676745363040 to 5680136605834777345 in commit 3cad75bb14bce5db5900c293e8b5c5c1e1e80a79 , causing the loss of references

References in .prefab and .asset files may also have been lost elsewhere, specifically for glass sheet, but possibly also any of the other items changed by 3cad75bb14bce5db5900c293e8b5c5c1e1e80a79

### CODE REVIEW

**Comment by corp-0** [comment]
this was already done in #3137
I know because I wanted to make it first and get my orange name :c

**Comment by CodeKalias** [comment]
> this was already done in #3137
> I know because I wanted to make it first and get my orange name :c

Yes, it has since broken again as mentioned in the notes

**Comment by hecksadecimal** [comment]
How in the world did this get broken again?

**Comment by corp-0** [comment]
someone must have pushed broken metas

**Comment by CodeKalias** [comment]
> How in the world did this get broken again?

3cad75bb14bce5db5900c293e8b5c5c1e1e80a79 's change to the glass sheet fileID was pulled at the same time as your fix, so it was broken pretty much instantly.

#3139 has also been broken by that, with the Ore Redemption Machine prefab also losing its reference to glass sheet

Broken via changes to .prefab files, not .meta

**Comment by hecksadecimal** [comment]
Yikes. Good to know it's not my fault, I was definitely the last person to touch CargoData.asset.

**Pull request merged**
