### PR TITLE
Render palettable sprites in right-click menu properly

### PR DESCRIPTION
**Pull request by Ruzihm**
###Purpose 
Fixes palettable sprites not being rendered properly in right click menus
Fixes red/green UI ghosts of items based on UI slot compatibility rendering incorrectly

###Notes
Also, adds right-click context option to ItemAttributesV2 that applies changes to palette to related sprites and icons.

progress towards #2110

### CODE REVIEW

**Comment by fomalsd** [comment]
Please keep in mind that your previous shader change affected inventory slot hint overlay appearance. 
Ones that were transparent-green ("can put it here") are now invisible, and ones that were transparent-red ("can't put it here") are now opaque-red. (#2201)
Can you do something about it?

**Comment by Ruzihm** [comment]
@fomalsd  thank you very much for the feedback. I can do something about it. I have fixed that issue with a3f364e

**Comment by Bod9001** [comment]
I got sprite Handler changes as well in the Action system ,  sprite Handler Can work with UI images

**Comment by DooblyNoobly** [comment]
testing on staging

**Pull request merged**
