### PR TITLE
Staging fixers

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [New] Artificial brains sprites change depending on if it's empty or claimed
CL: [Fix] Fixed buggy movement
CL: [Fix] Fixed door buttons working without power
CL: [Fix] Fixed exosuit fabricator not showing in research unlockables
CL: [Fix] Fixed microwaves being invisible

### CODE REVIEW

**Comment by corp-0** [comment]
hopefully fixed exosuit fabricator doing what?

**Comment by Bod9001** [comment]
idk, wasn't adding research?

**Comment by corp-0** [comment]
you don't know what you fixed?

**Comment by Bod9001** [comment]
well I just cleaned it up and hoped it fixed the parts not showing when you research them

**Comment by corp-0** [comment]
couldn't test if it worked? HDP, hope driven programming, isn't that popular of a methodology. Not entirely familiarised on how it works.

**Comment by Bod9001** [comment]
it seemed to work so, hopefully fixes the issue that was causing to not work

**Comment by corp-0** [comment]
Okay. I'm only asking not for being pedantic but because it wasn't clear what got fixed in your changelog entry.

**Comment by Bod9001** [comment]
yeah, Not too familiar with it I just fixed errors I saw

**Pull request merged**
