### PR TITLE
Removed tiles equalize their pressure

### LINKED ISSUE #2890: Mined rocks create wind
## Description
When you go to an asteroid and mine a rock, it creates wind and moves stuff around and disrupts you.

When you mine a rock it shouldn't create any wind.

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #2890 and the more general case of any removed tile ensuring it doesn't cause sudden wind.

Any time an atmos-impassable tile is removed, the gasmix on that tile is changed to be the average of its atmos-passable neighbors.

I haven't touched atmos too much and I have a bit of a sleep debt so I want someone else to take a look at this to make sure it seems alright.

### CODE REVIEW

**Comment by chairbender** [comment]
In particular, make sure shuttle crashing is not breaking atmos. I wasn't involved in that fix so I'm not sure how to spot the symptoms of a problem with Matrix Check.

**Comment by Bod9001** [comment]
just saying that this isn't thread safe, but stuff like fire isn't thread safe as well so don't worry about it, and technically since the atmospheric thread is limited, it should do all the calculation before the main thread gets to this spot

**Comment by chairbender** [comment]
Ah good point. I can make it thread safe.

**Comment by Bod9001** [comment]
Doesn't matter too much of it is not thread safe

**Comment by Bod9001** [comment]
humm  best thing to do make it not explode if it does become entangled in atmospheric thread and game thread

**Comment by chesse20** [comment]
make it thread safe fire already makes horrible lag its not a good example

**Comment by krille90** [comment]
wouldn't this be adding atmos gases to the system out of nothing?

**Comment by chairbender** [comment]
so i'm gonna close this. After having more of a look through atmos I see problems with how we are using it in a non-thread-safe manner so I'd rather fix those first

**Pull request closed without merging**
