### PR TITLE
Fixed channel keybinds and tweaked channel selection

### LINKED ISSUE #1510: Add ability to open radio chat and department chat with keybindings
# Description
When attempting to local chat, no text is displayed. Radio and department chat buttons do not even bring up the text entry box.

## Category
TODO
## Detailed Bug Report
**Build**: [d5b5627](https://github.com/unitystation/unitystation/commit/d5b56271e1390db3337adb9171770526b01901d5)
**Unity Version**: 2018.3.4f1Personal
OS: Windows 10 Pro x64

This one seems pretty critical. Unsure at this point if it effects connecting to a server that isn't localhost, but even if it only does effect localhost client-servers it is a glaring issue.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Run unitystation
2. Join round
3. Attempt to talk using any of the bound chat keys

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
Fixes #1510 
Also stops you from selecting None as a channel, keeping Local on by default.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### CODE REVIEW

**Comment by Jibbajabbafic** [comment]
Going to make some more improvements before merging

**Comment by krille90** [comment]
Any update?

**Comment by Jibbajabbafic** [comment]
I've not had much time to work on it recently, I can PR what I've got so far tomorrow though

**Comment by Jibbajabbafic** [comment]
Made some more progress, will make a new PR once it's ready

**Pull request closed without merging**
