### PR TITLE
Should finish #3124

### LINKED ISSUE #3124: Server feature. Motd to every single client and other info.
We need a possibility for headless (dedicated) server to send many kinds of info about server, rules, community, changelogs, discord, patreon and so on to the;
 

- [ ] Chat, splitted to public type ones and private ones for every client.

- [ ] Info tab (in the up right corner of the ui there controls and stats are placed). For example for rules page or so, it may be done in some kind of Book or so, cause rules may include pics and etc.

- [ ] Links to sites and such, with rules, wiki, discord channel and such.

- [ ] Info for every single client at connect to server loading, in lobby or/and at job selection.

Of course it needs to be configurable and hooked to external txt, html files or something like that.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Honestly, I'm a bit confused by some tasks in it, but almost everything can be done now in the MOTD and there is now a rules tab + It took me an entire year to realize this, but people couldn't see what timed events were going on when they joined the server because this only showed on the disclaimer prefab which is entirely different from the server info prefab. 

If you want to add links just add them in the server MOTD, not that hard really.
Server rules support BB Code, so we can utilize TMPro to lay out our rules.

closes #3124 (hopefully)

## Changelog:
CL: [New] - Added the ability for servers to display their own rules.
CL: [Fix] - Timed events will properly show up in the correct place this time.

### CODE REVIEW

**Comment by corp-0** [comment]
> The script for a component on Managers could not be loaded.
The script for a component on Disclaimer could not be loaded.
The script for a component on UIManager could not be loaded.

  Expected: False
  But was:  Trueat Tests.TestReport.AssertPassed () [0x00001] in /github/workspace/UnityProject/Assets/Tests/TestReport.cs:126
at Tests.Asset.MissingAssetReferences.CheckMissingComponentOnPrefabs () [0x00084] in /github/workspace/UnityProject/Assets/Tests/Asset/MissingAssetReferences.cs:33ScriptableObjects.Atmospherics.GasesSingleton SO took 56 ms to find! Try to serialize a reference to this SO singleton instead!

**Comment by MaxIsJoe** [comment]
how
i understand disclaimer going missing but what

**Review by Bod9001 — DISMISSED** [review]

**Comment by Bod9001** [comment]
Fix tests

**Comment by MaxIsJoe** [comment]
This should fix it

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
