### PR TITLE
Electrical construction and deconstruction VIR V0.96

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
Allow Electrical machines and cables to be constructed and deconstructed 
You can deconstruct electrical machines with a screwdriver
You can deconstruct  Cables with a Wire Cutter
You can now place cables with Cable coils
You can construct machines through the dev Menu

Also reduced the size of tools to fit in pockets
and Updated the cabling on Outpost station

Fixes Syndicate shuttle not having light  #1390 and #1276

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
We have conflicts due to another PR being merged. I'll try to sort it out on a new branch. Bod can you let me know what was changed on Crowbar and Screwdriver prefab?

**Comment by DooblyNoobly** [comment]
nvm @Bod9001 that was super easy to resolve. Will review PR soon

**Comment by DooblyNoobly** [comment]
Doesn't look like this solves #1276

Maybe you put that issue # in by accident?

**Comment by DooblyNoobly** [comment]
Looking good, laying cable is a bit tricky at the moment and I think we could improve the UX there but everything works as stated in your summary. Now we need to spawn cable coils when you use the cutters on them and also stop the department batteries from disappearing when you use the screw driver on them.

I'd suggest making the department battery unanchor from the floor by using the wrench instead so that it can be dragged around. See the Generator code for that. It is also good to have the syndie shuttle lights back!

Merging this now but I suggest working on the spawning of the cable coils and changing the machines from deconstructing to being anchored / unanchored using wrench instead.

**Comment by Bod9001** [comment]
I'm going to wait for stacking code before doing the  Returning cable when you cut it (Probably will make it myself)
And going to wait for deconstruct code as well for the machines  (Probably will make it myself)

**Comment by Bod9001** [comment]
#1751 that is the Proper issue

**Pull request merged**
