### PR TITLE
Spawn reference fix for canisters.

### LINKED ISSUE #5008: Canisters can be blown up multiple times
Canisters can be blown up multiple times, releasing new gas everytime.

### PR DESCRIPTION
**Pull request by ReiderJack**
fixes #5008
<details>
<summary>Error</summary>

```
NullReferenceException: Object reference not set to an instance of an object
Spawn.Server (SpawnInfo info) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Lifecycle/Spawn.cs:278)
Spawn.ServerPrefab (System.String prefabName, System.Nullable`1[T] worldPosition, UnityEngine.Transform parent, System.Nullable`1[T] localRotation, System.Int32 count, System.Nullable`1[T] scatterRadius, System.Boolean cancelIfImpassable) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Lifecycle/Spawn.cs:206)
Objects.GasContainer.OnWillDestroyServer (DestructionInfo info) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Objects/GasContainer.cs:68)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at /home/builduser/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:207)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at /home/builduser/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent/UnityEvent_1.cs:58)
Integrity.CheckDestruction () (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Health/Objects/Integrity.cs:264)
Integrity.ApplyDamage (System.Single damage, AttackType attackType, DamageType damageType) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Health/Objects/Integrity.cs:221)
Explosions.ExplosionNode.Process () (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Explosions/ExplosionNode.cs:69)
Explosions.ExplosionManager.Step () (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Explosions/ExplosionManager.cs:35)
UpdateManager.ProcessDelayUpdate () (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:294)
UpdateManager.Update () (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:273)
```

</details>

Issue was with spawning prefab by name, which was recently changed.
MEtal
Metal1

"Metal" is named now "MetalSheet".
But using reference is the best way to handle this issue.

### CODE REVIEW

**Comment by ThatDan123** [comment]
~~Missing reference found in scriptable object MetalConstructionList field Prefab~~
~~Missing reference found in scriptable object NitrogenCanister field Object~~
~~Missing reference found in scriptable object CO2Canister field Object~~
~~Missing reference found in scriptable object CargoData field Crate~~
~~Missing reference found in scriptable object CargoData field Crate~~
~~Missing reference found in scriptable object CargoData field Crate~~
~~Missing reference found in scriptable object CargoData field Crate~~
~~Missing reference found in scriptable object CargoData field Crate~~
~~Missing reference found in scriptable object CargoData field Crate~~
~~Missing reference found in scriptable object OxygenCanister field Object~~
~~Missing reference found in scriptable object PlasmaCanister field Object~~

All the cargo ones will be buying the canisters

**Comment by corp-0** [comment]
good to merge now?

**Comment by ReiderJack** [comment]
Looks like
Wonder what new issues it might introduce if it broke SOs references...

**Comment by corp-0** [comment]
only one way to find out 👀

**Pull request merged**
