### PR TITLE
Fixed grenade animation with new inventory system

### PR DESCRIPTION
**Pull request by Macoron**
### Purpose
Fixed grenade animation with new inventory system (#1755 again)
Fixed bug when destroyed grenade explodes in (0, 0, -100)
Validate, that grenade now destroys correctly (#2231)

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Proper-Spawning-and-Despawning-%28Object-Lifecycle%29)
- [x]  This PR has been tested with round restarts.
- [ ]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by fomalsd** [comment]
Fire effects stay forever because of this change
GIF

**Comment by Macoron** [comment]
Weird, I can't recreate this behavior.
Can you please describe steps to reproduce this bug?

**Comment by fomalsd** [comment]
any news? in Discord you mentioned separating shape generator into a util class, it'd be handy for my chem spilling needs, too

**Comment by Macoron** [comment]
Hey, sorry, have no free time to finish it right now. Can you accept PM as is? I'll fix this in a new issue.

**Comment by fomalsd** [comment]
I'm afraid I'll have to close this as this introduces an obvious bug. Could you try again in a new PR whenever you have time?

**Pull request closed without merging**
