### PR TITLE
Add basic alert level system

### PR DESCRIPTION
**Pull request by corp-0**
# Pull Request Template

### Purpose
This PR will let the Captain use the Comms console to change the current alert level on the station, displaying the proper message stripped directly from TG.

image

image

image

image

### Notes:
- Initial CentComm update was modified, it now displays the "Intercepted" message whenever the round is not Extended. When the round is indeed extended, it displays the extended message from TG.
- No changes to any of the other systems of the game were made, this addition will only work on a RP level of gameplay. Further PR's to make the level more significant will come eventually.
- Report for Cargonia game mode was delayed in a random amount of time, minimal of 10 minutes and maximum of 20. This would allow Cargo to prepare the rebellion better and even act before Command knows about them.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by Snowy1237** [comment]
does delta alert detonate the station automatically?

**Comment by corp-0** [comment]
As stated in notes, it won’t do anything beside the announcement. Not yet. I plan to add stuff to make the alert change more significant, right now it only plays in a RP level.

**Comment by ThatDan123** [comment]
In tg two heads of staff are required for red alert to occur using the keycard devices.

As red alert allows the emergency shuttle to arrive to the shuttle only 5 mins after called and not recallable, though this isnt applicable to unity station atm.

And delta alert is not manually triggerable.

Occurs when the nuke timer and other event happen.

Suppose this can be changed later when needed, but for now the system you've made is good.

**Comment by corp-0** [comment]
Thanks for your input. Yes, we don’t have the option to swipe two cards, I might try to replicate it in my next pr.

What I could do right now is disabling the red and delta button.

**Pull request merged**
