### PR TITLE
Fixes Lights and adds some on SquareStation

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Updates the lights on Square Station. I have added some and removed some. I also shifted the cell timers inside security so they can't be modified as easily by passerby's. The directional windows are also fixed around that tree/garden area at Research. Probably needs more lights, but we'll see what players think.

### Notes:
SquareStation does not have any light switches for the light tubes and bulbs. It is only bad when you try to replace the lights as they get stuck on their emergency light setting because they think they are off.
It'll be fixed later by one of us, but for now this PR should improve things somewhat.

### CODE REVIEW

**Comment by ThatDan123** [comment]
Please dont add light switches.

**Comment by ThatDan123** [comment]
Ive made an issue about the lights #4808, please do say if thats correct.

**Comment by ThatDan123** [comment]
SquareStation: "LightBulb (4)" miss APC reference.
SquareStation: "LightBulb (3)" miss APC reference.

SquareStation: "APC - MedicalCentral" has a null value in the list.

SquareStation: "LightBulb (2)" miss switch reference.
SquareStation: "LightBulb (1)" miss switch reference.

**Comment by corp-0** [comment]
If you didn’t know already, you can run the test runner locally in your unity editor so you get these light errors faster and can fix them quickly.

**Comment by Akbadain29** [comment]
@ThatDan123 that's fine. I just found it a little annoying when I was putting the lights back on Square Station while figuring out the lighting issue, that'll fix it fine.
@corp-0 I'll try and remember to use that in the future.

**Pull request merged**
