### PR TITLE
Removes unneeded  Cool down ( fixes plasma cutter )

### LINKED ISSUE #6907: You can't put plasma cutters into backpacks by clicking on backpacks with them.
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
When clicking on a backpack with a plasma cutter, the plasma cutter will not be put inside the backpack. This happens even if the backpack has free slots. Opening the backpack's inventory by clicking on it with an empty hand lets you put the plasma cutter in its slots in the UI, so it's clearly not because the plasma cutter cannot fit.

### Steps to reproduce
1. Obtain a plasma cutter.
2. Try to put the plasma cutter in your backpack by clicking on it with the plasma cutter. Fail.
3. Open the backpack's inventory with an empty hand, place the plasma cutter in one of its slots.

### PR DESCRIPTION
**Pull request by Bod9001**
why remove cool down?

I could have tried fixing it but the way it is implemented that since it's on the will interact side it will always trigger to a point where it will block random interaction,  the equivalent for server the form interaction is already implemented before the interaction takes place on an object, so I don't see much use for this since intrinsically will just cause issues down the line

closes #6907

### CODE REVIEW

**Comment by corp-0** [comment]
are you certain this has no repercusions on any other part of the game? What was the reason for us to have a cooldown in interaction validations to begin with?

**Comment by Bod9001** [comment]
looks like  it was used as a client side limit to the number of interactions,

I could code a better solution for, the client actually sending off for interactions and not just checking for interactions

**Comment by corp-0** [comment]
sounds reasonable to move the cooldown where it actually belongs, since it is a validation, instead of getting rid of it

**Comment by Bod9001** [comment]
ok, will work on tomorrow

**Review by corp-0 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]

**Pull request merged**
