### PR TITLE
Resolves Codacy issues for `"nameof" should be used`

### PR DESCRIPTION
**Pull request by CorruptComputer**
### Purpose
Inspired by #7389 I have fixed a handful of issues labeled critical on Codacy, the ones this doesn't fix didn't make sense to me and I think should be marked as false positives.

### Notes:
I have no idea what to put for the changelog since this is something players will never see, so I just left it blank.

### CODE REVIEW

**Comment by corp-0** [comment]
That's awesome, thank you!

> since this is something players will never see

Changelog is meant for players, yep. In cases like this you just don't include it in the PR description.

**Comment by MaxIsJoe** [comment]
godspeed for taming the beast

image

**Review by corp-0 — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
Tests are failing, check out why it doesn't like one of your changes.

**Comment by CorruptComputer** [comment]
image

The tests are fine for me locally. It looks like some file is missing from the build here? I'm really not sure what the cause of that would be.
```
Parsing test runner result file 'testReports/StandaloneWindows64/editmode-results.xml' ...
The html report will be output to the folder 'testReports/StandaloneWindows64/'.
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/runner/work/unitystation/unitystation/testReports/StandaloneWindows64/editmode-results.xml'.
File name: '/home/runner/work/unitystation/unitystation/testReports/StandaloneWindows64/editmode-results.xml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at AventStack.ExtentReports.CLI.Parser.NUnitParser.ParseTestRunnerOutput(String resultsFile) in C:\Users\Alex\Documents\extentreports-dotnet-cli\ExtentReportsDotNetCLI\ExtentReportsDotNetCLI\Parser\NUnitParser.cs:line 23
   at AventStack.ExtentReports.CLI.Program.ProcessSingle(String testResultsFilePath, String output, Boolean merge) in C:\Users\Alex\Documents\extentreports-dotnet-cli\ExtentReportsDotNetCLI\ExtentReportsDotNetCLI\Program.cs:line 108
   at AventStack.ExtentReports.CLI.Program.OnExecute() in C:\Users\Alex\Documents\extentreports-dotnet-cli\ExtentReportsDotNetCLI\ExtentReportsDotNetCLI\Program.cs:line 81
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at AventStack.ExtentReports.CLI.Program.Main(String[] args) in C:\Users\Alex\Documents\extentreports-dotnet-cli\ExtentReportsDotNetCLI\ExtentReportsDotNetCLI\Program.cs:line 43
```

**Comment by corp-0** [comment]
to see test results, you go into the summary and download the test results zip. In this case, it didn't generate the fancy html with results, likely because it isn't compiling. I will retrigger the tests in case it was a one time error (which has happened before).

**Comment by CorruptComputer** [comment]
Oh yeah, seems like just retrying the tests fixed it.

**Comment by CorruptComputer** [comment]
@corp-0 Do you agree that the remaining 3 issues in this category should be marked as false positives? https://app.codacy.com/gh/unitystation/unitystation/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJFcnJvciJdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6WyIxMDE3OSJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

**Comment by corp-0** [comment]
indeed

**Pull request merged**
