### PR TITLE
Ministation cargo refactor

### LINKED ISSUE #9028: Ministation Cargo needs a refactor
While ministations departments have enough room for the most part, Ministations Science and Medical stand out as being too small to expand once new features are added. The typical solution to this would be to just make them larger but there stands a problem. Cargo.

Ministations Cargo rn, acts as a barrier preventing Science and Medical from being expanded in the future, particularly the cargo shuttle, which prevents ministations science form being able to have an ordinance platform.

Refactoring one department is easier than remapping half the station to allow medical and science to expand to the left.
To prevent cargo feature locking ministation a few changes to its layout need to be made:

- [ ] Ministations cargo shuttle should be made to fly left to right as opposed to up and down to prevent it cutting of station expansion
- [ ] The cargo department itself should be remade to be long and short as opposed to being tall and skinny, this will allow science/medical to take up the space above and below cargo where it currently acts as a wall

Ministation

### PR DESCRIPTION
**Pull request by AtnerNT**
Rebuilds ministation cargo so It no longer blocks science expansion, also expands ministation science to have a proper ordnance setup and a research server.

This PR also has a bug fix and improvements to go in hand with this remapping.

The cargo shuttle autopilot has been given options for fly direction so we can now have cargo shuttles leave the station horizontally without having horrible crashes from rotations.

Fixes the bug with the facehugger count that allowed the xeno queen to spawn an uncapped number of facehuggers.

Fixes #9028 
Capture

### Changelog:

CL: [Improvement] Added ability for cargo shuttles to fly horizontal
CL: [Improvement] Remapped ministation cargo and expanded science to include ordnance.
CL: [Fix] Fixed bug with facehugger cap allowing queen to produce an unfiltered amount of spawn

### CODE REVIEW

**Comment by corp-0** [comment]
use past tense in changelog entries.

**Review by corp-0 — DISMISSED** [review]

**Comment by Fr-Dae** [comment]
**The following is a non-exhaustive list,**
```properties
- thick walls (very reinforced) 
- a defence turret
- cameras
- oxygen outlet
- light
- fire extinguisher
- fire door
- black box
- Processing unit
- Mainframe bus
- Message server
- Telecommunication server
- Telecommunication relay
- Telecom hub
- Departmental battery
- automatic announcer
- table, chair
- computer scrap part
- Energy storage unit
- air control
- APC
- wall terminal
- more camera
```

look like nerd-science lab =)


it's look like empty atm :/
(same at fallstation)

**Comment by Fr-Dae** [comment]
a disposal would be a good thing, in both xeno containment rooms, to throw away various things

**Comment by AtnerNT** [comment]
None of that stuff is needed for a research server, you are refering to the telecomms satelitte, which is a seperate part of the station

**Comment by AtnerNT** [comment]
> a disposal would be a good thing, in both xeno containment rooms, to throw away various things

There are two trash bins in xenobio, make that 3

**Comment by Fr-Dae** [comment]
> None of that stuff is needed for a research server, you are refering to the telecomms satelitte, which is a seperate part of the station

Ah indeed, my bad.

**Comment by Fr-Dae** [comment]
> > a disposal would be a good thing, in both xeno containment rooms, to throw away various things
> 
> There are two trash bins in xenobio

that go from the outside, to the inside of the containment chamber? 
or are you talking about a simple "trash can"?

**Comment by AtnerNT** [comment]
> 
Let's bring this to discord as to not cloud the review section of the PR

**Comment by AtnerNT** [comment]
Forgot to make the quantum pad go to lavaland oops. All fixed now, should be ready to merge if tests succeed

**Comment by ThatDan123** [comment]
MiniStation: Vent - QM - zqdLX worldPos: (92.00, 69.00, 0.00) localPos: (91.00, 68.00, 0.00)
has 0 pipe connections but needs 1!

MiniStation: Device "MiniStation/Station/Objects/Firelock (28)" at (87.00, 80.00, 0.00) is not connected to APC "MiniStation/Station/Objects/APC - Science" at (84.00, 74.00, 0.00).
The APC's devices list may unintentionally contain this device. The device is currently connected to "MiniStation/Station/Objects/APC - Rnd Labs" at (85.00, 80.00, 0.00).
MiniStation: Device "MiniStation/Station/Objects/AirlockExternalWindowed (17)" at (96.00, 89.00, 0.00) is not connected to APC "MiniStation/Station/Objects/APC - Mining" at (96.00, 76.00, 0.00).
The APC's devices list may unintentionally contain this device. The device is currently connected to "MiniStation/Station/Objects/APC - Rnd Labs" at (85.00, 80.00, 0.00).
MiniStation: Device "MiniStation/Station/Objects/AirlockExternalWindowed (1)" at (98.00, 89.00, 0.00) is not connected to APC "MiniStation/Station/Objects/APC - Mining" at (96.00, 76.00, 0.00).
The APC's devices list may unintentionally contain this device. The device is currently connected to "MiniStation/Station/Objects/APC - Rnd Labs" at (85.00, 80.00, 0.00).
MiniStation: Device "MiniStation/Station/Objects/Firelock (27)" at (92.00, 80.00, 0.00) is not connected to APC "MiniStation/Station/Objects/APC - Mining" at (96.00, 76.00, 0.00).
The APC's devices list may unintentionally contain this device. The device is currently connected to "MiniStation/Station/Objects/APC - Rnd Labs" at (85.00, 80.00, 0.00).
MiniStation: Device "MiniStation/Station/Objects/ButtonMassDriver (1)" at (98.00, 85.80, 0.00) is not connected to APC "MiniStation/Station/Objects/APC - Mining" at (96.00, 76.00, 0.00).
The APC's devices list may unintentionally contain this device. The device is currently connected to "MiniStation/Station/Objects/APC - Rnd Labs" at (85.00, 80.00, 0.00).

MiniStation: "LightTubeFixture (41)" at (85.00, 82.00, 0.00) has a missing switch reference.
MiniStation: "LightTubeFixture (42)" at (87.00, 87.00, 0.00) has a missing switch reference.
MiniStation: "LightBulbFixture (1)" at (81.00, 87.00, 0.00) has a missing switch reference.
MiniStation: "LightBulbFixture (1)" at (91.00, 84.00, 0.00) has a missing switch reference.
MiniStation: "LightBulbFixture (29)" at (91.00, 86.00, 0.00) has a missing switch reference.
MiniStation: "LightBulbFixture (30)" at (95.00, 86.00, 0.00) has a missing switch reference.
MiniStation: "LightBulbFixture (31)" at (95.00, 84.00, 0.00) has a missing switch reference.

MiniStation: "LightSwitch (1)" at (83.00, 85.00, 0.00) has no light sources.
MiniStation: "LightSwitch (1)" at (90.00, 83.00, 0.00) has no light sources.
MiniStation: "LightSwitch (1)" at (87.00, 77.00, 0.00) has no light sources.
MiniStation: "LightSwitch (19)" at (96.00, 81.00, 0.00) has no light sources.

**Comment by AtnerNT** [comment]
Tests fixed

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
