### PR TITLE
Staging fixes

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [Fix]  Fixed space cleaner not consuming reagents
CL: [Fix]  Fixed Spray particles not playing properly
CL: [Fix]  Fixed right click missing point, drag and pick-up actions

### CODE REVIEW

**Review by Fr-Dae — COMMENTED** [review]
link to https://github.com/unitystation/unitystation/issues/9522
 ?

**Comment by corp-0** [comment]
> CL: [Fix] Fix is right click

what does this mean?

**Comment by Bod9001** [comment]
Right click on a list of items didn't have the appointment Dragon Pick up and stuff actions

**Comment by corp-0** [comment]
Appointment dragon pick up?

**Comment by Bod9001** [comment]
Didn't have the point drag Pick up actions

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
