### PR TITLE
Merges Outfits and OccupationRosters prefabs

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes security records photos not showing gear defined in the standard gear outfit prefab.
Merges Outfit prefabs with OccupationRosters.
Removes the need of a standard gear prefab.
GameManager occupations list will now be a OccupationRoster list instead of GameObject, removing several getcomponent calls.
OccupationRoster will now save how many players spawned with its designated job type.
Removes the now unused Outfit prefabs and class.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by Bod9001** [comment]
~~Isn't there going to be issues with the split spreadsheet PR?~~

**Comment by Bod9001** [comment]
Or am I confusing it with something else. yes I am

**Comment by Bod9001** [comment]
image
Seems assistance gets it to -1, Replicated in lobby and Outpost station

**Comment by Aranclanos** [comment]
sorry not sure how I missed that, fixed

**Comment by DooblyNoobly** [comment]
Gracias Aranclanos. We still have a bug with the number of roles occupied not showing up in the choose profession screen. But this screen won't be there for 0.4 launch as players will need to set their preferences in the character set up screen in the lobby.

**Pull request merged**
