### PR TITLE
[Rebase] Moved Atlases out of resources. Added Spread setting to jukebox

### PR DESCRIPTION
**Pull request by NoooneyDude**
Rebases Doobly's PR #4798 to commit `c41d28c57c2dbe480bf980e1fdfe3e06009352f6` (latest develop at the time of this PR).

I couldn't tack the rebase onto the end of that PR, because it is a branch on this upstream repository `unitystation`.

Update:
That's a huge amount of .meta file changes. Hmmm...

> No new console warnings/errors after deleting `Library`. I think I had to delete it because I went so far back in git history to do the rebase.
> Tested in editor, no obvious issues or errors.
>
> Tested with two clients connected to headless and restarting, no problems though I did get some client errors on the second client: https://i.imgur.com/ASqb5Lz.png. Probably related to this PR, though I couldn't find any meta files that contained those IDs, even before this PR. I could find these: https://i.imgur.com/nAKELmY.png not sure if relevant.

### CODE REVIEW

**Comment by Bod9001** [comment]
I think this was Doobly trying to Get the build working

**Comment by NoooneyDude** [comment]
Yeah. I removed the build script changes, but not the file compression stuff. That seems to be the reason for all the .meta files. The jukebox update and moving stuff out of `Resources` would be nice, though.

**Comment by Bod9001** [comment]
you can really see the compression you can  that's the only problem

**Comment by corp-0** [comment]
I didn't understand. What's the state of this pr?

**Comment by Bod9001** [comment]
think it was attempt at fixing automated builds

**Comment by NoooneyDude** [comment]
I've reverted the file compression. Should just be the `Resources` cleanup and the jukebox stuff now.

**Pull request merged**
