### PR TITLE
Fixes Closet, Freezer and Leaper Sprites

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Should fix closets and freezers to make their closed door sprites reappear. I've also tried making Leaper reappear too and fixed up TestStation, some tables had gone missing.

### CODE REVIEW

**Comment by corp-0** [comment]
can you describe what you changed on the prefabs?

**Comment by Akbadain29** [comment]
While the door open sprite was fine for the closets etc. as there is a reference to it in the Closet Control component, but on their Door Layer inside the prefab there was a missing reference, all that was need to be done was to update the current present field inside the SpriteHandler component to restore the closed door sprite.

Leaper was missing DirectionalSprite V2 and SpriteHandler components. Hopefully with those added, it will be visible again, I could see it when I spawned it in.

**Comment by corp-0** [comment]
what about crates? I read some crates are invisible too. Do you have any idea on what could have caused the missing ref?

**Comment by Akbadain29** [comment]
I'll have another look for those. It's probably the same thing.

**Comment by PerfectTangent** [comment]
crate sprites are fucked. so is the reactor, turbine, boiler, water pump, the power transformer, and I believe one of the pipe colors are missing as well. There's probably more stuff, too.

**Comment by Akbadain29** [comment]
These crate sprites look fine to me, nothing invisible there. Reactor sprites should be now fixed up.

**Comment by corp-0** [comment]
Thanks a lot. If you don't mind, I will leave this PR open for a while, to see if we get more reports about invisible sprites.

**Comment by Akbadain29** [comment]
image
The problem seems to be with however Unity is dealing with Sprites (Texture 2Ds) and how it loads (or rather doesn't load) into the SpriteHandler, converting objects to be a single sprite inside a Sprite Data SO seems to fix it.

**Comment by Akbadain29** [comment]
Ok, should we be making sure that sprites are called from a Sprite Data SO and not a Texture 2D like the one above is?

**Comment by NoooneyDude** [comment]
Yep, SO is preferred.

**Comment by corp-0** [comment]
Brian, take a look at vending machines? Slucc said there are some invi ones

**Comment by Akbadain29** [comment]
Slug said the vending machines were missing on Fall, but I've had a look and none seem to be missing their sprites.

**Comment by NoooneyDude** [comment]
Good to merge?

Edit: I see scene changes so will merge earlier. Thank you.

**Pull request merged**
