### PR TITLE
Ajust headset sprites and shotgun fix

### PR DESCRIPTION
**Pull request by AutumnNova**
makes head headsets visually different from department headsets
adds unique worn sprites for research director and chief engineer headsets
adds in the lawyers unique headset
implements daPotato's new headset sprites

### CODE REVIEW

**Comment by craftxbox** [comment]
screenshots of changes please?

**Comment by AutumnNova** [comment]
[this](https://github.com/unitystation/unitystation/tree/develop/UnityProject/Assets/Textures/clothing/ears/NewHeadsets) is the new sprites

**Comment by AutumnNova** [comment]
headsets

**Review by Bod9001 — CHANGES_REQUESTED** [review]
for the multi-Sprite once it's missing the .json direction data, the data is pretty generic so you can copy it from one of the other headsets, and make sure you rename it exactly the same name but with out the png and with json instead,
there's also a tool that automatically splits them (from the DMI files) for you and gives you the jsons

**Comment by Bod9001** [comment]
oh yrah, Forgot to say You might have to reset the sprite references, Since they don't have reference to the sprites .json Data

**Comment by AutumnNova** [comment]
5th try's a charm or something

**Pull request merged**
