### PR TITLE
Added some chairs , space cleaner to Janitor's closet.

### PR DESCRIPTION
**Pull request by Evan-R-Rogers**
Added a few chairs, tables, faced some sprites to correct positions.

Added two space cleaner spray bottles to Janitor's closet.

### CODE REVIEW

**Comment by Jibbajabbafic** [comment]
Got some screenshots of the map changes?

Also, a better way to add the space cleaner would be to edit the janitor closet contents in this file: Assets/Resources/ScriptableObjects/SpawnableLists/Closets/Janitor.asset

That will give all janitor closets the space cleaner instead of just the ones on the map.

**Comment by Evan-R-Rogers** [comment]
Working on that now, as well as a few other scenery changes.

**Comment by Evan-R-Rogers** [comment]
Sec checkpoint airvent moved down one tile
Office chairs in HoP office now face the table and comm console
A potted plant, some metal chairs added to this area below and next to Captain's quarters

**Comment by ghost** [comment]
That chair in the bridge at the corner of the window not really doing anything feels kind of off...

**Comment by Jibbajabbafic** [comment]
Looks like you removed trash bags from the janitor closet.

Change the size to 9 and then you'll have another slot to add them to.
image

Other than that I like the map changes!

I see @gardenBanter's point about the chairs being a bit awkward though
image

Maybe you could add some other random decorative items instead to make it feel less empty?

**Comment by Evan-R-Rogers** [comment]
Hm, there were no trashbags in those closets when I had checked the inspector? Give me a few to check this out, I'll also try to flesh out that viewing room or whatever it is.

**Comment by Jibbajabbafic** [comment]
Alright seems to work, merging.

**Pull request merged**
