### PR TITLE
Adds electrifiable grilles

### PR DESCRIPTION
**Pull request by NoooneyDude**
### Purpose
- Adds electrified grilles.
79Ed6oLaH0

- Fixes mouse behaviour where they will chew wires that are covered by floor tiles.
- Enables electrocution animation sprite overlay on electrocution.

### Notes
- Electrified grilles are missing sparks VFX
- Electrified grilles have no bump interaction

> No scenes have been altered.

### CODE REVIEW

**Comment by Bod9001** [comment]
yeah, Someone needs to test this properly, I might do it tomorrow

**Comment by NoooneyDude** [comment]
You're right, I did stumble into a problem. Melee attack interactions for grilles seem to have been interrupted.

**Comment by Bod9001** [comment]
oh How's it going with that stuff?

**Comment by NoooneyDude** [comment]
Alright, ready for review!

Do we [have a go](https://www.youtube.com/watch?v=odiMeEhfi9I)?

**Comment by Bod9001** [comment]
ok, I finished my exams so let's do this review

**Pull request merged**
