### PR TITLE
Weapon changes

### PR DESCRIPTION
**Pull request by AutumnNova**
Corrects the sec hardsuit sprite
Changes UI coloring for the character customisation color picker
Remove unused ammo types
Reorder ammo types
Adds the hos laser gun to the hos locker populator
Changes tommygun to be .45
Changes uzi and smg to be 9mm
Adds a spent shell for shotguns to eject
Refactors the way ammo calibers are done, allowing for more then one mag type per caliber
Change the tazer firerate to 2 shots per second (was 5)

### CODE REVIEW

**Comment by corp-0** [comment]
you have missing components
```
Missing reference found in scene OutpostStation, GameObject Objects/vending_24, Component vending_24, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_51 (1), Component vending_51 (1), FieldName Item
```

and missing scriptable objects
```
Missing reference found in scriptable object Syndicate field Element 1
Missing reference found in scriptable object Syndicate field Element 2
```

**Comment by AutumnNova** [comment]
havent touched the vendin or outpost, dunno what caused that

**Comment by corp-0** [comment]
merged prs look green, so I don't think we introduced the missing references to develop. 
How old is your branch? Maybe an item was deleted recently and your outpost version still has a reference to it.

**Comment by AutumnNova** [comment]
25 commits behind unitystation:develop

**Comment by corp-0** [comment]
try fetching and merging them. Maybe that fixes the missing references.

**Comment by DooblyNoobly** [comment]
tests are complaining about missing references on outpost station. But there is no outpoststation changes in this pr. So I have nfi whats going on. Going to merge this tho

**Comment by CodeKalias** [comment]
> tests are complaining about missing references on outpost station. But there is no outpoststation changes in this pr. So I have nfi whats going on. Going to merge this tho

The outpoststation vending machines had references to ammo types which were removed, vending_24 seems fixed in current version of develop
vending_51 (1) in sec lost its reference to Magazine_12mm (prefab deleted)

**Comment by corp-0** [comment]
I think Doobly was fixing references on weapons last night

**Pull request merged**
