### PR TITLE
Lights

### PR DESCRIPTION
**Pull request by FuntimeDudeski**
### Purpose
New Light2D sprites: Terrain, updated drafts of animated+colored fire and lava, console lights, pulsing runway/collision light, draft update to Minimal Player Light, an initial attempt at glowing eyes, and a couple other effects

### Notes
image
image
Current firelight draft in game: https://discord.com/channels/273774715741667329/300454903250419712/1090494039050162237

image
Lava light draft in game: https://discord.com/channels/273774715741667329/300454903250419712/1090371953887563866

image
Console light preview in game: https://discord.com/channels/273774715741667329/300454903250419712/1087472759048765452
image
image

image

### Changelog:
Nothing player-visible for the moment (except possibly the changed firelight animation if currently implemented).

### CODE REVIEW

**Comment by corp-0** [comment]
your tets are failing, I think something is wrong with the scriptable object sprites

```
Pulse32 Index 0 Subindex 0 has a missing reference.
Pulse32 Index 0 Subindex 1 has a missing reference.
Pulse32 Index 0 Subindex 2 has a missing reference.
Pulse32 Index 0 Subindex 3 has a missing reference.
Pulse32 Index 0 Subindex 4 has a missing reference.
Pulse32 Index 0 Subindex 5 has a missing reference.
Pulse32 Index 0 Subindex 6 has a missing reference.
Pulse32 Index 0 Subindex 7 has a missing reference.
Pulse32 Index 0 Subindex 8 has a missing reference.
Pulse32 Index 0 Subindex 9 has a missing reference.
Pulse32 Index 0 Subindex 10 has a missing reference.
Pulse32 Index 0 Subindex 11 has a missing reference.
Pulse32 Index 0 Subindex 12 has a missing reference.
Pulse32 Index 0 Subindex 13 has a missing reference.
Pulse32 Index 0 Subindex 14 has a missing reference.
Pulse32 Index 0 Subindex 15 has a missing reference.
Pulse32 Index 0 Subindex 16 has a missing reference.
Pulse32 Index 0 Subindex 17 has a missing reference.
Pulse32 Index 0 Subindex 18 has a missing reference.
Pulse32 Index 0 Subindex 19 has a missing reference.
Pulse32 Index 0 Subindex 20 has a missing reference.
Pulse32 Index 0 Subindex 21 has a missing reference.
```

**Comment by FuntimeDudeski** [comment]
> your tets are failing, I think something is wrong with the scriptable object sprites
> 
> ```
> Pulse32 Index 0 Subindex 0 has a missing reference.
> Pulse32 Index 0 Subindex 1 has a missing reference.
> Pulse32 Index 0 Subindex 2 has a missing reference.
> Pulse32 Index 0 Subindex 3 has a missing reference.
> Pulse32 Index 0 Subindex 4 has a missing reference.
> Pulse32 Index 0 Subindex 5 has a missing reference.
> Pulse32 Index 0 Subindex 6 has a missing reference.
> Pulse32 Index 0 Subindex 7 has a missing reference.
> Pulse32 Index 0 Subindex 8 has a missing reference.
> Pulse32 Index 0 Subindex 9 has a missing reference.
> Pulse32 Index 0 Subindex 10 has a missing reference.
> Pulse32 Index 0 Subindex 11 has a missing reference.
> Pulse32 Index 0 Subindex 12 has a missing reference.
> Pulse32 Index 0 Subindex 13 has a missing reference.
> Pulse32 Index 0 Subindex 14 has a missing reference.
> Pulse32 Index 0 Subindex 15 has a missing reference.
> Pulse32 Index 0 Subindex 16 has a missing reference.
> Pulse32 Index 0 Subindex 17 has a missing reference.
> Pulse32 Index 0 Subindex 18 has a missing reference.
> Pulse32 Index 0 Subindex 19 has a missing reference.
> Pulse32 Index 0 Subindex 20 has a missing reference.
> Pulse32 Index 0 Subindex 21 has a missing reference.
> ```

aha thanks--i renamed the sprites in unity (or so i allege) but ig it didn't update the SO

**Comment by FuntimeDudeski** [comment]
thank god!

**Comment by corp-0** [comment]
Awesome. Lastly, do you have any screenshots we could use to see the improvement?

**Comment by FuntimeDudeski** [comment]
> Awesome. Lastly, do you have any screenshots we could use to see the improvement?

Added.

**Comment by FuntimeDudeski** [comment]
> Your PR has no registered changes in its description!

SILENCE, ANDROID.

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
