### PR TITLE
Variable viewer now Can change, int strings floats, enum and bools

### PR DESCRIPTION
**Pull request by Bod9001**
And now looks better with text mesh pro

### Purpose
VV's are fun

yeah, need anything added added am good  To do it

Tested in editor

### CODE REVIEW

**Comment by Bod9001** [comment]
need to quickly get the input focus stuff done

**Comment by Bod9001** [comment]
It's strange the input fields aren't being selected properly in builds idk What to do what to do

**Comment by chairbender** [comment]
We have some global stuff that affects UI focus, in UIManager I believe.

**Comment by Bod9001** [comment]
is good now

**Comment by chairbender** [comment]
yeah, VV Is looking nicer. Thanks!

**Pull request merged**
