### PR TITLE
The great hover tooltip

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Adds hover tooltips that will allow us to easily communicate concepts and interactions with new and old players. By default, it's enabled for everyone except those who have set their experience level to a high level which lets them only access it afterwards by holding shift.

All players can enter detailed mode using the shift key, which displays extra info about objects/items/players. In the future this will allow us to display the next steps for crafting/building objects and show important info that new players might not catch on first.

image
_Hovering over a locker in detailed mode while holding a welding tool_

image
_A dying captain, showing that you can perform CPR on them when they're in critical condition._

image
_New players might not catch on this at first.. but with the hover tooltip; now they can!_

### Notes:

This PR is going to be a test bench for any bugs or issues we might encounter later. As a result; no options and testing is limited to a few things currently.

In later PRs, the hovertooltip will be used on many other objects and will add the customizable delay i talked about on discord.

### Changelog:

CL: [New] Added hover tooltip. Press shift to enter detailed mode when hovering over things.
CL: [Improvement] Retired the default panel tooltip in favor of the hover tooltip. The classic tooltip will now be the only default option.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
> Your PR has no registered changes in its description!

and i aint seeing no bitches on your bot ass

**Comment by MaxIsJoe** [comment]
I'm aware of the tests not working, will work on it soon

**Comment by MaxIsJoe** [comment]
myprisfinishedplsrev

**Comment by MaxIsJoe** [comment]
the issues codacy is giving is stupid

**Comment by corp-0** [comment]
no you

**Comment by MaxIsJoe** [comment]
I will not not use null

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
