### PR TITLE
Fixes and cleanup related to direction, rotation, buckling and mouse drag

### LINKED ISSUE #1930: Buckling to a chair while walking past it causes strange behaviour
# Description
Walking past a chair and buckling to it will make it appear as though you are buckled to it while you are actually standing to the side of the chair. Unbuckling by clicking on the chair is impossible while in this state.

chair_walkby

## Category
BUG

## Steps to Reproduce
1. Walk past a chair
2. While walking past it, buckle yourself to it. I recommend just clicking on your sprite to do this. This may take a couple of tries.

### LINKED ISSUE #1931: Buckling to a chair doesn't update the direction you are facing on client B: 25
# Description
chair_netbug
(client on the left, server on the right)

When buckling yourself to a chair on the client, the direction you're facing is updated for all other clients and the server but not for you.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start the game with a separate server and client
2. On the client, buckle yourself to a chair while not facing the direction the chair is facing
3. Notice that you are still facing that direction.

### LINKED ISSUE #1951: Opened lockers can appear closed for late joiners
# Description
image

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host from build, open some lockers
2. Join from editor, look at lockers

### LINKED ISSUE #1952: Bodies appear underneath lockers
# Description
image
Player corpses appear underneath lockers when they are opened (instead of being above)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in build, join in editor
2. Let one of players onto opened locker, stab him into crit (but not to death)
3. Close locker
4. Wait till he's dead
5. Open locker
^ Reproduction can likely be simpler, but I only tried following scenario

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #1931 
Fixes #1930 
Fixes #1952 
Fixes #1951 

Refactors facing and rotation logic to have cleaner separation of concern between components.
Directional component allows an object to maintain a direction and have one assigned during mapping. This is used for chair and wallmounts. Other components can subscribe to Directional to receive direction changes. This is intended to be used for anything that has some sort of directional state, and it has logic for allowing client prediction as well as managing sync between client / server.

The way that a sprite rotates when a matrix is rotating is now part of SpriteMatrixRotation rather than RegisterTile.

Cleans up the directional sprite component, also renaming it to OccupiableDirectionalSprite to make it more clear what functionality it provides.

Fixes some other issues that weren't tickets:
1. Couldn't initiate a drag when someone was obscured by something (such as a corpse behind a chair)
2. Fix issues which were causing things like light tubes to be totally out of sync between client and server when client joins after the syndie shuttle has rotated. This was solved by adding CNT to LightTube, Light bulb, camera, and emergency light.

After this, there hopefully shouldn't be cases where light rotations are messed up on client side, so consider those a regression if it starts happening again after making a change.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
The large amount of prefab changes due to splitting logic out from RegisterTile into SpriteMatrixRotation.

The OutpostStation change was just modifying the Wallmounts to set Directional.InitialDirection. I've included some logic that allows this to be re-done if there are mapping conflicts, which can be removed once this PR is merged.

### CODE REVIEW

**Comment by chairbender** [comment]
also updated mapping wiki: https://github.com/unitystation/unitystation/wiki/How-to-Map

**Comment by chairbender** [comment]
Still cases where buckled direction no synced. Dnm

**Comment by fomalsd** [comment]
Directions work as expected when pulling mobs, good job!

**Comment by chairbender** [comment]
Sorry the PR blew up, but I ended up finding quite a few issues that I fixed.
Turns out I hadn't actually applied the wallmount changes to the scene and the prefabs were missing the Directional component. Had to learn some more editor scripting so I could modify the wallmounts in the scene to fix their Directional settings. Added the component to the prefabs as well.

Also fixes some other issues brought up recently:
- bodies appear over lockers #1952
- no more NRE when right clicking in certain situations
- locker show up correctly for late joiners #1951 

ready for review

**Review by fomalsd — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
