### PR TITLE
Gas Overlay Fix

### PR DESCRIPTION
**Pull request by ThatDan123**
Allows for multiple gas overlays again, woo

CL: Fixed multiple overlays not working
CL: Moved tile reactions to atmos simulation
CL: Moved gas overlay setting to atmos simulation

Squash merge this

### CODE REVIEW

**Comment by Bod9001** [comment]
does this move over wind as well?

**Comment by Bod9001** [comment]
press the wrong button xD

**Comment by ThatDan123** [comment]
Didnt move wind over, or hotspots as im not exactly sure how those systems work. Though they probably can be now and the reaction manager would be obsolete. I might do it in a PR after this one.

**Comment by Bod9001** [comment]
the only problem I see is moving items but that might be okay

**Pull request merged**
