### PR TITLE
[DNM] Access remote(#5819)

### PR DESCRIPTION
**Pull request by vlandemart**
### Purpose
Adds Access Remote, that allows to remotely control airlocks - open, bolt or set them to emergency access mode. 
Closes last task in #5819

https://user-images.githubusercontent.com/19672958/154288954-0a0ca49a-c2bc-4ffc-867b-e7bd587c928d.mp4

### Notes:
1. It doesn't check access as for now, this will be fixed in future commit
2. I haven't added them to any scenes. This either needs to be done in separate PR or I can add access remotes to default loadout of department heads

### CODE REVIEW

**Comment by PerfectTangent** [comment]
@Ahion what is left to prepare this draft PR?

**Comment by Ahion** [comment]
Wow, someone undertook to do my job while I was resting)) cool...

> @Ahion what is left to prepare this draft PR?

I do not know. The author of this PR knows better how much work he wants to do. The assignment says that every department head should have Remote Access. Probably it will be necessary to add more sprites for Remote Access of different departments. And this device should only open the doors of their department.

**Comment by NoooneyDude** [comment]
What's happening with this?

**Comment by vlandemart** [comment]
> What's happening with this?

I'm not in a shape to do anything, this one is stale.
I think the only thing lacking in this PR - ID check/authorization and I don't know when I would be able to sit and implement it.

**Comment by CdrCross** [comment]
Should the status here perhaps be moved to "Awaiting changes" and then we look actively for someone to finish it up? Access remotes would be really good to get in.

**Comment by PerfectTangent** [comment]
closing as #9035 finished this.

**Pull request closed without merging**
