### PR TITLE
Refactor PickupTrigger to IF2, improve IF2 usability/features/bugs

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Part of #1760 , an ongoing ticket.

Split PickupTrigger into a separate component, Pickupable, so it no longer needs to be subclassed. And refactored it to use IF2.

Added editor script (Prefabs/Create Required Component) for bulk-adding a RequireComponent'd component, and used it to add Pickupable to all the prefabs that need it.

Made some changes to the core classes of IF2 to (hopefully) make it easier to work with as I discovered various challenges implementing Pickupable.

IF2 now supports optional client side prediction and rollback (used in Pickupable).

Documentation has been updated here: https://github.com/unitystation/unitystation/wiki/Interaction-Framework-V2---How-to-Cleanly-Implement-Interactions

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Review by fomalsd — APPROVED** [review]
It's good, I like it!

**Comment by fomalsd** [comment]
@Bod9001 @Aranclanos do you have anything to say about this one? I think Pickupable component is convenient

**Comment by Aranclanos** [comment]
the logic behind it looks fine

**Comment by Bod9001** [comment]
I got  Some errors with PlayerLightControl on client, not sure if it was preexisting

**Comment by Bod9001** [comment]
When taking a mining lump of of the backpack and back in again*

**Comment by Bod9001** [comment]
Apart from that it looks good

**Comment by chairbender** [comment]
I'll fix the mining lamp thing and also wanted to do another small refactoring to the core IF2 classes that occurred to me today

**Comment by chairbender** [comment]
nvm on the refactor, changed my mind, but I will fix the lamp

**Comment by chairbender** [comment]
Okay, should be fixed.

**Comment by Bod9001** [comment]
A you can't take your clothes off with clicking on them
B after using a the chemistry dispenser with a glass, when you try taking off your close it get NRE

**Comment by chairbender** [comment]
Argh. Thanks @Bod9001 . Should be fixed now.

**Comment by fomalsd** [comment]
so, good to merge?

**Comment by chairbender** [comment]
Not sure if that's for me but yeah it should be good to merge.

**Pull request merged**
