### PR TITLE
PDA and Uplink functionality

### PR DESCRIPTION
**Pull request by Nukeuler123**
### Purpose
Adds functionality to the PDA by adding a navigatable menu and allowing traitors to use the PDA as an uplink.

### Notes:
- Currently, there is a problem with the NetUI automatically closing when a page needs to update, unknown reason. 

### Features that need to be implemented 
- [x] Fully functional PDA interface(GUI)
- [x] Fully functional PDA features(Cartridges, flashlight, atmospherics data gathering(maybe), crew manifest)
- [x] Traitor uplink 
- [ ] PDA bombs (On hold, requires the PDA messenger which im not skilled enough to do)
- [ ] Fancy looking UI with themes (On hold, likely to not be included in this PR)

### Please make sure you have followed the self-checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
**Note: There is currently a bug with the Notes not updating on clients beside the one who makes the edit, working on it**
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable) (Note, no late joiners were tested)
- [x] The PR has been tested with round restarts.

The foundation is in place for everyone to build off of and to improve

### CODE REVIEW

**Comment by Nukeuler123** [comment]
Please note this is on hold so I may help in fixing the major bugs with the new update

**Comment by fomalsd** [comment]
what's the status on this one?

**Comment by Nukeuler123** [comment]
It's just about done, the only big thing to note is the messenger system, which I've been having problems with. Though I will still have to to back through and make sure the code is optimized and secure.

**Comment by fomalsd** [comment]
any updates on this?

**Comment by Nukeuler123** [comment]
Update: Almost all features are added working on making sure the PDA notes sync across clients, PDA bombs will not be implemented due to that requiring a messenger system which will also not be implemented because networking is complicated.

**Comment by ReiderJack** [comment]
PDA UI closes when you move. The UI is not updated after a button is pressed.

**Comment by Nukeuler123** [comment]
> PDA UI closes when you move. The UI is not updated after a button is pressed.

Yeah, that's a problem i'm running in to when it comes to a UI on an item, at the moment I don't see a way to fix it, any ideas would help. The work around I know is pressing "Z" while the PDA is in the active hand, that will update the UI.

**Comment by fomalsd** [comment]
It's because NetUI was originally designed for consoles/other non-pickupable objects in the world, therefore there is a range checker that kicks in when interacting with/receiving updates from NetUI tab. That range checker should be modified to always allow interactions with UIs of items in your inventory

**Comment by Nukeuler123** [comment]
> That range checker should be modified to always allow interactions with UIs of items in your inventory

Sounds like work..... ill get onto it.

**Comment by Nukeuler123** [comment]
Im having a hard time trying to find where the Tab is closing from. I've created a simple bool in the NetTab script to allow the UI to bypass the `validatepeepers()` method though it seems to be closing from somewhere else, any help finding other line causing the UI closing would be appreciated.

**Comment by DooblyNoobly** [comment]
> 
> 
> Im having a hard time trying to find where the Tab is closing from. I've created a simple bool in the NetTab script to allow the UI to bypass the `validatepeepers()` method though it seems to be closing from somewhere else, any help finding other line causing the UI closing would be appreciated.

Have a look in the Validations.cs script, there is a code there that prevents users from spam clicking (I think there is a list or dictionary that captures the time a click was made and how often and if it thinks someone is spamming it will return a false validation which will close the nettab). Comment this code out and see if it fixes it. I have a feeling that dynamic list is still spamming the hell out of validations which needs to be fixed as some point.

**Comment by Nukeuler123** [comment]
Tried, did not work, im honestly at a loss for what is causing it to close, iv looked in many pieces of code where any method for NetTabs could be called. Anyway, im going to push my final changes (Which is just fixing my NetTab file) and it will be ready to merge, though much work will still need to be done on the staging server. (Also note that the PDA can only be spawned by admins in the object menu)

**Comment by DooblyNoobly** [comment]
Ok sounds good, we can look into the closing bug later

**Pull request merged**
