### PR TITLE
Fix New Player Door Sync

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: [Fix] Fixed the syncing of the door status to new players

### CODE REVIEW

**Comment by corp-0** [comment]
I edited the description to include the changelog [Label] and also changed the verbal time to past.

**Comment by corp-0** [comment]
I thought @Aranclanos did something some time ago to sync new doors, didn't he?

**Comment by ThatDan123** [comment]
> I thought @Aranclanos did something some time ago to sync new doors, didn't he?

This is for new players, it was partially hooked up, was missing the callback

**Comment by corp-0** [comment]
alrighty then, thanks.

**Pull request merged**
