### PR TITLE
More fixes22

### PR DESCRIPTION
**Pull request by Bod9001**
some general fixes

### Changelog:

CL: [Improvement] Research laser projection is slightly transparent now

CL: [Fix] Fixed clown and other lobby objects not producing any sound when clicked.
CL: [Fix] Fixed server passwords sometimes having strange behaviour when typing the password.

### CODE REVIEW

**Comment by corp-0** [comment]
> CL: [Fix] fixes sound effects on lobby
> CL: [Fix] Fixing some errors to do with servers with passwords

what was fixed?

**Comment by Bod9001** [comment]
the background Clown and stuff Now make noise again when you click on

**Comment by corp-0** [comment]
I updated your changelog entry. 

What about the other fix? How did you fix server password?

**Comment by Bod9001** [comment]
it seemed to have a non-connected component that was throwing errors, it was buggy when I had that, I removed it and then it seemed to work fine after that

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
