### PR TITLE
This works? (test fix)

### PR DESCRIPTION
**Pull request by Bod9001**
wasn't able to grab packages for some reason

### CODE REVIEW

**Comment by ThatDan123** [comment]
nope, still not working

**Comment by Bod9001** [comment]
this technically doesn't count since, I removed Fire base

**Comment by Bod9001** [comment]
let me check if it still compiles?

**Comment by ThatDan123** [comment]
I think it might be working fine.

**Comment by Bod9001** [comment]
doesn't compile,  must be importing project

**Comment by Bod9001** [comment]
humm, this works buts add 100 mb file

**Pull request merged**
