### PR TITLE
Moves the SyncPlayerData from each body transfer to the clients login

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Moves the SyncPlayerData from each body transfer to the clients login.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by chairbender** [comment]
For future reference, when you write the purpose, it will help with the review if you can explain _why_ you made the change.

I am assuming you did this so that SyncPlayerData would only be done on login rather than being repeated unnecessarily on each body transfer.

EDIT: Actually maybe you did it so that data is synced earlier during the connection process?

**Comment by chairbender** [comment]
in any case, this seems fine

**Comment by chairbender** [comment]
Noticing some problems during testing, standby...

**Comment by chairbender** [comment]
Okay, I am not sure if this is related to these changes. If you are sure it is not, I will create a ticket for this issue and you can feel free to merge it yourself. Other issues I noticed are already tickets.

Reproduction steps:
1. Host in editor and kill yourself somehow (in the game). Respawn. Validate that your corpse appears laying down.
2. Join as client. Corpse appears standing up.

**Comment by Aranclanos** [comment]
thats an old bug, it has a report open already

**Comment by chairbender** [comment]
@Aranclanos please link it, I couldn't find one. I know this issue happened before and was fixed at some point, but it looks like this is a regression.

**Comment by Aranclanos** [comment]
couldnt find it, I guess there wasnt an issue after all

**Comment by chairbender** [comment]
ok I'll just take your word for it that it was pre-existing and open a ticket

**Pull request merged**
