### PR TITLE
Highlighting first edition

### PR DESCRIPTION
**Pull request by Bod9001**
Thanks to MrMeatpie for the shader

Co-Authored-By: Leonard K <mrmeatpie@users.noreply.github.com>

### what this do?
ads highlights to items and objects to see if your interaction can be done
### why you do this?
because it's nice being able to see what you can do/clicking on
### what have you changed?
used existing interaction code probably could reuse it somehow but not smart enough
modified manager prefab, 
added one convenience method for worldtoscreen
### what you tested?
editor
### What do you need to add
I'm planning to add in some options for it so it's not finished yet and try some performance improvements

### CODE REVIEW

**Comment by Bod9001** [comment]
oh yeah gif 
dsfsdfsfGIF

**Comment by Bod9001** [comment]
oh yeah, try it out,  and drop some suggestions

**Comment by fomalsd** [comment]
Are you sure you've included everything necessary for this PR?
Getting errors instead of outlines: 
```
MissingReferenceException: The variable material of Highlight doesn't exist anymore.
You probably need to reassign the material variable of the 'Highlight' script in the inspector.
UnityEngine.Material.SetColorImpl (System.Int32 name, UnityEngine.Color value) <0x1562787e0 + 0x0006a> in <ad9beda1ab3247eeb4730364a1ba4085>:0
UnityEngine.Material.SetColor (System.String name, UnityEngine.Color value) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Shaders/Shader.cs:490)
Highlight.CheckHandApply (UnityEngine.GameObject target) (at Assets/Scripts/Highlight/Highlight.cs:134)
Highlight.HighlightThis (UnityEngine.GameObject Highlightobject) (at Assets/Scripts/Highlight/Highlight.cs:47)
Attributes.OnHoverStart () (at Assets/Scripts/Items/Attributes.cs:104)
UnityEngine.Component:SendMessageUpwards(String, SendMessageOptions)
MouseInputController:CheckHover() (at Assets/Scripts/Input System/MouseInputController.cs:298)
MouseInputController:CheckMouseInput() (at Assets/Scripts/Input System/MouseInputController.cs:218)
MouseInputController:LateUpdate() (at Assets/Scripts/Input System/MouseInputController.cs:98)
```

**Comment by Bod9001** [comment]
added back in

**Review by fomalsd — COMMENTED** [review]
I'm inclined to merge this as soon as this gets an option to turn it off.
It'll be a while until we make colouring right anyway.
There are a few bugs with colouring and animated things like airlocks, but this can be addressed as we go
gif

**Comment by Bod9001** [comment]
In the process of  adding player preferences

**Comment by Bod9001** [comment]
added Should be ready to merge now

**Pull request merged**
