### PR TITLE
OOC colour change

### LINKED ISSUE #4101: CMD chat and OOC chat are the same color
## Description
The CMD chat and OOC chat are the same exact shade of blue. This is an _incredibly_ easy fix, since all of the chat colors are stored in the same prefab. Like, literally all you need to do is click the color of one of them and make it like purple or something. Or even just a darker shade of blue.

### Why would this be an issue?
Because people are _constantly_ mixing the two chats up, mistaking cmd chat for ooc statements. Someone please just fix this.

### PR DESCRIPTION
**Pull request by ThatDan123**
-Changes OOC colour to be darker.
fixes #4101 

-Changes chat entries to use TMP

-Admins have a tag in OOC

image

image

### CODE REVIEW

**Comment by ThatDan123** [comment]
image

Had to comment this out for it to work as .GetGenerationSettings doesnt exist on TMP_Text, im unsure as to what the code does, but it seems to work without it.

**Comment by ThatDan123** [comment]
Dont merge just yet, someone who knows what the code does can you review the bit above.

**Comment by VernaSaurus** [comment]
THANK YOU

**Comment by Bod9001** [comment]
let's see how long this takes, shall I merge it?

**Comment by ThatDan123** [comment]
Im not sure, doobly might be a bit grumpy if i break things again.

**Comment by Bod9001** [comment]
yeah doolby  Said not to merge

**Comment by DooblyNoobly** [comment]
Hey @ThatDan123 the reason is because of the tmp.

quoting the discord message I sent ya:
```
you cannot use content fitter with TMP that is why its a regular text component
and I need to use content fitter to grow the chat entry based on text size
```

**Comment by ThatDan123** [comment]
Ah ok, sorry i couldnt find any message you sent me on discord. I'll close this and just do the admin tag and colour change.

**Pull request closed without merging**
