### PR TITLE
Unrealstation Sec and dorms tweaks + filled out nanomed vendor

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

This PR seeks to improve the usage of space in the center area of Unreal station. The Security department had lots of open, inefficiently used space and lacked some finishings such as an AmmoTech, lethals locker, doors to access rooms, and other stuff. The Dorms, library, and court room also had huge areas of under utilized space, all 3 being wide, narrow rooms that didn't leave a lot of space to actually do anything in them as so much room was designated for navigation. 

The redundant hallway between dorms and the library has been reworked into the new library and expanded dorms. Several other small changes and fixes were made to unreal across the station, like adding TinyFans to the arrivals shuttle so it does not instantly depressurize upon being opened.

Lastly, the NanoMed vendor has had several missing items added to it, so now it's actually useful.

### Notes:

- Security was rearranged and resized. The hallways to the east and west are now 3 tiles wide.
- the security brig comes with 3 additional brig cells, and they are much more efficiently sized.
- the armory has gained an AmmoTech and Lethals locker.
- Added doors to get into the armory.
- The court room has gained seating for observers and wastes less space.
- the detective's room has been shifted over and resized. it's original spot is a vacant spot of maintenance to be filled with something else in a future PR.
- The Library has been shrunken down without any loss of functionality.
- there's a reading and gaming area outside the dorms, now. The mini collection in the Detective's room has been moved to a table there.
- the dorms now have a foyer area with vendors and tables and seats.
- some small fixes to maintenance have been applied. frequency of rwalls has been reduced yet again.
- fluid carts that were in the dorms have been moved to the tool room.
- the tool room has been changed a bit superficially, but nothing has really changed about it's functionality.
- There's a large open space next to the tool room that will be filled with something in a future PR. Right now, it's just a waiting area with some plants and a water cooler.
- the NanoMed can dispense gauze, bruise packs, ointment, and other medical supplies, now.

### Changelog:

CL: [Improvement] Unreal station arrivals now has TinyFans to prevent depressurization.
CL: [Improvement] Unreal station security and dorms have been given lots of new furnishings, including 3 new brig cells.
CL: [Balance] NanoMed now comes with more than just syringes, making it an effective first aid vendor.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
so, I was having trouble testing the changes because something is very screwed up with Unreal. It would crash every time I tried to run the map. However, this problem doesn't seem to be a result of my PR to the best of my understanding, as it's fucked on staging right now and others have reported crashes with the map as well. Whether this should be merged or not, idk, I'm done dealing with this map for now.

**Comment by PerfectTangent** [comment]
here's the general makeover to the brig:

Screenshot 2021-09-24 190529

Dorms, courtroom, detective's room, and library changes:

Screenshot 2021-09-24 190456

and changes to the rest of sec:

Screenshot 2021-09-24 190607

**Review by corp-0 — APPROVED** [review]

**Comment by NoooneyDude** [comment]
Don't suppose you want to open a PR for the vendor changes?

**Comment by PerfectTangent** [comment]
yeah, I am working on it now.

**Comment by PerfectTangent** [comment]
got busy playing factorio, lol

**Comment by NoooneyDude** [comment]
> got busy playing factorio, lol

I completely understand 😂

**Pull request closed without merging**
