### PR TITLE
Refactor all uses of serializable dicts to make use of generics #7111

### LINKED ISSUE #7111: Refactor all uses of serializable dicts to make use of generics
### Description
Before Unity supported serializing generics, in order to use Serializable dictionaries we had to create child classes of a particular type pair and expose that class to the inspector. That is no longer needed and we can use ``SerializableDictionary<Type, Type>`` directly.

### To solve this issue
1. Add ``[Serializable]`` decorator to ``SerializableDictionary<TKey, TValue>``  from ``SerializableDictionary.cs``.
2. Find inheritors of ``SerializableDictionary<TKey, TValue>`` from ``SerializableDictionary.cs``.
3. Replace all inheritors usage with a direct usage of ``SerializableDictionary<TKey, TValue>`` from ``SerializableDictionary.cs``. For example, ``DemandDictionary`` from ``CargoBounty.cs`` replaced with ``SerializableDictionary<ItemTrait, int>``

### PR DESCRIPTION
**Pull request by davodico**
### Purpose
 <br>

Closes #7111, all inheritors usage are replaced with direct usage of SerializableDictionary<TKey, TValue> from SerializableDictionary.cs. Unused classes are removed.
### Notes:

No functionality was added it was just refactor.

### CODE REVIEW

**Comment by Bod9001** [comment]
just saying you have a few unneeded Meta Files, in your pr tho, most aren't too important apart from the
com.xeleh.enhancer/Settings.asset 
change, that's for the sidebar but that seemed to turn itself off constantly idk why does so

**Comment by davodico** [comment]
Yea, sorry about that I didn't notice it, anyway I added one extra commit with reverting my change in Settings.asset so it should be fine now.

**Comment by corp-0** [comment]
Looks good. Is the serialized data kept? As in, if a component used one of the custom dictionaries and had data set, do we keep the data or do we have to set everything again?

**Comment by davodico** [comment]
All original data are kept. It seems like unity saw the same data structure and kept original data without the need to rewrite them from my side. I was quite surprised about it because I was ready to rewrite them into a new field manually.

**Comment by corp-0** [comment]
Wonderful. Tests are failing though, would you mind downloading the zip with the results and check what is failing?

**Comment by corp-0** [comment]
can you confirm if tests are working locally for you? From what we can tell, it isn't compiling

**Comment by davodico** [comment]
The problem is with ReagentContainerTests.cs as in my version of code this whole class is commented so IDE wasn't showing usage of DictionaryReagentFloat. I removed this class and replaced other usages with direct usage of SerializableDictionary<TKey, TValue>.  I will try to change it also in commented code.

**Comment by davodico** [comment]
Well it isn't working it seems from the report: "Assets/Tests/Chemistry/ReagentContainerTests.cs(222,24): error CS0246: The type or namespace name 'DictionaryReagentFloat' could not be found (are you missing a using directive or an assembly reference?)"
that unit test needs to be changed using direct usage of "SerializableDictionary<TKey, TValue>" the same way I committed changes in this class.

**Comment by corp-0** [comment]
Can you edit the test? https://github.com/unitystation/unitystation/tree/develop/UnityProject/Assets/Tests/Chemistry

**Comment by davodico** [comment]
Yup, I made a stand-alone pull request for this change: https://github.com/unitystation/unitystation/pull/7854.

**Comment by davodico** [comment]
So, I closed #7854 and added all changes here, test passed so everything should be fine now. Waiting for review now.

**Review by Bod9001 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]
Thank you! There are a few unrelated file changes, try to avoid committing these next time : ) 

If you're thinking of contributing more and are on Discord ping me your username.

**Pull request merged**
