### PR TITLE
New held sprites for Security and Prototype Hardsuit Helmets and Bomb Hoods by Masada..

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR adds new held sprites for the Security Hardsuit Helmet, the Prototype Hardsuit Helmet, and all Bomb Hoods. **All credits for the sprites go to Masada on Discord.**

I also edited the Security Bomb Hood .prefab because it didn't point to the relevant sprite .asset file, oops.

### Notes:
~~There's also a bunch of random .meta changes and additions in this PR, but they should be harmless to include... should. I didn't intentionally stage them, they just appeared.~~ Not anymore.

### Please make sure you have followed the self checks below before submitting a PR:

- [ ] Code is sufficiently commented
- [ ] Code is indented with tabs and not spaces
- [ ] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [ ] The PR does not bring up any new compile errors
- [ ] The PR has been tested in editor
- [ ] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [ ] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [ ] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- [ ] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by ThatDan123** [comment]
You should only commit the metas of files youve changed.

**Review by RedlineTriad — CHANGES_REQUESTED** [review]
You have changes for meta files of files that don't even exist anymore on develop. Try to exclude non-relevant meta file changes in PRs.

**Comment by PetMudstone** [comment]
Alright, will do.

**Comment by PetMudstone** [comment]
Alright, I got rid of the extraneous files.

**Pull request merged**
