### PR TITLE
Client can mop, refactor FinishProgressAction to delegate to component

### LINKED ISSUE #1668: Mopping floors doesn't work for clients
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join steam server
2. Grab a mop
3. Try mopping blood

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #1668 

Refactors FinishProgressAction so that it isn't doing all of the actual logic of what happens at the end of every different kind of progress action. Instead, it invokes a callback so that the component that originally started the action can decide what to do - better separation of responsibility that way IMO.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### Notes:
I noticed an issue with tool->floor interactions where TileTrigger was "eating" interactions on the client side without doing anything - returning true from Interact even in cases where an interaction would've have actually occurred, and thus false should've been returned. I made a change to avoid that issue. I tested to see if interaction is still working fine but I'm not sure why that code was there to begin with and it seemed like it might've been a hack for something I'm unaware of. The code I changed seems to pertain to #1681 if you happen to know what the purpose of it was.

### CODE REVIEW

**Comment by fomalsd** [comment]
yep, that's pretty good, thanks!

**Comment by Aranclanos** [comment]
CanUse() broke and now vending machines and others that use it wont respond to clients

**Comment by chairbender** [comment]
ty @Aranclanos , I'll reopen the ticket and take a look

**Comment by chairbender** [comment]
@Aranclanos

I wouldn't call it broken. The only change I made was that it no longer has the side effect of sending an interaction message to the server when it is invoked on the client side. I removed this behavior because it doesn't make sense to have a method called "CanUse" which has a quite significant and undocumented side effect of performing network communication - the method was doing too much by having this side effect. CanUse should only be used to check if something is usable.

Please refactor your code to send this message in a different way.

In the meantime I will work on the other users of this method to ensure they do the same thing.

**Pull request merged**
