### PR TITLE
Clears receivers in signal manager at round end

### PR DESCRIPTION
**Pull request by MaxIsJoe**
This should be the last time tackling the signal manager getting bricked.

CL: [Fix] - The signal manager will now clear it's receivers list at the end of the round.

### CODE REVIEW

**Review by corp-0 — DISMISSED** [review]

**Comment by NoooneyDude** [comment]
This doesn't cover the case where someone adds a receiver after the round has ended but before restart.

**Comment by MaxIsJoe** [comment]
> This doesn't cover the case where someone adds a receiver after the round has ended but before restart.

what do you mean

**Comment by NoooneyDude** [comment]
> what do you mean

e.g. while the crew are at CentCom

**Comment by MaxIsJoe** [comment]
> > what do you mean
> 
> e.g. while the crew are at CentCom

what if you need to use the signal manager while the crew at are centcom?
what if the admin created a thing that requires signals and he was planning to trigger it before the round completely restarts?
what if a traitor had a bunch of explosions on him and he wanted to blow it up once the shuttle arrives?

I dont get why you want to signal manager to stop working when there's still gameplay going on; it should only clear it when the old receivers are no longer present in-game anymore because a new fresh round has started.

**Comment by MaxIsJoe** [comment]
It should also be noted that on some MRP and HRP servers people still roleplay even after the round has ended in centcom and the round end could go up to 3+ minutes for admins to wrap things up and for antags to pull out their last stunt. Stopping an entire system from working while people are playing is a bad idea.

**Comment by NoooneyDude** [comment]
You misunderstand me. You are clearing while players are still able to use the manager. They can still use it after the round has ended, (thus issue still exists). You want to clear the list when the scene is unloaded instead.

**Comment by MaxIsJoe** [comment]
> You want to clear the list when the scene is unloaded instead.

How do i do that?

**Comment by NoooneyDude** [comment]
> > You want to clear the list when the scene is unloaded instead.
> 
> How do i do that?

Hey Max. Sorry, this is partially my mistake. It turns out that the event is broadcast twice; once when the round ends and once just before the round restarts, which isn't good. Would you mind changing this by adding a `RoundRestarting` event and changing one of the broadcasts to broadcast this instead? 

`GameManager.cs` lines ~`567` ~`823` and `GUI_InGameMenu` line ~`201` (broadcast both events for the latter). You might need to check all the current listeners for the `RoundEnded` event and make sure they listen to the appropriate event.

**Comment by MaxIsJoe** [comment]
> GameManager.cs

Done.

**Comment by MaxIsJoe** [comment]
hewwooo? wewview pwease

**Comment by corp-0** [comment]
it looks fine, but Nooney was reviewing it

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
