### PR TITLE
Fix welding and other door interactions, eating bug

### LINKED ISSUE #3803: You are able to swap hands in middle of eating,
This causes the item you swap to to be replaced/Destroyed

### LINKED ISSUE #4074: Time to weld shut/open doors is static and not based on speed multiplier in the tool component.
### Description
As in the title, the time taken to weld doors shut or weld them open is fixed and not affected by the "Speed Multiplier" field in the "Tool" component that welders possess. I am certain that this should not the case.

### Steps to Reproduce
1.  Spawn a "WeldingTool" (speed 1), "ExperimentalWeldingTool" (speed 2), and "Speedy Welder" (speed 10).
2.  Test them on nearby walls to get a sense of how fast they work normally.
3.  Use them to weld shut and weld open doors and notice that they all take the exact same time to do so.

### PR DESCRIPTION
**Pull request by NoooneyDude**
- Fixes door welding, and other door interactions that hacking was stealing.
- Fixes #4074 - door weld times.
- Fixes #3803 - swapping hands while eating despawns actively held item

### CODE REVIEW

**Comment by NoooneyDude** [comment]
DNM, thought of a new case for me to test tomorrow.

**Comment by NoooneyDude** [comment]
Ready for review.

**Comment by DooblyNoobly** [comment]
Hey I tried in mp but couldn't weld a door with either host or client

**Comment by DooblyNoobly** [comment]
@NoooneyDude door interactions work now but on the client the melee attack for wrench doesn't work. It only works on host

**Comment by NoooneyDude** [comment]
Ready to merge. Tests failing for something unrelated in develop.

**Review by vlandemart — APPROVED** [review]
Seems to be working as intended, merging.

**Pull request merged**
