### PR TITLE
Headless Server Health Update Error Fix

### PR DESCRIPTION
**Pull request by ThatDan123**
-Fixes headless server error when trying to run client side health code

### CODE REVIEW

**Comment by Aranclanos** [comment]
wouldnt removing the [Client] fix that

**Comment by ThatDan123** [comment]
It would but then it would also run this which doesnt need to be run on a headless server.

`
CurrentHealthDollStorage = JsonConvert.DeserializeObject<HealthDollStorage>(healthDollData);
			for (int i = 0; i < CurrentHealthDollStorage.DollStates.Count; i++)
			{
				UIManager.PlayerHealthUI.bodyPartListeners[i].SetDamageColor(CurrentHealthDollStorage.DollStates[i].damageColor.UncompresseToColour());
				UIManager.PlayerHealthUI.bodyPartListeners[i].SetBodyPartColor(CurrentHealthDollStorage.DollStates[i].bodyPartColor.UncompresseToColour());
			}
`

**Comment by Aranclanos** [comment]
will the editor and non headless servers stop updating the doll color now?

**Comment by ThatDan123** [comment]
nope, as you connect as local host in editor so it would run the client hook

**Comment by ThatDan123** [comment]
I think...right?

**Comment by Aranclanos** [comment]
okay apparetly the server never sets DollDataChanged on his own character to true so the stuff in LateUpdate() doesn't even run so its irrelevant

**Comment by ThatDan123** [comment]
its set to true on line 142

**Comment by Aranclanos** [comment]
yeye but that function doesnt run if the PlayerHealthUI is the localplayer

**Comment by ThatDan123** [comment]
Yeah cus of the check in the PlayerHealthUI, it wont run on localplayer, but this still is syncing for other clients for their health updates so is still needed

**Comment by Bod9001** [comment]
do you need to add is server == false instead of the hook?

**Comment by Bod9001** [comment]
inside of the hook*

**Pull request merged**
