### PR TITLE
New wizard spell: Stunning Bolt, aka Thrown Lightning.

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

This PR adds the Thrown Lightning spell, renamed Stunning Bolt so as to be less ambiguous in relation to the other lightning spell. Stunning Bolt does exactly what it sounds like; It stuns someone. It's a useful spell for playing a pacifist or friendly wizard and should help vary up the possible play methods. Checks off one task from #5291.

### Changelog:

CL: [New] New defensive spell for wizards to learn: Stunning Bolt: The wizard casts a taser electrode to stun a target.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
Thanks for the wizard, @NoooneyDude!

**Comment by corp-0** [comment]
tests
```
StunningBolt (UnityEngine.GameObject) needs to be in the spawnPrefabs list and has been added. Since the list has been updated you NEED to commit the changed NetworkManager Prefab file
```

**Review by corp-0 — APPROVED** [review]

**Comment by PerfectTangent** [comment]
tests stalled out.

**Comment by PerfectTangent** [comment]
alright, it passed 3rd time.

**Pull request merged**
