### PR TITLE
Update bug_report.yml

### PR DESCRIPTION
**Pull request by Fr-Dae**
CL: [Fix] serveur options

### CODE REVIEW

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — CHANGES_REQUESTED** [review]
this is not what the options are supposed to mean

**Comment by Fr-Dae** [comment]
do you prefer, players, host headless, local host?

because that's exactly how people use this option. 

otherwise what's the use?

**Comment by corp-0** [comment]
The use is exactly what is says in the label. Were you the client or the host when the issue occured?

**Comment by Fr-Dae** [comment]
> The use is exactly what is says in the label. Were you the client or the host when the issue occured?

but there's a distinction to be made between 
- the client
- the headless which host + play, (error found via the server terminal or in joining game  in localhost)
- The LocalHost (game launched from the build in "host" mode and which closes as soon as the game closes)

these are the three different ways of connecting to the game, and some errors only occur in one of these modes. 

that's why I wanted to make this clear in the model

**Comment by MaxIsJoe** [comment]
Closing this after a brief discussion with other maintainers.
This PR is largely abandoned, and the changes are unnecessary because we do not look for issues with hosts playing on the same exact client they're hosting from (the host is not meant to play the game from the same hosting process anyways).

**Comment by Fr-Dae** [comment]
> the host is not meant to play the game from the same hosting process anyways

I'm sorry, what ? how does players who want to test in local solo mode be able to do so?

**Comment by MaxIsJoe** [comment]
You host an instance, then start another one that connects to the server.

**Comment by Fr-Dae** [comment]
> You host an instance, then start another one that connects to the server.

what you're saying isn't logical. 
a player wants to play solo or with a friend - he clicks on the [host] button.
Why should he have to do anything other than the button that is literally on the game menu?

**Comment by MaxIsJoe** [comment]
Because unitystation and ss13 are not a co-op games, and are not designed with that in mind.

**Comment by Fr-Dae** [comment]
they're not co-op? 
in other words? you mean that, although the game offers the possibility of playing by yourself, and hosting your own server locally, a user should not do this and ONLY 
connect to the EU-USA server to test the game? 

and if I only need to play with people on my local network, I'm not allowed to?

**Comment by MaxIsJoe** [comment]
You're only allowed to play the game on the same instance as the host because:

1. Unity never had the ability to launch more than one instance at a time without rebuilding the entire game every time you wanted to test a change.
2. Our project structure from the start was so bad, that the server and the client both were crammed together. (This is bad for a million different reasons for games like SS13)

The game offers this functionality as a side effect of a series of uninformed decisions and engine limitations. We never use the local instance of the host as a reflection on what happens in the game, because the server intentionally has various different behaviors - or are completely missing ones - to lower the processing requirement of unitystation (check #7226 for example)

If you run into an issue as the local host playing on the same instance, we have no clue if this issue is intended behavior or an actual issue; and even if its an actual issue, we don't want to waste our time fixing something that is not intended to be seen or experienced by other people in the first place.

Unitystation is a demanding game, this is why we always tell users to use docker and headless instances to give the server all the resources it needs. So understandably, we expect all servers to be hosted in a headless mode where the host can't play the game at all unless he connects to the server as a client.

**Comment by MaxIsJoe** [comment]
> and if I only need to play with people on my local network, I'm not allowed to?

No one is stopping you from playing the game the correct or wrong way. If you want to play on the same instance as the host, you are allowed to do so, even if it's not the intended way of playing.
Just don't clog our issue tracker with issues that are not worth our time because you peaked behind the curtains.

**Comment by Fr-Dae** [comment]
in the real world, there are three scenarios.

- The player connects to the server on the hub (e.g. USA) and plays.
- the player clicks on the "host" button and plays. (why not with friends on their local ip)

- the rare person who wants to do a serious project and offer performance to a dedicated computer to run the server to become host, 
they will be interested in a headless management, with or without docker. but this last category is only a tiny %, nobody does that, unless he really want to set up a private server.


to test a specific mechanism in a build it's much more practical to run it locally (selfhosted) with admin rights, do the test and give the result on discord/github

**Comment by MaxIsJoe** [comment]
In the real world:

A developer only tests the game from local host after making or testing a change, they see no issues, then merge it and then players discover later that headless and clients are broken and are unable to play the game properly, and we're forced to rollback to an older build immediately.

This is a scenario we ran into a million times, especially me and Bod. So I can confidently say that as someone who has worked on this project for more than 3 years at this point and has seen all sorts of issues this project has; your assumption of how things should operate is detached from how the project operates on every level.

What you *think* is practical does not align with how the game works. 

This discussion is getting locked 🔒.

**Pull request closed without merging**
