### PR TITLE
Show transparent overlay if item can or cannot fit in an item slot

### PR DESCRIPTION
**Pull request by StrawberryMoses**
### Purpose
Green or red transparent item shows in slot when hovering over it with an item in players hand. Does this for pockets, worn inventory, backpack slots

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Review by fomalsd — COMMENTED** [review]
very nice!  
there's one thing that newbies will find confusing – adjacent hand slot also lights up as green but just clicking it doesn't transfer item to another hand and changes slot instead (need to drag it over instead of clicking, and that's ok):
Scr 2019-10-12 в 15 46 36 mov
I don't know how this works in byond right now, but maybe just disable these overlays for hand slots?
Also I think byond overlays have lower transparency, maybe decrease it to like 70%? (~178 of 255)

**Comment by Bod9001** [comment]
yeah, It doesn't have it for Hand slots, the way you would swap with hands is swap to the other hand then click on the item in the other hand

**Comment by StrawberryMoses** [comment]
Changed to not display for hand slots. And 92% is correct, but i dunno if byond or anything changes it someplace else: 
Screen Shot 2019-10-09 at 1 08 36 PM

**Comment by fomalsd** [comment]
Sweet!
Got a feeling that it might be 92/255 or 92/127 in byond, that would explain higher transparency

**Comment by StrawberryMoses** [comment]
Looks like you were correct, changed it and it looks just about the same.

**Review by fomalsd — APPROVED** [review]

**Pull request merged**
