### PR TITLE
Chat Fonts

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Hi, been a bit busy with studying, so there has been a lack of PRs.. But don't worry, I've been working on a few things in the background in my free time, like part 2 of the sound expansion PRs.

- This PR is meant to address a common issue with some newer players (especially the SS14 folk) constantly complaining about unitystation's default fonts. This PR adds the ability for players to choose whatever TMP font we have available as their preferred font for chat text, and also fixes a few issues with the default font (like drop shadows being too strong)
- The Chat UI has also received some love, Players can now see up to 3 lines while typing! Unitystation is a role-playing game after all, so it makes sense to have players have the ability to see what they're typing.
- Default placeholder text is also added, giving new players some info on things like how to emote and how to speak over the radio.
- Good UX is when you organize stuff, so gameplay related buttons are now grouped together away from OOC related buttons in the Chat UI. They still live within the same list, but a little bit of organization helps with keeping things tidy and easy for player's to memorize.
- + some other smaller changes that other people may have overlooked back then. (Like how the scroll bar now no longer blends in with the chat background)

### Media:

image

### Changelog:

CL: [New] Added the ability for players to choose their own preferred font for chat in the options menu.
CL: [New] Added default/placeholder text for chat input.
CL: [New] You will now have a text indicator telling you in what channels you're about to speak in, and what identity you'll be presented as when speaking. 
CL: [Improvement] Chat Input now can now hold up to 3 lines, giving players more visibility and space on the text they write. 
CL: [Improvement] Improved chat input background colors for better visibility when writing.
CL: [Improvement] Removed an unused button that acted exactly like the prayer button.
CL: [Improvement] Chat buttons are no longer crammed within a small space, and are now represented as a list on the bottom right side of the chat window.
CL: [Fix] Clamped down the minimum allowed UI scales to avoid players giving themselves unplayable scales.
CL: [Fix] Fixed an issue with the chat scrollbar blending in with the background.
CL: [Fix] Several fonts now have fallbacks for non-latin text.
CL: [Fix] Fixed the default font's shadow being too strong, resulting in ugly text.

### CODE REVIEW

**Comment by AtnerNT** [comment]
Just from the screenshot it looks like the 'Pray' text is either a different font or font-style to the other side buttons. Would be nice to have these uniform

**Comment by MaxIsJoe** [comment]
> Just from the screenshot it looks like the 'Pray' text is either a different font or font-style to the other side buttons. Would be nice to have these uniform

Its the same font.
Old buttons use legacy font rendering, while this one is using TMP

**Comment by MaxIsJoe** [comment]
Moved all buttons to use TMP

**Comment by Bod9001** [comment]
any changes requested? from anyone

**Comment by corp-0** [comment]
Me personally, I don't like the positioning of the send and cancel buttons, since they don't communicate well with their position that they are sending or canceling the text in the input. 

Another nitpick, is how the languages button look with that amount of text. I understand the intention is for it to be instantly understood what it does, but it looks way too different.

**Comment by corp-0** [comment]
honestly, I don't think the new position of the buttons is better

image

If anything, at least leave send and cancel buttons where they are now

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
