### PR TITLE
Flora and Rocks Update Part 2

### PR DESCRIPTION
**Pull request by FuntimeDudeski**
### Purpose
- Replaces legacy plant/rock prefabs with their updated equivalents in all scenes
- Deletes legacy plant prefabs (except the Christmas Tree, which has a special script, and its parent prefab--This is left untouched in scenes)
- Updates the rock drop spell w/ the new random rock prefabs
- Fixes a couple missing descriptions

### CODE REVIEW

**Review by Bod9001 — APPROVED** [review]

**Comment by corp-0** [comment]
I saw you did Square and Unreal. If you plan to do a part 3 that includes Pog, please leave that map for later since we need to rescue #9764 first

**Comment by FuntimeDudeski** [comment]
> I saw you did Square and Unreal. If you plan to do a part 3 that includes Pog, please leave that map for later since we need to rescue #9764 first

Part 2 took care of all the remaining maps that needed anything. No Pog touching needed!

**Comment by AtnerNT** [comment]
Refactor your changes (PR description) in the below format, this lets our changelog bot record your changes.
Changelog:
CL: [Improvement] Replaces legacy plant/rock prefabs with their updated equivalents in all scenes
CL: [Improvement] Deletes legacy plant prefabs (except the Christmas Tree, which has a special script, and its parent prefab--This is left untouched in scenes)
CL: [Improvement] Updates the rock drop spell w/ the new random rock prefabs
CL: [Fix] Fixes a couple missing descriptions

**Comment by corp-0** [comment]
nah, it is fine. It isn't a change that players will notice.

**Pull request merged**
