### PR TITLE
Adds WizardAsteriod Scene

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Adds a Wizard spawn scene on an asteriod, so they'll be an option to spawn in on a ship or on a floating rock.

### Notes:
CL: Adds Wizard Asteroid Spawn Scene.

### CODE REVIEW

**Comment by Bod9001** [comment]
WizardSpawnPoint (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert

**Comment by ThatDan123** [comment]
If the scene is at 0,0 move it far away, thx

**Comment by NoooneyDude** [comment]
If something is at 0,0 local to the station and you want it there, you can just move it by 0.2 units to shut the alarm up - but yeah, make sure the root scene is not at 0,0 - something in the ~k range would be ideal - see the other additional scenes.

**Comment by Akbadain29** [comment]
That should be all good now.

**Pull request merged**
