### PR TITLE
Some light changes on OutpostStation

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Changes LightTubes for Command, LateSpawn and Arrivals on OutpostStation so it is dimmer. 

### Notes:
I'm doing it in stages so I don't miss anything. I'm doing Cargo, Engineering and Evac next.

### CODE REVIEW

**Comment by Bod9001** [comment]
cool, Will wait for Test to finish builds are broken

**Comment by Bod9001** [comment]
OutpostStation: "APC_Command_Hallway" has a null value in the list.
OutpostStation: "APC_Command_Hallway" has a null value in the list.
OutpostStation: "APC_Command_Hallway" has a null value in the list.
OutpostStation: "APC_Command_Hallway" has a null value in the list.
OutpostStation: "APC_Command_Hallway" has a null value in the list.
OutpostStation: "APC_Command_Hallway" has a null value in the list.
OutpostStation: "APC_Command_Meeting" has a null value in the list.
OutpostStation: "APC_Command_Meeting" has a null value in the list.
OutpostStation: "APC_Arrivals_Common_Right" has a null value in the list.
OutpostStation: "APC_Arrivals_Common_Right" has a null value in the list.
OutpostStation: "APC_Hallway_Command" has a null value in the list.
OutpostStation: "APC_Arrivals_Right" has a null value in the list.
OutpostStation: "APC_Arrivals_Right" has a null value in the list.
OutpostStation: "APC_Arrivals_Right" has a null value in the list.
OutpostStation: "APC_Arrivals_Right" has a null value in the list.
OutpostStation: "APC_Arrivals_Right" has a null value in the list.
OutpostStation: "APC_Hallway_Arrivalsright" has a null value in the list.
OutpostStation: "APC_Command_HOP" has a null value in the list.
OutpostStation: "APC_Command_HOP" has a null value in the list.
OutpostStation: "APC_Captain" has a null value in the list.
OutpostStation: "APC_Captain" has a null value in the list.
OutpostStation: "APC_Arrivals_Left" has a null value in the list.
OutpostStation: "APC_Arrivals_Left" has a null value in the list.
OutpostStation: "APC_Arrivals_Left" has a null value in the list.
OutpostStation: "APC_Arrivals_Left" has a null value in the list.
OutpostStation: "APC_Arrivals_Left" has a null value in the list.
OutpostStation: "APC_Arrivals_Left" has a null value in the list.
OutpostStation: "APC_Arrivals_Office" has a null value in the list.
OutpostStation: "APC_Captain_Study" has a null value in the list.
OutpostStation: "APC_Captain_Study" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_Bridge" has a null value in the list.
OutpostStation: "APC_Command_HOP_Study" has a null value in the list.
OutpostStation: "APC_Arrivals_Engineering (1)" has a null value in the list.
OutpostStation: "APC_Arrivals_Engineering (1)" has a null value in the list.
OutpostStation: "APC_Arrivals_Engineering (2)" has a null value in the list.
OutpostStation: "APC_Arrivals_Common" has a null value in the list.

**Comment by corp-0** [comment]
the test result means you forgot to link said lights

**Comment by Akbadain29** [comment]
I've forgotten to delete the references on the APCs to the lights I deleted, I'd better fix that.

**Comment by corp-0** [comment]
You're still missing some light references

```
OutpostStation: "APC_Command_Meeting" has a null value in the list.
OutpostStation: "APC_Command_Meeting" has a null value in the list.
OutpostStation: "LightTube (38)" is not assigned to "APC_Captain_Study"
OutpostStation: "MedicalRecordsConsole (1)" is not assigned to "APC_Command_Bridge"
[Tests] All APCs count: 389
[Tests] APCs with empty lists count: 0
[Tests] APCs with nulls in the list count: 2
[Tests] APCs with not assigned devices to it count: 3
```

**Pull request merged**
