### PR TITLE
Shutters added to HoP and Captains quarters windows

### LINKED ISSUE #3030: [SUGGESTION] Add shutters to close infront of HoP windows.
Add shutters that close in front of the HoP's windows when the side panel is pressed. Time and time again some naked man with a crowbar smacks through the front windows then the inner windows without much resistance at all.

This could similarly be applied to other areas such as the Captain's quarters for a pseudo lockdown mode.

### PR DESCRIPTION
**Pull request by Raptorizer**
# Pull Request Template

### Purpose
Adds extra security to the captains quarters and HoP room
 Fixes #3030 
### Notes:
F9naA
lSqHahX3DJ

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by Misterixmax** [comment]
Bad idea adding button to the window, better place it òn the wall near other one. Haven't seen in TG buttons on the windows cause it's not realistic. Also because windows usually get destroyed more often than walls statistically.

**Comment by Evan-R-Rogers** [comment]
I love it!

**Comment by Raptorizer** [comment]
> Bad idea adding button to the window, better place it òn the wall near other one. Haven't seen in TG buttons on the windows cause it's not realistic. Also because windowses usually get destroyed more often than walls statistically.

I know but due to THIS bug:
Unity_XQk1GytlaF
Unity_Ec6eBtLPNE

Both  of the buttons are stick under each other

There is no other good place to put it that is within tile reach of the Hop Counter, if there is about to be an issue, Hop can close the shutters on the window and deny their attempts to smash the window.

**Comment by Misterixmax** [comment]
@Raptorizer write an issue about buttons, posters, apcs,  fire extinguishers and all the other small stuff like items to be possible to have a non centered on tile positions. It's actually a huge problem for mapping. In original game it was possible to configure the pos offset of every object on a tile. If it was moved too far from initial tile - it snaps to another tile. We need such system.

Upd: Ahh ok, it works actually.

**Pull request merged**
