### PR TITLE
Includes Palette editor, documentation, and some fixes for use in more systems

### PR DESCRIPTION
**Pull request by Ruzihm**
Adds tool and documentation used for making, editing, and using paletteable sprites. See: #3153 and #3289 

Makes palette apply to action buttons.

Fixes regression on palette not applying to other UI icons.

### CODE REVIEW

**Comment by Bod9001** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ UnityProject/Assets/Scripts/UI/Systems/MainHUD/UI Bottom/UI_ItemImage.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/unitystation/unitystation/pullRequest?prid=6374732&bid=20683015)

**Comment by corp-0** [comment]
Wonderful, thank you very much.

**Comment by corp-0** [comment]
pdGbFOb
buttons look like this after merging. Can you give it a look?

**Comment by Ruzihm** [comment]
Yes. Shouldn't be a difficult fix. Will look later today.

**Comment by Ruzihm** [comment]
@corp-0 Please see #5379 for fix!

**Pull request merged**
