### PR TITLE
Pre-round character creator

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
Gives the character creator a big clean up and adds some more groundwork for job preferences.

- Made character creator independent of LobbyManager and added it to the pre-round window
- Moved character settings and a bunch of other classes/enums to separate files
- Made serialisation work for job preferences
- Added job description hover window to job prefs
- Removed underwear options for opposite genders and stopped females having facial hair
- BIG refactor of PlayerCustomisationData
  - Made it use the SOSingleton class and removed a bunch of duplicate versions of it
  - Re-organised the SOs into their own folders
  - Fixed the naming of the customisation options

Most of #3266 is finished now, still need antag prefs

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [ ] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [ ] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- [ ] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
@Jibbajabbafic its still failing tests. Can you look into that please

**Comment by Jibbajabbafic** [comment]
@DooblyNoobly do you know who made the color picker? I can't apply this override to the prefab and the texture doesn't seem to exist.
image

**Comment by corp-0** [comment]
> Removed underwear options for opposite genders

Why? I want to look pretty

**Comment by Jibbajabbafic** [comment]
> Why? I want to look pretty

Just copying how it is in /tg/

**Comment by Jibbajabbafic** [comment]
Right I might have to redo the color picker because it has some fucked up texture shit going on

**Comment by Jibbajabbafic** [comment]
Added a new color picker, hopefully that resolves the weird texture bugs
image

**Comment by DooblyNoobly** [comment]
tests are still failing my dude. Go to Windows > General >Test Runner in the editor to see what is failing

**Comment by DooblyNoobly** [comment]
ok its passing now

**Pull request merged**
