### PR TITLE
Performance benchmarks

### PR DESCRIPTION
**Pull request by RedlineTriad**
### Purpose
Add automated performance benchmarks for more objective and reproducible metrics.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### CODE REVIEW

**Comment by fomalsd** [comment]
Could someone check this out please? Can't download that benchmark package due to proxy

**Comment by chairbender** [comment]
@RedlineTriad really cool stuff!

I ran the Electrical test but I can't seem to view the report. When I click "Open Benchmark Report" it gives me the below error. Am I missing some step?

DirectoryNotFoundException: Could not find a part of the path 'C:\Programming\IntelliJProjects\unitystation\UnityProject\UnityPerformanceBenchmarkReporter\UnityPerformanceBenchmark'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.Directory.InternalGetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.DirectoryInfo.GetFiles (System.String searchPattern) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.DirectoryInfo.GetFiles () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFiles()
PerformanceBenchmarkReport.OpenBenchmarkReport () (at Assets/Scripts/Editor/PerformanceBenchmarkReport/PerformanceBenchmarkReport.cs:27)

**Comment by chairbender** [comment]
Also I get this in the console when running "Regenerate Benchmark Report", not sure if this is expected:

Microsoft Windows [Version 10.0.17763.437]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Programming\IntelliJProjects\unitystation\UnityProject>cd C:\Programming\IntelliJProjects\unitystation\UnityProject\UnityPerformanceBenchmarkReporter

C:\Programming\IntelliJProjects\unitystation\UnityProject\UnityPerformanceBenchmarkReporter>dotnet UnityPerformanceBenchmarkReporter.dll --results="TestResults" --baseline="BaselineResult.xml" 

C:\Programming\IntelliJProjects\unitystation\UnityProject\UnityPerformanceBenchmarkReporter>
UnityEngine.Debug:Log(Object)
PerformanceBenchmarkReport:RegenerateReport() (at Assets/Scripts/Editor/PerformanceBenchmarkReport/PerformanceBenchmarkReport.cs:99)

**Comment by DooblyNoobly** [comment]
Would merging this PR in its current state cause any bugs to the actual game? If it doesn't then we should merge it and create separate issues for the bugs.

**Comment by RedlineTriad** [comment]
I made some improvements and a [video ](https://www.youtube.com/watch?v=Nko31XP6koM&feature=youtu.be)on how to use them.

**Comment by chairbender** [comment]
No, it should't cause any bugs for gameplay from what I saw when I reviewed it. I'll go ahead and merge.

**Pull request merged**
