### PR TITLE
Unity Upgrade

### LINKED ISSUE #3844: Upgrade Unity Editor to 2019.3.8f1 B:100
## Criteria:

- Upgrade the project to Editor version 2019.3
- Resolve all errors caused by the upgrade
- Fix the Tilemap errors caused by the upgrade
- Test in multiplayer with 2 clients
- Update the automated GitHub builds and tests to work with the new version

Contributor who has a PR that has been successfully merged to solve the criteria points above will receive the 100usd bounty via paypal

### PR DESCRIPTION
**Pull request by ThatDan123**
~Upgrading to 2019.3.7f1~ The future is now old man, going to 2019.3.8f1!

fixes #3844

- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.

### CODE REVIEW

**Comment by ThatDan123** [comment]
Just got to do the github test stuff and test it.

**Comment by ThatDan123** [comment]
Think its ready.

**Comment by corp-0** [comment]
:o

**Comment by ThatDan123** [comment]
Doobly if this gets merged i'll accept $50 not $260, as the learning experience of assembly references is worth the $210 by itself.

If CodeKalias or Jibby or Redline want money put on a bounty please use the money that would have been given to me.

**Comment by DooblyNoobly** [comment]
> Doobly if this gets merged i'll accept $50 not $260, as the learning experience of assembly references is worth the $210 by itself.
> 
> If CodeKalias or Jibby or Redline want money put on a bounty please use the money that would have been given to me.

god bless ya

**Comment by DooblyNoobly** [comment]
I've merged it to 20193 branch. The prefabs seem to of lost their references. So not sure what is going on there

**Comment by DooblyNoobly** [comment]
my mistake. Looks like everyone might need to nuke their library folder when upgrading. CodeKalias has taken over getting the rest of the update done so I'll split a $100 bounty between both of you when he is done

**Pull request merged**
