### PR TITLE
Removing VS Code plugin because it's redundant

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
Unity now supports VS code natively and so this plugin is no longer necessary.

It hasn't been updated in a long time and the debugger still works without it so the only feature it really adds is auto opening VS code.

We can leave it in if people really want to keep it around though.

### CODE REVIEW

**Comment by fomalsd** [comment]
I don't mind, any VSCode users have a different opinion?

**Comment by DooblyNoobly** [comment]
alrighty! As long as vscode works as usual I'm happy

**Comment by Aranclanos** [comment]
should the `UnityProject/Assets/Plugins/Editor.meta` change be there?

**Comment by Aranclanos** [comment]
anyways tested locally and vscode seems to be working fine

**Comment by fomalsd** [comment]
aight, merging

**Pull request merged**
