### PR TITLE
Adds LazyFindObject helper

### PR DESCRIPTION
**Pull request by Copern**
Pulling some random stuff out into small PRs. Nothing fancy here, just converting the constant Instance null check + FindObjectOfType into a helper method.

### CODE REVIEW

**Comment by Copern** [comment]
No codacy, I will not change it.

**Comment by Copern** [comment]
Out of curiosity, some of these are MonoBehavior managers. Any reason they don't use the SingletonManager?

**Review by ThatDan123 — COMMENTED** [review]
These should eventually be changed to SingletonManagers<> but there's something weird initialisation issues (being null even though being set in awake in the base class) so they've been kept on the old find object method. Thx anyway for cleaning those up.

However i'm sorta agreeing with the issue codacy, i wouldnt have thought you'd need to use ref for reference types?

**Comment by Copern** [comment]
If you simply pass the object (pass by value), then it would set the local value (if it's null) instead. The object's instance field would never change. We want to set the reference of what we pass in instead.

**Review by ThatDan123 — APPROVED** [review]
Yeah, just one of those situations that doesn't happen often then.

**Pull request merged**
