### PR TITLE
Staging fixinng five

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [Fix] Fixes Scrubber Surge event
CL: [Fix] fixes not being able to walk past conveyoor belts switch

### CODE REVIEW

**Review by MaxIsJoe — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
tests

**Comment by corp-0** [comment]
> Fixes Scrubber Surge event

what did you fix?

**Comment by Bod9001** [comment]
Before it just didn't work , Since the reagents were incorrect/missing

**Comment by corp-0** [comment]
```
Unhandled log message: '[Error] Problem detected while opening the Scene file: 'Assets/Scenes/AdditionalScenes/CentCom.unity'. Check the following logs for more details.'. Use UnityEngine.TestTools.LogAssert.Expect

```

**Pull request merged**
