### PR TITLE
Adds posters

### PR DESCRIPTION
**Pull request by StrawberryMoses**
### Purpose
Adds placeable and removable posters to the station. A few posters were placed in maint, and a "Love Ian" poster is in the HoP office. Posters can be ripped down or cleanly taken down with wirecutters.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Object-Lifecycle-Best-Practices)
- [ ]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
On tg, there's an animation when placing posters. Honestly... I didn't want to figure it out and I was getting a little bored of this one. Right now posters are just placed instantly.

### CODE REVIEW

**Review by fomalsd — CHANGES_REQUESTED** [review]
1) There are scene conflicts, looks like you'll have to pull and map changes again
2) Poster sprite inside prefab has a zoom factor of 0.7x which never looks pixel perfect. Please set it to 1x.
3) Posters placed ingame from Rolled poster look like they're already removed
GIF
4) It would be nice if existing unitystation posters shared the same behaviour, otherwise people will get confused

**Comment by fomalsd** [comment]
I figured out why they spawn ripped – Rolled Poster prefab has "Ripped" variant selected

**Comment by fomalsd** [comment]
anyway, are placed posters supposed to show custom name and description when hovered?
at the moment they just display Poster (Clone)
img

**Comment by fomalsd** [comment]
Also initial integrity of 20 instead of 100 would be a nice touch

**Comment by StrawberryMoses** [comment]
Reminder from discord to add the unity station posters to the json, and scale them to 1x instead of 0.7x

**Comment by DooblyNoobly** [comment]
Problems now with OutpostStation scene. I'd suggest taking the code + prefabs from this and start a new branch. Would love to see this merged soon. @StrawberryMoses eta when it will be done?

**Comment by StrawberryMoses** [comment]
Been a bit swamped with work, but I'm still hoping to take a look this afternoon or tomorrow

**Comment by StrawberryMoses** [comment]
- Scene has been remapped
- Changed sprite to be 1x
- Added unity station poster sprites and removed unity poster prefabs

Unity station posters take up the whole tile now. Not sure if that's desired or not

**Comment by fomalsd** [comment]
unitystation_posters
seems like you forgot to replace branded posters with these smaller ones

**Comment by fomalsd** [comment]
Also rolled poster prefab still defaults to Ripped
Scr

**Comment by StrawberryMoses** [comment]
Hm, I took the icons from the folder and adjusted them to import same as the other posters... I can fiddle with it some more. I'll change the poster variant for rolled to be a random poster

**Comment by fomalsd** [comment]
I mean these are different to existing ones – smaller, no longer occupying the entire tile height

**Comment by StrawberryMoses** [comment]
Alright- replaced. They should be the same as the other posters. (hopefully, I didn't notice too much difference- they at least look to be the same size in comparison). Spawning a rolled poster now gives a random poster which becomes any available.

**Review by fomalsd — APPROVED** [review]
sweet!

**Pull request merged**
