### PR TITLE
New gizmos to aid mapping: Disconnected from APC and no doors in door switch

### PR DESCRIPTION
**Pull request by corp-0**
## Includes:
Warning icon when device is not connected to any APC
image

Warning message when device is not connected to any APC
image

Button to auto connect the device to closest APC
GIF 26-09-2020 23-45-29

Warning Icon for door switches that have no doors or are missing a door in their list.
image

## Notes:
Manipulating the Related APC of a particular device can only be done now using the selection button in the APC. The devices only show if they are connected or not since manually adding or removing APCs directly in the object could have ended in unexpected behavior from the APC not updating its list.

Feel free to change the icons if you guys want.

### CODE REVIEW

**Comment by corp-0** [comment]
I will see if I can add more improvements before making it ready for review

**Comment by corp-0** [comment]
conflicterino D:

**Comment by Bod9001** [comment]
oh god, the merge conflicts

**Comment by corp-0** [comment]
I'll leave the mapping cleaning for later. Let me solve conflicts and merge the gizmos as is.

**Pull request merged**
