### PR TITLE
Make switching on lights more visually pleasing

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Improvement] There is a small delay on light switches affecting its connected light bulbs, making them more visually pleasing when turning on/off.

### CODE REVIEW

**Comment by Bod9001** [comment]
What about loss of power?

**Comment by MaxIsJoe** [comment]
> What about loss of power?

there isn't even anything remotely in this PR that changes how power stuff is handled

light source handles that, we don't change anything about it

**Comment by Bod9001** [comment]
I think light switches get turned off when power goes off

**Comment by Bod9001** [comment]
also did you check that the  state of the  lights aren't  synchronised  already, since you added a hook on the synchronisation of the light switch

**Comment by MaxIsJoe** [comment]
I literally did not change anything, I just added a delay to the invocation

**Comment by MaxIsJoe** [comment]
image

**Comment by MaxIsJoe** [comment]
> since you added a hook on the synchronisation of the light switch

where in this PR did I add a syncvar, or any networking related changes.

**Comment by Bod9001** [comment]
ok, still the issue with light switches though, powering off

**Comment by MaxIsJoe** [comment]
> ok, still the issue with light switches though, powering off

If it was an issue, we would have noticed it long before I made this change.

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
