### PR TITLE
made plasma from plasma canisters colder so it won't catch on fire

### PR DESCRIPTION
**Pull request by Bod9001**
### what this do?
made plasma from plasma canisters colder so it won't catch on fire, and A lot of players are complaining about people who rush atmospherics to get the plasma ccanisters to burn everything down
### why you do this?
so it won't catch on fire
### what have you changed?
 plasma canisters
### what you tested?
editor

### CODE REVIEW

**Comment by AnimatedTanker** [comment]
> 
> ### what this do?
> 
> made plasma from plasma canisters colder so it won't catch on fire
> ### why you do this?
> 
> so it won't catch on fire
> ### what have you changed?
> 
> plasma canisters
> ### what you tested?
> 
> editor

This is very needed as it can stop plasmagriefers until we can get true moderation

**Comment by urbanawakening** [comment]
For the love of god, I beg you merge this.

**Comment by hecksadecimal** [comment]
Please. Please merge this.

**Comment by DooblyNoobly** [comment]
This is not the way to address the problem of plasma fires. The canisters need to be in a more secure lock up. The plan is to move atmos to a more secure location in the south west corner of outpost. Maybe even have a security post to guard it as well. We also need to reduce the amount of plasma canisters on the station which will help curb the massive station fires.

**Comment by Misterixmax** [comment]
@dooblynoobly +++++ agree

**Pull request closed without merging**
