### PR TITLE
More Hardsuits (and Softsuits)

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR adds several Hardsuits, including the:
- Captain's SWAT Suit
- Engineering Hardsuit
  - Atmospherics Hardsuit
  - Advanced Hardsuit
- Medical Hardsuit
- Prototype Hardsuit
- Security Hardsuit
  - Head of Security's Hardsuit
- and all associated Helmets.

Also added are the EVA Suit and generic Space Suit (also their helmets)
**All are EVA-capable** like the already-existing Mining and Blood-Red (Syndicate) Hardsuits.

### Notes:
I carried over protection stats and resistances from /tg/station for the new spacesuits, but every suit (and helmet) ought to be practically the same.
All hardsuit prefabs (excluding the soft spacesuits) are located in "Hardsuits" under "Outerwear" as per usual. 
I also created a new "HardsuitHelmets" folder under "Headwear" where all prefabs for hardsuit helmets (including the pre-existing Mining and Syndicate helmets) are now located.

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by fomalsd** [comment]
what happened to this PR? it looked fine and then there are a bunch of conflicts from nowhere and 2x files

**Comment by PetMudstone** [comment]
I have no idea what the hell happened either, beginning process of cleanup.

**Comment by fomalsd** [comment]
maybe it would be a better idea to go back in history than trying to manually delete things with a risk of an oversight?

**Comment by Robustin** [comment]
Man I just opened a branch and start on this yesterday, took me a while just to get 1 done. Were there any shortcuts or did you end up having to move a boatload of files around manually?

**Pull request closed without merging**
