### PR TITLE
Improves the addressable picker

### PR DESCRIPTION
**Pull request by Bod9001**
image

how it looks now

image

### CODE REVIEW

**Comment by Bod9001** [comment]
thanks for @MaxIsJoe  For finding the Unity selector  Video

**Comment by MaxIsJoe** [comment]
> thanks for @MaxIsJoe For finding the Unity selector Video

image

**Comment by corp-0** [comment]
Don't comment code, just remove it

**Comment by Bod9001** [comment]
ok

**Review by NoooneyDude — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
