### PR TITLE
Fix wood and reinforced table construction

### PR DESCRIPTION
**Pull request by NoooneyDude**
- Wood and reinforced tables are now constructable and do not turn into glass tables.
- Removes most instances of magic prefab strings in favour of inspector fields.

### CODE REVIEW

**Comment by Bod9001** [comment]
looks good, some of these Could have Used the common prefabs SO instance

**Comment by NoooneyDude** [comment]
Oh, I had no idea. I'll update them.

**Comment by Bod9001** [comment]
is ok ,quite   obscure it is

**Comment by NoooneyDude** [comment]
Updated. Ready for review.

**Pull request merged**
