### PR TITLE
Addition Of BoxStation.

### PR DESCRIPTION
**Pull request by ThatDan123**
Cus my other branch broke :(

### Purpose
Adds BoxStation to the map pool.

Trying to keep it as authentic as possible, but some changes will need to be made.

### Notes:
Still Under Active Development

This PR is to list how far along the mapping is and to list anything that needs to be added for the map to be complete.

- [x] Base,Walls and Full Tile Windows

- [x] Wiring
Done, though could do with a clean up in some areas
- [x] APCs
Done and name labeled too
- [x] 0.4 Atmos
Done, ~~though the central hallway is depressurised just need to find leak.~~
- [x] Ian added.
- [x] Set up Solars
Solar locations mapped, solar panels not added. 
- [x] Lockers
All lockers put in right place, needs some touching up and items assigned fully. Most items assigned.
- [x] Items
Lots of items added, loads to go.
- [x] Other objects
- [x] Machines/Consoles
- [x] EscapeShuttle needs to be able to set destination of escape/centcom.
Needs a custom script created.
- [x] Adjust Map to allow for movable shuttles, ie fix cargo and escape.
Cargo Shuttle needs new script to dock as for some reason the shuttle moves one tile backwards when it stops.
Mining Has been moved to above arrivals for shuttle space.
- [x] Lighting
Lighting is very buggy atm, hard to work with so i've stopped.
Needs a rework, and the ability for lights to function without switches.
50% complete, all lights are in position, just needed reworking light scripts.

- [x] Shutters and BlastDoors
Most shutters are in position, but their buttons need access restrictions.
Only bridge needs doing, waiting for maybe blastdoor sprite.

TODO: After Merge

- [ ] Floor Tiles
Mostly Done missing one or two textures, see: https://github.com/unitystation/unitystation/pull/3050#issuecomment-584826812.

- [ ] Doors
Lots of missing sprites, need see through and non-see through versions of all doors + special doors such as vault and AI, see: https://github.com/unitystation/unitystation/pull/3050#issuecomment-584828758.
Also glass window doors need to have their collision boxes fixed.

- [ ] Asteroid spawn prevention, stop them spawning on the station
While funny, needs fixing

- [ ] Side Windows
Optional, but would be very nice to have.
- [ ] Fire doors
When the PR is done, also optional.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] UPDATE OTHER MAPS TO SUPPORT NEW SHUTTLESCRIPT

- [x] - The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>

- [x] - The PR has been tested in editor

- [ ] - The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

- [ ] - The PR has been tested with round restarts.

- [x] - The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

Picture as of 15/02/2020:

image

### CODE REVIEW

**Comment by ThatDan123** [comment]
Actually now ive got problems to fix. Damn unity taking an hour to load

**Comment by ThatDan123** [comment]
image

Getting these errors when on outpost

**Comment by ThatDan123** [comment]
And these errors on box

image

**Comment by ThatDan123** [comment]
Fixed Spawn Points so the game actually works, If you change the amount of spawnpoints remember to update the prefab ffs.

**Comment by ThatDan123** [comment]
Anyway its ready to merge, those other errors above are also in the main develop so its not a problem with this branch.

**Comment by Robustin** [comment]
Thank you for this, must've been an ordeal.

**Comment by DooblyNoobly** [comment]
This must of taken you ages! Amazing work. There are things that need to be tweaked but they are small touch ups we can do in another pr. Thank you for doing this.

**Pull request merged**
