### PR TITLE
makes wrapping paper wrap an object with alt-click

### LINKED ISSUE #6840: Cannot put wrapping paper inside a backpack or any other wrappable container
### Environment
- Game Version: latest

### Detailed description of bug

if you try to place a roll of wrapping paper inside a backpack on help intent, you begin to wrap the backpack, even if the backpack is equipped. If you use any other intent, nothing happens.

### Steps to reproduce

1. get a roll of wrapping paper
2. try to put it in the backpack
3. observe how none of the intents have the desired effect of stowing the wrapping paper in the backpack.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Adds in the fix that was suggested in #6840

CL: [Fix] made wrapping paper wrap an object with alt-click to fix an interaction conflict with containers.

### CODE REVIEW

**Comment by corp-0** [comment]
I would append the alt click check to the rest of the return statement

**Comment by MaxIsJoe** [comment]
> I would append the alt click check to the rest of the return statement

I personally think it's best to not call any extra checks if the main requirement is not met, just a tinsy smol performance squeeze.

**Comment by corp-0** [comment]
yeah, that's what you do with ``&&``. If the first condition isn't true it won't try the second one

**Comment by MaxIsJoe** [comment]
done

**Review by Bod9001 — DISMISSED** [review]

**Review by vlandemart — DISMISSED** [review]

**Comment by corp-0** [comment]
Please don't do == true, == false is ugly enough

**Comment by corp-0** [comment]
Also tests be failing

**Review by corp-0 — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
