### PR TITLE
Fixed Head Doors

### PR DESCRIPTION
**Pull request by Zealwarrior**
Changed the Captain's Door, CMO's Door, and HoP's door to their respective access restrictions on OutpostStation

I tested the captain's door and HoP's door using the CMO Card, and used the HoP for the CMO door.

In response to issue #1781

### CODE REVIEW

**Comment by Bod9001** [comment]
good job ^^

**Comment by Bod9001** [comment]
I think the big differences from That they didn't have it setup with github originally and downloaded it and  modified it, then Copied it over to update the github fork, but git Doesn't like it being copied for some reason, It should be ok,  To merge Since it will fix the issue of copying it Other times When someone needs to manually override their Outpost station

**Comment by fomalsd** [comment]
Yeah, it fixes access for captain/HoP/CMO, but detective still doesn't have maint door access and sec officers don't have red airlock access (see my comment in #1781)
There might be more oversights in door access settings

**Comment by DooblyNoobly** [comment]
Hey @Zealwarrior would you be able to look into the access problems with sec and detective as well? You can make the changes and commit to your fork and it will update the PR here automatically.

**Comment by Zealwarrior** [comment]
I could try

**Pull request merged**
