### PR TITLE
Adds the Crewsimov module for the AI

### PR DESCRIPTION
**Pull request by AzzyIsNotHere**
### Purpose

This adds the Crewsimov lawset module to the game, and places it on BoxStation, FallStation, and SquareStation.

### Changelog:

CL: [New] Adds the Crewsimov lawset module to the game
CL: [New] Places the Crewsimov module on BoxStation, FallStation, and SquareStation
CL: [Improvement] Improves the Asimov lawset, changing it from "A robot may etc." to "You may etc."

### CODE REVIEW

**Comment by corp-0** [comment]
remove the bold and ``-`` from the changelog lines to make pr2changelog pass, otherwise it will fail. This is to ensure we have a standardized format we can easily parse later.

**Comment by AzzyIsNotHere** [comment]
> remove the bold and `-` from the changelog lines to make pr2changelog pass, otherwise it will fail. This is to ensure we have a standardized format we can easily parse later.

gotcha, done

**Comment by Cboyjet4** [comment]
Yes! Crewsimov is much better than stinky asimov

**Comment by waffielz** [comment]
more like lame-imov

**Pull request merged**
