### PR TITLE
Mod tool for max

### PR DESCRIPTION
**Pull request by Bod9001**
max most properly wants to work on this more

### CODE REVIEW

**Comment by corp-0** [comment]
If this is the same mod tool I suggested time ago, then it has a github repo and can be installed using the unity package manager

**Comment by Bod9001** [comment]
This was installed via a unity package

**Comment by corp-0** [comment]
But this pr is pushing the downloaded files

**Comment by MaxIsJoe** [comment]
There;s one important question:
Currently, the ModTool is incredibly slow because Unity takes forever to create the Exporter/Mods with how big our project is right now and can take hours on older hardware; which makes it very inefficient and unintuitive to use.

Should we fork our own repo of ModTool and fix this by zipping the essential contents instead of relying on unity's very slow importer?
We still have to modify ModTool either way to use whitelists instead of blacklists, so a fork would make more sense for us.

**Comment by Bod9001** [comment]
a Forking sounds like a good idea

**Comment by corp-0** [comment]
yes, forking was in my plans

**Pull request closed without merging**
