### PR TITLE
Make debug log more usable

### PR DESCRIPTION
**Pull request by christmoore**
### Purpose
_Fixes issue #1472_<br>
_Implements a new console logger and removes the previous one. This new logger allows us to filter through informational messages, warnings, and errors, as well as provide input to the console to run console commands during runtime._

### Open Questions and Pre-Merge TODOs

* [x]  This fix is tested on the same branch it is PR'ed to.
* [x]  I correctly commented my code
* [x]  My code is indented with tabs and not spaces
* [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
* [x]  This PR does not bring up any new compile errors
* [x]  This PR has been tested in editor

Not tested in multiplayer due to no direct multiplayer impact.

.meta changes include necessary .meta changes from asset import
Manager.prefab changed to remove previous logger within UIManager object.
Lobby.unity scene changed to include IngameDebug

### Notes:

F5 to open/close the logger console window

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Did you submit this using unity 2018.3? All the prefabs are missing in the lobby scene:
image

**Comment by DooblyNoobly** [comment]
I also noticed in your GIF that you are using F5 to open the actual console. F5 should be used to toggle the whole system not for switching between the small notification pop out and the console itself. We don't want the notification bar on by default as this system will be in the steam builds.

**Comment by christmoore** [comment]
I should be sticking with 2018.2? The wiki states `Note that you should use Unity 2018.2 and above as of 01.08.2018.`, so I assumed that 2018.3 was fine. I will close and rework using the earlier unity version

**Comment by fomalsd** [comment]
Actually we're moving to 2018.3 the day after tomorrow, so you can just keep this open for a few more days and we'll re-review it after update

**Comment by christmoore** [comment]
Alright! I will fix the console F5 implementation and we can hold off until then.

**Comment by christmoore** [comment]
F5 implementation now shows/hides the popup window during runtime, and will close the log window if it is opened as well.

**Comment by christmoore** [comment]
This should be ready now to be merged once 2018.3 comes along. Let me know if there's any issue.

**Comment by DooblyNoobly** [comment]
cool thanks

**Comment by DooblyNoobly** [comment]
Looks good! I might play around with the GUI and fonts after I merge this.

**Pull request merged**
