### PR TITLE
Fixes emote sounds being global

### PR DESCRIPTION
**Pull request by MaxIsJoe**
title

CL: [Fix] Fixed emote sounds being global. No more screams of the damned.

### CODE REVIEW

**Review by NoooneyDude — DISMISSED** [review]

**Comment by Fr-Dae** [comment]
if you can add a craft and an object
to be able to gag/muzzle someone.

to silence the prisoners without having to knock them out.

**Comment by MaxIsJoe** [comment]
> if you can add a craft and an object to be able to gag/muzzle someone.
> 
> to silence the prisoners without having to knock them out.

The muzzle is already something in-game that should be mapped into the security department, i don't have any plans to add a crafting recipe for them and if i wanted it would be in a separate PR.

**Comment by corp-0** [comment]
Did you test it actually works? The global parameter isn't what you would imaginr initially

**Comment by MaxIsJoe** [comment]
> Did you test it actually works? The global parameter isn't what you would imaginr initially

It was set to true by default, this sets it to false.

**Comment by corp-0** [comment]
Yes but again, the global parameter just has a confusing name. Making global true just means it will send the message to everyone and don't use the hardcoded 15 tiles distance. It doesn't mean everyone will hear it, it doesn't mean it will make the sound not spacial, it only means the message will be sent to everyone and each one of them will evaluate if they hear it and how.

**Comment by Bod9001** [comment]
any changes wanted?

**Comment by MaxIsJoe** [comment]
Alright fixed this for real this time

sounds were marked as 2D instead of 3D which made them global

**Review by corp-0 — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
