### PR TITLE
Change cable cutting window RegisterHandler to ReplaceHandler

### LINKED ISSUE #6450: InteractableTiles.cs RegisterHandler warning floods the console
### Environment
- Game Version: 0.4.1
- OS Version: Pop OS 20.10 (Linux)

### Detailed description of bug

InteractableTiles.cs `RegisterHandler()` call in the `Start()` method causes warnings to be flooded onto the console.

```
NetworkServer.RegisterHandler replacing handler for CableCuttingWindow+CableCuttingMessage, id=2979. If replacement is intentional, use ReplaceHandler instead to avoid this warning.
UnityEngine.Debug:LogWarning(Object)
Mirror.NetworkServer:RegisterHandler(Action`2, Boolean) (at Assets/Mirror/Runtime/NetworkServer.cs:625)
InteractableTiles:Start() (at Assets/Scripts/Tilemaps/Behaviours/InteractableTiles.cs:73)
```

Solving this could be considered progress towards #2526.

### Steps to reproduce

1. Open the project.
2. Start/host server.
3. Observe the warning pop up ~30 times.

### PR DESCRIPTION
**Pull request by Korywon**
### Purpose

Fixes #6450
Progress on #2526

### Notes:

There was an issue with Mirror flooding the console with warning messages about the use of `RegisterHandler()` (see issue #6450 for details). After digging a little more, I found that the implementation for `RegisterHandler()` and `ReplaceHandler()` is pretty much the same, with the difference being that `RegisterHandler()` warns about conflicting `msgType` ID.

This is `RegisterHandler()` implementation.

```cs
int msgType = MessagePacking.GetId<T>();
if (handlers.ContainsKey(msgType))
{
    Debug.LogWarning($"NetworkServer.RegisterHandler replacing handler for {typeof(T).FullName}, id={msgType}. If replacement is intentional, use ReplaceHandler instead to avoid this warning.");
}
handlers[msgType] = MessagePacking.WrapHandler(handler, requireAuthentication);
```

And this is `ReplaceHandler()`'s implementation.

```cs
int msgType = MessagePacking.GetId<T>();
handlers[msgType] = MessagePacking.WrapHandler(handler, requireAuthentication);
```

So, my conclusion is that we can use `ReplaceHandler()` without any differences, and my testing shows same behavior. I did add a TODO for someone with more expertise to comment on why this is called multiple times. Other than that, it should cut down the number warnings thrown out.

### CODE REVIEW

**Comment by Korywon** [comment]
Welp, not sure why it's showing the other commits. If someone has an idea why, let me know.

There should only be one file that's changed, and it's InteractableTiles.cs.

**Comment by Korywon** [comment]
I'll create another PR and try to rebase my fork so we don't see the unrelated commits. Closing this one for now.

**Comment by NoooneyDude** [comment]
You might find the workflow a bit easier if you keep `develop` pristine, instead creating a branch from `develop` for each PR.

**Comment by Korywon** [comment]
Good idea. I'll incorporate that into my next PRs.

**Pull request closed without merging**
