### PR TITLE
More items in belt slots, shaker in Booze-O-Mat, and some localization.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Make a few items (flashlights, wrenches, multitools, etc.) able to be equipped in the belt slot.
- Change some localization, "mining lamp" to lantern, "trowel" to "spade".
- Add shaker to Booze-O-Mat.
- Move empty pocket fire extinguisher to right folder.

### Notes:
Most items that are now equipable in the belt slot were also equipable in the belt slot in /tg/. Multitools and spades weren't in /tg/, but I added them because of personal tastes.

For some reason, the FileID for lanterns changed and I had to adjust all the references in .prefabs and .assets. ~~However, lanterns in scenes appear to be fine, but I'm still worried something might happen to them in the future.~~ Turns out all the lanterns reset to 0,0. Commit reverted.

### CODE REVIEW

**Comment by Bod9001** [comment]
Could you rename the item tray SO as well for  "trowel" to "spade".

**Comment by PetMudstone** [comment]
Done.

**Comment by Bod9001** [comment]
cool, Will wait forTests

**Comment by DooblyNoobly** [comment]
tests are good bod, I'll merge it

**Pull request merged**
