### PR TITLE
Character preview will no longer escape outside of the window

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: Character previews are now fully contained inside their preview containers. They can no longer escape.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
why is tests failing

**Comment by ThatDan123** [comment]
Turns out spritehandler controller is still needed

**Comment by ThatDan123** [comment]
You can download the test results:

image

And then open index.html

**Comment by corp-0** [comment]
probably, prefabs that had a reference to the deleted monobehaviour

**Comment by waffielz** [comment]
finally, proper contentment for the scp

**Pull request merged**
