### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:

CL: [Fix]  players not taking damage when walking of the glass
CL: [Fix]  fixes  stomach fat not spawning in the correct organ
CL: [Fix]  fixes Bullets not doing any damage
CL: [Fix]  hopefully fixes range check on turret
CL: [Fix]  fixes jerky movement of chat bubble

### CODE REVIEW

**Comment by corp-0** [comment]
CL: [Fix] contagion zone fixes crash may be idk?

do you really want this to be written in the changelog file?

**Comment by Bod9001** [comment]
hhah yeah good point

**Comment by MaxIsJoe** [comment]
While you're at it can you add a bitmask for players for all sicknesses

**Comment by Bod9001** [comment]
oh bitmask ?
~~todo Cleanup for hazard on Destroy~~

**Comment by corp-0** [comment]
What does the todo mean? Are you going to add it to this pr?

**Comment by Bod9001** [comment]
is good to merge

**Review by corp-0 — APPROVED** [review]
there are multiple casing violatiosn but I think I will fix them myself later

**Pull request merged**
