### PR TITLE
Ensure crit overlay disappears when returning to lobby, fix health monitor state after logging out.

### PR DESCRIPTION
**Pull request by VitrescentTortoise**
### Purpose
Fixes crit overlay not going away when logging out. Also fixes health monitor not updating from previous state after logging out. (Was broken when starting a second game). #1771 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
This should work but for some reason there is an NRE with shroudImg on CritOverlay: 
image

This is strange because the reference is there in the inspector:

image

I've even tried reimporting the whole project to make sure it wasn't a serialization issue on my side. Can you check this PR again and see if you get the same results?

**Comment by DooblyNoobly** [comment]
I've confirmed that this issue doesn't exist on latest develop branch, so its something to do with this PR

**Comment by VitrescentTortoise** [comment]
Yes, I get that NRE. Very sorry for missing that, don't know what I was doing.

So it appears upon scene change that shroudImg reference goes null briefly. No code modifies the reference, it is deserialized when the OverlayCrit prefab is loaded, and remains untouched afterwards. I do not know what the mechanisms are for scene change in Unity, and have no idea why it may appear null briefly. Observing the scene hierarchy, I find no indication of the image's instance leaving the scene, or the reference being cleared.

I have applied a crappy bandaid fix checking for null upon access, in the future if this reference is accessed during scene change we will get the same error. Shall I create an issue so this doesn't slip through the cracks? I suspect it's gonna be hard to fix, but maybe could be done with some research/experiments.

**Comment by DooblyNoobly** [comment]
Very strange, will look into it some more

**Comment by DooblyNoobly** [comment]
Figured it out, it was the async method causing the grief. Changed it a coroutine. Closing this PR as I made a branch to add the fix and will merge that. Thanks @VitrescentTortoise

**Pull request closed without merging**
