### PR TITLE
Adds Gibtonite

### LINKED ISSUE #2308: Gibtonite
# Description
Implement gibtonite, with the same sprite / sound / logic as tg.

Add a chance for it to spawn in mineable rocks.

Described here: https://tgstation13.org/wiki/Shaft_Miner

Can be seen in action here:
https://youtu.be/KOtfRZt6F3s?t=1482

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes #2308

# Gibtonite, the explosive ore.

Gibtonite is an uncommon ore that is hidden inside rocks and is not easily detectable without a mining scanner.
It has three states:

1. Inactive: is relatively harmless until it is exposed to heat or is damaged by energy, to which it returns to an active state again.
2. Active: While active, any damage the ore receives will cause it to switch to its fused state.
3. Fused: While fused, the ore will expload in 2.75 seconds unless it is disabled.

Upon mining the rocks that hide the ore, the Gibtonite will go into its fused state. The gibtonite can be defused by using a mining scanner, after it has been defused; a miner can ensure that the gibtonite will not cause further distress or damage by using a pickaxe or a drill to disable the Gibtonite completely.

The Gibtonite currently serves as a hazard for unsuspecting miners who are rushing carelessly inside lavaland, and serve as an upgrade path for an underutilized tool for miners.

# The Advanced Proto-kinetic accelerator.

Janitors recently got a shiny new toy in the form of the "Advanced Light Replacer", a revolutionary item that makes the jaintor's job a little bit easier when replacing light-bulbs and also introducing a new feature to let them customize the station to their liking. But why should our floor scrubbing intern have all the fun?

Miners get an upgrade for one of their under-used tools in their arsenal, the PKA. The new advanced variant is a lot meaner, powerful and useful. The APKA -as I'll call it from now on- is a fully lethal utility that is designed to let miners face the dangers of lavaland head-on while rivaling the Plasma Cutter's usefulness. 

The APKA can mine several tiles ahead from where it has impacted, allowing you to quickly dig tunnels. It also utilizes the Gibtonite's explosive capabilities to become a very effective self-defense/xeno hunting weapon.

However, this upgrade does have its own downsides. 
For starters, it has a full 8-second cooldown between each charge to use. It has a wide AOE damage that can damage both ores and even the person wielding it if they're not careful with their positioning. It is not easily accessible and requires you to spend resources and time to obtain it.

The APKA is not a replacement for the Advanced Plasma Cutter, as it is still much slower and less efficient. But it is a viable alternative for when cargo refuses to spend their credits on supplying their miners with better equipment, or when you need the extra stopping power to go against a nest of xenos.. or if you want a way to troll your fellow shaft miners during your shift over at lavaland.

# Improvements under the hood

There has been a few technical changes that allowed for these sorts of things to exist that I will not list in the changelog. One of those changes might seem unused, but eventually they will not be in future PRs as they will be used to expand upon mining a bit further in terms of visuals and gameplay.

# Changelog

CL: [New] Adds a new ore exclusive to Lavaland, the Gibtonite. 
CL: [New] An advanced variant for the PKA has arrived. Craft it using a Gibtonite, Matter Bin and a screwdriver.

### CODE REVIEW

**Review by Bod9001 — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
fixed tests. approvals pls.

**Review by Bod9001 — APPROVED** [review]

**Comment by PerfectTangent** [comment]
Great PR. Dunno if you are aware, there are already legacy sprites for advanced versions of the PKA back from when there used to be 3 different versions in /tg/.

**Comment by MaxIsJoe** [comment]
> Great PR. Dunno if you are aware, there are already legacy sprites for advanced versions of the PKA back from when there used to be 3 different versions in /tg/.

didn't know that, will look them up later tonight.

**Comment by MaxIsJoe** [comment]
nevermind you beat me to it

**Pull request merged**
