### PR TITLE
Server side UI actions 

### PR DESCRIPTION
**Pull request by Bod9001**
This should hopefully prevent client randomly losing their UI actions when re-logging

 
TODO requires a bit more testing

### Changelog:

CL: [Improvement]  UI should now be a bit more resilient when re-logging

### CODE REVIEW

**Comment by corp-0** [comment]
chemistry tests are failing? Also, please try to solve as many codacy issues as you can.

**Comment by ThatDan123** [comment]
From glancing over the code it seems fine and i'll do a proper build test just to check it all works.

**Comment by ThatDan123** [comment]
Respawning yourself as an alien in the editor doesnt give you any actions

**Comment by ThatDan123** [comment]
I know the reason why. It's because the interface where they are set assumes mind is set before the transfer, when actually the mind is set after the transfer to a new body so is null.

**Comment by ThatDan123** [comment]
Also in the Mind script there ResendSpellActions() is that still needed?

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
