### PR TITLE
Fixes various consoles not having power

### LINKED ISSUE #8235: Reactor and Boiler Consoles are Unpowered
They are both missing the APC Powered Device Component, in their prefabs.

### PR DESCRIPTION
**Pull request by AtnerNT**
Recently consoles were changed and a few of them had their APCPoweredDevice component removed which stopped them from working, this adds that component back and then remaps any APC connections that were broken by this.
(This has alot of scenes  changed as the shuttle console was one of the consoles affected)
Fixes #8235 
Note: This does not fix the bugs with the communication and ID consoles- merely the power issues.

CL: [Fix] fixed several consoles across many maps not being connected to power.

### CODE REVIEW

**Comment by AtnerNT** [comment]
Hey the labeler changes worked neat

**Comment by corp-0** [comment]
@tomasalves8 can you take a look at this? Why were the components removed?

**Comment by tomasalves8** [comment]
Turns out some of the consoles had this component removed for some reason. No idea why.

**Review by Bod9001 — DISMISSED** [review]

**Comment by ThatDan123** [comment]
PogStation: "NuclearReactorConsole (1)" is not assigned to "APC - EngiFront"
MiniStation: "NuclearReactorConsole (1)" is not assigned to "APC - Atmospherics"

**Review by ThatDan123 — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
