### PR TITLE
fixes APC frames being pulled from walls.

### LINKED ISSUE #8089: APC frames can be mounted on wall and then pulled
### Environment
- Game Version: latest staging build at the moment
- OS Version: win 10

### Detailed description of bug
After mounting APC frame onto wall you can simply pull it out of there and move around.

### Steps to reproduce
apc_frame
1. Get APC frame
2. Mount it on wall
3. Ctrl+click on it and move from wall
4. Profit

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #8089 ~~and updates APC Frame to use Item Attributes V2~~

CL: [Fix] fixed APC frames being pulled from walls.

### CODE REVIEW

**Review by Bod9001 — DISMISSED** [review]

**Comment by ThatDan123** [comment]
Do we not already have a APC frame item? Adding pickuable to the wall object seems like the wrong way to fix this issue?

Surely to fix #8089 we just want to not allow pushing?

**Comment by MaxIsJoe** [comment]
> Do we not already have a APC frame item? Adding pickuable to the wall object seems like the wrong way to fix this issue?
> 
> Surely to fix #8089 we just want to not allow pushing?

You can tell object behavior to stop players from pushing it but they can still pull it
Pickuable is what stops items from being pulled by players

And we already do have it but it has not been updated to use IAV2

**Comment by ThatDan123** [comment]
> You can tell object behavior to stop players from pushing it but they can still pull it Pickuable is what stops items from being pulled by players

Thats not how it works, using ObjectBehaviour and setting it to not be pushable stops pulling as well.

**Comment by MaxIsJoe** [comment]
> ObjectBehaviour

I tried setting it from ObjectBehaviour but it didn't work

**Comment by MaxIsJoe** [comment]
Needs another review

**Review by Bod9001 — APPROVED** [review]

**Comment by corp-0** [comment]
what did you change?

**Comment by MaxIsJoe** [comment]
> what did you change?

Set the "not initially pushable" bool to true.

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
