### PR TITLE
Access Restriction added to Door Switch

### PR DESCRIPTION
**Pull request by h3killa**
# Pull Request Template

### Purpose
Adds AccessRestriction script component capability to the doorswitch script.

### Notes:
Adding AccessRestriction to the doorswitch will restrict access same as airlocks.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] - Code is indented with tabs and not spaces
- [x] - The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- [x] - The PR does not bring up any new compile errors
- [x] - The PR has been tested in editor
- [x] - Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] - Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] - Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] - The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] - The PR has been tested with round restarts.
- [ ] - The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by JesterX666** [comment]
Review in progress

**Comment by DooblyNoobly** [comment]
Any chance you could add a toggle to enable / disable this behaviour? I know you are checking if AccessRestrictions is null but that means the prefab will have to have the component added. So a flag on the inspector would be better to toggle the behavior while you are mapping them out. 

I'd like to suggest tho that most switches be left with the restriction turned off as it makes it easier for antags if they have spent a lot of effort trying to get into a room to toggle the switch without having the id card to do it.

**Comment by h3killa** [comment]
Its only enabled when Access Restriction component is added to the individual switch. Otherwise it defaults to normal behavior.

**Comment by h3killa** [comment]
I haven't added the Component to any switches on the actual map just added the functionality for access restriction.

**Comment by DooblyNoobly** [comment]
Alright can you add a [ToolTip("")] or [Header("")] attribute to the public field so people understand that when looking at it via inspector

**Comment by JesterX666** [comment]
I do see the Green Sprite added property.  But I don't see the added Access Restriction added property.

image

What am I missing?

**Comment by h3killa** [comment]
> 
> 
> I do see the Green Sprite added property. But I don't see the added Access Restriction added property.
> 
> image
> 
> What am I missing?

It was previously using a editor placed Access Restriction script component. The most recent commit addresses that.
image

**Comment by JesterX666** [comment]
Code looks good.  Thanks for adding what Doobly asked.  Testing it in client/headless server right now.  Sorry for the delay.

**Comment by JesterX666** [comment]
Works as intended.  Perhaps one day it will be cool to add a sound effect to the refused access.

**Comment by JesterX666** [comment]
Oops... Forgot to merge... lol

**Pull request merged**
