### PR TITLE
Fire Resist Action B:20

### PR DESCRIPTION
**Pull request by aleios**
This is a PR to introduce resist mechanics into the game. Potentially fulfilling the issue: https://github.com/unitystation/unitystation/issues/2660

- Instead of the "rest" icon there now exists the resist icon as the rest icon was firing off a call to Resist(). As such changes were made to UIManager.prefab.

- Hitting resist whilst buckled but not handcuffed will unbuckle the player.

- Hitting resist whilst on fire and NOT buckled will make the player drop to the ground and roll to remove fire stacks. _This value may need to be tweaked along with the stun time on the ground_ but for now I've just used the values that were present in the byond version.

- Hitting resist whilst not on fire, not buckled, but handcuffed will start the handcuff removal timer.

Any situations missing let me know.

* [x]  Code is sufficiently commented 

* [x]  Code is indented with tabs and not spaces

* [x]  The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**

* [x]  The PR does not bring up any new compile errors

* [x]  The PR has been tested in editor

* [x]  The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

* [x]  The PR has been tested with round restarts.

* [x]  The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

fireroll

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Why do you need to commit UIManagers.prefab when the button you are changing is on Panel_Hud_Button prefab? I'm worried that you may have removed some admin chat window work in your UIManager changes

**Comment by aleios** [comment]
Thanks, moved the changes to the UI into Panel_Hud_Bottom.

**Comment by DooblyNoobly** [comment]
testing this one on staging. Jump on when the staging build is done and if it works fine I'll pay out the bounty

**Comment by DooblyNoobly** [comment]
it will be staging build 1317

**Pull request merged**
