### PR TITLE
Inventory refactor

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Inventory refactor
Strings will no longer be used to select the equipment slot, the EquipSlot enum replaces it.
Removes UUIDs from inventory slots.
Removes a lot of bloat from the different inventory interactions, making everything use the same calls.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
there's still a lot of room for improvement and cleaning, specially in storage code but im done for now

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Resolved Conflicts

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]
## Two major bugs that need resolving:
### Transfering item between UI_Slots by click or drag and drop bug:
Broken things:
- Cannot click on an UI_Slot with an item in the active hand and have it transfer the item
- Cannot drag and drop the item and have it be placed in the UI_Slots
- Cannot drag and drop the item onto the backpack and have it be placed in the next available UI_Slot
inventorybug

### Fire Cabinet bug:
Broken things:
- Clicking on the fire cabinet does not open it or update its sprite, instead the fire extinguisher is automatically placed in the players hand
- No matter where the fire extinguish is on the map, if you click on the Fire Cabinet of where it came from it will then be placed in the players hand
fireextinguishbug

**Comment by Aranclanos** [comment]
Fixed

**Comment by DooblyNoobly** [comment]
Yep looks good. There seems to be some blinking when it is being moved from slot to slot but we can polish that later.

**Pull request merged**
