### PR TITLE
Authentication move

### PR DESCRIPTION
**Pull request by NoooneyDude**
- Moves our client -> server authentication code to `Authenticator.cs`, a Mirror-derived component attached to the `NetworkManager` prefab.
This now happens _before_ we register the player on the player lists.
- Reduces `Ignorance` logging level now that the Mac issue is resolved.

### CODE REVIEW

**Review by corp-0 — DISMISSED** [review]

**Comment by Bod9001** [comment]
does this affect the request open scenes thing? 
Since currently the client Loads all the scenes before requesting data

**Comment by NoooneyDude** [comment]
I think that's in `JoinedViewer`, right? Authentication is now done before the JoinedViewer object is spawned and authority given to the client so shouldn't be affected.

**Comment by Bod9001** [comment]
well, the spawn Scenes was a bit intermingled with the authentication

**Comment by Bod9001** [comment]
had a look at the code it looks good

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
