### PR TITLE
Map Console Replace Pog 

### LINKED ISSUE #5941: Map Console Replace
After #5940 is merged all station scene will need to replace the shuttle console in the escape shuttle with the Escape Shuttle Console, to allow for traitors to emag it.

- [x] Square
- [x] Fall
- [x] Outpost
- [x] Pog
- [x] Box

### PR DESCRIPTION
**Pull request by SluggyWuggies**
Replaces the shuttle console with the Escape Shuttle Console, allowing traitors to emag it. 

fixes #5941

### CODE REVIEW

**Comment by corp-0** [comment]
what is it will all the other commits?

**Comment by SluggyWuggies** [comment]
I eh- Dunno. I may just be bad at maintaining a branch.

**Comment by corp-0** [comment]
make new fresh branches every time you make something new to pr.

**Comment by SluggyWuggies** [comment]
Noted! Appreciate the help.

**Pull request merged**
