### PR TITLE
A lot of Security clothing, some cloaks, Drobes, and miscellaneous additions.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR adds a **lot** of clothing for security, too much to make a comprehensive list, but in summary it adds:
- All uniforms in security.dm except for the newest one from the new Families gamemode
- Several new hats, including several variations of beret and 64x64 constable helmets.
- Few new coats for detective and others.
- SWAT and spacepol masks.

This PR also adds some other random stuff I decided to implement, including:
- Cloaks for all department heads, fit in the neck slot.
- Goliath Cloaks and Drake Armour, since they were in the same file as the above, come with hats.
- Hazard Jumpsuits and Vests for engineering.
- CargoDrobe, EngiDrobe, AtmosDrobe, and SecDrobe.
- Fix for the Street Judge Helmet's sprites.
- Khaki Pants, they don't come with a top.
- Generated .spriteatlas files.

A few screenshots: [formal officer's clothes](https://cdn.discordapp.com/attachments/273774715741667329/694813703337672724/Screenshot_1248.png), [Calhoun's uniform](https://cdn.discordapp.com/attachments/273774715741667329/694813651319914514/Screenshot_1245.png), [Drake Armour](https://cdn.discordapp.com/attachments/273774715741667329/694813681325834300/Screenshot_1246.png).

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by PetMudstone** [comment]
Ah damn, it appears variations are resetting theirselves for some reason and stuff is disappearing from Drobes. Gonna need to check and fix everything.

**Comment by Evan-R-Rogers** [comment]
Give us pictures! :)

**Comment by PetMudstone** [comment]
Well, I think I fixed the reset variations, but now the checks are failing. Oh dear.

**Comment by DooblyNoobly** [comment]
not your fault, I think tests are being weird today

**Comment by DooblyNoobly** [comment]
opps the tests were actually working. There is a missing component in all of the scenes:

```
            </failure>
            <output><![CDATA[[Tests] Missing component found in scene Lobby, GameObject UIManager/RightClickManager
[Tests] Missing component found in scene BoxStationV1, GameObject UIManager/RightClickManager
[Tests] Missing component found in scene OutpostStation, GameObject UIManager/RightClickManager
[Tests] Missing component found in scene PogStation, GameObject UIManager/RightClickManager
[Tests] Missing component found in scene AsteroidStation, GameObject UIManager/RightClickManager
```

**Pull request merged**
