### PR TITLE
fixes highlight disappearing

### PR DESCRIPTION
**Pull request by Bod9001**
scale was getting set too small randomly somehow

### CODE REVIEW

**Comment by Aranclanos** [comment]
I'd suggest finding the reason of the bug before slapping a fix

**Comment by corp-0** [comment]
> I'd suggest finding the reason of the bug before slapping a fix

Same. That mysterious reason might be doing more than just making highlight small

**Comment by Bod9001** [comment]
it's because of the lean tween animation squishing it down when you pick it up

**Comment by corp-0** [comment]
oooh, so it doesn't go back to normal after. What is your change doing?

**Comment by Bod9001** [comment]
just reset scale and, tells it not to bring scale over

**Pull request merged**
