### PR TITLE
TestStation Scene v1

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
This Station is meant to help developers test code/objects/other stuff quickly on a map. It loads in pretty fast as there are little to no pipes or wires and all the lights/machines are self powered. However, I just need an extra set of eyes to help pick up and correct anything I missed, such as the shuttles, as they are not behaving correctly.

### Changelog
CL:  Added TestStation Scene so that developers can quickly map and load up new features to test in a round.

### CODE REVIEW

**Comment by Bod9001** [comment]
TestStation.unity: SpaceshipDoor (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
 "LightBulbFixture (43)" miss switch reference.
 "LightSwitch" miss switch reference.
humm, Probably need to change test

**Comment by Bod9001** [comment]
ok, for updating the map you have to remove all the Tile map Colliders
then 
image
remove all those from the object layer and make a new layer called tables

image
then add those components on it like this, do these for all the matrices

**Comment by Akbadain29** [comment]
Alright, Tables should now be fixed up.

**Comment by Bod9001** [comment]
cool, sadly I can't help too much of the shuttles , can have a look at the tests to see if there error incorrectly on your map?
maybe that Daniel could help you with the shuttles

**Comment by Akbadain29** [comment]
Alright shuttles and tables are readjusted. All the tests now pass.

**Pull request merged**
