### PR TITLE
Fix lavaland Tiles

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: [Fix] Hopefully fix lavaland tiles (again again)

### CODE REVIEW

**Review by Bod9001 — APPROVED** [review]

**Comment by corp-0** [comment]
by doing what?

**Comment by ThatDan123** [comment]
Replaced the bad tile in the pallete and redid the base tiles on the scene

**Comment by pyrosshade** [comment]
Yes, what is being fixed? :thonk:

edit: welp, guess i didn't type fast enough

**Comment by corp-0** [comment]
uhm, I think Pet already did that before and they broke shortly after. It won't do any harm merging tho

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
