### PR TITLE
Update manager update

### PR DESCRIPTION
**Pull request by RedlineTriad**
### Purpose
Changes UpdateManager to increase readability and also calls FixedUpdateMe and LateUpdateMe correctly now.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### CODE REVIEW

**Comment by fomalsd** [comment]
is there a difference in performance?

**Comment by PJB3005** [comment]
This is definitely gonna impact performance *and* perhaps make future optimizations like more efficient collection algorithms harder.

This is a critical system and some code style changes are dumb.

**Comment by DooblyNoobly** [comment]
Alright, I profiled the Update in UpdateManager using 2000 actions spawned on start and compared the two versions from the PR and develop branch:

New UpdateManager:
0.88ms CPU @ 2000 actions - 1.1KB GC

Develop UpdateManager:
0.91 CPU @ 2000 actions - 1.2KB GC

So as you can see there is a slight improvement. Now compare this to not having an UpdateManager at all and we will be running into the 7 or 10ms CPU times (according to unity blog).

I like the readability of this solution. Merging it.

**Comment by PJB3005** [comment]
Did you profile insertion/removal speed?

**Comment by PJB3005** [comment]
I'm also curious in a comparison with a correctly implemented update manager because this PR did change it to be less incorrectly implemented. It might be responsible for the relative performance improvement.

**Pull request merged**
