### PR TITLE
Increased size of Botany Area

### PR DESCRIPTION
**Pull request by Raptorizer**
# Pull Request Template

### Purpose
Increases the size of the botany area to allow more players to perform their jobs.

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by Bod9001** [comment]
Only problem is you've made a new scene for it

**Comment by Bod9001** [comment]
image
It's a bit dark in the backroom

**Comment by Bod9001** [comment]
image
I would prefer if there was another exit but Not to to important

**Comment by Bod9001** [comment]
Also set this as the default output station map

**Comment by Bod9001** [comment]
since he got scene changes can you move the emergency shuttle  further away?

**Comment by Jibbajabbafic** [comment]
Please rename your scene to OutpostStation.unity and replace the existing map

**Review by Jibbajabbafic — CHANGES_REQUESTED** [review]
Please rename your scene to OutpostStation.unity and replace the existing map

**Comment by ghost** [comment]
Whose idea was it anyway to put a red security jail door in botany?

**Review by Raptorizer — COMMENTED** [review]
Fix made

**Pull request merged**
