### PR TITLE
Fixes a sound issue, modifies and adds some sounds.

### PR DESCRIPTION
**Pull request by MrAsbestos**
### Purpose
This PR adds tap sounds to items that do not do damage, so now people won't kill each other in 5 minutes because they thought they got horribly assaulted by a piece of paper, this will give some pretty good feedback to other players, also modified other stuff.

Fixes issue #5094

### Changelog:
-All items that do not make damage now make the "Tap" sound.
-Improved disposal outlet sound.
-Added trayhit1 and trayhit2 as addresable sounds.
-New hit sounds for chairs, gas tanks, fire extinguishers, and toolboxes (just like classic TG).
-Correct sounds for the cabinet, trash bin, and wood crate.
-Added the correct name and description to the "Cuban Carp" food item.
-Toy guns no longer do melee damage.
-Better pulling sound (the default one for almost all TG branched servers).
-Fixed cigarettes being able to be used as internals.

### CODE REVIEW

**Comment by MrAsbestos** [comment]
fuck I should have updated my repo, dammit.

**Comment by MrAsbestos** [comment]
ok, let's hope this doesn't break stuff

**Comment by MrAsbestos** [comment]
please conflicts go away <3

**Comment by MrAsbestos** [comment]
YES

**Comment by MrAsbestos** [comment]
I DID IT :DDDD

**Comment by MrAsbestos** [comment]
do not merge btw, going to check some files

**Comment by MrAsbestos** [comment]
Ready to merge after this check!

also please remove the "merge conflict" tags, I no longer have conflicts.

**Comment by MrAsbestos** [comment]
Oh crap nevermind, forgot to set some stuff to "tap"

**Comment by ThatDan123** [comment]
Did you move the new sounds you added into the sounds category?

**Comment by MrAsbestos** [comment]
I believe so?

The disposal ones are in "prefabs>machines>disposals"
Tray ones are in "prefabs>effects"
The closet sounds are in "prefabs>machines>closet"

**Comment by ThatDan123** [comment]
i mean on this screen:

image

As the new sounds default to music, which should really be changed as we will be adding sounds more often than music

**Comment by MrAsbestos** [comment]
oooh okay
from now and then I will uncheck the music thing
I asked Gilles, but he told he had no idea about it so I left it there

**Comment by MrAsbestos** [comment]
huh, the sounds I added are not in music?... 
Huh that's good

**Comment by MrAsbestos** [comment]
After this check passes, I think it's ready to merge!

**Comment by corp-0** [comment]
It really looks like we should add the tap sound to the common sounds and make it play whenever the damage of the object is 0 instead of manually setting the tap sound.

**Comment by MrAsbestos** [comment]
Hm yeah.. but for now all items that don't do damage and will never do, have the "tap" sound by default, I don't know coding, so.. I think I'll leave it to someone else, but if it's easy enough I'll try to do it, if you can explain it to me.

**Comment by MrAsbestos** [comment]
By the way it's ready to merge, just telling ya.

**Comment by ThatDan123** [comment]
Can you redo the sound for the pen to fix the conflict

**Pull request merged**
