### PR TITLE
Nuclear Operatives Rewrite

### LINKED ISSUE #3173: Proper nuclear operatives rewrite B: 80
Right now nuke ops is a very basic game-mode and some things need major changes.

These changes would allow nuke operatives rounds to be a lot more dynamic and IMO more fun. this changes the dynamic from nukies rush sec and put in code to nukies have to get the disk, put the nuke in place, arm it, and get out of dodge before it blows.  while the station crew defend the captain and in turn prevent and keep the ops from getting said disk.

[Here is a tgstation wiki link for nuclear operatives](https://tgstation13.org/wiki/Nuclear_Operative)

1.  The captains quarters should have a nuclear authentication disk which is required to be placed inside of the nuke before it can detonate. Once armed the disk is able to be taken out of the nuke with the countdown still going, the nuke also cannot be disarmed without the disk inside.

2. the nuke should be in the nukies shuttle behind a glass door, that stays anchored until the nukies insert the disk and de-anchor it.

3. The nuke should be bolted and unmovable until the nuke disk is inserted and should have a button to anchor it again in the GUI.

4. The nuke should have a timer with a minimum of 3 minutes to make sure people have enough time to potentially counterattack the nuke ops and get the disk back, and for the nuke ops to be able to get a safe distance. with the ops able to choose to make it longer by setting a time after the code is set

5. If the nuke ops die when the nuke goes off it counts as a partial failure.

6. A nuke disk tracker that spawns on all nukies and in the HOS locker, that constantly updates its sprite to a arrow pointing to the disk, when you are close it turns to a green arrow and finally a dot when you are right on it.

### LINKED ISSUE #3174: Move nuke to vault/add vault
Right now the nuke is in armory which is improper. meant to improve the nukeies rewrite #3173

- the nuke needs to be moved to a reinforced vault.

- the nuke needs to be changed to be the stationary kind, to prevent the sec from destroying/selling it.

### PR DESCRIPTION
**Pull request by DeeJayhX**
# Purpose
Fixes #3173 
Fixes #3174 

## Plan:

- [x] Create Nuclear Disk
- - [ ] Spawn Nuclear Disk in Captain's Quarters
- - [x] Make Nuclear Disk indestructible.
- [ ] Create Nukie nuke
- - [ ] Spawn Nuke inside Nukie shuttle behind glass door
- - [ ] Make Nuke initially bolted/unmovable
- - [ ] Make Nuke's bolts retractable/place-able with Nuclear Disk
- - [ ] Make Nuke's nuclear warhead arm-able/disarm-able with Nuclear Disk
- - [ ] Make Nuke Timer last 3 minutes (unless otherwise set) before self destruct, continues counting if disk is removed.
- [ ] Create Disk Pin-pointer (2 Variants, one for Crew, one for Syndicate)
- - [ ] Crew pin-pointer pawns in HOS locker
- - [ ] Syndicate pin-pointer spawns on all Nukies
- - [ ] Always points towards nearest nuclear disk
- - [ ] Indicates when close
- - [ ] Indicates when same tile
- [ ] Create Nuke Vault for on-station nuke (?)
- - [ ] Place on-station nuke inside vault
- - [ ] Make on-station nuke immovable

# Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- [x] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by Jibbajabbafic** [comment]
@DeeJayhX Is this still being worked on? I would suggest closing the PR until you're ready for it to be reviewed.

**Comment by DeeJayhX** [comment]
> @DeeJayhX Is this still being worked on? I would suggest closing the PR until you're ready for it to be reviewed.

@Jibbajabbafic 
This is literally the purpose of a Draft Pull Request, you cannot merge it until I mark it ready for review. The DNM tag was unnecessary, but you may add the In Progress tag if you like.

image

**Comment by Jibbajabbafic** [comment]
Sorry I missed that, I'm not used to people using that feature. It just clutters up the PRs is all.

**Comment by DeeJayhX** [comment]
> Sorry I missed that, I'm not used to people using that feature. It just clutters up the PRs is all.

@Jibbajabbafic 
No worries, if PRs are handled in a timely manner (and they seem to be here) then any drafts will end up at the bottom of the PR list in no time and out of the way. Thanks for talking it out.

**Comment by fomalsd** [comment]
I really think you should only make a PR when it's almost ready and you have something to show. 
I'm going to close this one.

**Comment by DeeJayhX** [comment]
> I really think you should only make a PR when it's almost ready and you have something to show.
> I'm going to close this one.

@fomalsd Well, as previously mentioned, [You're Wrong](https://github.blog/2019-02-14-introducing-draft-pull-requests/), but do as you please.

**Comment by RedlineTriad** [comment]
@DeeJayhX I like draft pull requests but not if you are just sitting on it for a week after opening.
We want other people to have a chance to do bounties.
Otherwise, I wish we used draft pull requests more often instead of `DNM`.

**Pull request closed without merging**
