### PR TITLE
Global Admin Sound

### PR DESCRIPTION
**Pull request by ThatDan123**
Lets admins play any sound in soundmanager globally.

Doesnt work quiet right, half the sounds dont play, but no errors so.......

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by ThatDan123** [comment]
Stupid MediDrobe

**Comment by corp-0** [comment]
fixed in my PR

**Comment by ThatDan123** [comment]
Good to merge when ready

**Comment by ThatDan123** [comment]
~Im actually gonna refactor so as long as i dont actually commit you can still merge this, it works fine but im gonna change some stuff.~

**Comment by ThatDan123** [comment]
Was trying the get music to work but it didnt work, but i have reorganised the SoundManager

Good to merge.

**Comment by ThatDan123** [comment]
#3747 Is now pull request

**Pull request closed without merging**
