### PR TITLE
Electrical VIR V0.95 now with optimisation and bug fixes electric boogaloo

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
Optimises and fixes a few bugs
refactor as well
 Did some shots at cleaning up GC usage
The main bottleneck of the GC is now dictionary_set , I can't really think of anything else from dictionaries that I could use so
a special thanks to RedlineTriad For making electrical synchronisation more Readable and cleaner

A little bit of  Current Performance Bottlenecks B: 70 x 5 (Total B350) #1442
Fixes Rapid changes to power source breaks electricity #1588

Fixes the issue where it would take one tick for the batteries to kick in resulting in the power going out for one tick when the power generator gets turned off
### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### Notes:
Next update will be construction and deconstruction of electrical stuff

### CODE REVIEW

**Comment by fomalsd** [comment]
is there anything in particular I should look at that was fixed? I have no idea what's going on in that code

**Comment by Bod9001** [comment]
oh yeah let me labeled what I fix

**Comment by Bod9001** [comment]
A little bit of  Current Performance Bottlenecks  #1442
Fixes Rapid changes to power source breaks electricity #1588

**Comment by fomalsd** [comment]
idk, I can still break electricity generation the way it's described in #1588
Scr 2019-04-06 в 16 04 39 2019-04-06 16_08_19

**Comment by Bod9001** [comment]
aww dam it

**Comment by fomalsd** [comment]
*it doesn't break ALL electricity on the station, just the generator. so if you turn on SMES it will work again

**Comment by Bod9001** [comment]
It should be fixed now

**Comment by fomalsd** [comment]
yeah, that fixes it!

**Pull request merged**
