### PR TITLE
Allows users to customize how big their chat logs can be

### LINKED ISSUE #7222: Chat Log history is too short
### Environment
- Game Version: Staging (8-8-2021)
- OS Version: Windows 10 Home

### Detailed description of bug

In SS13, you could scroll back to a several minutes worth of chat logs to find something you want. Either it is because you yourself forgot about an IC thing or are trying to show logs to an admin to prove something. In US13 the chat logs don't expand very far for the end user and can only go so far.

### Steps to reproduce

1. Scroll up after a few minutes of nonstop talking and receiving messages.
2. Notice how short the chat log is

### PR DESCRIPTION
**Pull request by MaxIsJoe**
title. Closes #7222 

### Changelog:

CL: [Improvement] - Players can now choose how big their chat log history is.

### CODE REVIEW

**Comment by NoooneyDude** [comment]
The chat entry maximum count was limited as a temporary™ fix to performance issues. Have you tested with 250 entries?

**Comment by MaxIsJoe** [comment]
wrote a script to spam chat with random messages and 250 seemed to work fine and that's why I kept it as the default for now. But I still gave the ability for people to increase and decrease the chat limit to their own liking.

**Comment by NoooneyDude** [comment]
Great, thank you.

**Comment by NoooneyDude** [comment]
Reminder from Discord: make setting persistent

**Comment by MaxIsJoe** [comment]
> Reminder from Discord: make setting persistent

Done and tested twice now. We can go for one more review then merge.

**Pull request merged**
