### PR TITLE
MORE Vending Items and Ghost speed

### LINKED ISSUE #2923: Make ghosts move 3x faster
Because going at walking speed you can barely keep up with people and there's no possibility to follow shuttles.

### LINKED ISSUE #2951: Suggestion: More foods/drinks to vending machines.
So we are not forced between beef jerky and cookies.

### PR DESCRIPTION
**Pull request by Emma3DSS**
# MORE Vending Items and Ghost speed

### Purpose
Grants Nukies the ability to vend 1 emag which will let them disable safeties on shuttles.
Adds more food to vending machines
Increases Ghost SPEED
Fixes #2951 
Fixes #2923 

### Notes:
All relevant info is above

### Please make sure you have followed the self checks below before submitting a PR:

- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor

### CODE REVIEW

**Comment by JesterX666** [comment]
Review in progress

**Comment by JesterX666** [comment]
That's weird.  It seems that the ghost speed isn't working.  It's becoming slower and jittier.

Ghost

**Comment by JesterX666** [comment]
If we compare to my alive speed:
Alive

**Comment by Emma3DSS** [comment]
ghost speed weird

**Pull request merged**
