### PR TITLE
Seed packets

### PR DESCRIPTION
**Pull request by Raptorizer**
# Pull Request Template

### Purpose
Added proper descriptions and names to seeds  and seed vendor from #2556 
### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by chairbender** [comment]
I see that new avatar, pretty cool. Reviewing...

EDIT: Or maybe it isn't new and I'm just noticing it now. Looks cool nonetheless

**Comment by chairbender** [comment]
Oh wow, and it looks like you converted them to be prefab variants which is great. Now they can actually be spawned by the dev spawner.

**Comment by chairbender** [comment]
I'll still merge this but @Raptorizer for future reference, all files should follow the naming convention of UppercaseCamelCase (like "SomePrefab.prefab"). The lowercasing and the spaces can someties screw with version control and certain operating systems. I know the plant data assets were like that to begin with so wanted to make sure you're aware it was just a mistake on our part awhile ago. I don't think this will cause issues as is.

**Comment by chairbender** [comment]
Good to merge, thanks again!

**Comment by fomalsd** [comment]
sorry for misinformation, I think it was me who advised naming these in lowercase 👀

**Pull request merged**
