### PR TITLE
Create wiki page

### LINKED ISSUE #2491: Setup better wiki page
# Description

The current problem is that you need write access to the repository to add stuff
It makes it a pain to add stuff from Part-time devs

There are suggestions of using hackmd.io for the wiki page, But going through the current github PR system might be good as well

### PR DESCRIPTION
**Pull request by christmoore**
### Purpose
_Creates a dedicated wiki page for the project. This wiki page is generated from markdown files held within docs/ folder. GitHub Pages is leveraged to deploy this wiki using a dedicated gh-pages branch which will contain all of the compiled mkdocs pages. These pages are automatically built when pushes or merges are performed on the develop branch, where a mkdocs container is then used to push the compiled wiki page onto the gh-pages branch. This branch is used to deploy the GitHub Pages site defined in the repository settings._<br>
_Fixes #2491 and #2450_

### Notes:
_I need to work with Doobly on getting the secret generated for use by the GitHub Actions script. Without it, GitHub Pages will not be automatically deployed, only built. Details can be found here: https://github.com/marketplace/actions/github-pages-deploy_

Example Wiki Page found here:  
https://mrmanicotti.github.io/unitystation/

### CODE REVIEW

**Comment by christmoore** [comment]
@DooblyNoobly I need you to perform the following:
1. Create this github action:  

```
name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: 'develop'

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

```

2. Create your secret for the repository:  
  
> You therefore have to create a custom Personal Access Token (PAT) much like you'd do for external services (say, Travis). This token must be created with repo permissions in order to deploy to Github Pages. You then have to paste this token into the GitHub UI as a secret under the name GH_PAT (repository settings/secrets) and call it in the action as in the below.

https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

**Comment by christmoore** [comment]
Also, make sure to enable gh-pages in the repository settings. Have it point to the gh-pages branch.

**Comment by chairbender** [comment]
looks great

**Comment by DooblyNoobly** [comment]
I'll make a separate branch for PRing too for beginning the action as every push to develop will trigger it

**Pull request merged**
