### PR TITLE
Removes Polly from Outpost

### PR DESCRIPTION
**Pull request by Ranzarth**
### Purpose
He is too powerful, and broken.

He can currently open shutters by touching them, which happens when he is moving around or is pushed into one. Also he has no animations and just looks strange atm.

The other mobs probably have the same issue, but polly is the most profound

### CODE REVIEW

**Comment by waffielz** [comment]
remove him from all maps

**Comment by wraith-54321** [comment]
Polly is female

**Comment by waffielz** [comment]
no u

**Comment by DTraitor** [comment]
> remove him from all maps

don't do it

**Pull request merged**
