### PR TITLE
Cherry-pick #6928

### PR DESCRIPTION
**Pull request by craftxbox**
### Purpose
Cherrypick #6928 to this branch

### CODE REVIEW

**Comment by corp-0** [comment]
I'm adding a DNM until the issues with lizard-vulps are solved

**Comment by corp-0** [comment]
is it working now after the last commit?

**Comment by craftxbox** [comment]
Shit, sorry, I didnt mean to push that, it's one of the commits nessecary but no, not yet

**Comment by NoooneyDude** [comment]
I guess this is no longer relevant?

**Comment by craftxbox** [comment]
Yeah probably not.

**Pull request closed without merging**
