### PR TITLE
Fixing the massive text size

### PR DESCRIPTION
**Pull request by YunoGasai9862**
### Purpose
Fixes the issue: #8282 (Text's size)

CL: [Improvement] Tweaked player list UI size so it isn't huge anymore.

Below are the screenshots:

They pretty much resize with the dimensions of the window.

EDIT: I have made the box smaller, and it looks better now.

Screenshot (408)

### CODE REVIEW

**Comment by corp-0** [comment]
hey, thank you for contributing it. I was also midly annoyed by the size of that UI. Can you include a couple pictures in the PR description? Also, how does the new size behave if you resize the game window?

**Comment by YunoGasasi9862** [comment]
> hey, thank you for contributing it. I was also midly annoyed by the size of that UI. Can you include a couple pictures in the PR description? Also, how does the new size behave if you resize the game window?

Here are a few screenshots.

Screenshot (396)
Screenshot (397)
Screenshot (395)

**Comment by YunoGasai9862** [comment]
> hey, thank you for contributing it. I was also midly annoyed by the size of that UI. Can you include a couple pictures in the PR description? Also, how does the new size behave if you resize the game window?

I have attached the screenshots now.

**Comment by YunoGasai9862** [comment]
Btw, how long the merge takes? @Bod9001

**Comment by MaxIsJoe** [comment]
It depends on how free the maintainers are to review your PR

also, since you've made the text smaller; reduce the box's size as well and align things correctly because now it looks bad.

**Comment by YunoGasai9862** [comment]
Will do so. Thanks for pointing it out, yeah it does look bad though.

**Comment by Bod9001** [comment]
yeah, I would make the box smaller

**Comment by YunoGasai9862** [comment]
> yeah, I would make the box smaller

Done.

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
