### PR TITLE
Turn boxes, toolboxes, and backpacks into variants (includes scene changes).

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR cleans up cardboard boxes, toolboxes, and backpacks by turning most of them into variants of parents.

Since I had to create variants and replace the old .prefabs, **I modified several scenes in order to replace any old boxes, toolboxes, and backpacks** with the new variant versions. I also had to modify populators and vendors to use the new variants as well.

Also updates the sprites for shotgun shell boxes and gives some backpack sprites proper formatting.

### Notes:
I also happened to make the layer for the illustrations that appear on boxes 41 instead of 40, like the latches on toolboxes. While this makes said illustrations actually appear, they render over other items such as glass sheets as a result.

### CODE REVIEW

**Comment by Bod9001** [comment]
Did you remember to refill out the job populaters?

**Comment by PetMudstone** [comment]
I did in fact refill the job populators. I did several local tests to see which references broke after removing .prefabs so I could fix said references.

**Comment by Bod9001** [comment]
oops Sorry conflict

**Comment by PetMudstone** [comment]
oh god all i did was merge in order to try to resolve a conflict with one file and now this has happened

**Comment by PetMudstone** [comment]
Back to normal now. That was messy. I don't want to do that again.

**Comment by Bod9001** [comment]
oof ok, I will wait for the test to finish

**Comment by corp-0** [comment]
tests passed and there are no conflicts. This change should be high priority to merge since it has prefabs and scenes changes that will affect other prs for sure.

**Comment by Bod9001** [comment]
dam it, map conflicts

**Comment by PetMudstone** [comment]
It's ready, again.

**Pull request merged**
