### PR TITLE
Fixes pipes sprites on shuttle rotations

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes pipes sprites on shuttle rotations
Pipes will now use their registerTile position to set their sprite.
Removes the SpriteMatrixRotation from pipes and the requirement of them in ItemAttributes.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
commit says server player but its both client/server, fixed it and forgot to change that
I'm thinking on renaming the bitflag later on so it isn't also called direction, but for another PR

### CODE REVIEW

**Comment by Jibbajabbafic** [comment]
I like what you've done with atmos pipes so far but I don't think removing SpriteMatrixRotation from the required list for items is a good solution. 

When pipes aren't anchored they don't rotate like normal objects should:
eCJgJTc98i

You could argue that they should keep their rotation even when anchored, but 99% of items will still need that behaviour so you're removing a big safeguard for new people creating items.

You could easily change it to enable/disable the SMR component when anchoring so I suggest doing it that way:
eJCNwci2jv

**Review by Jibbajabbafic — CHANGES_REQUESTED** [review]
See other comment

**Comment by Aranclanos** [comment]
I like them not rotating when not anchored I think it looks better, plus it wouldnt drive you crazy if you're building and someone turns the ship

**Comment by Aranclanos** [comment]
I'll readd the requirement and just disable it for pipes

**Comment by Jibbajabbafic** [comment]
Sounds good, ty

**Comment by Aranclanos** [comment]
At the end I can't do that easily so i'd rather get this merged as it is

**Pull request merged**
