### PR TITLE
OOC Help selection UI

### PR DESCRIPTION
**Pull request by craftxbox**
### Purpose
Replaces the non-descript A-HELP and M-HELP buttons in the chat window with just 'HELP'
Adds a new window to select between Admin and Mentor help, with explanation of what and why you would choose one of the the other

### Notes:

Becomes

The window itself:

Escape menu changes:

### Changelog:
CL: [New] OOC Help selection window
CL: [New] Help button in Escape menu.
CL: [Improvement] A-Help and M-Help buttons replaced with a single HELP button
CL: [Fix] Add missing entry for Mentorhelp keybinds

### CODE REVIEW

**Comment by craftxbox** [comment]
tests are failing due to code out of my control

**Comment by PerfectTangent** [comment]
good changes, I like the addition of the help button to the escape menu. That's a useful kind of redundancy.

**Review by Bod9001 — APPROVED** [review]

**Comment by Bod9001** [comment]
waiting on testing from craft box they want to it test quickly

**Comment by craftxbox** [comment]
ready to merge, my test originally failed but after trying to debug it went away and is not replicable since.

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
