### PR TITLE
Fix secured objects considered as cargo, entering closets with magboots

### LINKED ISSUE #7617: players with active magboots cant go inside lockers
### Environment
- Game Version: Staging 21101813
- OS Version: Arch Linux

### Detailed description of bug

if you have mag boots active your character doesn't go inside lockers

https://user-images.githubusercontent.com/80334192/137836660-0a09675f-bbf8-45fb-8346-ccbd122736a6.mp4

### Steps to reproduce

1. get the drip
2. activate drip
3. your drip is too strong you cannot go inside lockers now

### PR DESCRIPTION
**Pull request by NoooneyDude**
CL: [Fix] Secured objects, such as conveyors, are no longer considered cargo and so won't be sold.
CL: [Fix] Fixes being unable to enter closets with magboots enabled (closes #7617).

### CODE REVIEW

**Comment by PerfectTangent** [comment]
so, I was talking with @corp-0 about the cargo selling thing. checking if an object is secured solves a lot of the existing problems with cargo, but it may be desirable to make whether something is sold a toggleable attribute so we have maximum control over what is and isn't sold by the shuttle.

**Comment by NoooneyDude** [comment]
> so, I was talking with @corp-0 about the cargo selling thing. checking if an object i secured solves a lot of the existing problems with cargo, but it may be desireable to make whether something is sold a toggleable attribute so we have maximum control over what is and isn't sold by the shuttle.

Can you think of something that'll use it - perhaps in the future - ? Else I'd rather just add that function when required, if I'm honest.

**Comment by PerfectTangent** [comment]
well, I don't think it's optimal to sell just about anything that doesn't have an export value.

**Comment by corp-0** [comment]
This won't sell anything that's secured to the floor, regardless of export value

**Comment by NoooneyDude** [comment]
> This won't sell anything that's secured to the floor, regardless of export value

That's right. Do you think that is an issue?

**Comment by corp-0** [comment]
> > This won't sell anything that's secured to the floor, regardless of export value
> 
> That's right. Do you think that is an issue?

No, I think I misread Jack. Will you change this to don't sell stuff without selling value?

**Review by Bod9001 — DISMISSED** [review]

**Comment by NoooneyDude** [comment]
Cargo code is nightmare fuel.

**Review by Bod9001 — APPROVED** [review]

**Comment by ThatDan123** [comment]
Codacy wants you to use a string builder

**Comment by corp-0** [comment]
in codacy we trust

**Comment by NoooneyDude** [comment]
I think refactoring it to use SB would require touching more files. Can we let it slide? This PR was originally small ; )

**Review by Bod9001 — APPROVED** [review]

**Comment by Bod9001** [comment]
Didn't see who the original approvals was and wondered why It didn't work xD

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
