### PR TITLE
New airlock variants and airlock assembly tweaks.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Adds a few new airlock variants using the new airlock base introduced in #5030.
- Adds some sprites to the sprite catalogues of the airlock assemblies, for future usage.

### Notes:
- Incapable of properly testing due to current status of my primary desktop computer. Additions and modifications were done on a much less powerful laptop.

### CODE REVIEW

**Comment by corp-0** [comment]
Thanks. I can give it a look in editor tomorrow. Did you add the animations? What do you think about the animation workflow now?

**Comment by PetMudstone** [comment]
I did add all the relevant sprites to the sprite catalogues in the .prefabs, yes. I did miss a few since the sprites are absent for some reason in both here and in /tg/. A bit tedious to work with, but at least I can actually work with it unlike the old airlock animator. Doesn't help that all the damn airlock overlay files are named the same so I had to look at file paths.

We could use a generic sprite SO for a blank sprite, come to think of it. I'm not sure how to deal with airlocks that lack filling sprites so I just filled all the catalogue fields with the same open panel "sprite".

**Comment by corp-0** [comment]
Absolutely, a generic empty sprite we all know about is a very good idea. Would you mind doing a copy of the open panel but name it something everyone can understand as an empty sprite?

**Comment by PetMudstone** [comment]
I'd make a blank sprite if my spare laptop wasn't busy importing right now, so I'm not quite capable of doing so at the moment.

**Pull request merged**
