### PR TITLE
Bettter light sprite for Lasers

### PR DESCRIPTION
**Pull request by Bod9001**
new
image
old 
image

### Changelog:
CL: [Improvement] Bettter light sprite for Lasers 
CL: [Improvement] Darker spaces Should look less crunchy

### CODE REVIEW

**Comment by corp-0** [comment]
do you mean lights when you say "lease"?

**Comment by Bod9001** [comment]
corrected

**Comment by eurtod** [comment]
What do you mean by crunchy? Like jarring when it transitions?

**Comment by Bod9001** [comment]
looking like it's been compressed Through YouTube

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
