### PR TITLE
 unity been complaining about some stuff so  time to reserialise

### PR DESCRIPTION
**Pull request by Bod9001**

### CODE REVIEW

**Comment by corp-0** [comment]
if we merge this before what other peopel are working on, will their local break?

**Comment by Bod9001** [comment]
shouldn't do , the only worry is merge conflicts?

**Comment by corp-0** [comment]
from what I understand reserialising gives all tracked files a new id and all, doesn't it? I'm just worried about people losing their work because something stupid like missing references

**Comment by Bod9001** [comment]
it just causes unity to look at every file and do the changes that haven't been tracked over time, such as new fields being added to scripts and stuff

**Comment by Bod9001** [comment]
image
all stuff like this

**Review by corp-0 — DISMISSED** [review]

**Comment by corp-0** [comment]
merging, if shit gets utterly broken I backpedal

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
