### PR TITLE
Adds department and special roles spawn sounds, also fixes a tiny issue

### PR DESCRIPTION
**Pull request by MrAsbestos**
### Purpose
This PR adds spawn sounds for every department and also for special roles (like the ERT and Deathsquad), also fixes an issue with shutters and blast doors, they didn't have a close sound for some reason.

### Changelog:
CL: Added unique spawn sounds for every existing department and special roles.
CL: Fixed an issue with blast doors and shutters sounds.

### CODE REVIEW

**Comment by Bod9001** [comment]
where you do get the  sounds/licences/permission?

**Comment by Bod9001** [comment]
otherwise PR is good

**Comment by PerfectTangent** [comment]
> where you do get the sounds/licences/permission?

conveniently, @MrAsbestos provided me an extremely detailed report of the sources of all his material.

**Comment by PerfectTangent** [comment]
> --Sounds used for Deathsquad spawn--
> 
> -Intro, Explosion (mostly works as a "Dun...." for suspense): Used the old explosion far sound from SS13 (fetched from VG)
> 
> -Mid section, Drums: https://freesound.org/people/kiddpark/sounds/457210/ (used only 13 seconds of it)
> 
> -End, War cry: https://freesound.org/people/qubodup/sounds/184417/
> --Sounds used for Engineering spawn--
> 
> -Intro, drill: https://freesound.org/people/LuannWepener/sounds/326102/ (the sound is split into different parts)
> 
> -Mid section, Engineer ambience: Used the ambisin2 from SS13, sound that plays when you enter the engineering department in TG.
> 
> -Other sound, Alarm thing: Used ambimaint2 from SS13, sound that plays when you enter maintenance in TG, I splited the sound so you can only hear that tiny alarm thing.
> --Sounds used for ERT spawn--
> 
> -Intro, stomping: https://freesound.org/people/WebbFilmsUK/sounds/200321/ (used only 2 steps)
> 
> -End, police siren: https://freesound.org/people/guitarguy1985/sounds/70938/
> --Sounds used for Security spawn--
> 
> -Intro and ambience, ambience thing: Used ambigen5 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and other codebases (like VG) use this.
> 
> -Mid section, Sec Chatter: https://freesound.org/people/nnus/sounds/126526/
> 
> -End, radio beep: https://freesound.org/people/Kijadzel/sounds/170608/ (used only the ending part)
> --Sounds used for Service spawn--
> 
> -Intro, and ambience: Used ambigen4 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and other codebases (like VG) use this.
> 
> -Mid section, canteen and people sounds: https://freesound.org/people/Agonda/sounds/210589/
> 
> -Other sounds (In order, first to last)
> Eating food sound (eatfood, plays when you eat something), fetched from SS13 (99% of the codebases use this sound, including Unitystation).
> 
> Coin flip sound (coinflip, plays when you flip a coin), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> Drinking a liquid sound (drink, plays when you drink something), fetched from SS13 (99% of the codebases use this sound, including Unitystation).
> 
> Spraying something (spray2, play when you spray something with a sprayer), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> Bike horn sound (honk, plays when you honk the famous clown horn), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> -End, Ding sound (microwave-end, plays when a microwave end it's cooking process), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> --Sounds used for Command spawn--
> 
> -Intro, ambience: Used ambigen15 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and some codebases (idk how many) use this.
> 
> -Mid section, office sounds: https://freesound.org/people/Nightwatcher98/sounds/407292/ (splitted, starts at like 11 seconds in)
> 
> -Other sounds
> Chatter: https://freesound.org/people/DRFX/sounds/353712/ (cutted out the parts with static)
> 
> -End, phone beep: https://freesound.org/people/Kijadzel/sounds/170608/ (yup that's a radio, used only the beginning, really sounds like a phone)
> --Sounds used for Assistant spawn--
> 
> -It's only one sound, ambience: Used ambigen4 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and other codebases (like VG) use this.
> --Sounds used for Cargo spawn--
> 
> -Intro and ambience, ambience thing: Used ambigen5 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and other codebases (like VG) use this.
> 
> Mid section, cargo ambience: Used ambimaint3  from SS13, sound that plays when you enter maintenance in TG.
> 
> -Other sounds (In order, first to last)
> That ping sound (ping, plays on some machines or borgs, normally used for positive feedback, like something good happening), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> Alarm sound (ambimaint2, fetched from SS13, sound that plays when you enter maintenance in TG, I splited the sound so you can only hear that tiny alarm thing), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> Digging sound (picaxe1, plays when you use the pickaxe to mine something), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> -End, Another ping (terminal_success, plays when a terminal does something succesfully), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> --Sounds for Medical spawn--
> 
> -Intro (somewhat) and ambience, ambience: Used ambigen10 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and other codebases (like VG) use this.
> 
> -Mid section and end (they are various sounds) 
> Health monitor: https://www.videvo.net/es/efecto-de-sonido/monitor-de-hospital-02/427526/
> 
> Medical ventilator: https://www.videvo.net/es/efecto-de-sonido/ventilador-de-hospital-03/427557/
> 
> For the ending I just really reverbed the last health monitor sound
> --Sounds for Research spawn--
> 
> -Intro and ambience, ambience thing: Used ambigen6 from SS13, plays randomly when walking around the hallways of Space Station 13, TG and other codebases (like VG) use this.
> 
> -Mid section (used 2 sounds)
> Beeping and weird lab sounds: https://freesound.org/people/opticaillusions/sounds/522662/ (splitted)
> 
> Terminals and machinery ambience: https://freesound.org/people/BugInTheSYS/sounds/108287/
> 
> -Other sounds (In order, first to last)
> Weird beeping noises: https://freesound.org/people/JavierZumer/sounds/257228/
> 
> Monkey screaming (monkey_screech_6, sounds when a monkey is freaking pissed), grabbed it from TG, I don't know how many codebases use this.
> 
> Laser sound (laser3, plays when you fire a laser gun, another type of laser gun, not the normal ones), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> 
> Weird tech sound (flash, plays when the flash device is activated, a device which blinds an attacker or a victim....), fetched from SS13, grabbed it from TG, I don't know how many codebases use this.
> --Sound for Synthetic spawn--
> 
> Intro, eerie tech ambience: https://freesound.org/people/staticpony1/sounds/249593/
> 
> -Mid section (used 2 sounds)
> Beeping and weird lab sounds: https://freesound.org/people/opticaillusions/sounds/522662/ (splitted)
> 
> Computer and other terminal sounds: https://freesound.org/people/pj2105/sounds/426811/
> 
> -End (used 2 sounds, in order, first to last)
> 
> Robot saying "Say it" (reference to the malf AI spawn sound, don't worry, there's no way to get it confused with the antag one, the antag one sounds waaay more aggressive): https://freesound.org/people/deaf02/sounds/563028/
> 
> Weird robot noises: https://freesound.org/people/DRFX/sounds/353712/ (yup same one as the command, just heavily distorted, and splitted)

**Comment by Bod9001** [comment]
there we go, this should be good enough for reference

**Pull request merged**
