### PR TITLE
add GibbingAllowed to gameconfig file

### PR DESCRIPTION
**Pull request by corp-0**
### Purpose
Adds a new option to game config file so servers can allow or disallow gibbing people when they receive enough post-death damage.

This is a temporal fix for #4454 as many players have voiced their concern with how easy it is to gib people. Gibbin would get more complex with health rework #4100 

### Notes:
It is disabled by default so servers who are ok with current gibbin situation will have to manually change it.

### CODE REVIEW

**Comment by Bod9001** [comment]
I feel like after a bit this is going to go redundant, Since I think you should be never able to Gib someone?

**Comment by corp-0** [comment]
Yes. I honestly don’t know why it was implemented like that in the first place, so I did a toggle instead of getting rid of the feature.

**Comment by Bod9001** [comment]
are you willing to put in the extra work for making it so shuttles can still gib but players can't?

**Comment by corp-0** [comment]
Yes, sure

**Comment by corp-0** [comment]
found this in build log
```
2020-07-23T12:33:36.2202981Z Scripts have compiler errors. 
2020-07-23T12:33:36.2203653Z (Filename: ./Runtime/Utilities/Argv.cpp Line: 361)
2020-07-23T12:33:36.2203946Z 
2020-07-23T12:33:36.2207764Z 
2020-07-23T12:33:36.2208195Z Aborting batchmode due to failure:
2020-07-23T12:33:36.2208518Z Scripts have compiler errors.
```

**Comment by Bod9001** [comment]
try your own builds if it works?

**Comment by ThatDan123** [comment]
~Can you merge latest, so i can test without having to change 30000 files.~

**Comment by ThatDan123** [comment]
nvm, forgot i could merge it into a branch which is on latest.

**Comment by ThatDan123** [comment]
Ive built tested and it seems fine, no errors.

**Pull request merged**
