### PR TITLE
Remote signaller pairing for bombs, interactions and pizzabomb improvements and fixes

### PR DESCRIPTION
**Pull request by MaxIsJoe**
part of #6149 

after this is merged this should be the final thing for this bounty

CL: [Fix] fixed a number of bugs with remote signallers, C4, and Pizza bombs

### CODE REVIEW

**Comment by Bod9001** [comment]
tests feeling for some reason

**Comment by MaxIsJoe** [comment]
> tests feeling for some reason

unsure why

**Comment by Bod9001** [comment]
"Unhandled log message: '[Error] The same field name is serialized multiple times in the class or its parent class. This is not supported: Base(MonoBehaviour) GUI'. Use "

**Comment by Bod9001** [comment]
basically you're overwriting one of the names from an inherited class

**Comment by MaxIsJoe** [comment]
> "Unhandled log message: '[Error] The same field name is serialized multiple times in the class or its parent class. This is not supported: Base(MonoBehaviour) GUI'. Use "

You know, this would have been useful if it actually told me what class has this problem

**Comment by Bod9001** [comment]
IDE usually highlights it

**Comment by MaxIsJoe** [comment]
> IDE usually highlights it

Nothing in Rider

**Comment by MaxIsJoe** [comment]
Found the issue and fixed it, review pls

**Review by Bod9001 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]

**Pull request merged**
