### PR TITLE
More scores for the score machine

### PR DESCRIPTION
**Pull request by MaxIsJoe**
# Changelog:

CL: [New] Station getting nuked has a massive score penalty now.
CL: [New] Hugs are now recorded in the score machine.
CL: [New] Electrified doors from an AI are now recorded in the score machine.
CL: [New] When the big service bell Easter egg triggers, it will show up in the round end score screen.
CL: [Improvement] "Most hurt crewmember" score will only appear if there is a crew member below 50 overall health.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
CODACY, IM GOING TO KILL YOOOOUUUUU
image

**Comment by corp-0** [comment]
those look more like constant to me though

**Comment by MaxIsJoe** [comment]
> those look more like constant to me though

static because you can just do `RoundEndScoreBuilder.COMMON_SCORE_SOMETHING` instead of `RoundEndScoreBuilder.instance.COMMON_SCORE_SOMETHING`

**Comment by corp-0** [comment]
you can access constant members of a class without the singleton pattern

**Comment by MaxIsJoe** [comment]
oh shoot, you actually can

why cant there be a const for functions then

**Comment by corp-0** [comment]
because functions aren't values, they perform an operation and would, optionally, return a value form that operation. If you want to call a method from a class without instantiating it, you can make the function static but then you can't really access the class members that aren't also static.

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
