### PR TITLE
Variable viewer

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
To allow clients to view variables on the server, will be eventually upgraded to a variable editor as well

TODO
comments
any suggestions you guys have

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [Please Complain at me]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [see notes]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
due to me rebasing when Aranclanso managed to PR when something was faulty, you have to go to cloning console.cs and replace characterSettings = playerScript.CharacterSettings; with characterSettings = playerScript.characterSettings;

rebasing was a pain there was a lot of  conflicts last time I did it

variableviewer
for retrieving of values and cashing and data structure
GUI_variable viewer 
for displaying the values
bookshelf viewer for the bookshelf stuff

### CODE REVIEW

**Comment by fomalsd** [comment]
`This branch is out-of-date with the base branch`
it's a good idea to update your branch periodically

**Comment by Bod9001** [comment]
still needs the networking stuff and any suggestions you have and comments, but it's mostly finished and you can through the code and complainant me for anything I've done wrong

**Comment by Bod9001** [comment]
when you forget to remove logs

**Comment by DooblyNoobly** [comment]
image

This option opens the Dev Cloner window.

Also I had some errors when diving deep into the pen transform variables:
image

Please be aware of these issues and address them in new PR's. I'll merge this one to avoid conflicts with our work.

**Pull request merged**
