### PR TITLE
Reverse Animation

### LINKED ISSUE #8236: Security cameras do not have a full animation cycle.
### Environment
- Game Version: 22012720
- OS Version: Windows (server is headless/linux)

### Detailed description of bug

Security cameras only swing one direction, then awkawrdly snap back to their starting position instead of swinging back.

### Steps to reproduce

1.  Look at a security camera thats powered
2. Profit

### PR DESCRIPTION
**Pull request by ThatDan123**
Fixes #8236

### CODE REVIEW

**Comment by PerfectTangent** [comment]
lol, programmers are funny. You know you could have just duplicated the frames of the camera swinging in reverse to get it to loop correctly? Still, this could be useful for other applications in the future.

**Review by corp-0 — APPROVED** [review]
the update method has gotten rather complex and could use moving logic into methods to make it more readable but this is fine for now

**Comment by NoooneyDude** [comment]
There's a few sprites from /tg/ that would benefit from this option, though the camera was probably the worst offender. I can't think of the others right now : / Thanks ThatDan.

**Comment by NoooneyDude** [comment]
> There's a few sprites from /tg/ that would benefit from this option, though the camera was probably the worst offender. I can't think of the others right now : / Thanks ThatDan.

Ahh, the magic mirror and magic green book with the keyway on the cover... I forget the name.

**Review by NoooneyDude — APPROVED** [review]

**Comment by NoooneyDude** [comment]
Oh, the PACMAN too, yay!

**Pull request merged**
