### PR TITLE
Fixes lava acting as a wall

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Fix] - Fixes lava tiles acting as walls.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
ready for review

**Review by Alainx277 — DISMISSED** [review]
Looks good on the code side.

**Comment by Bod9001** [comment]
if (registerTile.Matrix.MetaTileMap.ObjectLayer.FloorHazardList == null) return; Will return before  the lava actually gets triggered, need to think of optimal way of doing this, since it's triggered every step

**Comment by MaxIsJoe** [comment]
I don't think there is an "optimal" way at all with how tilemaps are handled currently but at the same time the foreach almost never gets triggered as long as theres nothing to check for.

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
