### PR TITLE
Outpost station spring cleaning

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
for #2139 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [N/A]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
@Bod9001 can you have a go at resolving these conflicts? I can't do it by hand

**Comment by DooblyNoobly** [comment]
Can you go through and make the chairs face in the correct direction. These should be facing up: 
image

**Comment by DooblyNoobly** [comment]
hop needs a chair too: 
image

**Comment by DooblyNoobly** [comment]
seat should be facing desk: 
image 

I'd say just do a review of all chairs and adjust them

**Comment by DooblyNoobly** [comment]
hops light doesn't seem to work: 
image

**Comment by DooblyNoobly** [comment]
edit: nevermind found the cells. Very nice!

**Comment by DooblyNoobly** [comment]
btw love the scattered donuts everywhere lol

**Comment by DooblyNoobly** [comment]
amazing work bod. I loved that the cells face the hallway so people can speak to the prisoners. The tile fixes are great. The hidden surgery in maint is great. Capts shuttle dock is great. Overall its better then I expected. Get those other issues fixed up so we can merge asap

**Comment by fomalsd** [comment]
could you also perhaps place a locker in HoP's room with a few spare IDs inside?

**Comment by Bod9001** [comment]
cool cool will do

**Comment by Bod9001** [comment]
all done

**Comment by DooblyNoobly** [comment]
something weird going on with the pr. I'm going to merge with a separate branch off develop first

**Comment by DooblyNoobly** [comment]
I'm assuming you can't get the seats the right way? 
image

**Comment by Bod9001** [comment]
oof I think that might got lost in the fork fuckrey I did to get Rid of the merge conflicts, Will fix now

**Pull request merged**
