### PR TITLE
Better iOS support, RAM optimisations, UI improvements

### LINKED ISSUE #1591: Mobile/touchscreen support bugs
# Description
image
Here's a demo of game running on iOS with virtual gamepad that simulates key presses:
https://files.catbox.moe/520q9z.MP4

- Pressing gamepad buttons doesn't consume touch event (player always attempts to face your finger on gamepad), not reproducible w/mouse
- Touch presses duplicate key down events (not reproducible w/mouse)
- Pixel perfect camera is broken, can see texture leakage
- Throwing aim picks the first touch instead of the last one (will throw in direction of your finger on gamepad)
- CommonInput needs rightclick menu activation by holding finger on one spot for around 700ms
- Pressing `Equip-Clothing` button while holding gamepad button will not make gamepad depress

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
Prereqs:
- Not too slow iOS/Android device with at least 2GB RAM (Android 4+, iOS 9+)
- Installed Unity module to support building for your platform
- Installed dev tools for your platform (Xcode/Android SDK)

1. Switch to `ios` branch if you're on iOS, for Android you can stay at latest develop
2. Go to Build Settings and switch platform (takes time!)
3. Build and deploy it to your device (steps vary)

### PR DESCRIPTION
**Pull request by fomalsd**
warning: Lobby, UIManager changes!

Scr

fixes #1591 
phone UI support: smart UI scale, notch detection
shaved off ~400mb RAM for iOS
ability to host a server on 3gb RAM iOS devices (memory consumption is now below 1,8gb limitation)
prettier virtual joystick

more consistent Midnight UI style
ability to Start Now when hosting locally without pressing F7

### CODE REVIEW

**Comment by Bod9001** [comment]
wonder if it's the atlas issue again

**Comment by ThatDan123** [comment]
Ive rerun it to see if that'll fix it.

**Comment by ThatDan123** [comment]
If the tests fail this time then it might be compile issues, as other PRs rerunning the tests fixed them.

**Comment by Bod9001** [comment]
I think it's atlas cash issues

**Comment by Bod9001** [comment]
I'll try looking at the branch and doing a manual trigger of the atlases if it doesn't work and pushing that

**Comment by Bod9001** [comment]
ok, this makes no sense

**Comment by fomalsd** [comment]
was pretty sure that it previously failed win and mac but built linux, now it’s the opposite lol

**Comment by Bod9001** [comment]
you think it's okay to merge?

**Comment by fomalsd** [comment]
yeah, it should be fine
though its’s strange that rerunning jobs for this one is like throwing a dice, every time result is different

**Pull request merged**
