### PR TITLE
Vote yes immediately to save clicks

### LINKED ISSUE #7385: You should automatically vote "Yes" when you click restart vote in menu while vote is active
### Description

Saves clicks

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes #7385

CL: [Improvement] The player that starts a restart vote automatically votes yes

### CODE REVIEW

**Comment by ThatDan123** [comment]
This will set everyone to Yes, the issue only wanted the person who made the vote to have Yes selected. 

Gonna say it'll be more annoying for someone to ask for a reset then everyone having to press No than the opposite tbh

**Comment by ThatDan123** [comment]
Add a new Target Rpc in the VotingManager for the player who requests the vote to set their vote to Yes. Call it after the all player Rpc line 103.

https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Systems/Voting/VotingManager.cs

To get the player who sent the command to start the vote you need to add a network connection parameter to the command see the commands in the admin commands manager

**Comment by Bod9001** [comment]
humm, wouldn't it be better to have it if they haven't chosen option defaults to yes? vs voting yes

**Comment by MaxIsJoe** [comment]
> This will set everyone to Yes, the issue only wanted the person who made the vote to have Yes selected.
> 
> Gonna say it'll be more annoying for someone to ask for a reset then everyone having to press No than the opposite tbh



> humm, wouldn't it be better to have it if they haven't chosen option defaults to yes? vs voting yes

I thought the same but I'm leaving that for my voting system overhaul along side the rest of the tips and admin QoL to-do list

**Comment by NoooneyDude** [comment]
> humm, wouldn't it be better to have it if they haven't chosen option defaults to yes? vs voting yes

I disagree with this. Doing nothing should indicate business as usual.

**Comment by Bod9001** [comment]
is this for the person who initiated the vote?

**Comment by NoooneyDude** [comment]
> is this for the person who initiated the vote?

Oh, for the person starting the vote, sure, they should automatically register as yes.

**Comment by corp-0** [comment]
I think this is fine

**Review by corp-0 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]

**Comment by Fogapod** [comment]
does this implement both things? I posted 2 different feature requests in issue:
- vote YES when starting vote
- vote YES when vote is active and you try to start vote from menu

**Pull request merged**
