### PR TITLE
fixes clothing not refreshing properly

### PR DESCRIPTION
**Pull request by Bod9001**
changes light sprite,
adds colour picker to VV
fixes UI actions
fixes clothing not refreshing properly
addeds Mono behaviour manager Singleton tho tried implementing it but you UI manager had issues for some reason

### CODE REVIEW

**Comment by corp-0** [comment]
if the singleton doesn't work, remove the class to avoid anyone of using it thinking it does. Then we merge.

**Comment by Bod9001** [comment]
Singleton does work, it's just some classes do accessing in a strange way/strange times/custom cleaning up

**Comment by ReiderJack** [comment]
If it's not used anywhere, no point keeping it imo

**Comment by Bod9001** [comment]
ok done

**Comment by NoooneyDude** [comment]
Fixed by #5024.

**Pull request merged**
