### PR TITLE
Discord Rich Presence

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [New] Unitystation now has discord rich presence. Show off which server and map you're playing on, and for how long as well.

### CODE REVIEW

**Comment by corp-0** [comment]
@Bod9001 how can we make scan code happy here? It would be cool to merge this for this weeks playtest

**Comment by Bod9001** [comment]
oh sorry for taking so long

**Comment by Bod9001** [comment]
Sandbox violation: Method has illegal MethodAttributes: Discord.Discord.DiscordCreate(unsigned int32, Discord.Discord/FFICreateParams&, native int&) Returns Discord.Result  in Assembly Assets 
so, It will need to be wrapped in a secure stuff handler

**Comment by Bod9001** [comment]
looks  like you'll have to move all the library stuff into secure stuff and then poke a few holes ffor access

**Comment by MaxIsJoe** [comment]
Closing this because It's frustrating to get it working, will move this over to stationhub when we actually are going to push an update for it.

**Pull request closed without merging**
