### PR TITLE
Adds more chemistry reactions and metabolic system 

### PR DESCRIPTION
**Pull request by Bod9001**
humm llooks like commits got a bit funny,

as metabolic system,
adds reactions for
AmatoxinInBody
Anti-ToxinInbody
BadFoodinBody
BicaridineInBody
CarpotoxinInBody
ClonexadoneInBody
CryoxadoneInBody
KelotaneInBody
PestKillerInBody
Plant-B-GoneInBody
PoloniumInBody
PotassiumIodideInBody
TirizeneInbBody
ToxinInBody
TricordrazineInBody
WeedKillerInBody

fixes character customisations not working, 

requested changes will be done tomorrow

### CODE REVIEW

**Comment by corp-0** [comment]
Will this fix conflict with max’s Pr?

**Comment by Bod9001** [comment]
#6298?

**Comment by MaxIsJoe** [comment]
what does this exactly fix that isn't fixed in #6282 ?
Character's can be randomized and Bod pushed a fix that let people spawn with their character sheets, was there something else broken?

**Comment by Bod9001** [comment]
I think only partially fixed it there was 2 fixes but I missed one
first bug  body part not getting added to implant list
second bug checking the wrong field on lobby customisation

**Pull request merged**
