### PR TITLE
Fix guns but for real

### PR DESCRIPTION
**Pull request by AutumnNova**
CL: adds clown clumsy behaviour with guns
CL: adds id locks for weapons
CL: fix pkas

### CODE REVIEW

**Comment by ThatDan123** [comment]
Can you build test this

**Comment by AutumnNova** [comment]
i dont have enough ram, kernel would segfault if i tried

**Comment by ThatDan123** [comment]
Ok, can someone if they have time build test headless with two clients.

**Comment by Bod9001** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- UnityProject/Assets/Scripts/Items/Weapons/GunElectrical.cs  2
         

Complexity decreasing per file
==============================
+ UnityProject/Assets/Scripts/Items/Weapons/GunPKA.cs  -3
         

Clones removed
==============
+ UnityProject/Assets/Scripts/Items/Weapons/GunPKA.cs  -1
+ UnityProject/Assets/Scripts/Items/Weapons/Gun.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/unitystation/unitystation/pullRequest?prid=6397069&bid=20742999)

**Comment by Bod9001** [comment]
it seems to get stuck on
public MagazineBehaviour CurrentMagazine =>
			magSlot.Item != null ? magSlot.Item.GetComponent<MagazineBehaviour>() : null;
idk if it's just my editor being strange

**Comment by corp-0** [comment]
Nooney also mentioned the build getting stuck

**Comment by Bod9001** [comment]
is this on this PR? like Happens inside of the editor to?

**Comment by NoooneyDude** [comment]
I didn't try running the PR in the editor, I immediately built it.

**Comment by NoooneyDude** [comment]
I tested shotguns and energy carbines on headless. While the carbine fires now (at least for the local client - perhaps not server), both projectiles are back to being invisible for the second client. No related errors on either client or the server. I also noticed the carbine projectile does not despawn on collision.

**Comment by AutumnNova** [comment]
right, this should be good to go

**Comment by NoooneyDude** [comment]
Still broken for other clients on headless.

**Comment by NoooneyDude** [comment]
Looks like clients now see all projectiles, however, the second clients don't seem to display the correct projectile when the fire mode on an energy weapon is swapped. They still show the initial projectile. Not as big of an issue, this PR is still an improvement.
The other clients still complain about `CurrentMagazine` being null, but at least they correctly appear.

**Pull request merged**
