### PR TITLE
Fixes ash drake and blood miner broken prefabs

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes ash drake and blood miner sprites being invisible and not having a prefab tracker

### CODE REVIEW

**Comment by PetMudstone** [comment]
How did you fix the sprites? I tried looking at it before but couldn't figure out what was wrong.

**Comment by MaxIsJoe** [comment]
> How did you fix the sprites? I tried looking at it before but couldn't figure out what was wrong.

Simple, there were no sorting groups so they just looked invisible. Adding one and setting them to NPC fixes them

**Comment by MaxIsJoe** [comment]
image

look at them!

**Review by corp-0 — APPROVED** [review]

**Comment by PerfectTangent** [comment]
is the leaper sprite still invis, as described in #5289? I presume so. Perhaps it needs the same treatment.

**Comment by MaxIsJoe** [comment]
> is the leaper sprite still invis, as described in #5289? I presume so. Perhaps it needs the same treatment.

ah, i didn't look at the leaber, will open a PR for it soon.

**Pull request merged**
