### PR TITLE
Banana peel from banana

### LINKED ISSUE #3293: Bananas dont make banana peels when eaten.
This makes it heartbreaking when someone steals your banana peel as clown.

### PR DESCRIPTION
**Pull request by ReiderJack**
# Pull Request Template

### Purpose
Make clowns happy
fixes #3293

### Notes:
PeelBanna

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Review by vlandemart — APPROVED** [review]

**Comment by DooblyNoobly** [comment]
err what is wrong with that gif?

**Comment by ReiderJack** [comment]
It's not the gif. All growing plants are acting so when you gather them.

**Comment by ReiderJack** [comment]
fixes #3293

**Comment by ThatDan123** [comment]
Dancing Plants.

**Comment by DooblyNoobly** [comment]
testing it on staging

**Pull request merged**
