### PR TITLE
Smexy Pog Engineering Update

### PR DESCRIPTION
**Pull request by SluggyWuggies**
Changes: Yes, please.
Updates Pog Engineering, completely tearing out the old, ugly layout, with a new, fully reworked one. 
Addresses issue #6038 
Adds spess suits out of lockers, just in time for a rework. 
Slight lighting changes. 
Adds the secret sauce. 
Small changes to canteen.
Adds Singulo, Tesla, PA, and other fun stuff. 
Changes to engineering dock. 
image
Look at how beautiful she is!
image
PA System for quick and easy setup!
image
This is where the "Magic" happens. 
And by magic, we mean "Mutilation Assisted by Generator Incompetent Crewmates."
image
I'm sorry for this one, actually.
image
Engineering has _never_ looked this passable!
And neither have I-
Welp, that seems like all for this update. I hope you enjoy!

### CODE REVIEW

**Comment by SluggyWuggies** [comment]
damnit, what failed

**Comment by ThatDan123** [comment]
PogStation: "LightTubeFixture (1)" miss switch reference.

**Comment by SluggyWuggies** [comment]
I know exactly which one...

**Comment by corp-0** [comment]
your finger is safe... For now.

**Pull request merged**
