### PR TITLE
Fixed Issue #2032; Players can now move when cuffed

### LINKED ISSUE #2032: Handcuffs stop player movement B: 35
# Description
Players should still be able to move when handcuffed, but any hand interactions should be disabled (in inventory and in the world). 

The only time they can't move is if the player is being dragged by someone else as well. The handcuffed player shouldn't be able to break pulls either.

Edit: 
When Doobly made #1935 he specified that cuffs should stop movement which isn't the case in /tg/

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get handcuffed
2. Try to move

### PR DESCRIPTION
**Pull request by JohnHandley**
Removed the check for the handcuffs when attempting a move.

### Purpose
Fixes #2032

### Notes:
Don't care about any bounty, just wanted to try out contributing if it's useful.

### CODE REVIEW

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]
The cuffed player shouldn't be allowed to move if he is being dragged by another player or is buckled to a chair or bed

**Comment by JohnHandley** [comment]
Ah, I see, will try to correct it.

**Comment by JohnHandley** [comment]
I believe the latest commit resolves the requested change.

**Comment by DooblyNoobly** [comment]
cool thanks

**Comment by DooblyNoobly** [comment]
Reviewed it again and it seems to introduce a player sync bug.

Too recreate:
1) Make a build and host a game
2) connect with editor
3) get some handcuffs while playing as the editor player and handcuff the other player
4) start dragging the player
5) switch to build and run away
6) notice that you can run away while cuffed and that it also breaks the player sync

A gif of the bug:
movebug

**Comment by fomalsd** [comment]
thing is, client thinks it's allowed to move predictively.
need to check for handcuffs on clientside, too, and don't allow predictive movement if cuffed and pulled by someone.
it's something among these lines: 
https://github.com/unitystation/unitystation/blob/a7eae55556775256a378949378a95d22c2379bbb/UnityProject/Assets/Scripts/Player/PlayerSync.cs#L486-L526
should avoid calling DoAction() in that particular case, either by setting `didWiggle` to true or otherwise

**Comment by JohnHandley** [comment]
Thanks, I'll try to fix that. Thanks for the tip!

**Comment by JohnHandley** [comment]
I switched to use the what I believe is the client version of the beingPulled check which seems to resolve the syncing issues. I could be approaching this the wrong way. Still figuring out the client and server relationship but this seems to work so far.

**Comment by DooblyNoobly** [comment]
Thank you, its all working now

**Pull request merged**
