### PR TITLE
PogStation Medical and Lighting changes

### PR DESCRIPTION
**Pull request by SluggyWuggies**

### CODE REVIEW

**Comment by wraith-54321** [comment]
great name but uh, what is it

**Comment by corp-0** [comment]
Slug I added a DNM tag until you:
1- Name the Pr something we can understand 
2- Add a little description
3- see what’s up with tests

**Comment by SluggyWuggies** [comment]
Here- I'll just make a new one when I finish up some things I suppose.

**Comment by SluggyWuggies** [comment]
An update on some changes to PogStation Medical and Lighting, namely:
- Renovating the entire medical department with a more practical, and hopefully more efficient design.
- Addressing issue #4849, fixing the lighting around the station.
- Getting the map into a playable state, some slight alterations to a few departments and hallways.
- Adds some fun secret stuff.

**Comment by corp-0** [comment]
way better, only the tests fix is missing

**Comment by corp-0** [comment]
@craftxbox can you help slug on using your merge conflict tool? This is conflicting with #5802 which is just assigning Id numbers and should be able to be solved without problems.

**Comment by Aranclanos** [comment]
I just redid my changes on his version of the map and made a pr to his branch so that should be solved

**Comment by corp-0** [comment]
Beautiful, thank you very much

**Comment by craftxbox** [comment]
> @craftxbox can you help slug on using your merge conflict tool? This is conflicting with #5802 which is just assigning Id numbers and should be able to be solved without problems.

what tool? the one i had added previously didnt function as expected, so i removed it. I ended up reverting all my prefabs and rebuilding them manually.

**Comment by corp-0** [comment]
yes, sorry about the ping. The problem was solved. Thanks for answering, I will remember we don't have the tool the next time we get to the same problem.

**Pull request merged**
