### PR TITLE
Square and additional scenes updated to doors V2 + silo

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

This PR updates Square station and all additional scenes except the Fall station syndicate scene to Doors V2. I also made a medium quantity of small other changes to Square and some of the additional scenes and added a tiny amount of prefab variants for SSUs. Makes progress on #6554.

### Notes:

- fixed _a lot_ of stuff that was fucked up with the Centcom scene.
- Gary the Guard borg has been confined to Centcom's attic for the safety of visiting personnel.
- removed the deathsquad hardsuits and disruptor cannons that could just be freely taken by ERT personnel in Centcom.
- added a couple new suit storage units for ERT hardsuits. Also mapped a few of them into Centcom and Fall station centcom where ERT hardsuits were previously stored.
- slightly increased the size of R&D in Square and replaced all of the science walls with rwalls.
- added a few APCs to Square's maintenance halls.
- added a mineral silo to Square's vault.
- fixed a couple weird bits of Lavaland's mining base layout.
- removed the old mining equipment vendors in Lavaland and replaced them with the new version.
- liberally added ore boxes to lavaland.
- reworked both syndicate Outpost and syndicate Pog a bit, and removed all of the old legacy weaponry vendors and lockers in them. Removed a total of about _30_ stalker SMGs from both scenes combined. They aren't needed since nukies have the majority of their intended equipment available now in the uplink, which they should be paying for. I did leave a small number of weapon lockers in the very back of the syndicate Outpost scene.
- slightly reoriented the operations console in the Syndicate Outpost scene to make it a bit more visibly apparent.
- some other shit, idk. When I close my eyes all I see are doors, now.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
yup. Knew that would happen. I'll handle it in the morning.

**Comment by PerfectTangent** [comment]
who am I kidding, it is morning already.

**Comment by ThatDan123** [comment]
Please run tests locally, if tests are still broken once you have finished.

**Comment by PerfectTangent** [comment]
There was a couple lights without switches. I fixed them. Everything has passed.

update doorsv2 test

**Pull request merged**
