### PR TITLE
Hivebot fabricators

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

This PR adds hivebot fabricators to the Ancient Station, adding a new threat to be taken care of. Hivebot fabs continually spawn hivebots (limit of 2 active per fabricator) until destroyed. With this continual supply of hivebots, hivebots in general have had their health nerfed to about half of where it was before.

### Notes:

- hivebot health pool nerfed to 40
- all hivebot variants are weak to bomb damage. Melee damage resistance was cut slightly on the non-heavy variants.
- the Ancient station has 2 hivebot fabs located in the secondary power room and the security room.
- These fabs should also allow admins to create more interesting events related to hivebots.
- also removed the facehugger in the Ancient Station.
- hivebots shouldn't bleed anymore, either.

The fabs reuse the mob leashing component that artifacts use, so it should work just fine, but I was unable to actually test because I kept getting kicked in the editor for an invalid username. 

### Changelog:

CL: [New] The Ancient Station now has Hivebot Fabricators that continually spawn hivebots until destroyed.
CL: [Balance] all hivebot health nerfed from 100 to 40
CL: [balance] all hivebots are now weak to bomb damage
CL: [Fix] hivebots should no longer bleed when damaged.

### CODE REVIEW

**Comment by VernaSaurus** [comment]
i am not smart please kindly ignore me

**Comment by PerfectTangent** [comment]
> please nerf hivebots before making them able to infinitely reproduce please

please read the PR before asking for things that are included in it.

**Comment by corp-0** [comment]
modify and save your character to solve the invalid name issue

**Review by NoooneyDude — APPROVED** [review]

**Comment by PerfectTangent** [comment]
ye, I tried that. It has worked before, but it didn't work in this instance.

**Review by ThatDan123 — APPROVED** [review]

**Pull request merged**
