### PR TITLE
Protip save states are now saved in AppData rather than in the build folder

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Improvement] Protip save states are now saved in AppData rather than in the build folder

### CODE REVIEW

**Review by corp-0 — APPROVED** [review]

**Comment by corp-0** [comment]
uhhm, tests suggest there is a compiling error but I don't see anything wrong with your changes. Is develop currently broken?

**Comment by MaxIsJoe** [comment]
re-run?

**Comment by MaxIsJoe** [comment]
I'm on the latest commit on my other branch, nothing seems to be broken.

**Comment by MaxIsJoe** [comment]
it passed

**Pull request merged**
