### PR TITLE
Character settings transferring while logged out

### LINKED ISSUE #1766: Leaving and Rejoining steam server as a ghost or in crit causes unexpected behaviours B: 20
# Description
Please note only contributors with the discord role "Engineer" can complete this ticket as you need access to the steam server:

#### Issue 1:

As client, die and become a ghost. Log out while you are a ghost.

When you rejoin, you appear completely white (no playerprefs are applied).

Expected is that your playerprefs are applied and you have the correct appearance.

#### Issue 2:

Another one from steam server:
Get into crit by stabbing yourself repeatedly, quit game before dying
Rejoin game: you'll be lying dead and won't have a ghost.
Also you might not be seen by other players:

image

A bounty of 20usd will be awarded to the contributor on a successful merge of a solution to these issues.

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes character settings not passing on if the player is logged out while transferring bodies.

Removes the automatic relog toggle copypaste, now the GUI of the login screen will just check for the preferences and run the standard login.
Character settings will now only transfer from the client to the server when the player is a JoinedViewer, on other type of body transfers, the settings will move from body to body.
The CharacterSettings is now saved in PlayerScript.

Fixes #1766

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
this was way more fun than doing UI stuff

### CODE REVIEW

**Comment by Aranclanos** [comment]
don't merge I found an error

**Comment by Aranclanos** [comment]
alright its all good now

**Comment by Jibbajabbafic** [comment]
Havin a look

**Review by Jibbajabbafic — CHANGES_REQUESTED** [review]
Ok so a few things...

When running OutpostStation scene directly from editor you get an NRE when selecting a job:
```NullReferenceException: Object reference not set to an instance of an object
PlayerManager.get_PlayerNameCache () (at Assets/Scripts/Player/PlayerManager.cs:21)
PlayerScript.Init () (at Assets/Scripts/Player/PlayerScript.cs:125)
PlayerScript.OnStartLocalPlayer () (at Assets/Scripts/Player/PlayerScript.cs:85)
UnityEngine.Networking.NetworkIdentity.SetLocalPlayer (System.Int16 localPlayerControllerId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:780)
UnityEngine.Networking.NetworkServer.SetupLocalPlayerForConnection (UnityEngine.Networking.NetworkConnection conn, UnityEngine.Networking.NetworkIdentity uv, UnityEngine.Networking.PlayerController newPlayerController) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:1006)
UnityEngine.Networking.NetworkServer.InternalReplacePlayerForConnection (UnityEngine.Networking.NetworkConnection conn, UnityEngine.GameObject playerGameObject, System.Int16 playerControllerId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:1060)
UnityEngine.Networking.NetworkServer.ReplacePlayerForConnection (UnityEngine.Networking.NetworkConnection conn, UnityEngine.GameObject player, System.Int16 playerControllerId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:893)
SpawnHandler.TransferPlayer (UnityEngine.Networking.NetworkConnection conn, System.Int16 playerControllerId, UnityEngine.GameObject newBody, UnityEngine.GameObject oldBody, EVENT eventType, CharacterSettings characterSettings) (at Assets/Scripts/Managers/NetworkManagement/SpawnHandler.cs:53)
SpawnHandler.RespawnPlayer (UnityEngine.Networking.NetworkConnection conn, System.Int16 playerControllerId, JobType jobType, CharacterSettings characterSettings, UnityEngine.GameObject oldBody) (at Assets/Scripts/Managers/NetworkManagement/SpawnHandler.cs:25)
JoinedViewer.CmdRequestJob (JobType jobType, CharacterSettings characterSettings) (at Assets/Scripts/Player/JoinedViewer.cs:106)
JoinedViewer.CallCmdRequestJob (JobType jobType, CharacterSettings characterSettings) (at <110c20800b0b461da4aa02e822937f18>:0)
GUI_PlayerJobs.BtnOk (JobType preference) (at Assets/Scripts/UI/Jobs/GUI_PlayerJobs.cs:27)
GUI_PlayerJobs+<>c__DisplayClass8_0.<UpdateJobsList>b__0 () (at Assets/Scripts/UI/Jobs/GUI_PlayerJobs.cs:64)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:66)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()
```

Running from the scene directly speeds up testing so much, so I'd say this is a must fix.

When I tested with 2 clients it fixed issue 1 and 2 of #1766, but I noticed some other weirdness which I'm not sure is related. 

The standing state doesn't seem to sync when you rejoin which makes it look like you're alive still:
image

The health UI gets stuck on crit after rejoining (this was taken when the player was alive):
image

The code changes looked good though, so I'm happy to merge if the NRE gets fixed and we can make separate tickets for the other issues if they are unrelated.

**Comment by Aranclanos** [comment]
Done

**Review by Jibbajabbafic — APPROVED** [review]

**Comment by Jibbajabbafic** [comment]
Sweet, all good now thanks!

**Pull request merged**
