### PR TITLE
Tile Conductivity

### PR DESCRIPTION
**Pull request by ThatDan123**
-Adds tile temperature conductivity which triggers at high temperature

-Fixes welder heating room issue

### CODE REVIEW

**Comment by ThatDan123** [comment]
Dont ask about the git commit history, am bad at git. The changed files show the correct ones

**Comment by corp-0** [comment]
> Dont ask about the git commit history, am bad at git. The changed files show the correct ones

that's what happens with merges

Looks good, though it makes me unconfortable to add yet another property to BasicTile

**Comment by Bod9001** [comment]
"Looks good, though it makes me unconfortable to add yet another property to BasicTile" why so?

**Comment by corp-0** [comment]
Because BasicTile is a mess. At least this property makes sense to be there, but we have floors with radiation penetration, walls with footstep sounds, cables that change the footsteps. Instead of specializing the tiles into their own classes, we just added everything in BasicTile and slapped bools.

**Pull request merged**
