### PR TITLE
The best kind of Christmas Presents!!!

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [Improvement] Christmas event now gives you a truly random present

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
what did it give you before?

**Comment by Bod9001** [comment]
It gave you selection from big list of predetermined items

**Comment by MaxIsJoe** [comment]
and now?

**Comment by Bod9001** [comment]
it picks a random prefab that has universal object physics and has item attributes

**Review by MaxIsJoe — APPROVED** [review]

**Pull request merged**
