### PR TITLE
bugfixes and outpost kitchen improvement

### PR DESCRIPTION
**Pull request by VernaSaurus**
exactly what the title says, just some small food fixes and a slight modification to the outpost kitchen

### CODE REVIEW

**Comment by AutumnNova** [comment]
i did say i was doing scene changes to outpost, now there is going to be a conflict

**Comment by VernaSaurus** [comment]
oh great, sorry

**Comment by VernaSaurus** [comment]
this is why i haven't made any changes to pog because i know there are people working on it

**Comment by VernaSaurus** [comment]
i don't know why the check failed

**Comment by VernaSaurus** [comment]
should i revert my outpost changes

**Comment by PetMudstone** [comment]
Did you run the test runner in Window > General > Test Runner? It might give you some more information.

EDIT: Perhaps you could send otherguywolf a copy of your map, or at least a screenshot of what the kitchen on your Outpost looks like. I'm sure if it's just a "slight modification" they can easily replicate it.

**Comment by VernaSaurus** [comment]
I fixed the errors

**Comment by Bod9001** [comment]
so What order shall I merge these in?

**Comment by AutumnNova** [comment]
merge this first

**Comment by AutumnNova** [comment]
ill fix the conflict after

**Comment by Bod9001** [comment]
ok cool

**Pull request merged**
