### PR TITLE
Fixes alt click error - #1041

### LINKED ISSUE #1041: Alt+click is broken
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
NRE when alt+clicking tiles around you
`NullReferenceException: Object reference not set to an instance of an object
UITileList.ClearItemPanel () (at Assets/Scripts/UI/UITileList.cs:181)
UITileList.UpdateTileList (System.Collections.Generic.IEnumerable1[T] objects, Tilemaps.Tiles.LayerTile tile, UnityEngine.Vector3 position) (at Assets/Scripts/UI/UITileList.cs:163)
UI.ControlTabs.ShowItemListTab (System.Collections.Generic.IEnumerable1[T] objects, Tilemaps.Tiles.LayerTile tile, UnityEngine.Vector3 position) (at Assets/Scripts/UI/ControlTabs.cs:143)
PlayGroups.Input.InputController.CheckAltClick () (at Assets/Scripts/PlayGroups/Input/InputController.cs:93)
PlayGroups.Input.InputController.Update () (at Assets/Scripts/PlayGroups/Input/InputController.cs:56)
`

## Expected/Wanted/Requested Behavior
Should show object list for chosen tile in a new tab + its world position in tooltip

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Host a server in editor, join as assistant
2.Alt+click nearby tile

## OS used:
Windows

## Notes
Seems like it can't FindObjectOfType<UITileList>, did anyone remove it?

### PR DESCRIPTION
**Pull request by badbon**
### Purpose
Fixes #1041<br>

### Approach
First of all, this is my first PR on this project and first one in a while, so have mercy 👍 I probably messed up somewhere.

So FindObjectOfType only works on active objects, yet it tried to get it from disabled object, I just enabled PANEL_Item_List (parent of that object where the script is attached) in Lobby scene (not sure why it was disabled, hopefully that won't mess things up?) and uncommented the code that was previously giving error. Let me know if this is all correct.

### Notes:
🙏

### CODE REVIEW

**Comment by fomalsd** [comment]
Oh, it's in Managers.prefab.
You should press Apply button inside it, otherwise this change would only affect Lobby scene and not the other scenes.
default
Scene change is unnecessary in this case, please revert it after applying Managers.prefab change

**Comment by badbon** [comment]
I am not sure how to revert the scene :c

**Comment by badbon** [comment]
After an hour of having no idea what I am doing, it worked out in the end, I think.

:D

**Comment by fomalsd** [comment]
Nice, will check out now

**Comment by fomalsd** [comment]
default
you forgot to enable tab header :)
default

**Comment by badbon** [comment]
Try it now.

Also made some adjustments to controltabs.cs, fixed ui stuff.

**Comment by fomalsd** [comment]
Works wonderfully! 
Props for fixing the font, too

**Pull request merged**
