### PR TITLE
Adds RequireComponents to ItemAttributes.cs

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
Added these:
```cs
[RequireComponent(typeof(NetworkIdentity))]
[RequireComponent(typeof(Pickupable))]
[RequireComponent(typeof(ObjectBehaviour))]
[RequireComponent(typeof(RegisterItem))]
[RequireComponent(typeof(CustomNetTransform))]
[RequireComponent(typeof(SpriteMatrixRotation))]
```

Updated some prefabs that were missing RegisterItem and made sure to remove RegisterObject from them too:

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by fomalsd** [comment]
Why should SpriteMatrixRotation be required?

**Comment by fomalsd** [comment]
Also I think Network Identity is implicitly required, because all NetworkBehaviours do

**Comment by Jibbajabbafic** [comment]
SpriteMatrixRotation is definitely needed on items or else this happens:
d8o1ownJoe

You're right about NetworkIdentify though so I've removed that

**Comment by Aranclanos** [comment]
the networkidentity is autoadded, but it can be removed by mistake, maybe? I think?

**Comment by Jibbajabbafic** [comment]
I tested this and it can't be removed since a lot of components depend on it

**Comment by fomalsd** [comment]
I feel like SpriteMatrixRotation should still be optional (thinking about pipes and bloodsplats)

**Comment by Jibbajabbafic** [comment]
Will those be items though? If pipes aren't anchored we'll want them to rotate still

**Comment by Aranclanos** [comment]
I like it

**Pull request merged**
