### PR TITLE
Mobs will hit windows and grills again, Mobs will also hit adjacent tiles if they cant move to target

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: [Fix] Mobs will hit windows and grills again

CL: [Improvement] Mobs will also hit adjacent tiles if they cant move to target

### CODE REVIEW

**Comment by corp-0** [comment]
very nice. Why is it important to find grills in particular?

**Comment by ThatDan123** [comment]
image

Basically the red target is what the raycast has hit and is what the mob trys to attack but the yellow is where the mob is getting blocked from doing a move to, so now it'll attack the raycast target then hit the adjacent tiles around it if it can. So it checks for windows, grills and objects

**Comment by corp-0** [comment]
Yes, thanks. I gave the code a second read with more calm and got it.

**Comment by waffielz** [comment]
sick

**Pull request merged**
