### PR TITLE
Moves textures out of the resource folder saving 400mb~ ram on builds + Add in hands for clothing item form StrawberryMoses 

### LINKED ISSUE #1748: Inconsistency with in-hand sprites (chef only, maybe there's more)
# Description
image
On this image, the chef's suit (not exosuit) is invisible on-hand and the chef hat has the exosuit sprite on-hand
I am not aware if there's more in-hand sprite inconsistencies, I haven't tested much

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Pick up the chef's hat and cook's suit with your hands
2.Look over at the in-hand sprites for said items
3.Notice their lack of sprite or different sprite as the appropriate item

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
A simple action to save quite a bit of memory

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [? Maybe they did have desktop client wouldn't let me scroll down through the entire list of changes so there might be a few at the end I couldn't Scroll to]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  Any new / changed components have been [tested using Respawn](https://github.com/unitystation/unitystation/wiki/Proper-Spawning-and-Despawning-%28Object-Lifecycle%29)
- [ ]  This PR has been tested with round restarts.
- [x]  This PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

@StrawberryMoses did 

Fixes #1748 
I added inhand sprites for everything I could under textures/clothing.
Notes:

Gonna be honest.. I didn't test this super thoroughly, since this was just prefab edits and adding in hands. If I missed something or there's an inconsistency, we can always fix when we find them since it's fairly trivial. This will at least get the bulk of the work done

### CODE REVIEW

**Comment by chairbender** [comment]
@Bod9001 darn, not working for me. I even cleared PlayerPrefs but I get KeyNotFoundException when spawning:
```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
PlayerSprites.SetupCustomisations () (at Assets/Scripts/Player/PlayerSprites.cs:101)
PlayerSprites.SetupCharacterData (CharacterSettings Character) (at Assets/Scripts/Player/PlayerSprites.cs:91)
PlayerSprites.OnCharacterSettingsChange (CharacterSettings characterSettings) (at Assets/Scripts/Player/PlayerSprites.cs:312)
PlayerSpawn.ServerTransferPlayer (Mirror.NetworkConnection conn, UnityEngine.GameObject newBody, UnityEngine.GameObject oldBody, EVENT eventType, CharacterSettings characterSettings, Occupation occupation) (at Assets/Scripts/Lifecycle/PlayerSpawn.cs:345)
PlayerSpawn.ServerSpawnInternal (Mirror.NetworkConnection connection, Occupation occupation, CharacterSettings characterSettings, Mind existingMind, System.Nullable`1[T] spawnPos, System.Boolean naked) (at Assets/Scripts/Lifecycle/PlayerSpawn.cs:130)
PlayerSpawn.ServerSpawnPlayer (JoinedViewer forViewer, Occupation occupation, CharacterSettings characterSettings) (at Assets/Scripts/Lifecycle/PlayerSpawn.cs:24)
JoinedViewer.CmdRequestJob (JobType jobType, CharacterSettings characterSettings) (at Assets/Scripts/Player/JoinedViewer.cs:146)
JoinedViewer.CallCmdRequestJob (JobType jobType, CharacterSettings characterSettings) (at <2dd91b3f871343f6be972f5ea04dcea0>:0)
GUI_PlayerJobs.BtnOk (JobType preference) (at Assets/Scripts/UI/Jobs/GUI_PlayerJobs.cs:29)
GUI_PlayerJobs+<>c__DisplayClass8_0.<UpdateJobsList>b__0 () (at Assets/Scripts/UI/Jobs/GUI_PlayerJobs.cs:74)
UnityEngine.Events.InvokableCall.Invoke () (at /Users/builduser/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at /Users/builduser/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at /Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at /Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at /Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at /Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at /Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
```

And also get exceptions when trying to go to the Character settings screen:
```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Lobby.CharacterCustomization.RefreshHair () (at Assets/Scripts/UI/Lobby/CharacterCustomization.cs:487)
Lobby.CharacterCustomization.RefreshAll () (at Assets/Scripts/UI/Lobby/CharacterCustomization.cs:116)
Lobby.CharacterCustomization.RollRandomCharacter () (at Assets/Scripts/UI/Lobby/CharacterCustomization.cs:160)
Lobby.CharacterCustomization.DoInitChecks () (at Assets/Scripts/UI/Lobby/CharacterCustomization.cs:102)
Lobby.CharacterCustomization.LoadSettings () (at Assets/Scripts/UI/Lobby/CharacterCustomization.cs:93)
Lobby.CharacterCustomization.OnEnable () (at Assets/Scripts/UI/Lobby/CharacterCustomization.cs:61)
UnityEngine.GameObject:SetActive(Boolean)
Lobby.GUI_LobbyDialogue:ShowCharacterEditor(Action) (at Assets/Scripts/UI/Lobby/GUI_LobbyDialogue.cs:91)
Lobby.GUI_LobbyDialogue:OnCharacterButton() (at Assets/Scripts/UI/Lobby/GUI_LobbyDialogue.cs:318)
UnityEngine.EventSystems.EventSystem:Update() (at /Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
```

**Comment by fomalsd** [comment]
Scr 2019-11-22 в 9 44 09
don't have issues described above

**Comment by fomalsd** [comment]
ah, got that in multiplayer on client side, seems to concern underwear
Scr 2019-11-22 в 9 59 21
Scr 2019-11-22 в 10 02 20

**Comment by fomalsd** [comment]
it's worth noting that multiplayer cloth sync has been bad since sprite refactor on that particular machine (mac) for some reason

**Comment by Bod9001** [comment]
ok,  that should fix the issues

**Comment by chairbender** [comment]
Yep, working good now

**Pull request merged**
