### PR TITLE
Makes deathsquad troopers non-targetable by antags

### PR DESCRIPTION
**Pull request by MrAsbestos**
### Purpose
The title explains it, makes deathsquad troopers non-targetable by antags, now it is guarenteed that you will not get a ghost role as an objective.

### Changelog:
-Made deathsquad troopers non-targetable. 

### Notes
This is legit the smallest PR I have ever made lol

### CODE REVIEW

**Comment by wraith-54321** [comment]
it may be possible to get blobs as a target, I am just guessing

**Comment by MrAsbestos** [comment]
Blobs aren't like a job, or well I didn't find them in the ghost role section, so my guess is that it can't be a target, neither I have seen it happening.

**Comment by DTraitor** [comment]
what about ancient engineers? are they still a target?

**Comment by PerfectTangent** [comment]
No, that was fixed 2 weeks ago.

**Comment by waffielz** [comment]
small pr gaming

**Pull request merged**
