### PR TITLE
Active radio panel and ControlChat refactor

### LINKED ISSUE #1269: "None" as channel name after round restart
# Description

## Category
BUG

## Detailed Bug Report
(Actually not sure if it's really a bug)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Chat a little
2. Restart round
3. have "None" as channel

image

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
### Purpose
- Added a panel to show which radio channels you have selected.
image
- Made a separate channel button to show channel toggles
- Label next to input field now shows "Say:", "Ghost:", or "OOC:" depending on the main channel selected
- Added an UpdateChatChannels event to select a default channel (Local, Ghost or OOC) and to refresh the channel panel (fixes bug where ghost channel wouldn't update correctly)

Also unintentionally ended up refactoring most of ControlChat.cs to make it a bit clearer and added some more documentation.

Now ChannelToggles all get created at once and activate/deactivate as needed, instead of always creating and destroying them.

Fixes #1269 

Some progress towards #948 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by Jibbajabbafic** [comment]
Apologies for changing so much in ControlChat, it's made the diff viewer useless lol

**Comment by fomalsd** [comment]
is it intended that channel list resets each time you open chat window?
GIF

**Comment by Jibbajabbafic** [comment]
Yes it's intentional, I changed it so that `T` always selects Local, since that's the most likely channel people will want to chat in quickly. Pressing `Y` should preserve selected radio channels, or enable Common if none are selected and `U` should always switch to OOC.

**Comment by Jibbajabbafic** [comment]
It can easily be changed in the future if people prefer different behaviour

**Comment by fomalsd** [comment]
Getting a bit weird behaviour:
When pressing esc to close chat window a menu appears, and it somehow messes up chat logic:
After sending a message with multiple channels selected chat window doesn't go away, but channels are still erased.
Then, after reopening chat window via Y it restores with a different channel set
GIF

**Review by fomalsd — COMMENTED** [review]
Getting some esc button weirdness

**Comment by Jibbajabbafic** [comment]
Good find, will look into it later

**Comment by Jibbajabbafic** [comment]
@fomalsd unable to reproduce that bug, whenever I press Esc it closes the chat window for me. I tried pressing Esc then opening chat and Esc still closes chat first. Tried in editor and build too. What version of Unity were you using and what OS?

Anything in the logs either?

**Comment by fomalsd** [comment]
Win10, 2018.3.12 I think
Happened in editor
Might have made a few clicks in and out of input field before that
If it still isn't reproducible, I will try reproducing it again tomorrow

**Comment by Jibbajabbafic** [comment]
Ok cool, if it still happens I'd recommend trying 2018.3.14f

**Comment by fomalsd** [comment]
> After sending a message with multiple channels selected chat window doesn't go away, but channels are still erased.

This one certainly can be reproduced by clicking into input field before sending message:  you have to click into input field after picking channels because it loses focus and chat window just closes if you try to type something

Also you can open esc menu first then press Enter, T or Y to have both open simultaneously. This is what happened on that gif, didn't really notice esc menu being open until after recording
GIF

**Comment by Jibbajabbafic** [comment]
So shall I change it so you can't open chat with the main menu open?

**Comment by fomalsd** [comment]
yeah, I think so
it's also worth keeping channel list intact if a message is sent, but chat window isn't closed (if keeping chat window opened is intended feature)

**Comment by Jibbajabbafic** [comment]
Ok all fixed, ready for re-review

**Review by fomalsd — APPROVED** [review]
Ok, you can't enable chat with esc menu open anymore
Still, clicking channel buttons makes input field lose focus, but it can be addressed later I guess

**Pull request merged**
