### PR TITLE
A small fix for starting sets of clothing

### LINKED ISSUE #2713: Revise loadouts for each job
– HOP wears a Detective's coat and vice versa
– Clown has a grey backpack and no horn or peels
– Janitor spawns with engineering tools in his belt
...who knows what else?
Need someone to look through each job loadout and make them match /tg/-2017 or bee

### PR DESCRIPTION
**Pull request by smugmann**
Removes different inconsistencies, every assigned slot now has an appropriate piece of clothing.
Everyone has an earpiece and some jobs should start with full belts now.

### CODE REVIEW

**Comment by fomalsd** [comment]
I don't see clown populators modified here :'( 
Clown is missing a bike horn and banana peels

**Comment by smugmann** [comment]
> 
> 
> I don't see clown populators modified here :'(
> Clown is missing a bike horn and banana peels

it will require creating a bunch of new items though, perhaps you could create another issue for that?

**Comment by fomalsd** [comment]
bike horn and peel items are present though, I'm not asking to implement soap and other items that aren't currently in

**Comment by DooblyNoobly** [comment]
going to merge these populators in the mean time

**Pull request merged**
