### PR TITLE
Paletteable shoes

### PR DESCRIPTION
**Pull request by Ruzihm**
Makes paletteable shoes where the front and back colors are paletteable. re-implements black and brown shoes with them.

example

### Purpose
Progress towards #2110

### Notes
recommended test: spawn as staff assistant, search for "BlackShoes", change palette elements 0 and 1 in ItemAttributesV2, right click on ItemAttributesV2 and select "Propagate Palette Changes"

Sprites created using [this tool](https://codepen.io/ruzihm/full/ZEGWWGM)

### CODE REVIEW

**Review by vlandemart — APPROVED** [review]
Only changed prefabs, jsons and pngs so really nothing to review
Seems to be working fine, checked it locally with 2 clients

**Comment by DooblyNoobly** [comment]
Reverting this as there are shoe problems and NRE's on client and server

**Comment by DooblyNoobly** [comment]
see issues that were attributed to this pr here: 

https://github.com/unitystation/unitystation/issues/3317#issuecomment-590156019 (shoes bug)
https://github.com/unitystation/unitystation/issues/3317#issuecomment-590573793
https://github.com/unitystation/unitystation/issues/3317#issuecomment-590574445

**Comment by Ruzihm** [comment]
@dooblynoobly that issue is closed, was the shoe issue fixed?

**Comment by DooblyNoobly** [comment]
nope it wasn't resolved in that issue so thats why we reverted it

**Comment by Ruzihm** [comment]
@DooblyNoobly please see #3345

**Pull request merged**
