### PR TITLE
Grown Foods can be eaten and Drinks leave behind empty glass

### LINKED ISSUE #3181: Grown plants should be edible
Currently grown plants are basically useless since they transform into seeds on activation and aren’t getting consumed. So botanists‘ purpose is questionable  at the moment.
Bananas should also leave peels when eaten!

### PR DESCRIPTION
**Pull request by Raptorizer**
# Pull Request Template

### Purpose
fixes #3181 
Also adds Empty Glass as a leftover item after consuming a glass drink
### Notes:
Not sure if this PR causes botany plants to flicker, but it happened in my local.
Code could be better made, such as despawning instead of disapearing

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by AutumnNova** [comment]
does this affect the cappuccino with the edible cup?

**Comment by Raptorizer** [comment]
> does this affect the cappuccino with the edible cup?

yes

**Comment by AutumnNova** [comment]
might wanna change it so it isnt called a cappuccino with an edible cup then, if you haven't already, or dont, it doesnt matter that much

**Comment by fomalsd** [comment]
seeing you comment out spawning leavings in NPC eating method is weird, but I'll merge this anyway

**Pull request merged**
