### PR TITLE
Prevents objects  being pushed by wind and stuff when being draagged

### PR DESCRIPTION
**Pull request by Bod9001**

### CODE REVIEW

**Review by ThatDan123 — DISMISSED** [review]

**Comment by ThatDan123** [comment]
This would also prevent someone from walking through something being pulled by someone else?

**Comment by Bod9001** [comment]
"This would also prevent someone from walking through something being pulled by someone else?"
That would be a normal tile push, This is only Newtonian push E,g  stuff bouncing off it and applying momentum And wind

**Review by ThatDan123 — DISMISSED** [review]

**Comment by Bod9001** [comment]
why tests why

**Comment by Bod9001** [comment]
should be fixed?

**Comment by corp-0** [comment]
rebase and push to pass the tests

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
