### PR TITLE
Added hover tooltips for UI elements

### LINKED ISSUE #1464: Tooltip doesn't show up when mousing over UI
# Description
Mousing over UI doesn't show the tooltip for the items being moused over in the player's inventory. It should show the tooltip for whatever item is moused over.

## Steps to Reproduce
1. Launch in editor and host.
2. Mouse over an item in the inventory
3. Note that the tooltip on the bottom left doesn't change to show what is moused over.

mouseover

### PR DESCRIPTION
**Pull request by plnqux**
### Purpose
Fixes #1464 by adding tooltips for most UI elements.

### Open Questions and Pre-Merge TODOs
- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
- Tooltips exist for bottom UI hud, ghost hud, and player health hud, and zoom/options hud
- Added generic UI_HoverTooltip class for hover tooltips
- Updated UI_ItemSlot to capture slot hover name and display item hovered
- Updated UI_ItemSwap to display hover name for slot
- Changed heart monitor image to be a raycast target since hovering is determined by raycast
- Removed OxygenButton component reference from buckled button

This PR needs to wait #2120 is merged and then I'll rebase my changes on that.  Is there a specific SS13 codebase I should use to test what things should look like?  I used tg for these changes and I believe I verified everything but "High Pressure" and "Freezing" since I wasn't able to get those to pop up.  Some of the Control*.cs classes used to have a namespace and their formatting is a bit weird right now.

### CODE REVIEW

**Comment by fomalsd** [comment]
very nice!

**Comment by fomalsd** [comment]
#2120 is merged by the way

**Comment by plnqux** [comment]
Yeah I saw, I tried to work on this last night but got stuck by some prefab serialization issues.  I'll see what I can do to get something submitted.

**Comment by plnqux** [comment]
I've pushed the rebase now.  I think due to #2120 Unity now serializes the InventorySlot in UI_ItemSlot at https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/UI/UI%20Bottom/UI_ItemSlot.cs#L15 into the prefab.  I was also having trouble getting the prefab to auto-save and I had to move an item in the hierarchy to force it to save the content to the file.  I think it's something that might need to be looked at and I spent a few hours last night trying to change the way the UI_ItemSlotEditor works and didn't find a fix.

**Comment by plnqux** [comment]
Ok I think I fixed the issue with editing UI_ItemSlots by switching the custom editor to use PropertyField components.  Without that change it wasn't detecting modifications to text fields for some reason.

**Review by fomalsd — COMMENTED** [review]
Works nicely, thanks!
Code duplication is a bit annoying to my eye though, so I'm proposing a PR to your branch that encapsulates hover logic in common `TooltipMonoBehaviour` class so you only have to override `Tooltip` property

**Comment by fomalsd** [comment]
See https://github.com/spacerecycler/unitystation/pull/1

**Review by fomalsd — APPROVED** [review]

**Pull request merged**
