### PR TITLE
Add sprite scaling to singularity

### PR DESCRIPTION
**Pull request by NoooneyDude**
- Adds sprite scaling to the singularity.

> Does not include the singularity lerping as previously demonstrated, sorry. Ran into issues and saw no obvious solution.

### CODE REVIEW

**Review by ThatDan123 — APPROVED** [review]
Looks good, did you test with spawning the bigger stages in the admin spawn menu?

**Comment by NoooneyDude** [comment]
> Looks good, did you test with spawning the bigger stages in the admin spawn menu?

Hmm no, only the first stage was available in the spawn menu.

**Comment by ThatDan123** [comment]
ah, yeah you'll need to build test to get the others as the spawn menu doesnt show all the prefabs for some reason when playing in editor

**Comment by ThatDan123** [comment]
Actually hosting from lobby in editor might work, try that

**Pull request merged**
