### PR TITLE
Overflow protection for tile damage

### PR DESCRIPTION
**Pull request by ThatDan123**
Just in case theres a loop, where a tile is spawned and then spawns the one that spawns itself

### CODE REVIEW

**Comment by corp-0** [comment]
> a tile is spawned and then spawns the one that spawns itself

Mind = blown, I did not understand what is happening there

**Comment by ThatDan123** [comment]
I dont think theres a loop problem but for example, floor1 turns into floor2 when destroyed, but then floor2 accidently is set to turn to floor1 if it is damaged enough. And somehow even though the damage should reduce it still forever loops.

**Comment by ThatDan123** [comment]
But i dont think this is the crash issue, i did double check the tiles i set up.

**Comment by corp-0** [comment]
why is the limit 10?

**Comment by ThatDan123** [comment]
10 is a nice number, it's divisible by 2, and 5. :p

In all seriousness, i dont think theres a tile damage route which is bigger than like 6 which i think it what RWalls is.

I can change it to a const if you think i should.

**Comment by corp-0** [comment]
yes, that way the number is identified and we can easily find it and change it if we ever do something that should exceed that limit.

**Comment by ThatDan123** [comment]
cool, done

**Pull request merged**
