### PR TITLE
Tiny Fan

### PR DESCRIPTION
**Pull request by ThatDan123**
image

Is not atmos passable. 

- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor

### CODE REVIEW

**Comment by fomalsd** [comment]
be aware that non-atmos passable objects are buggy:
https://github.com/unitystation/unitystation/issues/1902#issuecomment-575571921
so if someone destroys such fan the tile will most likely stay non-atmos passable

**Comment by ThatDan123** [comment]
Ah right.... humm tricky

**Comment by ThatDan123** [comment]
Do you still have the special command?

**Comment by corp-0** [comment]
from what I understood, the problem is with objects. If you make it a tile when active, it should work... Maybe.

**Comment by fomalsd** [comment]
yes, forcefully updating tile can be done with alt+click when hosting

**Comment by ThatDan123** [comment]
Can that be done in code?

**Comment by ThatDan123** [comment]
Just gonna get this in, i accidentally deleted the other stuff like the holograms which i was working on and cant find the files anywhere rip.

**Pull request merged**
