### PR TITLE
Escape shuttle ghost-teleports added

### LINKED ISSUE #7762: Add Ghost Teleport Point to Escape Shuttles
Add Ghost Teleport Point to Escape Shuttles

- [x] Fall
- [x] Outpost
- [x] Pog
- [x] Box
- [x] Square
- [x] UnReal

### PR DESCRIPTION
**Pull request by greyqwilson**
### Purpose
 <br>

Fixes #7762 

### Changelog:

Adds escape shuttle ghost teleport locations to shuttles  on maps:
  Fall
  Outpost
  Pog
  Box
  Square
  UnReal

### CODE REVIEW

**Comment by corp-0** [comment]
beautiful, thank you!

**Review by NoooneyDude — APPROVED** [review]
Thanks for your contribution!

**Comment by NoooneyDude** [comment]
Come join us in Discord and get the mapper role if you want to do more mapping.

**Comment by greyqwilson** [comment]
I'll stop by the discord thank you! I don't know how active I will be but I'll try to contribute when I see something I have the skill to work on.

**Pull request merged**
