### PR TITLE
Improvements to Outpost

### PR DESCRIPTION
**Pull request by Ranzarth**
### Purpose

- Renovates Escape
- Adds new clothing to vendors and winter jackets to appropriate departments
- General tweaks and additions
- Changes the items in two vendor varients

DNM until fixed

### CODE REVIEW

**Comment by ThatDan123** [comment]
Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_51, Component vending_51, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_51, Component vending_51, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_190, Component vending_190, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/vending_190 (2), Component vending_190 (2), FieldName Item

  Expected: <empty>
  But was:  < (OutpostStation, Objects/vending_192 (1), vending_192 (1), Item), (OutpostStation, Objects/vending_192 (1), vending_192 (1), Item), (OutpostStation, Objects/vending_192 (1), vending_192 (1), Item), (OutpostStation, Objects/vending_192 (1), vending_192 (1), Item), (OutpostStation, Objects/vending_192 (1), vending_192 (1), Item), (OutpostStation, Objects/vending_192 (1), vending_192 (1), Item), (OutpostStation, Objects/vending_192, vending_192, Item), (OutpostStation, Objects/vending_192, vending_192, Item), (OutpostStation, Objects/vending_192, vending_192, Item), (OutpostStation, Objects/vending_192, vending_192, Item)... >at Tests.MissingAssetReferences.CheckMissingComponentsOnScenes () [0x0028e] in /github/workspace/UnityProject/Assets/Tests/Asset/MissingAssetReferences.cs:237[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192 (1), Component vending_192 (1), FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_192, Component vending_192, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_51, Component vending_51, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_51, Component vending_51, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_190, Component vending_190, FieldName Item
[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_190 (2), Component vending_190 (2), FieldName Item

**Comment by ThatDan123** [comment]
You got missing references

**Comment by ThatDan123** [comment]
Missing reference found in scene OutpostStation, GameObject Objects/vending_51, Component vending_51, FieldName Item

  Expected: <empty>
  But was:  < (OutpostStation, Objects/vending_51, vending_51, Item) >at Tests.MissingAssetReferences.CheckMissingComponentsOnScenes () [0x0028e] in /github/workspace/UnityProject/Assets/Tests/Asset/MissingAssetReferences.cs:237[Tests] Missing reference found in scene OutpostStation, GameObject Objects/vending_51, Component vending_51, FieldName Item

**Comment by DooblyNoobly** [comment]
fixed?

**Comment by ThatDan123** [comment]
Looks like it, testing didnt fail

**Comment by Ranzarth** [comment]
Fixing up some stuff with this atm

**Comment by ThatDan123** [comment]
rip

**Comment by DooblyNoobly** [comment]
click the details button next to the failed test, on the next screen you will see an artifacts drop down. Download it and check what is failing

**Comment by DooblyNoobly** [comment]
failed again

**Comment by PetMudstone** [comment]
I copied over this PR's OutpostStation to my local repository and I noticed that [a bunch of winter coats in the hierarchy are at 0,0](https://media.discordapp.net/attachments/285240893160685570/692550381447807006/Screenshot_1103.png?width=1204&height=678) instead of on lockers.

**Comment by corp-0** [comment]
fetch! You shouldn't be experiencing all of those missing references now

**Pull request merged**
