### PR TITLE
Lobby Music Additions - Fixes issue #2454

### LINKED ISSUE #2454: Lobby Music Additions B: 45
# Criteria:

- Determine when a track ends (checking AudioSource.isPlaying is one way to do it) and play another random track after it stops (make sure not to play the last song that just played)
- Show the Name of the song and the Artist somewhere on the lobby screen. Make sure it updates correctly when a new track is played
- Make sure the placement and size of the text fits in with the overall layout
- Add the Space Asshole song to our lobby music list rotation: https://www.youtube.com/watch?v=GISnTECX8Eg Chris has given us permission to use it

Contributor will receive a bounty of 45usd on a successful merge of a solution that meets the criteria above.

### PR DESCRIPTION
**Pull request by nikopetr**
### Purpose
Lobby Music Additions
Fixes #2454 

### Notes:
- Added Spaceasshole song by Chris Remo.
- Changed varius tracks' filenames to the actual ones.
- Added text to the lobby screen that shows the name of song and artist that currently plays.
- After a song ends in the lobby, another random track plays (not the last song that just played).

### CODE REVIEW

**Comment by voidel** [comment]
Really minor, but would it make sense to make the seperator in-filename to seperate the song title and artist as something other than hypen? Otherwise hypens can't be used in song titles. Again, minor. Feel free to ignore if nobody thinks this is important.

**Comment by nikopetr** [comment]
It's possible to have the artists and names saved in a hashmap ,a dictionary or something. I can change that if you think it's important of course. But I believed it's better to have the filenames named like that since it's more practical if the information is on the filename.

**Comment by voidel** [comment]
It is practical, i just wonder whether the seperator should be an underscore, since they are far less likely to appear in song titles.

For example:

X-Static by Foo Fighters

X-Static_Foo Fighters

**Comment by nikopetr** [comment]
Done !

**Comment by voidel** [comment]
Excellent! Thank you.

**Comment by DooblyNoobly** [comment]
cool, looks good. A few minor touch ups I want to make after this is merged. Can you let me know who you are in discord so I can organise  the bounty.

**Pull request merged**
