### PR TITLE
Importing various sprites from Beestation, mainly engineering stuff.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Imports a large amount of sprites from [a pull request made by SomeAngryMiner (AKA Azlan) for Beestation.](https://github.com/BeeStation/BeeStation-Hornet/pull/2339)
- Sprites included are
  - Engineering backwear (backpacks, duffels, satchels) and hardhats **done by thatguythere03**.
  - Security hardsuits **done by Agameofscones (AKA Triiodine)**.
  -Just about everything else (stock parts, tools, belts, shoes, firesuits, rad suits, etc.) **done by SomeAngryMiner (AKA Azlan)**.
- Also imports RCD and RPD sprites **done by Toriate**.
- Adds new locked and unlocked light overlays for CBF's lockers.

### Notes:
I haven't actually replaced "everything" yet. I've placed a few files in the asset library (such as the hardsuits) for further evaluation (AKA polls).

### CODE REVIEW

**Comment by PetMudstone** [comment]
i dunno why this has commits from #4966 in it but it does.

**Comment by VernaSaurus** [comment]
uh oh

**Comment by VernaSaurus** [comment]
you know what i give up, closing my pr

**Comment by ThatDan123** [comment]
Missing reference found in prefab Multitool component Sprite field Sprite
Missing reference found in prefab Debug Multitool component Sprite field Sprite
Missing reference found in prefab IndustrialWeldingTool component IndustrialWeldingTool field Element 4

**Comment by Bod9001** [comment]
should have a poll for them, and do one for the spacesuit locker was well

**Comment by PetMudstone** [comment]
image
Poll for the tools is going quite well in favor of the new sprites, if that means anything.

**Comment by ike709** [comment]
🤔

**Comment by Crossedfall** [comment]
Not going to co-author them onto the commit to give them proper attribution?

**Comment by ike709** [comment]
Also jeez we haven't even merged the PR yet.

**Comment by PetMudstone** [comment]
I'll see what I can do about the co-authoring business. I'm not sure if it's practical to amend my commits here (I've had bad experiences with force pushing to open PRs in the past) but I'll attempt to perform co-authoring in future PRs.

**Comment by Crossedfall** [comment]
> 
> 
> I'll see what I can do about the co-authoring business. I'm not sure if it's practical to amend my commits here (I've had bad experiences with force pushing to open PRs in the past) but I'll attempt to perform co-authoring in future PRs.

Just add an empty commit with the co-author line

**Comment by PetMudstone** [comment]
well, I did need to commit a transform change to a flame sprite anyways sooooo

**Comment by PetMudstone** [comment]
Oh hey, I didn't fuck up my attempt at a commit that includes co-authors!
And there goes the autohelper...

**Comment by NoooneyDude** [comment]
Looks like it's just the autolabeler upset. Merging.

**Pull request merged**
