### PR TITLE
Add prefab-mode-only and scene-mode-only attributes

### PR DESCRIPTION
**Pull request by NoooneyDude**
- Adds prefab-editing mode and scene-editing only attributes.
Reduces inspector complexity significantly for mapping.
- Applies the former attribute to a bunch of common components.

### CODE REVIEW

**Comment by Bod9001** [comment]
one good thing to think about is how much should you be able to change Through an item on the map?

**Comment by NoooneyDude** [comment]
> one good thing to think about is how much should you be able to change Through an item on the map?

I don't think there's much advantage in any of the variables I've added the attribute to being changed on the map, but point out any that you disagree on.

**Comment by corp-0** [comment]
It is fine to merge, I think. I don't know how close are we to change mapping but we won't be editing scenes anymore in the future, right?

**Comment by Bod9001** [comment]
with the mapping tools you could do it through the editor or in game the plan is currently

**Comment by Bod9001** [comment]
all I say add an override somewhere that you can toggle

**Review by corp-0 — DISMISSED** [review]

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
