### PR TITLE
ChatFilter.cs int division fix

### PR DESCRIPTION
**Pull request by PaulRitter**
fix
I recommend that this should be fixed,

### CODE REVIEW

**Review by exp111 — APPROVED** [review]
Seems good

**Comment by Bod9001** [comment]
image
looks like it was serialised correctly, so didn't actually affect gameplay

**Comment by Bod9001** [comment]
seems like the file was last touched before codacy was implemented on PR or on the project

**Review by NoooneyDude — APPROVED** [review]

**Comment by PaulRitter** [comment]
> seems like the file was last touched before code as he was implemented on PR or on the project

sir what
grafik

**Comment by Bod9001** [comment]
try reading it again, since I use voice to text doesn't quite understand everything all the time, and it often generates similar sounding words, that only notice after you post, I'm sure this isn't a big inconvenience for you.

**Comment by PaulRitter** [comment]
> seems like the file was last touched before codacy was implemented on PR or on the project

oh you're right sorry

**Pull request closed without merging**
