### PR TITLE
Add ForeignAssets folder and put Goon assets inside.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR adds a ForeignAssets folder in the Assets folder. Inside ForeignAssets is a GoonAssets folder in which assets taken from Goon exist. These assets include the werewolf costume's sprites from #3862, FireAlarm.ogg from #4226, and cannabis sprites from #3587

Included in the GoonAssets folder are unmodified versions of LICENSE.MD and README.MD from /tg/'s "goon" folder.

In relevant folders where .prefabs and .assets point to Goon sprites, I've added .txt files named "zForeignAssets.txt" that state which files use Goon sprites, give the path to said sprites, and what license they are under (in this case, CC BY-NC-SA 3.0 US).

image

### Notes
FireAlarm.ogg and the cannabis sprites were added to GoonAssets after a look in /tg/'s goon folder showed they were imported from Goonstation's 2016 release.

"ForeignAssets" might need a better name.

### CODE REVIEW

**Comment by Bod9001** [comment]
do we have the weed sprites for goon?

**Comment by Jibbajabbafic** [comment]
I'd keep the prefabs in their original place, we just need the sprites and sounds separate with the license since we can always switch them out later on.

**Comment by PetMudstone** [comment]
Well, those are all the Goon assets I could find, for now.

**Comment by Bod9001** [comment]
cool beans, if we find anything else that needs to be moved over should be no problem to do it in another PR

**Pull request merged**
