### PR TITLE
Many small fixes and updates to Outpost's rooms

### PR DESCRIPTION
**Pull request by PerfectTangent**
### Purpose

This PR continues work on #4145 and makes some general modifications and improvement to Outpost station.

changes of significance:

- reworked atmos's foyer area to have a bit more space and not feel so squeezed in.
- shrunk the size of the bridge as described in #4145
- enlarged robotics as described in #4145. It's about double in size, now, with separate places for surgery and manufacturing
- added a maintenance door to the north of Atmos
- added a sec door in the Detective's room to let them walk straight into security without having to walk around through the front door.
- added some extra lighting in places in medical, botany, security, atmos, bathrooms and near arrivals
- added a security post next to arrivals
- rotated some consoles to have more appropriate facings
- slightly rearranged the lawyer's office so that it can support 2 attornies at law (probably is too small, though. Might move the office to near wherever the Courtroom ends up going, but that's for the next PR).
- added secondary entrance to cargo that exists to bring crates through for delivery
- replaced all instances of surgery_12 with operating tables
- fixed an issues in the command shuttle and the two docked utility shuttles that caused them to be depressurized (engine prefabs are not air tight).
- fixed a few mismatched tiles
- fixed about 15 orphaned pipes, mis rotated pipes, or missing pipes in the atmos pipe network
- added a missing tiny fan to one of the doors in the command shuttle
- found and deleted some assets that lacked sprites in the scene (portable air pumps and scrubbers)

### CODE REVIEW

**Comment by PerfectTangent** [comment]
This is a draft PR because there is something very strange going on with Outpost's UnderFloor layer. It's not clear to me what is the problem, but it appears that the original UnderFloor layer has somehow had all of the pipes and wires on it become disconnected. 

Any new wires and pipes I mapped into the scene instead went on to a new UnderFloor (1) layer that spontaneously popped up. Deleting this layer cause the tile palette tools to stop functioning. Deleting the original UnderFloor layer doesn't seem to do much at all; none of the original wires and pipes in the scene are deleted with it. Same with hiding it in the hierarchy.

underfloor

**Comment by Bod9001** [comment]
try deleting the rogue layer then restarting the editor/loading a different map then loading them up again

**Comment by corp-0** [comment]
````
OutpostStation: "APC - Atmos02" has a null value in the list.
OutpostStation: "APC - Atmos02" has a null value in the list.
OutpostStation: "APC - Atmos02" has a null value in the list.
````

**Comment by PerfectTangent** [comment]
Alright, fixed the UnderFloor layer issue. Thanks, Bod. Your suggest helped me solve it. I also fixed the null values. 

If the tests pass, then it should be good to merge. Then I can wash my hands of this.

**Pull request merged**
