### PR TITLE
Adds progress bar to struggling player

### PR DESCRIPTION
**Pull request by vladb99**
Fix for #3282 
Changes resist time from Handcuffs.prefab to 30.

### CODE REVIEW

**Review by fomalsd — CHANGES_REQUESTED** [review]
Thanks, it works when you're standing still!
The only issue is that progress bar disappears if you change facing direction while otherwise standing still, but uncuff sequence isn't really interrupted and in 30s you get uncuffed without the progress bar.

**Comment by vladb99** [comment]
Thanks for the correction. For some reason I assumed the uncuffing process would be cancelled on direction change and didn't think of proving the assumption. It should work now.

**Review by fomalsd — CHANGES_REQUESTED** [review]
Relying on clothing icon doesn't seem like a good solution.
Existing uncuffing implementation is unorthodox, but it doesn't have to stay like that. 
I think you can safely convert that sketchy coroutine with a progress action of yours – since it was most likely implemented before we introduced progress bar system

**Comment by vladb99** [comment]
I am closing the PR till I find a better solution.

**Pull request closed without merging**
