### PR TITLE
Fixes and Adds more Stuff to How-To-Map

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Adds a couple more headings and more things to help the mapping process.

### CODE REVIEW

**Comment by Akbadain29** [comment]
I don't know why the list for Introduction to Scenes has lost the ordered list (ol) html tags I put in. They are still showing up on my end fine and I didn't change anything.

**Comment by Bod9001** [comment]
seems like you have a merge conflict

**Comment by corp-0** [comment]
tell us know on discord if you have problems rebasing to solve the conflict.

**Comment by Akbadain29** [comment]
I think I cleared it now.

**Pull request merged**
