### PR TITLE
Add AIgunship to Square for testing purposes

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
I put this on UnRealStation months ago, but then UnRealStation broke and no one could test it. So I have put it on Square to be tested. Note that you will need to get someone to hook up the gas so the shuttle can fly.

### Changelog:
CL: [Improvement] Adds AI driven shuttle to SquareStation for testing.

### CODE REVIEW

**Comment by PerfectTangent** [comment]
uh, I don't think this is a good idea for a map currently in rotation. It's not something the AI should have.

**Comment by mmails** [comment]
God forbid, some shitter AI is gonna use this to kill everyone

**Comment by MaxIsJoe** [comment]
It's fine, it's for testing purposes.

Will be a fun for both traitor AI and AIs with lawsets that allow them to protect the crew from human harm

**Comment by NoooneyDude** [comment]
Testing what, exactly? Wouldn't Teststation be more appropriate?

**Comment by PerfectTangent** [comment]
yeah, what needs testing with this gunship? It has significant gameplay consequences and it's not intended for standard play that the AI gets a gunship.

**Comment by Akbadain29** [comment]
The ship isn't meant to be permanently on this map, it's meant to be there for a couple of weeks at most. I just wanted to get some feedback on it from people who play. The ship itself can't move unless a crewmember wrenches the gas canister down, the ship's electrical systems are all powered by an onboard plasma generator and not self powered so eventually it will run out of juice. If it's too game braking I'll remove it early no worries.

**Comment by Akbadain29** [comment]
Eh, I'll move it TestStation. That way it won't be an issue for gameplay. I'll just make another commit to this.

**Comment by corp-0** [comment]
can you drop the other commit?

**Comment by Akbadain29** [comment]
I don't know how to do that.

**Comment by Akbadain29** [comment]
Do I cherry pick it?

**Comment by Akbadain29** [comment]
Do you mean rebase it off?

**Comment by VernaSaurus** [comment]
Cherry pick the second commit to a new branch so you can remove the first commit.

**Comment by corp-0** [comment]
``git rebase head~2 -i``
find the commit you want to drop and delete it from the list
``git push --force``

**Comment by Akbadain29** [comment]
Yeah that didn't work at all. I'm going to close this.

**Pull request closed without merging**
