### PR TITLE
Clothes for science and clothes vendor tweaks.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
This PR adds more clothing for science, including the:
- Skirt variations for the RD, scientist, roboticist, and geneticist.
- Techpriest robes.

This PR also adds the SciDrobe, GeneDrobe, and RoboDrobe. Radio headsets were also added to other Drobes, so the MediDrobe will have four medical headsets for example. No job populators are modified.

This PR also adds a bunch of new .assets for the skirts to use, because trying to use Variant Types caused issues.

### Notes:
~~I came across an odd bug regarding skirt variations. For some reason, when you put on a jumpskirt, the research director's uniform (both variations), the nurse's dress, and all three kinds of medical scrubs (blue, green, purple) not appear on you when you put them on. Wearing on any clothing that isn't affected by the bug and isn't a jumpskirt makes the affected clothing appear again when worn. Looking at the Unity console reveals an ArgumentOutOfRangeException. I've tried to fix the issue by fiddling with the .prefabs, but nothing I've done has solved it and I am at a loss. **I've put the exception below in a comment.**~~ Resolved by using seperate .asset files for skirts.

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [ ] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by PetMudstone** [comment]
Here is the exception that fires, same one appears for all affected clothing.
```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <567df3e0919241ba98db88bec4c6696f>:0 
  at SpriteHandler.isPaletted () [0x00034] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Sprite Handler\SpriteHandler.cs:166 
  at SpriteHandler.SetPaletteOfCurrentSprite (System.Collections.Generic.List`1[T] newPalette) [0x00001] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Sprite Handler\SpriteHandler.cs:180 
  at ClothingItem.RefreshFromClothing (ClothingV2 clothing) [0x0003a] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Items\ClothingItem.cs:139 
  at ClothingV2.RefreshClothingItem () [0x00012] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Clothing\ClothingV2.cs:201 
  at ClothingV2.LinkClothingItem (ClothingItem clothingItem) [0x00008] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Clothing\ClothingV2.cs:194 
  at ClothingItem.SetReference (UnityEngine.GameObject Item) [0x000cb] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Items\ClothingItem.cs:117 
  at PlayerAppearanceMessage+<Process>d__6.MoveNext () [0x000f4] in D:\Games\AGit_Projects\unitystation\UnityProject\Assets\Scripts\Messages\Server\PlayerAppearanceMessage.cs:48 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00028] in C:\buildslave\unity\build\Runtime\Export\Scripting\Coroutines.cs:17 

(Filename: <567df3e0919241ba98db88bec4c6696f> Line: 0)
```

**Comment by corp-0** [comment]
> Looking at the Unity console reveals an ArgumentOutOfRangeException

can you show the entire error? Maybe we can fix it before merging

EDIT: lol, just realized you already posted it

**Comment by PetMudstone** [comment]
Yes, just commented it.

**Comment by PetMudstone** [comment]
I'm titling this [Do Not Merge] until I implement my temporary solution for the skirt problems.

**Comment by PetMudstone** [comment]
Fixes (new .asset files) added, should be good to merge now.

**Comment by PetMudstone** [comment]
Titling Do Not Merge again until Dragon's backpack preference PR gets merged as our populators likely conflict.

**Comment by PetMudstone** [comment]
Removed the populator changes, should be good to merge, again.

**Pull request merged**
