### PR TITLE
AI Job

### LINKED ISSUE #6753: Blob stripping
Staging linux

On staging blob can use the inspect window to strip players

it's pretty simple. shift-click and click on the equipment items 

https://user-images.githubusercontent.com/55299415/120909373-7a7bb180-c642-11eb-8036-4dca43f8e0ed.mov

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: [New] Added Ai Job Role and Logic
CL: [New] Added Ai Upload Console and law changing
CL: [New] Added Turrets logic and construction
CL: [New] Added InteliCard logic
CL: [New] Added Ai Core Frame construction

Fixes #6753

This Pr adds a functioning AI Job

It works differently than how AI works in classic, you are not omniscient and see everything all the time. Instead you have to move from camera to camera in order to see stuff.

-You can click on the camera images on the map, or use arrow/movement keys to move to the next nearest camera.

-You can still go to players or mobs by tracking them, that will take you to the camera they can be seen from.

-You can also save cameras for quick movement

-You can interact with doors, and other machines if you can see them, theres an interaction visual when validating an interaction showing whether you can interact with the object or not

Theres a basic door interaction screen (new doors only) but also hotkeys which are:
-Shift click => open/close door
-Ctrl Click => bolt/unbolt door (new doors only)

-Laws can now be changed, fully supports for adding new modules and changing Ai laws using Ai upload console

-Multiple Ai's should be fine too, though they are limited to the spawnpoints on the map as they are one use only, any more Ais will spawn in arrivals. Default amount of Ais is one, but admins can respawn people as Ais

-Traitor Ai is possible and can get objectives to kill players. Wont get objectives to escape or steal items as Ai's dont have hands.... (maybe in the future with borgs we'll allow stealing of items and then at the end of the round they have to be by your core on the ground to count as complete?) (Or maybe we'll just have custom objectives like hacking an amount of APC's, stealing money from Id cards, destroy machine etc....)

-Ai can call the shuttle but not recall

-Ai can be carded and moved to another empty core

-Ai cannot be built yet using a brain, that will be in another PR

Remember to squash merge this

-UI still needs some work

image

image

image

I'm sorry, Dave. I'm afraid I can't do that.

### CODE REVIEW

**Comment by corp-0** [comment]
> Instead you have to move from camera to camera in order to see stuff.

Does this work with players adding/removing cameras during the game?

**Comment by pyrosshade** [comment]
> 
> 
> > Instead you have to move from camera to camera in order to see stuff.
> 
> Does this work with players adding/removing cameras during the game?

seconded, we gotta be able to fight against shodan, yknow

**Comment by ThatDan123** [comment]
> > Instead you have to move from camera to camera in order to see stuff.
> 
> Does this work with players adding/removing cameras during the game?

I did put logic in for detecting camera destruction and when they enable. So that should be fine.

**Comment by ThatDan123** [comment]
Think this is now ready for full testing. I havent done full testing yet, i'll do that tomorrow

Use square as it has cameras, and when saving a camera the box should have the camera name in but the name needs to be mapped and i'll do the mapping after this PR.

**Comment by ThatDan123** [comment]
This is now feature complete for version 1, and I have tested headless and two clients. 

Codacy is failing as it wants me to put playerscript into a namespace, but its fine for it to not be. Would change a lot of unrelated files if it is moved.

**Comment by ThatDan123** [comment]
PR also contains turrets:

-Adds buildable turrets, uses energy guns. But technically on the prefab you could put a bullet gun and it should work

-The energy gun you build it with is the lethal bullet that is shot. The stun setting always uses the taser bullet.

**Comment by corp-0** [comment]
we will be test merging this PR. If things go terribly wrong, we have a checkpoint with 4119. Freeze is soon to be over, we're still evaluating how stability goes so other frozen prs aren't going to be merged, not just yet.

**Comment by waffielz** [comment]
hal 9000 gaming

**Pull request merged**
