### PR TITLE
Adds Unreal, MiniStation and TestStation to the autolabler

### PR DESCRIPTION
**Pull request by AtnerNT**
Took a look around I don't think I need to change any other files that I know of, so this should be good

### CODE REVIEW

**Comment by corp-0** [comment]
yes, this is all it needs to work

**Review by corp-0 — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]

**Comment by ThatDan123** [comment]
@corp-0 The tests don't seem to run when you force the branch to update

**Comment by corp-0** [comment]
damn I knew this needing to be up to date thing was annoying, but it is also the only way for us to be safe and don't merge non-compiling code. @AtnerNT can you please update your branch and push?

**Comment by ThatDan123** [comment]
> damn I knew this needing to be up to date thing was annoying, but it is also the only way for us to be safe and don't merge non-compiling code. @AtnerNT can you please update your branch and push?

Seems Force pushing works fine for other PR's. Might be the tests not wanting to run as a file wasnt changed in the actual project folder? Not sure if we check that

**Comment by corp-0** [comment]
nah, we just check if the changed files are in some particular folders we're ignoring.

**Pull request merged**
