### PR TITLE
NetTabs: multiple pages support, multiple dynamic lists support

### LINKED ISSUE #1837: Multiple Pages support for NetTab system B: 100
# Description
There are a lot of interfaces in original game that use different html pages for navigation. 
Pages can have totally different layout and element sets.
Trying to recreate such interfaces with a single screen and one dynamic list can be hard or impossible (I don't think PDAs will be possible without this)

So a support for page switching must be added. 

## Criteria
1. Hidden page updates shouldn't be sent to observers
2. Nesting of pages must be supported
3. Page switching should be reliable and easy to use

### PR DESCRIPTION
**Pull request by fomalsd**
### Purpose
Resolves #1837 
Adds pages and page switcher component (can be nested)
Adds support for multiple dynamic lists in one tab (choose entry prefab yourself)
Introduces reusing for dynamic list entries on both sides (radar isn’t 100% compatible yet tho)
Adds very experimental composite gameobject sprite renderer (a bit buggy)
GIF

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Look at GUI_Spawner code and corresponding prefab to see how it works
Also important note: I moved ItemList and ItemEntry to different folder – if you develop new tabs on your branch please check out your new dynamic entry prefabs as they might have lost references to these – it happened to spawner in my case

### CODE REVIEW

**Comment by fomalsd** [comment]
It’s ready for review. Has a bit of dirty code and duplication (marked with todo’s), but I don’t want to make Vlandemart and Aran wait any longer

**Comment by Bod9001** [comment]
https://cdn.discordapp.com/attachments/527605784675352586/581576162262646803/unknown.png 
getting errors like this when using it  in build and on editor

pressing the fire button rapidly can cause it to fire at an  increase speed
is the moblist page supposed to scroll?
everything looks good apart from those errors

**Comment by fomalsd** [comment]
Yeah, that GenerateCaret thing is known and likely a Unity/TextMeshPro bug

**Comment by fomalsd** [comment]
Mob list isn't supposed to scroll atm

**Comment by fomalsd** [comment]
Also important note: I moved ItemList and ItemEntry to different folder – if you develop new tabs on your branch please check out your new dynamic entry prefabs as they might have lost references to these – it happened to spawner in my case

**Comment by vlandemart** [comment]
I didn't get any build errors - just tested it in multiplayer with two clients, works as expected.

**Comment by fomalsd** [comment]
I mean you might get Missing Script instead of ItemList and ItemEntry – if you used these in your own tabs, be aware of that

**Comment by fomalsd** [comment]
fixed caret NREs, should be good to merge

**Comment by Bod9001** [comment]
ok, Haven't encountered any errors, would DooblyNoobly Be the one to merge it since it is a bounty?
I say it's all good for merging

**Comment by fomalsd** [comment]
he asked us to merge it if it's ok

**Comment by Bod9001** [comment]
ok, looks all good merging it.

**Pull request merged**
