### PR TITLE
"Fixes" sprite Handler

### PR DESCRIPTION
**Pull request by Bod9001**
### Purpose
also another poke to see if git will properly track the admin folders

this should get rid of the error when dropping items

### Notes:
it's kind of a ghetto way of fixing it but it would work

tested in editor
haven't tested in headless 

I don't think this is worth a bounty so you could just put it back in the pool or add it to my next Bounty

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
whats this about the admin folders? `also another poke to see if git will properly track the admin folders`

**Comment by Bod9001** [comment]
when I updated my fork, the folders for the admin.txt weren't generated so it errored and broke everything

**Comment by DooblyNoobly** [comment]
yikes, merging now

**Comment by Bod9001** [comment]
it's only differences so it might be needed to be tested a bit more

**Pull request merged**
