### PR TITLE
[DNM] Bunch of graphical UI improvements.

### PR DESCRIPTION
**Pull request by alex180500**
**IGNORE EVERYTHING EXCEPT "Managers.prefab" CHANGES**

- All the windows in UI now have cleaner numbers
- All the "Window" go used as base for the panels and tabs are now full size and content is resized correctly
- Added "Tabs" and "Panels" go to sort out stuff
- Values corrected, text fixes
- Fixed chat scrollbar (cannot test)
- Other stuff

### Open Questions and Pre-Merge TODOs

- [X]  I read the contribution guidelines and the wiki.
- [X]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [ ]  This PR does not include files without specific need to do so.
- [X]  This PR does not bring up any new compile errors
- [ ]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Yo @alex180500 make sure you only PR the files you need to PR for your feature or bug fix. You say to ignore everything but the Managers.prefab but you've included a whole bunch of other files. 

What you should do is pull the latest from upstream into your develop branch on your fork and then create a new branch from that and then cut and paste the managers.prefab from this PR branch on to the new one and PR that to unitystation/unitystation.

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]
Current issues that need addressing before merging:

- Playerlist scrolls to the bottom on default, hiding player names at the top.
- Chat scroll bar doesn't work (probably because the chat content rect is not auto fitting the content).
- When stretching right panel out, chat scroll bar stretchs on the x axis also
- Unneeded files included in the PR
- Merge conflict with DoorController.cs

**Comment by Bonfire** [comment]
If you're on Windows or MacOSX you can download the "Github for Desktop" program and within the program you can include or exclude any file you'd like to any push/commit you make. I'd recommend it if you're editing a bunch of files, but only looking to push specific ones. For future reference of course.

**Comment by alex180500** [comment]
Yes, the problem is that whenever I start working on something and then a pr is merged in the upstream I should manually update my fork branch using the desktop app.
I will close this pr and fix all the problem, then pr again.
Thank you guys.

**Pull request closed without merging**
