### PR TITLE
Turns all explosives into bounced signal devices

### PR DESCRIPTION
**Pull request by MaxIsJoe**
part of #6149 

No more pairing to get results, fire in the hole!

### CODE REVIEW

**Comment by PerfectTangent** [comment]
this seems half baked. It doesn't incorporate what we discussed and allows anyone to trigger any explosive without any verification or security.

**Comment by MaxIsJoe** [comment]
> this seems half baked. It doesn't incorporate what we discussed and allows anyone to trigger any explosive without any verification or security.



> this seems half baked. It doesn't incorporate what we discussed and allows anyone to trigger any explosive without any verification or security.

not planning on adding that in this PR.

**Comment by PerfectTangent** [comment]
Isn't this a bit preemptive then? the changes in this PR should probably wait until the rest is complete.

**Comment by MaxIsJoe** [comment]
> Isn't this a bit preemptive then? the changes in this PR should probably wait until the rest is complete.

i'll probably get to add it properly before the next play test. But right now i don't have the brain power to go through that.

**Comment by Bod9001** [comment]
tests still rip

**Comment by corp-0** [comment]
failing tests

**Comment by MaxIsJoe** [comment]
Tests appear fine on my end and no compiler errors, can you re-run tests?

**Comment by NoooneyDude** [comment]
Second run:

```
Missing reference found in scene BoxStationV1, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene OutpostStation, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene FallStation, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene PogStation, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene SquareStation, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene SyndicateOutpost, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene Fallstation Syndicate, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
Missing reference found in scene MiniStation, GameObject Objects/Vendomat, Component Vendomat, FieldName Item
```

```
Assets/Scenes/AdditionalScenes/AncientStation.unity: RemoteSignaller (Missing Prefab) Missing prefab
Assets/Scenes/AdditionalScenes/AncientStation.unity: RemoteSignaller (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/AdditionalScenes/AncientStation.unity: RemoteSignaller (Missing Prefab) Missing prefab
Assets/Scenes/AdditionalScenes/AncientStation.unity: RemoteSignaller (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (4) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (4) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (1) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (1) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (3) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (3) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (1) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (1) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (2) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/BoxStationV1.unity: RemoteSignaller (2) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/OutpostStation.unity: RemoteSignaller (1) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/OutpostStation.unity: RemoteSignaller (1) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/OutpostStation.unity: RemoteSignaller (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/OutpostStation.unity: RemoteSignaller (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/SquareStation.unity: RemoteSignaller (1) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/SquareStation.unity: RemoteSignaller (1) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/SquareStation.unity: RemoteSignaller (1) (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/SquareStation.unity: RemoteSignaller (1) (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revert 
Assets/Scenes/MainStations/SquareStation.unity: RemoteSignaller (Missing Prefab) Missing prefab
Assets/Scenes/MainStations/SquareStation.unity: RemoteSignaller (Missing Prefab) (UnityEngine.Transform) is at 0,0 Please update the prefab/update the map/revertat Tests.SubsceneTests.Check00prefabs () [0x00156] in /github/workspace/UnityProject/Assets/Tests/SubsceneTests.cs:165SendMessage cannot be called during Awake, CheckConsistency, or OnValidate
```

Deleted the wrong prefab?

**Comment by MaxIsJoe** [comment]
maybe we shouldn't deleted any remotes... @PerfectTangent

**Comment by MaxIsJoe** [comment]
this should fix it now

**Review by NoooneyDude — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
mmeerrggee

**Pull request merged**
