### PR TITLE
Sorts player list through alphabitcal order

### LINKED ISSUE #8504: Make the "Jump to Mob"-list Alphabetical
### Description
The current implementation of the "Jump to Mob"-list as a Ghost is disorganized. By my reckoning, people are most likely to be looking for a certain name to follow. I think the list should by default be sorted alphabetically, so a given name is easy to find.

For bonus points, add a sorting option by role, so people can easily find antags to follow.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes #8504

CL: [Improvement] player list is sorted alphabetically.

### CODE REVIEW

**Comment by corp-0** [comment]
I didn't know linq could do that. Is this sorted player list generated every time we open the window?

**Comment by MaxIsJoe** [comment]
> I didn't know linq could do that. Is this sorted player list generated every time we open the window?

ye

**Comment by MaxIsJoe** [comment]
Since it's client sided it doesnt matter

**Comment by corp-0** [comment]
aight but good to know it is updated when we open it

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
