### PR TITLE
Gives Ministation its own syndicate base

### PR DESCRIPTION
**Pull request by AtnerNT**
Capture

Gives Ministation its own syndicate base to match pog and fallstation

### Changelog:
CL: [New] Added new syndicate base to ministation

### CODE REVIEW

**Comment by PerfectTangent** [comment]
Cool, very rad!

I have a couple thoughts; First, I like the flavor, cool shuttle design, it all feels unique. Thanks for reminding me that syndicate secret docs should be in each syndicate base. You should try to fit a tool room in the base somewhere with the parts vendor, can't remember what it's called. That is so nukies have the opportunity to craft IEDs and other gizmos if they want. An airlock separating the bridge of the shuttle from the rest also would be a good addition, I think.

Also, for sake of balance and not prescribing how the operatives play, maybe it would be better to replace the sniper with a randomized contraband gun spawner. It keeps replayability just a bit fresher and doesn't upset the balance as much as an always available sniper rifle would. I think one artifact spawner is sufficient.


The shuttle looks like a space invader.

**Comment by AtnerNT** [comment]
Suggestions applied

**Comment by MaxIsJoe** [comment]
Tests are failing, check your SOs and build settings.

**Comment by corp-0** [comment]
> Ministation Syndicate: "LightSwitch (1)" at (-3008.00, -244.00, 0.00) has no light sources.

**Comment by AtnerNT** [comment]
Will finish this, just been very busy irl as of late

**Comment by AtnerNT** [comment]
Aight, Got round to fixing tests, good to merge

**Review by NoooneyDude — APPROVED** [review]

**Comment by NoooneyDude** [comment]
Nice one 👍

**Pull request merged**
