### PR TITLE
Vomit PR {DNM}

### LINKED ISSUE #6400: Vomitting B:80
### Description

**This is a health related bounty and is immune to the feature freeze.** This bounty calls for the addition of a generalized method for letting characters vomit when needed from various causes.

## What is needed to fulfill the bounty

- [x] provide a generalized system that can be utilized to allow for a character to vomit in response to specific circumstances. the vomiting tool should be configurable to allow for flexibility, such as enabling blood to be vomitted up, how likely someone is to vomit from a specific stimulus and other similar parameters.
- [x] make a component that lets food and reagents induce vomitting when consumed.
- [x] vomitting should cause a temporary movement penalty.
- [x] make vomitting cure a small random amount of toxin damage when done.
- [x] make characters dry heave when they have no food or reagents left in the stomach to vomit up.
- [x] make a *vomit emote for when people wish to willingly force themselves to vomit.

### PR DESCRIPTION
**Pull request by dapocalypse**
### Purpose
Fixed #6400 
Adds a vomitting sysstem.

### CODE REVIEW

**Comment by NoooneyDude** [comment]
Is this a WIP? As it stands, this won't resolve the issue.

**Comment by dapocalypse** [comment]
> 
> 
> Is this a WIP? As it stands, this won't resolve the issue.

That is correct yes, also, does the vomit thing have to be an entirely new component? can I just slap it onto the reagent script

**Comment by corp-0** [comment]
making an already huge script bigger doesn't sound wise. Explain how are you planning to approach the problem.

**Comment by dapocalypse** [comment]
> making an already huge script bigger doesn't sound wise. Explain how are you planning to approach the problem.

Add a variable for vomit chance and vomit type. When metabolizing check to see if the vomit chance isn't zero and roll the dice.

**Comment by dapocalypse** [comment]
ok so uhh, no idea how to get worldpos

**Comment by dapocalypse** [comment]
can somebody plz remove the merge conflict tag

**Comment by dapocalypse** [comment]
its been 7 days so i'm just going to post this to let yall know that i'm still going to be working on this

**Comment by dapocalypse** [comment]
its been 7 days so i'm just going to post this to let yall know that i'm still going to be working on this

**Comment by PerfectTangent** [comment]
@dapocalypse how is this coming along?

**Comment by dapocalypse** [comment]
> 
> 
> @dapocalypse how is this coming along?

sorry, life

I'll try to resume work on this when I can

**Comment by PerfectTangent** [comment]
closing this due to inactivity.

@dapocalypse It can be reopened if and when you find time.

**Pull request closed without merging**
