### PR TITLE
fixes item slots sending interaction twice

### PR DESCRIPTION
**Pull request by Bod9001**
Apparently sending an interaction twice is not a good thing, 

With the Item slot changes
itemStorage should always be the main component , there shouldn't be a time when it's a subobject

### CODE REVIEW

**Comment by ThatDan123** [comment]
Have you checked to make sure there isnt a storage on a child somewhere?

**Comment by Bod9001** [comment]
well the problem is it would break every other item storage though

**Comment by ThatDan123** [comment]
oh sorry didnt read the class as Item Slot, thought you were changing item storage stuff

**Comment by ThatDan123** [comment]
Have you check that all the cases of item slot have the net identity on them?

**Comment by ThatDan123** [comment]
What i mean is have you checked that all the item slot storages have their network identity on them? You've changed the hand prefab, but is that the only case?

**Comment by Bod9001** [comment]
humm, hand prefab was fixing the "Apparently sending an interaction twice is not a good thing," thing

I don't believe anywhere there's a item with a sub game object that does the item storage on it well all item storage being parented to an item

**Pull request merged**
