### PR TITLE
Added information to help UI development

### PR DESCRIPTION
**Pull request by Akbadain29**
### Purpose
Added in file locations so people know how to start making a UI in the documentation. I'll try and add more instructions to link everything together later, but I wanted to add this in before I forget again.

### CODE REVIEW

**Comment by corp-0** [comment]
shouldn't it be "a**n** user interface" ?

**Comment by PerfectTangent** [comment]
The use of "an" is a bit weird with words that start with "u." Some varieties of english accents will use "a" instead of "an" for words like unicorn, university, useful, union, umbrella, etc.. It's just some weird shit that has become a standard in some accents. English is a unreliable, absolute trash brain language. Grammatically, you're right that it would be "an user interface." That would be the correct usage.

**Comment by corp-0** [comment]
what would be the proper way in this case? "A user interface"?

**Comment by PerfectTangent** [comment]
Either is fine for me. I personally would say "**a** user interface."

**Comment by corp-0** [comment]
alrighty then

**Pull request merged**
