### PR TITLE
Fixes infinite monkey Glass shard death Torment

### LINKED ISSUE #9887: [BUG] Wrong dirt footprints when walking horizontaly
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23060210

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

walking through a pile of dirt/paint/blood horizontally leaves 4 footprints
https://github.com/unitystation/unitystation/assets/10403536/e1c4c301-6c57-4809-84d6-658171ee0d33

### What should have happened instead?

straight horizontal footprints

### Steps to reproduce the issue

go through the pile of paint horizontally

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:
CL: [Balance] Resonance cascade only comes from rare items now but it's now back up to 1 in 100.
CL: [Fix] Fixed infinite monkey glass shard death Torment (fixes a server crash).
CL: [Fix] Fixed not being able pull stuff properly.
CL: [Fix] Fixed footprints Getting place weirdly when walking horizontally.

### CODE REVIEW

**Review by corp-0 — DISMISSED** [review]

**Comment by corp-0** [comment]
where in the code is the footprint fix?

**Comment by Bod9001** [comment]
so, it was just breaking from calling Reach local tile twice

**Comment by corp-0** [comment]
does it fix this https://github.com/unitystation/unitystation/issues/9887 ?

**Comment by Bod9001** [comment]
yeah

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
