### PR TITLE
Fixed growing/harvestable Aloe plant

### PR DESCRIPTION
**Pull request by badbon**
S747BS6yCG

### Purpose
Fixes issue #9523

### Notes:
There seemed to be no original sprites for growing aloe plants in unitystation or tg codebase, so I tried making my own. 

### Changelog:

CL: [Fix] Planting aloe seeds no longer results in empty tray.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
ayy! nice one.
I'll be reviewing this PR now

**Comment by MaxIsJoe** [comment]
hm? I can't seem to find the file that assigns these new SOs to something, did you forget to commit it or?

**Comment by badbon** [comment]
Yep sorry. Applied it to prefab now

**Comment by MaxIsJoe** [comment]
image

Tested and working.

**Review by MaxIsJoe — APPROVED** [review]

**Pull request merged**
