### PR TITLE
Shuttle console coordinates fix

### LINKED ISSUE #2077: BUG: Shuttle co-ordinate updates stop working after some time B: 30
# Description

Shuttle co-ordinates stop being updated after some time of shuttle console use

image

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Fly around in a shuttle while watching the co-ordinate GUI
2. Stop interacting with the shuttle GUI (walk away from the console) then come back and reopen it
3. Fly somewhere and notice that the co-ordinates are not being updated

Contributor will receive a bounty of 30usd on a successful merge of a solution that fixes the bug.

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes shuttle console coordionates not updating if the player moves away and returns to the console.
Fixes #2077

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by chairbender** [comment]
Doesn't seem to fix it.

Launch from OutpostStation or Lobby in editor.
Click any shuttle console.
Coordinates are blank.

There might be an issue with order of initialization of things. 

Following errors appear when I try it on any console:
UnassignedReferenceException: The variable Provider of GUI_ShuttleControl has not been assigned.
You probably need to assign the Provider variable of the GUI_ShuttleControl script in the inspector.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/Runtime/Export/GameObject.bindings.cs:28)
GUI_ShuttleControl.get_MatrixMove () (at Assets/Scripts/UI/Shuttles/GUI_ShuttleControl.cs:22)
GUI_CoordReadout.OnEnable () (at Assets/Scripts/UI/Shuttles/GUI_CoordReadout.cs:33)
UnityEngine.Object:Instantiate(GameObject, Transform)
NetTabDescriptor:Spawn(Transform) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:127)
NetworkTabManager:Add(NetTabDescriptor, GameObject) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:72)
NetworkTabManager:Add(GameObject, NetTabType, GameObject) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:79)
TabUpdateMessage:Send(GameObject, GameObject, NetTabType, TabAction, GameObject, ElementValue[]) (at Assets/Scripts/Messages/Server/TabUpdateMessage.cs:66)
HasNetworkTab:ServerPerformInteraction(HandApply) (at Assets/Scripts/Objects/HasNetworkTab.cs:16)
InteractionCoordinator`1:ServerValidateAndPerform(HandApply) (at Assets/Scripts/Input System/InteractionV2/Helpers/InteractionCoordinator.cs:71)
InteractionComponentUtils:ServerProcessCoordinatedInteraction(HandApply, InteractionCoordinator`1) (at Assets/Scripts/Input System/InteractionV2/CoreComponents/InteractionComponentUtils.cs:21)
Interactable`1:ServerProcessInteraction(HandApply) (at Assets/Scripts/Input System/InteractionV2/CoreComponents/Interactable.cs:87)
RequestHandApplyMessage:ProcessHandApply(GameObject, GameObject, GameObject, GameObject, HandSlot) (at Assets/Scripts/Messages/Client/Interaction/RequestHandApplyMessage.cs:51)
<Process>d__4:MoveNext() (at Assets/Scripts/Messages/Client/Interaction/RequestHandApplyMessage.cs:39)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

UnassignedReferenceException: The variable Provider of GUI_ShuttleControl has not been assigned.
You probably need to assign the Provider variable of the GUI_ShuttleControl script in the inspector.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/Runtime/Export/GameObject.bindings.cs:28)
GUI_ShuttleControl.get_MatrixMove () (at Assets/Scripts/UI/Shuttles/GUI_ShuttleControl.cs:22)
GUI_CoordReadout.OnEnable () (at Assets/Scripts/UI/Shuttles/GUI_CoordReadout.cs:33)
UnityEngine.Object:Instantiate(GameObject, Transform)
NetTabDescriptor:Spawn(Transform) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:127)
ControlTabs:FindOrSpawn(GameObject, NetTabDescriptor) (at Assets/Scripts/UI/ControlTabs.cs:491)
ControlTabs:ShowTab(NetTabType, GameObject, ElementValue[]) (at Assets/Scripts/UI/ControlTabs.cs:425)
<Process>d__7:MoveNext() (at Assets/Scripts/Messages/Server/TabUpdateMessage.cs:24)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Review by chairbender — CHANGES_REQUESTED** [review]
Doesn't seem to fix it.

Launch from OutpostStation or Lobby in editor.
Click any shuttle console.
Coordinates are blank.

There might be an issue with order of initialization of things. 

Following errors appear when I try it on any console:
UnassignedReferenceException: The variable Provider of GUI_ShuttleControl has not been assigned.
You probably need to assign the Provider variable of the GUI_ShuttleControl script in the inspector.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/Runtime/Export/GameObject.bindings.cs:28)
GUI_ShuttleControl.get_MatrixMove () (at Assets/Scripts/UI/Shuttles/GUI_ShuttleControl.cs:22)
GUI_CoordReadout.OnEnable () (at Assets/Scripts/UI/Shuttles/GUI_CoordReadout.cs:33)
UnityEngine.Object:Instantiate(GameObject, Transform)
NetTabDescriptor:Spawn(Transform) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:127)
NetworkTabManager:Add(NetTabDescriptor, GameObject) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:72)
NetworkTabManager:Add(GameObject, NetTabType, GameObject) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:79)
TabUpdateMessage:Send(GameObject, GameObject, NetTabType, TabAction, GameObject, ElementValue[]) (at Assets/Scripts/Messages/Server/TabUpdateMessage.cs:66)
HasNetworkTab:ServerPerformInteraction(HandApply) (at Assets/Scripts/Objects/HasNetworkTab.cs:16)
InteractionCoordinator`1:ServerValidateAndPerform(HandApply) (at Assets/Scripts/Input System/InteractionV2/Helpers/InteractionCoordinator.cs:71)
InteractionComponentUtils:ServerProcessCoordinatedInteraction(HandApply, InteractionCoordinator`1) (at Assets/Scripts/Input System/InteractionV2/CoreComponents/InteractionComponentUtils.cs:21)
Interactable`1:ServerProcessInteraction(HandApply) (at Assets/Scripts/Input System/InteractionV2/CoreComponents/Interactable.cs:87)
RequestHandApplyMessage:ProcessHandApply(GameObject, GameObject, GameObject, GameObject, HandSlot) (at Assets/Scripts/Messages/Client/Interaction/RequestHandApplyMessage.cs:51)
<Process>d__4:MoveNext() (at Assets/Scripts/Messages/Client/Interaction/RequestHandApplyMessage.cs:39)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

UnassignedReferenceException: The variable Provider of GUI_ShuttleControl has not been assigned.
You probably need to assign the Provider variable of the GUI_ShuttleControl script in the inspector.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/Runtime/Export/GameObject.bindings.cs:28)
GUI_ShuttleControl.get_MatrixMove () (at Assets/Scripts/UI/Shuttles/GUI_ShuttleControl.cs:22)
GUI_CoordReadout.OnEnable () (at Assets/Scripts/UI/Shuttles/GUI_CoordReadout.cs:33)
UnityEngine.Object:Instantiate(GameObject, Transform)
NetTabDescriptor:Spawn(Transform) (at Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:127)
ControlTabs:FindOrSpawn(GameObject, NetTabDescriptor) (at Assets/Scripts/UI/ControlTabs.cs:491)
ControlTabs:ShowTab(NetTabType, GameObject, ElementValue[]) (at Assets/Scripts/UI/ControlTabs.cs:425)
<Process>d__7:MoveNext() (at Assets/Scripts/Messages/Server/TabUpdateMessage.cs:24)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Aranclanos** [comment]
I can't reproduce your errors

**Comment by DooblyNoobly** [comment]
@chairbender you may of had a meta data problem when checking out the PR. Perhaps try it again but close the editor when checking out the pr via git and then open it again. I've been following that approach since I had similar problems and haven't had a problem since.

**Comment by chairbender** [comment]
sigh...stupid me forgot that was a thing that could happen. working fine now

**Pull request merged**
