### PR TITLE
Loading Screen

### PR DESCRIPTION
**Pull request by NinjaDanz3r**
### Purpose
Part of a solution to issue #4936, introduces a loading screen to the UI Manager.
The loading screen prefab uses a new loading bar prefab, which is a modified slider component.
The screen also includes a TMP text that can be used to inform the player of what is currently being loaded.
It is placed at the last point in the UI manager, which means it renders on top of all other UI elements.
Tested against the standard resolutions and scales correctly.

### Notes:
Very simple, no scripts added but I would like this to get in quick in order to reduce future potential merge conflicts in prefabs.

Looks like this:
loadingscreen

### CODE REVIEW

**Comment by Bod9001** [comment]
looks good, so still requires integration code wise?
I don't mind integrating it if it needs to be

**Comment by fomalsd** [comment]
Hm, this one looks kind of inconsistent with our existing loading screen (which also looks sleeker IMO):
94B422DF-1FE6-4BFB-BB71-EC3BF343F947

**Comment by Bod9001** [comment]
I like it because it's got more information about what's loading

**Comment by NinjaDanz3r** [comment]
> Hm, this one looks kind of inconsistent with our existing loading screen (which also looks sleeker IMO):
> 94B422DF-1FE6-4BFB-BB71-EC3BF343F947

Huh, yeah I might go hunting for those assets and adjust the bar.
It's been a while since I contributed, is there a style guide hanging around the project somewhere?

**Comment by NinjaDanz3r** [comment]
> looks good, so still requires integration code wise?
> I don't mind integrating it if it needs to be

Yep, this commit should meet the requirements of the Loading Screen part of #4936, which does not say anything about how it should function.
I could go in and add a behaviour at the root of the loading screen that would allow a user to show and hide the loading screen as well as changing the text, but at this point I'm pretty much guessing :D

In other words, hit me up if it needs any additional behaviour, it would be no problems adding it.

**Comment by Bod9001** [comment]
check with doobly,I will send them message about it

**Comment by DooblyNoobly** [comment]
hey @NinjaDanz3r kind of just relying on you to make it functional. The criteria I wrote out just paints a broad picture of what is needed. Our end goal is to have this show up when you use the AssetManager to sync an asset. Please add anything that is required to make this functional (i.e. add the code to this functional in the AssetManager). Thanks

**Comment by NinjaDanz3r** [comment]
> hey @NinjaDanz3r kind of just relying on you to make it functional. The criteria I wrote out just paints a broad picture of what is needed. Our end goal is to have this show up when you use the AssetManager to sync an asset. Please add anything that is required to make this functional (i.e. add the code to this functional in the AssetManager). Thanks

Will do, closing PR until then.

**Pull request closed without merging**
