### PR TITLE
Cleanbots removing slippery factor

### LINKED ISSUE #5222: Cleanbot Mayhem
## Description
Cleanbots make lube invisible instead of actually cleaning it up
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Create and use lube
2.  Create clearbot near them
3.  Observe results.

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Cleanbots will now make floors stop being slippery.
Removes a copypasted cleaning method, and now all cleaning will use the Clean() in MetaDataLayer
Fixes half of #5222

### CODE REVIEW

**Comment by corp-0** [comment]
I will make it close the issue. If the bust thing is clarified, we can reopen.

**Comment by PerfectTangent** [comment]
I believe it's referring to a case where a cleanbot moved onto a tile that had a hippocrates statue to clean blood under it and it deleted the statue

**Comment by corp-0** [comment]
if the bust is a game object, then it makes no sense.

**Comment by AutumnNova** [comment]
I believe npcs at some point could seek out and consume food, so im assuming somehow the bust is being consumed?

**Comment by corp-0** [comment]
only if someone manually set the bust as food for that particular NPC

**Comment by Aranclanos** [comment]
at the moment of cleaning the cleanbots -used to- run 
`var floorDecal = registerObj.Matrix.Get<FloorDecal>(checkPos, true).FirstOrDefault(p => p.Cleanable);`

But neither prefabs called Bust or BustHippocrates have a FloorDecal

**Pull request merged**
