### PR TITLE
Quatumn pad fix

### PR DESCRIPTION
**Pull request by ThatDan123**
Quatumn pad teleporting self fix.

CL: [Fix] fixed Quatumn pad teleporting themselves (lol).

### CODE REVIEW

**Review by Bod9001 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]
lol, how did this even happen

**Comment by corp-0** [comment]
> lol, how did this even happen

Bod added PullPush to all objects by default and teleporters use PushPull to know when to teleport stuff.

**Comment by corp-0** [comment]
it still teleports itself when someone is is on top of the pad

**Comment by jamessimo** [comment]
I think this issue was not fixed.

**Pull request merged**
