### PR TITLE
Revert "New locker sprites by Cornelius Bogfrollup Fitzgerald."

### PR DESCRIPTION
**Pull request by ghost**
Reverts unitystation/unitystation#4966

### CODE REVIEW

**Comment by AzzyIsNotHere** [comment]
hi swept how ya doin?
food for thought, fuck off

**Comment by ghost** [comment]
https://youtu.be/2-mCpRYCM7A

**Comment by AzzyIsNotHere** [comment]
lol. like i said, hi swept
why are you here? you've been banned. go away

**Comment by BootlegBow** [comment]
I agree with Canadian, fuck off

**Pull request closed without merging**
