### PR TITLE
Made vents scrubbers more resilient to fire and fixed reactor interactions

### PR DESCRIPTION
**Pull request by Bod9001**
yeah is odd the serialise data for the reagent mix part is not getting applied properly so I had to manually make it at water

### CODE REVIEW

**Comment by Bod9001** [comment]
this bot is useful

**Comment by Bod9001** [comment]
can't work out how to get rid of the scene changes

**Comment by ThatDan123** [comment]
Gonna have merge conflicts with #4886 

Which ever one is merged second will need to update the atmos devices to have 15 gases in their lists not 4.

**Comment by corp-0** [comment]
https://devconnected.com/how-to-remove-files-from-git-commit/ give this a try

**Comment by Bod9001** [comment]
there we go fixed

**Comment by ThatDan123** [comment]
Missing reference found in scene BoxStationV1, GameObject Objects/NuclearReactorConsole (1), Component NuclearReactorConsole (1), FieldName Reactor Chambers
Missing reference found in scene BoxStationV1, GameObject Objects/NuclearReactorConsole (1), Component NuclearReactorConsole (1), FieldName Reactor Chambers

Missing reference found in scene OutpostStation, GameObject Objects/NuclearReactorConsole (1), Component NuclearReactorConsole (1), FieldName Reactor Chambers

Missing reference found in scene SquareStation, GameObject Objects/NuclearReactorConsole (1), Component NuclearReactorConsole (1), FieldName Reactor Chambers

**Comment by corp-0** [comment]
we should totally make the test publish the result as a comment

**Comment by Bod9001** [comment]
man, I didn't even touch the scenes

**Comment by corp-0** [comment]
https://github.com/unitystation/unitystation/blob/82c1c64bef63514c83954599750231fc81b22a2a/UnityProject/Assets/Scenes/DevScenes/RRT%20DEV2.unity this one appears as changed

**Comment by Bod9001** [comment]
but that one doesn't have any problems though xD

**Comment by corp-0** [comment]
image
now you have changes on all of these

**Comment by Bod9001** [comment]
yeah to fix the tests

**Pull request merged**
