### PR TITLE
[DNM] Table climbing

### PR DESCRIPTION
**Pull request by aleios**
Adds the ability to climb on tables. Can probably be expanded to just about anything that takes a TileInteraction.

I've put this up as 'Do Not Merge' to get the code reviewed and to get ideas of how to handle the TileInteractions better. I am not happy with the solution implemented as it shoehorns the event data into TileApply whilst sending an entirely new event TileMouseDrop. 

It works but it's not exactly elegant. Any thoughts are appreciated.

### CODE REVIEW

**Comment by Ranzarth** [comment]
Probably want to wait until #3646 is merged before merging this

**Comment by aleios** [comment]
Yep, I think https://github.com/unitystation/unitystation/pull/3644 will also help for its change to IsPassableTo().

**Comment by ThatDan123** [comment]
The PRs were merged so you might want to do some more testing to make sure nothing broke.

**Comment by aleios** [comment]
Yep, done some tests locally. Still works with those PRs merged. Syncs on server and client and late joins.

**Comment by DooblyNoobly** [comment]
cool, lets see how it goes on staging

**Pull request merged**
