### PR TITLE
Fix Maintrooms Tests

### PR DESCRIPTION
**Pull request by AtnerNT**

### CODE REVIEW

**Review by MaxIsJoe — DISMISSED** [review]

**Comment by AtnerNT** [comment]
I literally moved it off 0,0

**Comment by AtnerNT** [comment]
I have a fix in mind but in class, will fix this soon

**Comment by AtnerNT** [comment]
Capture
straight up not at 0,0

**Comment by MaxIsJoe** [comment]
> Capture straight up not at 0,0

what about the scene itself?

**Comment by AtnerNT** [comment]
> what about the scene itself?

Maint rooms is at -3000 -3000, Ran the test locally and it succeeded, so just gonna try again and hope there was an error pushing the commit

**Comment by AtnerNT** [comment]
Okay I straight have no idea why this aint working, tried it locally and tests past fine. Thing aint even at 0,0 on any matrix

**Comment by MaxIsJoe** [comment]
Merge and see if it fixes itself?

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
