### PR TITLE
Removes bvold objects from boxstation

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Removes bvold objects from boxstation

### CODE REVIEW

**Comment by ThatDan123** [comment]
BoxStationV1: "APC" has a null value in the list.
BoxStationV1: "APC" has a null value in the list.
BoxStationV1: "APC" has a null value in the list.
BoxStationV1: "APC" has a null value in the list.
BoxStationV1: "ButtonDoor" is not assigned to "APC"
BoxStationV1: "FireAlarm" is not assigned to "APC"
BoxStationV1: "FireAlarm" is not assigned to "APC"
BoxStationV1: "FireAlarm" is not assigned to "APC_Permabrig"
BoxStationV1: "WinDoorRight (1)" is not assigned to "APC"
BoxStationV1: "CommServer (2)" is not assigned to "APC"
BoxStationV1: "Processor (3)" is not assigned to "APC"
BoxStationV1: "BusMainframe (2)" is not assigned to "APC"
BoxStationV1: "CommServer (3)" is not assigned to "APC"
BoxStationV1: "CommServer (4)" is not assigned to "APC"
BoxStationV1: "Processor (4)" is not assigned to "APC"
BoxStationV1: "BusMainframe (1)" is not assigned to "APC"
BoxStationV1: "CommServer (1)" is not assigned to "APC"
BoxStationV1: "MessageServer (1)" is not assigned to "APC"
BoxStationV1: "Receiver (2)" is not assigned to "APC"
BoxStationV1: "Broadcaster (1)" is not assigned to "APC"
BoxStationV1: "Hub (1)" is not assigned to "APC"
BoxStationV1: "BlackBoxRecorder (1)" is not assigned to "APC"
BoxStationV1: "Receiver (1)" is not assigned to "APC"
BoxStationV1: "Broadcaster (2)" is not assigned to "APC"
BoxStationV1: "CommServer (6)" is not assigned to "APC"
BoxStationV1: "BusMainframe (4)" is not assigned to "APC"
BoxStationV1: "Processor (2)" is not assigned to "APC"
BoxStationV1: "CommServer (8)" is not assigned to "APC"
BoxStationV1: "CommServer (7)" is not assigned to "APC"
BoxStationV1: "BusMainframe (3)" is not assigned to "APC"
BoxStationV1: "Processor (1)" is not assigned to "APC"
BoxStationV1: "CommServer (5)" is not assigned to "APC"
BoxStationV1: "Relay (1)" is not assigned to "APC"

**Comment by ThatDan123** [comment]
BoxStationV1: "LightTubeFixture" miss switch reference.

**Comment by ThatDan123** [comment]
Could you look at #5582 if you have time.

**Comment by ThatDan123** [comment]
BoxStationV1: "ButtonDoor" is not assigned to "APC"
BoxStationV1: "FireAlarm" is not assigned to "APC"
BoxStationV1: "FireAlarm" is not assigned to "APC"
BoxStationV1: "FireAlarm" is not assigned to "APC_Permabrig"
BoxStationV1: "WinDoorRight (1)" is not assigned to "APC"
BoxStationV1: "CommServer (2)" is not assigned to "APC"
BoxStationV1: "Processor (3)" is not assigned to "APC"
BoxStationV1: "BusMainframe (2)" is not assigned to "APC"
BoxStationV1: "CommServer (3)" is not assigned to "APC"
BoxStationV1: "CommServer (4)" is not assigned to "APC"
BoxStationV1: "Processor (4)" is not assigned to "APC"
BoxStationV1: "BusMainframe (1)" is not assigned to "APC"
BoxStationV1: "CommServer (1)" is not assigned to "APC"
BoxStationV1: "MessageServer (1)" is not assigned to "APC"
BoxStationV1: "Receiver (2)" is not assigned to "APC"
BoxStationV1: "Broadcaster (1)" is not assigned to "APC"
BoxStationV1: "Hub (1)" is not assigned to "APC"
BoxStationV1: "BlackBoxRecorder (1)" is not assigned to "APC"
BoxStationV1: "Receiver (1)" is not assigned to "APC"
BoxStationV1: "Broadcaster (2)" is not assigned to "APC"
BoxStationV1: "CommServer (6)" is not assigned to "APC"
BoxStationV1: "BusMainframe (4)" is not assigned to "APC"
BoxStationV1: "Processor (2)" is not assigned to "APC"
BoxStationV1: "CommServer (8)" is not assigned to "APC"
BoxStationV1: "CommServer (7)" is not assigned to "APC"
BoxStationV1: "BusMainframe (3)" is not assigned to "APC"
BoxStationV1: "Processor (1)" is not assigned to "APC"
BoxStationV1: "CommServer (5)" is not assigned to "APC"
BoxStationV1: "Relay (1)" is not assigned to "APC"

BoxStationV1: "LightTubeFixture" miss switch reference.

**Comment by ThatDan123** [comment]
Remember you can run the tests in the editor too. If you click the giant unitystation button at the side, I think that's the test button.

If theyre not saving the APC, you might have to add it manually to the field, instead of using the connect tool, Ive had that problem in the past.

**Comment by corp-0** [comment]
green so I merge

**Pull request merged**
