### PR TITLE
Fixes fireLocks being invisible and fixes being able to pull vomit and other floor decals

### PR DESCRIPTION
**Pull request by Bod9001**
### Changelog:

CL: [Fix] Fixed being able to pull vomit and others unmovable objects.
CL: [Fix] Fixed fireLocks being invisible

### CODE REVIEW

**Comment by eurtod** [comment]
what do you mean by being able to "pull a sick"?

**Comment by corp-0** [comment]
yeah, what do you mean?

**Comment by Bod9001** [comment]
The sick prefab You can pull it

**Comment by Bod9001** [comment]
You shouldn't be able to pull Decals

**Comment by corp-0** [comment]
> The sick prefab You can pull it

the sickness zone prefab isn't in the list of changes. I modified your changelog to mention floor decals.

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
