### PR TITLE
Bruisepack/Ointment code changes and bleeding values reduction 

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Merges BruisePackTrigger and OintmentTrigger into MedicalStackTrigger
Now these two items will have a defined amount of uses, wont heal limbs that are healthy and characters who try to heal themselves will have a progress action. Healing others is still instantaneous.
Fixes Attack() using the server's character bodylimb aim instead of the originator.

Bleeding speed is greatly reduced and will start at 20 brute damage on a single limb. Several limbs bleeding at the same time will increase the amount of blood loss.
Limb bleeding stops when the brute damage of said limb is below 20.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Unless im forgetting anything else, #1724 can be closed after this

### CODE REVIEW

**Comment by fomalsd** [comment]
While bruise packs work, ointments do not, and just make a punching sound (yes, I tried to treat burn damage)
Did you forget to slap a script on them?

**Comment by Aranclanos** [comment]
Fixed

**Comment by DooblyNoobly** [comment]
Looks like this PR does not solve Stability, Security and maybe even the Tile Melee Damage(?) requirements for #1724 so we might split the bounty here and close that issue and create separate ones for the remaining todo criteria. Will do that after this PR has been fully reviewed

**Comment by Aranclanos** [comment]
Security part should be done, today I noticed some errors about pets that im still checking
no idea about tile damage, that doesnt exist

**Comment by DooblyNoobly** [comment]
Cool, yeah I think Tile Damage really needs it own issue as it is a bit more involved to lump in with this stuff.

**Comment by Aranclanos** [comment]
the issue can stay open but this is ready to merge since the pet stuff is already in develop heheHEHEHE

**Comment by Aranclanos** [comment]
All pet issues should be fixed now

**Pull request merged**
