### PR TITLE
Late Joiners Spawn At Arrivals After 2 Min

### LINKED ISSUE #3259: Make all late joiners spawn on arrivals shuttle
As per title.
If you didn't join within 1-2 mins after round start you should spawn in arrivals shuttle instead of your usual spawn.
Make sure it doesn't interfere with nuke ops spawn point!

### PR DESCRIPTION
**Pull request by DVanwart**
# Late Joiners Spawn At Arrivals

### Purpose
All players, excluding special jobs, will use the assistant spawn location after 2 minutes station time.
Resolves #3259

### Notes:
- Gets current round time from GameManager.stationTime
- In PlayerSpawn.NEVER_SPAWN_ARRIVALS_JOBS can be updated with any new jobs that should ignore this rule, current values are below
```
{
	JobType.AI, 
	JobType.SYNDICATE
});
```
- ~~OK BUT WHAT IF YOU HAD TO WHEEL THE AI INTO THE STATION ON LATE JOIN~~
- PlayerSpawn.ARRIVALS_SPAWN_TIME holds the time for when this rule starts applying
- Also small NRE protection for seed extractor if power state change call happens before awake is called.

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.

### CODE REVIEW

**Comment by DVanwart** [comment]
Just noticed POG doesn't have assistant's spawn on the shuttle so I'm going to rework this to check for a shuttle spawn and just use assistant as a fallback

**Comment by PetMudstone** [comment]
I would like to note that SeedExtractor.cs is included in this PR and has a single character ("?" to be exact) added to a line. Is this intentional?

**Comment by DVanwart** [comment]
@PetMudstone yep! Was getting a NRE when clients joined and the power loaded before the seed extractor did
> Also small NRE protection for seed extractor if power state change call happens before awake is called.

**Comment by DVanwart** [comment]
If tests pass this should be good to merge

**Pull request merged**
