### PR TITLE
Some new sprites 

### PR DESCRIPTION
**Pull request by GenericDaemon**
Some sprites for later use

### CODE REVIEW

**Comment by GenericDaemon** [comment]
Oh wait i forgot to change the desc dammit

**Comment by corp-0** [comment]
It’s fine. Are these sprites yours? If not, what is the source and what is the license?

**Comment by ThatDan123** [comment]
You can edit the post desc by click the ... at the side next to the emoji button.

**Comment by GenericDaemon** [comment]
oh yeah all sprites with the exception of the vending machines are mine
the vending machines are ripped directly from /tg/'s source code

**Comment by corp-0** [comment]
Alrighty then. Thank you.

**Pull request merged**
