### PR TITLE
Fixes job slots lock after player dc

### LINKED ISSUE #1663: Job slots still occupied after round restart or player disconnecting B: 30
# Description
When users disconnect, the job slot they chose is still marked as occupied and the job list is not updated, preventing anyone else from taking on the job. The player count is also not reduced on the job screen.

Additionally, when the round is restarted, the job list doesn't clear out and all the slots that were occupied the previous round still show as occupied. It should show as completely empty at the start of a new round.

(Currently only discovered on headless)

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes the logout item dropping process runtiming, locking jobs for new logins
Fixes #1663 

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### Notes:
lambda expressions and null propagation operators dont get along

### CODE REVIEW

**Comment by Aranclanos** [comment]
Looks like it also fixes #1664

**Comment by fomalsd** [comment]
nice, thanks!
don't think it fixes #1664 though, it's only been reported on headless server

**Comment by Aranclanos** [comment]
on the form I was able to reproduce the bug, it definetely fixes it

**Comment by DooblyNoobly** [comment]
ok we should be able to test this now

**Pull request merged**
