### PR TITLE
Fixes maps having sprites manually set to null

### LINKED ISSUE #5860: Fix Prefabs in each Map with Sprite set to "None"
## Description
Prefabs had their Sprite set to "None" after being placed into a Scene, causing it to have no sprite in-game.
This problem is specific to each map, since overrides affect only the scene the prefab is in and not the base prefab.

### tl;dr 
Right-click and press revert on the child sprite object(s) on the overwritten field. 
Repeat for every object in the scene that has such issue(s).

### Main Stations
* [x] Fix Missing Sprites in Outpost Station
* [x] Fix Missing Sprites in Square Station
* [ ] Fix Missing Sprites in Box Station
* [x] Fix Missing Sprites in Fall Station
* [x] Fix Missing Sprites in Pog Station
* [x] Fix Missing Sprites on Test Station

### Awaysites / Other Scenes
* [ ] Fix Missing Sprites on the Outpost Station Syndicate Base Scene
* [ ] Fix Missing Sprites on Buldinn's Centcomm Scene
* [ ] Fix Missing Sprites on the Wizards Asteroid Scene
* [x] Fix Missing Sprites on the Wizards Shuttle Scene
* [ ] Fix Missing Sprites on LavaLand Scene
* [ ] Fix Missing Sprites on Ancient Temple Awaysite
* [ ] Fix Missing Sprites on Palace Awaysite 

* [x] Fix Missing Sprites on Fall Station Syndicate Base Scene
* [x] Fix Missing Sprites on Fall Station Centcomm Scene 
* [x] Fix Missing Sprites on Pog Station Syndicate Base Scene
* [x] Fix Missing Sprites on Dark Jungle Awaysite
* [x] Fix Missing Sprites on Cavernia Awaysite
* [x] Fix Missing Sprites on Relictica Awaysite
* [x] Fix Missing Sprites on Asteroid Scenes

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Resets all sprite values being manually set to null in all objects of all maps to their default values.
Fixes #5860

### Notes:
It's so many lines that I'm clueless about side effects that this might produce 
If anyone has conflicts just overwrite my change and I'll do it again, its just a replaceall click. Or just ask me to make a pr to your branch.

### CODE REVIEW

**Comment by Bod9001** [comment]
did you test in editor?

**Comment by Aranclanos** [comment]
yeah but its a rather ewak testing since I'm not sure what to even do besides walking around and randomly click things

**Comment by Bod9001** [comment]
yeah, If the sprites haven't gone all crazy then it is working fine

**Comment by corp-0** [comment]
Discard Pog changes since it will conflict with whatever slug has been doing. We can reapply this once he pr's

**Comment by Aranclanos** [comment]
pog and syndicate pog or just pog

**Comment by corp-0** [comment]
@SluggyWuggies ^

**Comment by ThatDan123** [comment]
I had a look around the scenes, seems like everything is fine. I'll merge

**Pull request merged**
