### PR TITLE
Adds antag banners at spawn

### PR DESCRIPTION
**Pull request by corp-0**
### Purpose
GIF 13-09-2020 22-36-58

When a player spawns as an antag, it will play a little animated banner so it is absolutely impossible to miss it. It also plays an optional sound cue like it did in TG.

The banners can be customized in the Antagonist scriptable object 
image

### Notes:
I included a library to do tween animation in an efficient way.
I didn't touch SoundManager since JesterX is working on it, so I didn't add the TG spawn sounds to the manager.
Finally, of course it can be improved further, all I did was program a silly fadein/fadeout linear animation and used a random image for the background. Stylistic improvements should come later.

### CODE REVIEW

**Comment by corp-0** [comment]
5egapdhexxm51

**Comment by Bod9001** [comment]
Can you move the plugging into the standard assets folder?
and give it a assembly definition, then It shouldn't have to recompile every time you recompile main code

**Comment by corp-0** [comment]
I will give it a try. Tried installing with the package manager but it didn't work so I use the regular assets store.

**Comment by corp-0** [comment]
done

**Pull request merged**
