### PR TITLE
movement improvements

### LINKED ISSUE #8769: Blob camera can be pushed around by air pressure
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

Having your blob cam close to a pressurized tile or area pushes you around as if you were an object or player

### Steps to reproduce

1. Be a blob
2. Cause something to create air pressure, like destroying any gas canister
3. Be next to said cause of air pressure

### LINKED ISSUE #8793: Conveyor Belts have lost their animations
### Environment
- Game Version: Staging 7-6-2022
- OS Version: Win 10

### Detailed description of bug

Title

### Steps to reproduce

1. Try turning on the Conveyor belt
2. Watch as no animations play

### LINKED ISSUE #8794: Conveyor belts stop working randomly and are very slow
### Environment
- Game Version: 07-06-2022
- OS Version: Win10

### Detailed description of bug

Title

### Steps to reproduce

1. Stand on a Conveyor belt that is active
2. Watch as you no longer move randomly
3. The belt push is very slow when its working
4. You do not have control over your character while being moved by the belts

### PR DESCRIPTION
**Pull request by Bod9001**
Adds multi-tile movement check, 
changes how space wind works

Fixes  #8769
Fixes  #8794
Fixes   #8793

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
Can we get a explanation on how the new wind works?

**Comment by Bod9001** [comment]
it pushes you with the Newtonian movement now

**Comment by corp-0** [comment]
Using two different bools for stickyMovement, StickyMovement and Ignore stickyMovement, feels dirty

**Comment by corp-0** [comment]
remember to link the issues this fixes, if any

**Pull request merged**
