### PR TITLE
why do I have to use this method ( test do not merge )

### PR DESCRIPTION
**Pull request by Bod9001**
Will this work

### CODE REVIEW

**Comment by corp-0** [comment]
the workflows that PR runs are the ones in our repository so this won't ever trigger unless merged. Let's wait for the support team to answer, we shouldn't need to make a workflow for codacy.

**Comment by corp-0** [comment]
well never mind I see the thing running in the list of checks in progress

**Comment by Bod9001** [comment]
apparently didn't find anything wrong with it xD 
humm I wait for support

**Comment by corp-0** [comment]
probably because of this ``max-allowed-issues: 2147483647``

**Comment by corp-0** [comment]
but still, I would rather have the codacy.app panel and all

**Comment by Bod9001** [comment]
yeah, apparently supposed to report back but doesn't seem to be working

**Pull request closed without merging**
