### PR TITLE
Goodbye InputTrigger - finish IF2 migration

### LINKED ISSUE #1760: Refactor mouse interaction system
# Description
A number of us have had difficulties working with, understanding, and building on the current interaction system. Let's use this ticket to try to figure out what we don't like about it, what we would want in an alternative, and to come up with a plan for how we could make it better. We can add comments to list our ideas and update this description based on our conclusions.

By "interaction system", I'm referring to:

- the logic in MouseInputController which begins with CheckMouseInput
- InputTrigger and EVERYTHING that derives from it (lots of stuff)

Please provide your ideas in the comments for:

1. Things you don't like about the current system.
2. Things you would want in the new system.
3. How the new system would work.

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #1760 

Removes all traces of the old interaction system, refactoring everything to use IF2.

Note that nettab is no longer using inheritance. HasNetTab component defines what tab to show when clicked, and logic specific to the nettab (such as chem dispenser allowing you to put in a beaker) is in a different component.

Some other components were refactored to split things up or delete things no longer needed.

Adds / tweaks a few interaction types based on the needs observed as I refactored. InventoryApply can be done with emtpy hand, PositionalHandApply includes the position that was clicked (needed for tile interaction)

InteractionValidationChain is now immutable, to allow re-using them safely.

Documentation updated as always: https://github.com/unitystation/unitystation/wiki/Implementing-Interactions

Also fixes a random glitch I noticed where the welder icon in inventory wasn't being updated for clients when activated.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
It's on me to help anyone who has merge conflicts trying to merge stuff into develop, unless they manage to figure out how to do it themselves.

### CODE REVIEW

**Comment by chairbender** [comment]
Just to add to this after some discussion on Discord - if you don't like InteractionValidationChain then don't worry, I also think it needs to work differently and am planning to improve it. I think it's okay to have it for now for this PR.

As it stands it's a little unclear how it works and what it's doing unless you read the docs, and also it should be possible to just write an interactable component without being forced to implement the validation chain method and it should "just work", so I have some ideas on that. Additionally, it's just kind of awkward to use because you might have some conditional validation logic that you want to run on server or client side but validation  chain is a straight sequence of validators. So I will devise a way to fix that as my next step.

**Comment by chairbender** [comment]
Actually, I think I want to fix those problems before merging it. Now that I realize the issue I'm too annoyed to let it get merged, and I'm already underway on an improvement. Will give time for other people to merge their upcoming PRs also so I can take care of refactoring them at that time.

it should make the PR smaller, if anything

**Comment by chairbender** [comment]
Oookay, ready for another look. I completely revamped the documentation as well:
https://github.com/unitystation/unitystation/wiki/Implementing-Interactions

**Comment by Bod9001** [comment]
Thanks for putting your time and effort into coding for us, is amazing how much work you have done and especially documentation is excellent as well
Good job

**Comment by fomalsd** [comment]
I've just merged Vending GUI PR and some conflicts appeared, could you please resolve them so I could merge this one?

**Comment by chairbender** [comment]
@fomalsd done

**Pull request merged**
