### PR TITLE
Revised Pog Overhaul

### PR DESCRIPTION
**Pull request by SluggyWuggies**
Now doors will have less of a chance for evisceration, as before, moved most western and northern departments to the middle, expanded atmos, added sci, made things worse in general, broke cargo shuttle, broke possibly many things, gave sec more pew, added solars around the station, wired them to grid

image

### CODE REVIEW

**Comment by ThatDan123** [comment]
Try running the test runner to make sure everything passes for pog:

image

As i think you might have some light switch stuff to fix.

**Comment by ThatDan123** [comment]
DNM

**Comment by SluggyWuggies** [comment]
completely fucked. patch soon™️

**Comment by ThatDan123** [comment]
Bit confused as to the other file you commited.

**Comment by SluggyWuggies** [comment]
that one wasn't one i wanted to commit, nor could i delete it, so.. feck

**Comment by ThatDan123** [comment]
If you find that file readd that stuff then commit, it should be removed. Probably an easier way but it should work.

**Comment by ThatDan123** [comment]
Ready to merge?

**Comment by SluggyWuggies** [comment]
yes.

**Comment by unit0016** [comment]
calling it now, this'll make pog liked by the community.

**Pull request merged**
