### PR TITLE
Gamemode max antag

### PR DESCRIPTION
**Pull request by ThatDan123**
Adds max antag field to gamemode SO

-Sets max antags for blob to 1

### CODE REVIEW

**Comment by Bod9001** [comment]
could it be adjusted later on to be scalable with population?

**Comment by ThatDan123** [comment]
Already is, thats what the antag ratio variable is, this new one is literally the max it will go.

**Comment by Bod9001** [comment]
2017 TG allowed multiple blobs,  lare you limiting it for it being too overpowered
and
can admins spawn more than the max?

**Comment by ThatDan123** [comment]
Yeah, this doesnt affect admins. Just on round start (or if the gamemode has mid round antags on which blob doesnt atm)

What ratio would you suggest if we want more than one?

Like 1 for every 30 players? (not that we'd get to 60 players atm) 

Or if you wanted to make it hard for the crew i could add so that the blob gains more resources after a certain player limit is hit.

**Comment by Bod9001** [comment]
humm, I think we can tweak it later on

**Comment by wraith-54321** [comment]
[https://github.com/unitystation/unitystation/issues/5196](url)
this is an issue I opened about this

**Comment by corp-0** [comment]
it is related, but this PR doesn't solve your issue just yet.

**Pull request merged**
