### PR TITLE
PogstationREDUX Patch v2

### PR DESCRIPTION
**Pull request by LastCaptainBonk**
Purpose
Fixes some minor issues plaguing Pogstation (hopefully this will be the last PR for PSR for a while).

Changelog:
CL: [New] Adds a light tube fixture outside EVA room, CE office on Pogstation.

CL: [New] Adds some statues around the station on Pogstation.

CL: [New] Adds some tiny fans to the toxins testing maintenance vents to prevent a major breach on Pogstation.

CL: [New] Adds various medkits around the station regarding where they'd be most useful on Pogstation.

CL: [New] Adds gauze to the surgery room on Pogstation.

CL: [New] Adds prisoner IDs all along the outside of permabrig on Pogstation.

CL: [New] Adds water coolers around the station and in break rooms on Pogstation.

CL: [New] Evac now outfitted with proper seating on Pogstation.

CL: [Improvement] Flips the windoor in the curator's office for aesthetic reasons on Pogstation.

CL: [Improvement] Removes the lights in the maintenance vents below the restrooms on Pogstation.

CL: [Improvement] Renovates nuclear chamber on Pogstation.

CL: [Improvement] Renovates dorms on Pogstation.

CL: [Improvement] Turns a lookout in maintenance into a cat room on Pogstation.

CL: [Improvement] Moves gibber in science into the freezer at the kitchen on Pogstation.

CL: [Improvement] Other minor and miscellaneous tweaks around the station regarding tiles and whatnot on Pogstation.

CL: [Fix] The turret in the vault should now actually fire on Pogstation.

CL: [Fix] The turrets in the AI core should be able to actually hit their targets now on Pogstation.

CL: [Fix] Links up machines to the research server directly on Pogstation.

CL: [Fix] Replaces the bomb closets in xenoarchaeology to anomaly closets on Pogstation.

CL: [Fix] Adds available machines to the research server directly on Pogstation.

CL: [Fix] Adds all available machines to the ore silo on Pogstation.

CL: [Fix] Replaces the biohazard suit closets in xenoarchaeology with anomaly suit closets on Pogstation.

### CODE REVIEW

**Comment by AtnerNT** [comment]
forgot to comment this on last PR, for the research server stuff.
So on all science equipment, (Artifact Analysers, Protolathes, Circuit Imprinters, Blast yield detectors etc). On the relevant script there is a field that says 'Research Server' or 'Connected Research Server'. All you have to do is set that field to the research server you have mapped.

(Note, by relevant script, I mean like the ArtifactAnalyser Component on Artifact Analysers, or the RDProductionMachine script on Protolathes and Imprinters)

**Comment by LastCaptainBonk** [comment]
I see. Well then I guess I wish this PR NOT TO BE MERGED until science has been linked successfully.

**Comment by corp-0** [comment]
changelog needs to mention Pogstation, otherwise you have no idea what the context is

**Comment by AtnerNT** [comment]
Also been taking a tour around new pog (big fan), however I have noticed that you have put bomb closets in xenoarch instead of anomaly closets

**Comment by LastCaptainBonk** [comment]
Thanks for the heads up! The PR has been updated and, I believe, is ready for merging.

**Comment by corp-0** [comment]
I would tune down the amount of records for the changelog. Surely you can merge some into a single one.

**Comment by corp-0** [comment]
```
PogStation: Device "PogStation/Station/Objects/Gibber (1)" at (65.00, 225.00, 0.00) is not connected to APC "PogStation/Station/Objects/APC - XenoBio" at (2.00, 237.00, 0.00).
The APC's devices list may unintentionally contain this device. The device is currently connected to "PogStation/Station/Objects/APC - KitchenBar&Hydro" at (66.00, 222.00, 0.00).
```

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
