### PR TITLE
Internal magazines and clips(partial fix of #3312)

### PR DESCRIPTION
**Pull request by Tjarr737**
### Content
- Magazines now may be classified as "clips" by setting a toggle in the editor. Clips can be used to reload other magazines. The name is modeled after things like stripper clips, but also includes singular bullets and ammo boxes.
- Guns may now have internal magazines by setting a toggle in the editor. These can not be ejected and only be reloaded with clips applied to the gun.
- All shotguns are set to use internal magazines. The combat shotgun holds 7 shells, the others hold 5. (see #3312)
- Shotgun slugs and the 9mm ammo box have been made clips.

### Notes:
- MagazineBehaviour was rewritten in large parts, as the syncing previously only served to decrease client-side ammo if it was too high, so increases in content would not be properly synced. (On a sidenote, the RNG was moved into a table instead of starting it again and advancing to the wanted position.)
- Clips are currently just deleted when emptied. While this makes sense for shotgun slugs (if the gun casings are replaced at least) for stripper clips we might want some garbage and we might just want to use regular magazines for reloading other magazines.
- Weapons with internal magazines spawn their own magazine on initialization and adjust the size and content. The spawned magazine is a new prefab which is a variant of the generic magazine.
- There is no pump action in this. Shotguns are still semi-automatic.

### Self-Checks:

* [x] Code is sufficiently commented
* [x] Code is indented with tabs and not spaces
* [ ] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b> [I think using a new internal magazine instead of a generic one and making internal magazines a new type of ammunition for mag slot purposes is reasonable]
* [x] The PR does not bring up any new compile errors
* [x] The PR has been tested in editor
* [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
* [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
* [ ] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants) [The generic internal magazine is placed right next to the generic magazine instead of in some folder like all other variants, though I think this is reasonable]
* [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable) [local]
* [x] The PR has been tested with round restarts.
* [x] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Might throw this one to staging for test

**Comment by DooblyNoobly** [comment]
This accidentally made it into production and players can no longer reload their weapons. Can you look into it please. Also are you on discord?

**Comment by AutumnNova** [comment]
reloading works fine

**Comment by Tjarr737** [comment]
For me reloading works on build 4052 with local host, 30ms ping (EU) and 300ms ping (AUS). Both normal guns and shotguns. It might be specific guns or some other situation I did not encounter.
Edit: Can't find any faults with the prefabs either.

**Pull request merged**
