### PR TITLE
Teleporter menu will now have the correct mob position when they're inside storage

### LINKED ISSUE #7004: Players who are in lockers or disposals are treated as if they are at 0,0 by the ghost teleport menu.
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
When a player is in a locker or in disposal pipes, then the ghost teleport menu will show them as being at 0,0. Trying to teleport to them will bring you to 0,0 instead of their actual position.
image
image

### Steps to reproduce
1. Get into a locker.
2. Hit F5, type in "suicide". You will die. Move to become a ghost.
3. Find yourself in the ghost teleportation menu. You will be shown as being at 0,0.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #7004
CL: [Fix] Teleporter menu will now have the correct mob position when they're inside storage

### CODE REVIEW

**Review by corp-0 — DISMISSED** [review]

**Comment by NoooneyDude** [comment]
`AssumedWorldPos` is server only. I fell into the same trap : )

**Comment by corp-0** [comment]
Wait so the teleport thing is client sided?

**Comment by NoooneyDude** [comment]
Yep

**Comment by MaxIsJoe** [comment]
hang on a second, why is the client getting all that info in the first place?
should this function turn into a server side one only then?

**Comment by MaxIsJoe** [comment]
image


this thing is a lying pos

**Comment by corp-0** [comment]
I think it would be better as a command the client asks the server to perform

**Comment by MaxIsJoe** [comment]
synced it

**Review by Bod9001 — APPROVED** [review]

**Pull request merged**
