### PR TITLE
Adds Paramedic and Psychiatrist occupations

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
### Purpose
Adds two jobs, Paramedic and Psychiatrist, that are in /tg/ but missing from unitystation
image

**Paramedic:** You are essentially a rescue medic. You spend most of your time outside medbay and therefore have reduced access. However you have increased access to the rest of the station.
image

**Psychiatrist:**  The Psychiatrist is a listening ear, a shoulder to cry on, and a friend to all. they are tasked with diffusing disputes and seeing to the psychological well-being of all the crew using both therapy and prescribing medicine.
image

Note: The job was renamed to psychiatrist based on a community vote in the discord, as well as the fact that in /tg/ you prescribe medicine, but real word psychologists don't, psychiatrists do.

I've also added a psychiatrists headset with access to both medical and service channels, the same as /tg/.

Both jobs spawn in the same place as other medical staff, and the data for their jobs and access has been added to the ID Console.

Inventory populators are based on /tg/ with some modifications due to some items not being implemented, this can be changed when those items are implemented.  

### Notes:
Up next is Psychologist items like the straight jacket, as well as roller beds for Paramedics. 
Special thanks to @PetMudstone for helping with the mapping icons and many other things, as well as the developers in the discord.

### CODE REVIEW

**Comment by corp-0** [comment]
Wonderful, congrats on your first PR it looks very good and you thought about everything. I need to ask though, how does it look in the picking job screen? I remember you posted something about it not taking new jobs very nicely.

**Comment by ZeroDayDaemon** [comment]
The job picking screen was done by lowering the spectator button, some jobs are in new places due to the additions, the job preferences screen was harder as I was for some reason unable to edit it, but I was able to find a configuration where everything fit. 

image
image

**Comment by corp-0** [comment]
yeah, the job preferences screen is populated automagically. Aight, looks good. I will wait for tests and check if anything new is breaking them.

**Comment by corp-0** [comment]
looks like only problems are the maps related ones so this is fine to merge. Thanks again.

**Pull request merged**
