### PR TITLE
Collision atmos

### LINKED ISSUE #2291: Shuttle crashing into station doesn't update atmospherics properly B: 100
# Description
It seems that atmospherics isn't properly notified about the destruction of tiles resulting in with behaviour like

image
image
image
image

## Category
BUG 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Get on mining shuttle 
2.smash in to station
3.Open up Matrix checker
4 Observe strange space values In atmospherics

### PR DESCRIPTION
**Pull request by krille90**
### Purpose
Fixes #2291, where crashing shuttles and then created space tiles wouldnt be updated properly.
Problem was how the neighbors of a node were chosen.
Previously, if a neighboring tile was space, there was a check if there is a neighboring matrix and if there is a tile.
Now, this check doesn't trigger anymore, when the current tile is also space, thus choosing the proper neighboring tiles.

Extended the matrix check for neighboring nodes to draw a white line between two neighboring nodes.

### Notes:
Multiplayer test wasn't done, since the fix doesn't touch anything network-related.

### CODE REVIEW

**Comment by krille90** [comment]
will add some comments on the MetaDataSystem class to make it more understandable.

**Comment by krille90** [comment]
done commenting

**Comment by JesterX666** [comment]
On it.

**Comment by JesterX666** [comment]
Code looks clean enough.  Just gonna test it before merging it.

**Comment by JesterX666** [comment]
Moles + Connected to space

Connected to Space and moles are still behaving weird. See that row that contains those 2 x "6.829" moles tiles? That row is not loosing gaz component at all.

**Comment by JesterX666** [comment]
Is it normal that the red tiles are both "Connected to space" :

image

And "Space" at the same time ? :

image

I thought that space would have "no moles" instead of 0.

Please see with a pro at atmos if this is acceptable.

**Comment by krille90** [comment]
> Is it normal that the red tiles are both "Connected to space" And "Space" at the same time ?

Yes, the check is defined like that:
`node.IsSpace || node.Neighbors.Any(n => n != null && n.IsSpace)`

> I thought that space would have "no moles" instead of 0.

Moles in GasMix are always the sum of all gases (with is a float array):

`public readonly float[] Gases;`
`public float Moles => Gases.Sum();`

**Comment by JesterX666** [comment]
Since it doesn't seem to cause troubles and everything seems to work fine, I'm merging it.

**Pull request merged**
