### PR TITLE
Fix firelocks

### LINKED ISSUE #4382: Firelocks should be only be manually openable using crowbars.
## Description
Right now, players can just open closed firelocks using anything. Empty hands, welders, guns, they all open firelocks if you use on them with said items. In /tg/, you can only open firelocks using crowbars (and other prying tools I believe, like fire axes). Since anyone can just open firelocks whenever, any fool can open one to let a fire spread.

Curiously, you can already manually close firelocks but only using crowbars and at any time,

On a side note in /tg/, if you click on a firelock with an empty hand you bang on it according to chat but no sound plays.

image

### Steps to Reproduce
1.  Go to Outpost or Box so you have firelocks available, Pog has none.
2.  Get a firelock closed, either by pulling a nearby alarm or by using a crowbar.
3.  Use anything on the firelock, it should open.

### PR DESCRIPTION
**Pull request by AutumnNova**
fixes #4382  and fixes a mistake in the french accent

### CODE REVIEW

**Comment by Aranclanos** [comment]
this interaction already exists, reimplementing it is a bad idea

take a look at TryCrowbar() in InteractableDoor.cs, it worked originally but I believe the door hacking broke it, but I can't say how without taking a closer look
just make sure that before fixing it, you understand what's causing the error

**Comment by AutumnNova** [comment]
nothing in TryCrowbar() will fix the issue as it is caused by the ServerTryOpen at the end of ServerPerformInteraction(). Replacing it with a return did fix the issue.

**Comment by Aranclanos** [comment]
Again, do not attempt to fix an issue without knowing the source of the error
if I'm not wrong, the functions TryOpen() and TryClose() from InteractableDoor dont get called because of a bad merge conflicts
replace line 129 and 133 with those calls

**Comment by Aranclanos** [comment]
probably remove the changes in firelock.cs I think that override will make all interactions do nothing

**Comment by AutumnNova** [comment]
I cant imagine changing things in TryCrowbar() will fix opening it with just your hand, but alright

**Comment by Aranclanos** [comment]
oh yeah right, change the ServerTryOpen() calls from bump and hand interaction to the TryOpen()
looking at the commit that broke all this would be the best, just to see if theres something more

**Comment by AutumnNova** [comment]
> Again, do not attempt to fix an issue without knowing the source of the error
> if I'm not wrong, the functions TryOpen() and TryClose() from InteractableDoor dont get called because of a bad merge conflicts
> replace line 129 and 133 with those calls

replacing those calls would prevent opening the firedoors with a crowbar, no?
as firelock.cs overwrites them to nothing?

**Comment by Aranclanos** [comment]
sounds about right, the ones inside trycrowbar() were fine

**Comment by ThatDan123** [comment]
You have compile errors.

**Comment by Bod9001** [comment]
good to merge?

**Comment by AutumnNova** [comment]
yep

**Pull request merged**
