### PR TITLE
Revamp ghosts so they are now separate, PlayerSync objects

### LINKED ISSUE #1540: Client ghosts cannot see each other and ghost can become stuck when corpse is destroyed B: 80
# Description
2 client ghosts can't see each other. They should be able to see each other while they are both ghosts.

Additionally, if a player's body is destroyed with the knife and turned into meat, I think the ghost loses the ability to move.

## Steps to Reproduce
1. Host in editor. (You may want to increase the amount of time before a ghost respawns in order to make testing easier, I think you can do this in PlayerHealth.OnDeathActions by adjusting the timeout passed to RespawnPlayer).
2. Join 2 clients from standalone.
3. Get the knife as the host and stand between the 2 clients.
4. Alternate stabbing them left and right evenly so they both die and become ghosts at the same time.
5. Try moving around as one of the ghosts and notice that the other client doesn't see the ghost.
6. Continue stabbing to turn a corpse to meat. Verify that the ghost becomes stuck.

### LINKED ISSUE #1569: If a ghost is revived, other ghosts will become invisible
# Description
When multiple clients are ghost and one is revived, any other ghost's model will become invisible
## Category
BUG

## Detailed Bug Report
#1540 could possibly fix this issue if it's done correctly, adding in case there is no effect to it.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. have two players die at near the same time
2. watch when 1st dead revives, other player becomes invisible

### LINKED ISSUE #1608: ghost spawns at incorrect position when dying in a locker B: 30
# Description
Ghosts currently spawn using the actual location of the player. if someone dies in a locker the ghost will spawn at 0,0,-100

This should be using objectBehaviour.AssumedLocation to grab it's location if they are inside another container.
## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. close a locker on yourself in space and obtain the sweet release of death
2. when you spawn as ghost it will be at 0,0,-100

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
Fixes #1540 
Fixes #1608
Fixes #1569

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
Ghosts are now spawned as separate objects and are, for all intents and purposes, just additional players that can only be seen by other ghosts. Sets us up to be able to more easily customize how the ghost works rather than having it be tightly coupled to the player and the player's behaviors.

Any logic that needs to check if the game object is a ghost vs. an alive player can use PlayerSync.IsGhost, or can manually check if the game object is in the Ghosts layer (which is all that PlayerSync.IsGhost does).

Got rid of the really old FoV code as well since it's no longer needed.

### CODE REVIEW

**Comment by fomalsd** [comment]
Tested with 200ms ping simulation.
1) Got NREs after players joined, they ended up having white skin:
image
```
NullReferenceException: Object reference not set to an instance of an object
  at PlayerSprites.UpdateCharacterSprites (System.String data) [0x00051] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Player\PlayerSprites.cs:57 
  at PlayerSprites.set_NetworkcharacterData (System.String value) [0x00029] in <376ba6965c3e41db8515c18ecce06bb6>:0 
  at PlayerSprites.CmdUpdateCharacter (System.String data) [0x0001a] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Player\PlayerSprites.cs:44 
  at PlayerSprites.CallCmdUpdateCharacter (System.String data) [0x00021] in <376ba6965c3e41db8515c18ecce06bb6>:0 
  at PlayerSprites+<WaitForLoad>d__9.MoveNext () [0x00063] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Player\PlayerSprites.cs:97 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <945c24c342914372bc599495ca1ade0d>:0 
```
2) after killing serverplayer got following exception. ghost never spawned:
image
```
ArgumentException: The Object you want to instantiate is null.
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x0004f] in <945c24c342914372bc599495ca1ade0d>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00001] in <945c24c342914372bc599495ca1ade0d>:0 
  at SpawnHandler.CreateGhost (ConnectedPlayer forPlayer, JobType jobType) [0x00031] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Managers\NetworkManagement\SpawnHandler.cs:69 
  at SpawnHandler.SpawnPlayerGhost (UnityEngine.Networking.NetworkConnection conn, System.Int16 playerControllerId) [0x00021] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Managers\NetworkManagement\SpawnHandler.cs:50 
  at PlayerNetworkActions.SpawnPlayerGhost () [0x0001d] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Player\PlayerNetworkActions.cs:744 
  at PlayerHealth.OnDeathActions () [0x00140] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Health\Living\HumanHealth\PlayerHealth.cs:90 
  at LivingHealthBehaviour.Death () [0x0001f] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Health\Living\LivingHealthBehaviour.cs:460 
  at LivingHealthBehaviour.CheckHealthAndUpdateConsciousState () [0x00088] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Health\Living\LivingHealthBehaviour.cs:512 
  at LivingHealthBehaviour.CalculateOverallHealth () [0x0007d] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Health\Living\LivingHealthBehaviour.cs:400 
  at LivingHealthBehaviour.UpdateMe () [0x0004e] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Health\Living\LivingHealthBehaviour.cs:346 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at UpdateManager.Update () [0x00013] in C:\homeproj\unitystation\UnityProject\Assets\Scripts\Managers\UpdateManager\UpdateManager.cs:95 
```

**Review by fomalsd — CHANGES_REQUESTED** [review]
See previous comments.
Also does ghost player position get broadcasted to normal players? because it certainly shouldn't

**Comment by fomalsd** [comment]
also does this fix #1569?

**Comment by chairbender** [comment]
Yes

**Comment by chairbender** [comment]
@fomalsd thanks for the testing and for catching that security issue!

Ready to test again. If you experience the NRE issue still please try to reimport Ghost.prefab.

**Comment by DooblyNoobly** [comment]
Very nice, I just tested on headless with two clients and everything is working well. Thanks

**Pull request merged**
