### PR TITLE
Chat Fixes and Enhancement

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: OOC names will have their tags removed
CL: Fixes discord webhook having <color=red>{name}</color>
CL: Adds bolding and underlining of OOC name or in game name when in chat
CL: Added sound to play when character name mentioned in chat
CL: Added option to turn off chat highlighting and mention sound

image

image

### CODE REVIEW

**Comment by Bod9001** [comment]
Could add separate box for admin like icon that can't be replaced by text?

**Comment by Bod9001** [comment]
But then changeung size too hummm

**Comment by Bod9001** [comment]
Ready to merge?

**Comment by ThatDan123** [comment]
Good to merge, the current sound is the click sound. It can be changed when a new sound is suggested

**Comment by Bod9001** [comment]
Looks good

**Pull request merged**
