### PR TITLE
Field Gen bug fix

### PR DESCRIPTION
**Pull request by ThatDan123**
Fixes being able to move around and activate unwelded generators

### CODE REVIEW

**Comment by corp-0** [comment]
Isn't there a wrenchable component that could handle this stuff?

**Comment by ThatDan123** [comment]
There is but i decided not to use it, this issue still wouldve been there as i just forgot to add a check for if it was wrenched.

**Comment by Bod9001** [comment]
does this fix a bug with being able to move the Field Gen  while on?

**Comment by corp-0** [comment]
> There is but i decided not to use it, this issue still wouldve been there as i just forgot to add a check for if it was wrenched.

I just think standardizing common stuff like wrenching machinery/furniture is better. You could always expose a bool in the wrenchable component to get IsWrenched and keep all the rest.

**Comment by corp-0** [comment]
alright I'm merging because we need to drop a new release with fixes so we can keep working with health in develop branch, but think about it. Standardizing good.

**Pull request merged**
