### PR TITLE
Pog-Station changes.

### PR DESCRIPTION
**Pull request by Evan-R-Rogers**
Fixed breach in maint, added HoS' office, scattered a few more vending machines around, gave atmos more lockers, gave every job their respective hardsuits and helms.

### CODE REVIEW

**Comment by Evan-R-Rogers** [comment]
Err what failed?

**Comment by RedlineTriad** [comment]
You can download and view the artifact from the tests to see what failed.

**Comment by Evan-R-Rogers** [comment]
@RedlineTriad 

The errors I'm getting are oddly enough reference errors from AsteroidStation. Curious.

**Comment by RedlineTriad** [comment]
I don't think it's an issue from you, but something merged into develop with failing tests, so wait a bit and rebase/merge and it should be good again.

**Comment by ThatDan123** [comment]
Think you can merge this now as well.

**Pull request merged**
