### PR TITLE
Replacing handcuffs on maps, simple zipcuffs.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Creates a base restraint prefab from which the handcuffs its variants are derived from.
- Replaces handcuffs on maps with the new prefab.
- Adds simple zipcuffs, which at the moment only have reduced breakout times.
  - Zipcuffs have a unique handcuffing sound.

### CODE REVIEW

**Comment by Bod9001** [comment]
what are the sound additions?

**Comment by PetMudstone** [comment]
The sound addition is a unique sound for applying cable restraints/zipcuffs.

**Comment by mmails** [comment]
Call them zipties, please, not zipcuffs

**Comment by PerfectTangent** [comment]
zipcuffs are a distinct tool from zipties.

zipties
racers-edge-rce5604bk-4-black-zip-tie-wraps

zipcuffs
41d9ezizq5L _AC_

if they are specifically zipcuffs, they should be called zipcuffs.

**Comment by mmails** [comment]
Ziptie handcuffs, yeah

**Pull request merged**
