### PR TITLE
Security fix for cmd in admin commands manager

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Prevents none admins from changing a very important bool in Cargo manager

### CODE REVIEW

**Review by corp-0 — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
can you re-run tests? its complaining about something that i didn't even do

**Comment by corp-0** [comment]
it is an issue on develop,  I  think. Be the hero we need, add the prefab to the list

**Comment by MaxIsJoe** [comment]
> it is an issue on develop, I think. Be the hero we need, add the prefab to the list

Doesn't sound like it's an issue on develop if my other PR had passing tests

**Comment by corp-0** [comment]
those were probably old enough to not get affected. Two of recent Jack's PRs had the same test failing with the same prefab

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
