### PR TITLE
Shovel, Sand. Glass Sheets production.

### PR DESCRIPTION
**Pull request by CykaGuy**
### Purpose

- This PR Adds Shovel, ability to dig Sand and make Glass Sheets, fixes some other, related to mining, stuff.
- Satisfies issue _#2459 ._

### Notes:

- Adds new items: Shovel and Sand.

- Shovel can be used on red sand tiles to get the sand.

- Sand can be transformed into glass sheets with ORM.

- Shovel can be obtained from the mining vending machine, mining closets, or from a Mining Cargo Crate.

- Shovel, Pickaxe, and Mining Lamp got in-hand sprites.

- Adds new sprite for dug red sand.

- Modified ChangeTileWhenItemUsed script to be able spawn lists of objects, if needed.

- New interaction: 'DigWithShovel', it is applied to red sand tiles. 

- Also fixes a few descriptions for items.

### Applicable checks:

- [x] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>

- [x] The PR does not bring up any new compile errors

- [x] The PR has been tested in editor

- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)

- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)

- [x] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)

- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

- [x] The PR has been tested with round restarts.

### CODE REVIEW

**Comment by fomalsd** [comment]
there is a conflict with mining_machines_54.prefab, could you resolve it please?

**Review by fomalsd — APPROVED** [review]
Yet to playtest this, but code looks good!

**Comment by fomalsd** [comment]
Scr 2020-02-03 at 22 53 26
hm, mining vending machine only has a pickaxe for some reason

**Comment by fomalsd** [comment]
Couldn't find shovels anywhere, are you sure you included them? (or maybe github build is borked)
Scr 2020-02-03 at 23 07 25
Scr 2020-02-03 at 23 11 10

**Comment by DooblyNoobly** [comment]
Digging does not work as client and on the server player you get a NRE:

image

**Comment by DooblyNoobly** [comment]
I wanted to get this merged before release but unfortunately I couldn't get digging to work when play testing. We will have to leave this for after alpha release.

**Pull request closed without merging**
