### PR TITLE
Added 2 new songs to title screen

### PR DESCRIPTION
**Pull request by Bonfire**
### Purpose
Spices up the title screen a little bit with two more SS13 songs

### Approach
Increased the music track size in the Lobby SoundManager and added the two songs to the tracklist

### Open Questions and Pre-Merge TODOs

- [x]  I read the contribution guidelines and the wiki.
- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  This PR does not include files without specific need to do so.
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
Last time I will be pushing with the develop branch, will be using separate branches from here on out (if everything goes well)

### CODE REVIEW

**Comment by fomalsd** [comment]
You forgot to include actual music I think
default

**Comment by Bonfire** [comment]
EDIT: Having some issues with my local repo. Give me a moment to update this.

**Comment by fomalsd** [comment]
Also you made the same mistake someone else did recently: you're commiting Lobby scene and you should have only commited Managers.prefab. 
After editing SoundManager you should press Apply button above so that actual prefab would be modified, and ignore scene-specific changes.
I'm using 2017.3.1p1

**Comment by fomalsd** [comment]
Here's what it shows for me:
default
1 and 3 are the same tracks

**Comment by Bonfire** [comment]
I understand, my mistake. I applied the changes to the new title objects in the hierarchy, and I assumed changes to the lobby would be in the Lobby prefab, but I see now that it would be in the Manager

**Comment by Bonfire** [comment]
I'll close this and redo it when I'm home tomorrow.

**Pull request closed without merging**
