### PR TITLE
shield generators block explosions, eject cartridge fix, lavaland tile fixes, chair wood dupe fix, ambience slider fix

### LINKED ISSUE #6517: The ambience sound slider doesn't affect ambience volume
### Environment
- Game Version: upstream/develop (May 15th, 2021)
- OS Version: Win10

### Detailed description of bug

The volume slider for ambience in the options menu does not affect the volume of ambience.

### Steps to reproduce

1. Open the options menu
2. Go to sound
3. Slide "Ambience volume" around

### Notes :

Master volume works fine though.

### LINKED ISSUE #6650: Chair wood dupe
Wood can be infinitely duplicated.

image

### LINKED ISSUE #6705: Lavaland tiles show as if they don't have flooring
image

### LINKED ISSUE #6706: Certain lavaland tiles show as invisible
Certain lavaland tiles show as invisible, more prominently, ores

tile to the left is not walkable
image

after being cleared, ore dropped, tile is walkable
image

### LINKED ISSUE #6768: Bad mining message for stone
### Environment
- Game Version: 21060620

### Detailed description of bug

image

This message is shown both for stone and ores.

This is relatively new, i think 4118 does not have this.

### Steps to reproduce

1. start digging stone with pickaxe

### LINKED ISSUE #6770: Eject Cartridge button in PDA drops ID on floor instead
### Environment
- Game Version: 21060620

### Detailed description of bug

Title.
ID is dropped on floor even if ID slot is empty, hands are empty and if empty hand is selected. If PDA has no ID, nothing happens.
There is nothing in logs.
This button was working properly some time ago.

### Steps to reproduce

1. open PDA UI
2. go to settings
3. press "Eject Cartridge"

### PR DESCRIPTION
**Pull request by ThatDan123**
Fixes #6650

Fixes #6705

Fixes #6706

Fixes #6768

Fixes #6517

Fixes #6770

-Adds separate reliable channels for chat messages and VV

CL: [New] Adds Ghost Teleport spots to singularity, tesla and SM

CL: [Change] Shields from field generators now block explosions

### CODE REVIEW

**Comment by pyrosshade** [comment]
making mining great again

**Comment by Fogapod** [comment]
PDAs no longer drop ID on floor, but do not eject cartridge either (https://github.com/unitystation/unitystation/issues/6770)

**Comment by ThatDan123** [comment]
> PDAs no longer drop ID on floor, but do not eject cartridge either (#6770)

I cant reproduce this on staging

**Comment by Fogapod** [comment]
> I cant reproduce this on staging

Does your PDA eject cartridge? Because mine does nothing now.
The issue wasn't just about ID being dropped, but PDA not ejecting cartridge as it did before

**Comment by ThatDan123** [comment]
> Does your PDA eject cartridge? Because mine does nothing now.
> The issue wasn't just about ID being dropped, but PDA not ejecting cartridge as it did before

Yeah, cartridge is ejecting fine for me on staging. Are you sure your job type has a PDA cartridge? I only tried with HOP

**Comment by Fogapod** [comment]
> Yeah, cartridge is ejecting fine for me on staging. Are you sure your job type has a PDA cartridge? I only tried with HOP

Yeah, nvm. I didn't know this is job specific. It's weird that there's no feedback at all for that button if there is no cartridge though.
So either it shouldn't be shown or at least print a message.

**Pull request merged**
